WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bandeira__c</fullName>
        <label>Bandeira</label>
        <picklist>
            <picklistValues>
                <fullName>Wise Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>You Move</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wise Up e You Move</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CNPJ__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>O CNPJ deve ser digitado no formato 00.000.000/0000-00</inlineHelpText>
        <label>CNPJ</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Data_inicio_curso__c</fullName>
        <inlineHelpText>Somente o dia 5 é permitido nesta data.</inlineHelpText>
        <label>Data de início do curso</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unidade_curso__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Unidade onde realizará o curso</inlineHelpText>
        <label>Unidade do curso</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Franquias</value>
            </filterItems>
            <filterItems>
                <field>Account.Catalogo_precos__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades - Unidade curso</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unidade_matriculadora__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Unidade que está matriculando o aluno</inlineHelpText>
        <label>Unidade matriculadora</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Franquias</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades - Unidade matriculadora</relationshipLabel>
        <relationshipName>UnidadeMatriculadora</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valor_investimento_unico__c</fullName>
        <label>Valor matrícula</label>
        <summarizedField>OpportunityLineItem.Valor_total_periodo__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.Forma_cobranca__c</field>
            <operation>notEqual</operation>
            <value>Recorrente</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>afinancecielo__Opcao_Pagamento_Unico__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opção de Pagamento Único</label>
        <referenceTo>afinance__Payment_Option__c</referenceTo>
        <relationshipLabel>Oportunidades (Opção de Pagamento Único)</relationshipLabel>
        <relationshipName>Oportunidades_unico</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/classes/Direciona_Pagina_Com_Email.cls
/*
    Overview: Define e redireciona para página correta de acordo com o curso.
    Autor: Sergio Migueis
    Classe de teste: Direciona_Pagina_Com_Email_Teste
*/

global without sharing class Direciona_Pagina_Com_Email{

    public afinance__Transaction__c tr {get;set;}
    
    
    public Opportunity opp {get; set;}
    
    public Contact ct {get;set;}
    
    public String inicioCurso {
    get{
        return opp.Data_inicio_curso__c.day() + '/' + opp.Data_inicio_curso__c.month() + '/' + opp.Data_inicio_curso__c.year();
    }
        set;
    }
    


    public Direciona_Pagina_Com_Email(){
        opp = [
            SELECT Id
            , Account.Name
            , Account.CPF__pc
            , Account.PersonEmail
            , Account.PersonHomePhone
            , Account.Phone
            , Account.PersonContactId
            , Unidade_curso__r.Name
            , Unidade_curso__r.Phone
            , Unidade_curso__r.CNPJ__c
            , Valor_investimento_unico__c
            , afinancecielo__Opcao_Pagamento_Unico__r.Name
            , Data_inicio_curso__c
            FROM Opportunity WHERE Id =: ApexPages.currentPage().getParameters().get('idOpp')
        ];
    }
     
    
    public Direciona_Pagina_Com_Email(afinancecielo.Confirmar_Pagamento controller){
        System.debug(' Proposta - PDF ');
        carregaDados();
    }
    
    public void carregaDados(){
        String trId = ApexPages.currentPage().getParameters().get('idTR');
        String trIdUnt = ApexPages.currentPage().getParameters().get('idTRunt');
        if(trId != null){
            tr = carregaTR(trId);                       
        }else{
            tr = carregaTR(trIdUnt);
        }
        
    }
    
    public PageReference redirect(){
        if(tr.afinance__Opportunity__c != null && tr.afinance__Payment_date__c != null){
            if(tr.afinance__Opportunity__r.Unidade_matriculadora__r.Bandeira__c.Contains('Wise Up')){                
                //enviar o email
                OrgWideEmailAddress owa = [select id, DisplayName, Address from OrgWideEmailAddress limit 1];
                EmailTemplate templateId = [Select id from EmailTemplate where name = 'wu - confirmação pagamento'];           
                List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setTemplateID(templateId.Id); 
                mail.setSaveAsActivity(false);
                mail.setOrgWideEmailAddressId(owa.id);
                mail.setTargetObjectId(tr.afinance__Opportunity__r.Account.PersonContactId);
                mail.setWhatId(tr.afinance__Opportunity__c);
                allmsg.add(mail);
                Messaging.SendEmailResult[] result = Messaging.sendEmail(allmsg,false); 
                System.debug(result);              
                PageReference requestPage = Page.confirmacao_pagamento_wise_up;
                requestPage.getParameters().put('idOpp',tr.afinance__Opportunity__c);
                requestPage.setRedirect(true);
                return requestPage;
            } else{                 
                //enviar o email
                OrgWideEmailAddress owa = [select id, DisplayName, Address from OrgWideEmailAddress limit 1];
                EmailTemplate templateId = [Select id from EmailTemplate where name = 'ym - confirmação pagamento'];           
                List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setTemplateID(templateId.Id); 
                mail.setSaveAsActivity(false);
                mail.setOrgWideEmailAddressId(owa.id);
                mail.setTargetObjectId(tr.afinance__Opportunity__r.Account.PersonContactId);
                mail.setWhatId(tr.afinance__Opportunity__c);
                allmsg.add(mail);
                Messaging.SendEmailResult[] result = Messaging.sendEmail(allmsg,false);  
                System.debug(result);                                 
                PageReference requestPage = Page.confirmacao_pagamento_you_move;
                requestPage.getParameters().put('idOpp',tr.afinance__Opportunity__c);
                requestPage.setRedirect(true);
                return requestPage;
            }
        }
        return null;
    }
    
    public static afinance__Transaction__c carregaTR(String idt){
        
        return [
                SELECT Id
                ,afinance__Opportunity__c
                ,afinance__Opportunity__r.Unidade_matriculadora__r.Bandeira__c
                ,afinance__Payment_date__c
                ,afinance__Opportunity__r.Account.PersonContactId
                FROM afinance__Transaction__c
                WHERE Id =: idt
            ];
    }
    
}