WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bandeira__c</fullName>
        <label>Bandeira</label>
        <picklist>
            <picklistValues>
                <fullName>Wise Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>You Move</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wise Up e You Move</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CNPJ__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>O CNPJ deve ser digitado no formato 00.000.000/0000-00</inlineHelpText>
        <label>CNPJ</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Cidade_endereco_cobranca__c</fullName>
        <label>Cidade de cobrança</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estado_endereco_cobranca__c</fullName>
        <label>Estado de cobrança</label>
        <picklist>
            <picklistValues>
                <fullName>AC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ID_ometznet__c</fullName>
        <externalId>true</externalId>
        <label>ID Ometznet</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Pais_endereco_cobranca__c</fullName>
        <label>País de cobrança</label>
        <picklist>
            <picklistValues>
                <fullName>Brasil</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ativo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arquivado</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Franquias</fullName>
        <active>true</active>
        <label>Franquias</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Account.object
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>any 3rd party marketing or re-seller relationship</description>
        <label>Partner</label>
    </recordTypes>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Campaign.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Campaign.object
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Event will not be published until Status is set to Active</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Development</fullName>
                    <default>true</default>
                    <label>In Development</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>At Capacity</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Bairro_endereco__c</fullName>
        <label>Bairro</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cidade_endereco__c</fullName>
        <label>Cidade</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complemento_endereco__c</fullName>
        <label>Complemento</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Genero__c</fullName>
        <label>Gênero</label>
        <picklist>
            <picklistValues>
                <fullName>Masculino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feminino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ID_ometznet__c</fullName>
        <externalId>true</externalId>
        <label>ID Ometznet</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Numero_endereco__c</fullName>
        <label>Número</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rua_endereco__c</fullName>
        <label>Rua</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/Contact.object
    <fields>
        <fullName>Status__c</fullName>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>1- Working - Active Opp Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2- Working - Talking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3- Working - Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4- Strategic Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5- Active Project Team Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6- Active Self Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7- Passive &amp; Friendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8- Passive &amp; Unfriendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9-HOLD Not mine/move</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10-Dimagi Staff</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/ControleAtribuicaoComercial__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>IdFilaRoleta__c</fullName>
        <label>Id da fila roleta</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LimiteLeads__c</fullName>
        <defaultValue>35</defaultValue>
        <inlineHelpText>Quantidade de Lead em que um comercial meuSucesso.com pode receber por dia. Por padrão o campo é preenchido com 35.</inlineHelpText>
        <label>Limite diário Leads</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Controle Atribuição Comercial</label>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Bairro_endereco__c</fullName>
        <label>Bairro</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CNPJ__c</fullName>
        <label>CNPJ</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Cidade_endereco__c</fullName>
        <label>Cidade</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complemento_endereco__c</fullName>
        <label>Complemento</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Ometznet__c</fullName>
        <externalId>true</externalId>
        <label>Id Ometznet</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Numero_endereco__c</fullName>
        <label>Número</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rua_endereco__c</fullName>
        <label>Rua</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Id_Ometznet__c</fullName>
        <externalId>true</externalId>
        <label>Id Ometznet</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Opportunity.object
    <fields>
        <fullName>Status__c</fullName>
        <label>x-Status</label>
        <picklist>
            <picklistValues>
                <fullName>Dead/Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open-Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Session/Needs Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presentation/Proposal/Price Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pilot/Trial/Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation/Verbal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won: Contract/CRA/Booked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Id_Ometznet__c</fullName>
        <externalId>true</externalId>
        <label>Id Ometznet</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Id_Ometznet__c</fullName>
        <externalId>true</externalId>
        <label>Id Ometznet</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Triggers__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Membros_Campanha_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Membros Campanha Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Oli_trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Oli trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Oportunidade_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Oportunidade_Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Triggers</label>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ID_ometznet__c</fullName>
        <label>ID ometznet</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/classes/Teste_Util.cls
/*
Classe Util para testes

*gerado pelo software Util
*/
@isTest(seeAllData=true)
public class Teste_Util{
    
    public static void createParams(){
        Triggers__c tr = new Triggers__c();
        tr.Oportunidade_Trigger__c = true;
        tr.Oli_trigger__c = true;
        tr.Membros_Campanha_trigger__c = true;
        insert tr;
    
    }
 
    public static void newControleAtribuicaoComercial(String Name, Id Fila, Integer DayliLimit){
        ControleAtribuicaoComercial__c CAC2 = new ControleAtribuicaoComercial__c();
        CAC2.LimiteLeads__c = DayliLimit;
        CAC2.Name = Name;
        CAC2.IdFilaRoleta__c = Fila;
        INSERT CAC2;  
        
        
    }
        
    public static Lead newLead(){
        Lead lead = new Lead();
        lead.LastName = 'Lead Teste';
        lead.Company = 'Empresa Teste';
        lead.Status = 'Novo';
        lead.LeadSource = 'Teste';

        insert lead;
        
        return
            [SELECT Id
             , Name
             , LastName
             , Company
             FROM Lead
             WHERE Id =: lead.Id];
    }
    public static Lead newLead(String RecordTypeName, String LeadSource){
        Lead lead = new Lead();
        lead.LastName = 'Lead Teste';
        lead.Company = 'Empresa Teste';
        lead.Status = 'Novo';
        lead.LeadSource = LeadSource;
        lead.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get(RecordTypeName).getRecordTypeId();
        lead.Email = String.ValueOf(system.now().format('YYYYMddhmsSSS'))+ Math.random() + '@email.com';

        return lead;
       
    }
    
    public static Contact newContact(String accountId){
        Contact con = new Contact();
        con.LastName = 'Contato Teste';
        con.AccountId = accountId;
        
        insert con;
        
        return
            [SELECT Id
             , Name
             , LastName
             , AccountId
             , Account.Name
             FROM Contact
             WHERE Id =: con.Id];
    }
    
    public static Account newAccount(){
        Account acc = new Account();
        acc.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Pessoa Física').getRecordTypeId();
        acc.FirstName = 'Conta';
        acc.LastName = ' Teste';
        acc.Genero__pc = Contact.SObjectType.Genero__c.getDescribe().getPickListValues().get(0).getValue();    
        acc.ID_ometznet__c = '123321';
        acc.Data_nascimento__pc = System.Today().addYears(-20);
        insert acc;
        
        return 
            [SELECT Id
             , FirstName
             , LastName
             , Genero__pc
             , RecordTypeId
             FROM Account
             WHERE Id =: acc.Id];
    }
    
    public static Account newAccountPJ(){
        Account acc = new Account();
        acc.Name = 'Conta Teste';
        acc.CNPJ__c = '05.807.857/0001-31';
        acc.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Pessoa Jurídica').getRecordTypeId();
        acc.ID_ometznet__c = '4321';
        insert acc;
        
        return
            [SELECT Id
             , Name
             , CNPJ__c
             , RecordTypeId
             FROM Account
             WHERE Id =: acc.Id];
    }
    
    public static User newUser(){
        User u = new User();
        u.Alias = 'user';
        u.CommunityNickname = 'NickName';
        u.Email = 'email@user.com';
        u.FirstName = 'Usuario';
        u.LastName = 'LastName';  
        u.Username = 'username@user.com';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        u.TimeZoneSidKey = 'America/Chicago';
        
        return u;
    }
    
    public static Account newAccountPJSemInserir(){
        Account acc = new Account();
        acc.Name = 'Conta Teste';       
        acc.CNPJ__c = '20.173.841/0001-08';
        acc.Phone = '+55 00 0000 0000';
        acc.Status__c = 'Ativo';
        acc.Bandeira__c = 'Wise Up';
        acc.Cidade_endereco_cobranca__c = 'Curitiba';
        acc.Estado_endereco_cobranca__c = 'PR';
        acc.Pais_endereco_cobranca__c = 'Brasil';
        return acc;
    }
    
    public static Lead newLeadNotInserted(){
        Lead lead = new Lead();
        lead.LastName = 'Lead Teste';
        lead.Company = 'Empresa Teste';
        
        return lead;
    }    
    public static Lead newLeadSemInserir(){
        Lead lead = new Lead();
        lead.LastName = 'Lead Teste';
        lead.Company = 'Empresa Teste';
        lead.LeadSource = 'Novo';
        lead.Email = 'teste@email.com';
        lead.Phone = '+55 99 99999 9999';
        lead.Rua_endereco__c = 'abc';
        lead.Numero_endereco__c = '123';
        lead.Complemento_endereco__c  = 'abc';
        lead.Bairro_endereco__c  = 'abc';
        lead.Cidade_endereco__c = 'São paulo';
        lead.Estado_endereco__c = 'SP';
        lead.CEP_endereco__c = '80620-340';
        lead.Pais_endereco__c = 'Brasil';
        return lead;
    }    
    
    public static Account newAccountFranquia(){
        Account acc = new Account();
        acc.Name = 'Conta Teste';
        acc.CNPJ__c = '05.807.857/0001-31';
        acc.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Franquias').getRecordTypeId();
        acc.ID_ometznet__c = '54321';
        acc.Catalogo_precos__c = Test.getStandardPriceBookId();
        acc.Type = 'Franquia';
        insert acc;
        
        return
            [SELECT Id
             , Name
             , CNPJ__c
             , RecordTypeId
             FROM Account
             WHERE Id =: acc.Id];
    }    
    public static Campaign newCampaign(){
        Campaign cam = new Campaign();
        cam.Name = 'Teste';
        cam.isActive = true;
        insert cam;
        return cam;
    }
    
    public static CampaignMember newCampaignMember(Id campaignId, Id leadId){
        
        CampaignMember cm = new CampaignMember();
        cm.CampaignId = campaignId;
        cm.LeadId = leadId;
        
        insert cm;
        return cm;
    }
    
    public static Opportunity newOpportunity(String AccountId){
        Date data = system.today(); 
        data = data.addMonths(1);
        Integer mes = data.month();
        Integer ano = data.year();
        Date dataCurso = date.newInstance(ano, mes, 05);
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Oportunidade Teste';
        opp.AccountId = AccountId;
        opp.CloseDate = data;
        opp.Data_inicio_curso__c = dataCurso;
        opp.StageName = Opportunity.SObjectType.StageName.getDescribe().getPickListValues().get(0).getValue();
        opp.Status_integracao_OmetzPlatform__c = null;
        opp.Responsavel__c = null;
        
        opp.afinancecielo__Valor_Unico_Cartao__c = 123321;
        
        insert opp;
        
        return
            [SELECT Id
             , Name
             , AccountId
             , Account.Name
             , CloseDate
             , StageName
             FROM Opportunity
             WHERE Id =: opp.Id];
    }
    
    public static Opportunity newOpportunity(String AccountId, String UnidadeId){
        Date data = system.today(); 
        data = data.addMonths(1);
        Integer mes = data.month();
        Integer ano = data.year();
        Date dataCurso = date.newInstance(ano, mes, 05);
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Oportunidade Teste';
        opp.AccountId = AccountId;
        opp.CloseDate = data;
        opp.Data_inicio_curso__c = dataCurso;
        opp.StageName = Opportunity.SObjectType.StageName.getDescribe().getPickListValues().get(0).getValue();
        opp.Status_integracao_OmetzPlatform__c = null;
        opp.Responsavel__c = null;
        opp.Unidade_curso__c = UnidadeId;
        opp.afinancecielo__Valor_Unico_Cartao__c = 123321;
        
        insert opp;
        
        return
            [SELECT Id
             , Name
             , AccountId
             , Account.Name
             , CloseDate
             , StageName
             FROM Opportunity
             WHERE Id =: opp.Id];
    }
    
    public static Product2 newProduct2(){
        return newProduct2('1');
    }
    
    public static Product2 newProduct2(String codigo){
        Product2 prod = new Product2();
        prod.Name = 'Produto Teste ' + codigo;
        prod.isActive = true;
        //        prod.Id_Ometznet__c = codigo;
        
        insert prod;
        
        return 
            [SELECT Id
             , Name
             , IsActive
             , Id_ometznet__c
             FROM Product2
             WHERE Id =: prod.Id];
    }
    
    public static PricebookEntry newPricebookEntry(String product2Id){
        PricebookEntry pbe = new PricebookEntry();
        pbe.Pricebook2Id = Test.getStandardPriceBookId();
        pbe.Product2Id = product2Id;
        pbe.UseStandardPrice = false;
        pbe.IsActive = true;
        pbe.UnitPrice = 100;
        
        insert pbe;
        
        return
            [SELECT Id
             , PriceBook2Id
             , Product2Id
             , IsActive
             , UnitPrice
             FROM PriceBookEntry
             WHERE Id =: pbe.Id];
    }
    
    public static OpportunityLineItem newOpportunityLineItem(String opportunityId, String pricebookEntryId){
        OpportunityLineItem oppli = new OpportunityLineItem();
        oppli.OpportunityId = opportunityId;
        oppli.PricebookEntryId = pricebookEntryId;
        oppli.UnitPrice = 1;
        oppli.Quantity = 1;
        
        insert oppli;
        
        return
            [SELECT Id
             , OpportunityId
             , Opportunity.Name
             , PriceBookEntryId
             , UnitPrice
             , Quantity
             FROM OpportunityLineItem
             WHERE Id =: oppli.Id];
    }
    
    public static User newPortalUser(String idContato){
        Id idPerfilPortal = 
            [SELECT Id 
             FROM Profile 
             WHERE Name = 'Partner Community User'
             LIMIT 1].Id;
        
        User u = new User();
        u.Email = 'usuarioteste@usuarioteste.com';
        u.UserName = u.Email;
        u.FirstName = 'Usuario';
        u.LastName = 'Teste';
        u.Alias = 'uTeste';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'pt_BR';
        u.ProfileId = idPerfilPortal;
        u.ContactId = idContato;
        u.LocaleSidKey = 'pt_BR';
        u.TimeZoneSidKey = 'America/Sao_Paulo';
        u.CompanyName = 'Wise Up';
        
        insert u;
        
        return
            [SELECT Id
             , Name
             , FirstName
             , LastName
             , Email
             , UserName
             , Alias
             , ContactId
             FROM User
             WHERE Id =: u.Id];
    }
    
    public static void ativarTriggers(){
        Triggers__c t = new Triggers__c();
        insert t;
    }
    
}