WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ID_ometznet__c</fullName>
        <externalId>true</externalId>
        <label>ID Ometznet</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Dados_integracao__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Dados necessários para a integração.</description>
    <fields>
        <fullName>Product_values_unit_copy__c</fullName>
        <label>Product values by unit copy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL_chamada__c</fullName>
        <label>URL de chamada</label>
        <type>Url</type>
    </fields>
    <label>Integração - OmetzNet</label>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Log_integracao__c.object
<CustomObject>
    <fields>
        <fullName>XML_resposta__c</fullName>
        <label>XML resposta</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log integração</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Cód. Log integração</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs integração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Id_Ometznet__c</fullName>
        <externalId>true</externalId>
        <label>Id Ometznet</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Unidade_curso__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Unidade onde realizará o curso</inlineHelpText>
        <label>Unidade do curso</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Franquias</value>
            </filterItems>
            <filterItems>
                <field>Account.Catalogo_precos__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades - Unidade curso</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Forma_cobranca__c</fullName>
        <label>Forma de cobrança</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valor_minimo__c</fullName>
        <label>Valor mínimo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Valor_unitario_periodo__c</fullName>
        <label>Valor negociado</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Forma_cobranca__c</fullName>
        <label>Forma de cobrança</label>
        <picklist>
            <picklistValues>
                <fullName>Recorrente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investimento único</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Id_Ometznet__c</fullName>
        <externalId>true</externalId>
        <label>Id Ometznet</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ID_ometznet__c</fullName>
        <label>ID ometznet</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/classes/ProductRequest.cls
public class ProductRequest {

    public Integer pkProductDefault {get; set;}
    public String product {get; set;}
    public String state {get; set;}
    public String city {get; set;}
    public String unit {get; set;}
    public Double minEnrollment {get; set;}
    public Double maxEnrollment {get; set;}
    public Double scholarshipEnrollment {get; set;}
    public Double minMonthPayment {get; set;}
    public Double maxMonthPayment {get; set;}
    public Double scholarshipMonthPayment {get; set;}
    public String user {get; set;}
    public String status {get; set;}
    public String created {get; set;}
    public String edited {get; set;}
    
    
    

    public ProductRequest(){

    }
    
    @future(callout = true)
    public static void futureIntegrateOli(List<Id> oliIds){
        List<OpportunityLineItem> olis = [
              SELECT Id
              , Opportunity.Id
              , Opportunity.Id_Ometznet__c
              , Opportunity.Unidade_curso__r.Id_Ometznet__c
              , Product2.Id_Ometznet__c
              , Product2.name
              , Valor_minimo__c
              , UnitPrice
              , Forma_cobranca__c
              FROM OpportunityLineItem
              WHERE Id in: oliIds
        ];
        for(OpportunityLineItem oli : olis)
        {
            try{
                ProductRequest req = ProductRequest.getValues(oli.Opportunity.Unidade_curso__r.Id_Ometznet__c, oli.Product2.Id_Ometznet__c.replaceAll('[^0-9]', ''), oli.opportunity.Id_Ometznet__c, oli.Product2.name);
                if(oli.Forma_cobranca__c == 'Recorrente')
                {
                    oli.unitPrice = req.maxMonthPayment;
                    oli.Valor_minimo__c = req.minMonthPayment * 12;
                    oli.Valor_unitario_periodo__c = req.minMonthPayment * 12;
                } else{
                    oli.unitPrice = req.maxEnrollment;
                    oli.Valor_minimo__c = req.minEnrollment;
                    oli.Valor_unitario_periodo__c = req.minEnrollment;
                }
            }
            catch(Exception ex){
                System.debug('cls__ ProductRequest erro: ' + ex.getMessage() + '-' + ex.getLineNumber());
            }
        }
        if(olis.size() > 0) update olis;
        if(logs.size() > 0 ) insert logs;
    }
    private static List<Log_integracao__c> logs = new List<Log_integracao__c>();
    public static ProductRequest getValues(String unitValue, String productId, String salesforceId, String prodName){
        
        String AmbienteName = OrganizationDAO.IsSandbox() ? 'Staging' : 'Production';
        Dados_integracao__c dados = Dados_integracao__c.getAll().get(AmbienteName);
        Map<String,String> headers = new Map<String,String>();
        headers.put('Accept','application/json');
        Log_integracao__c log = SFRequest.doIt(salesforceId, '', 'OmetzPlatform', dados.URL_chamada__c + dados.Product_values_unit_copy__c + unitValue + '?productId=' + productId, null, 'GET',headers);
        logs.add(log);
        log.xml_Resposta__c = log.xml_resposta__c.replace('pkProductDefault','pkProductDefault1'); //remover quando eles arrumarem o servidor.
        ProductRequest prod = (ProductRequest) JSON.deserialize(log.xml_resposta__c, ProductRequest.class);
        return prod;
    }

}