WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Article__c.object
<CustomObject>
    <label>Parágrafo</label>
    <nameField>
        <label>Article Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parágrafos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contract Template</label>
        <referenceTo>Contract_Template__c</referenceTo>
        <relationshipLabel>Contratos</relationshipLabel>
        <relationshipName>Contratos</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Contract_Template__c.object
<CustomObject>
    <label>Modelo de Contrato</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modelos de Contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Modelo_Contrato__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modelo de Contrato</label>
        <referenceTo>Contract_Template__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Template_Article__c.object
<CustomObject>
    <fields>
        <fullName>Article__c</fullName>
        <label>Article</label>
        <referenceTo>Article__c</referenceTo>
        <relationshipLabel>Template Article</relationshipLabel>
        <relationshipName>Articles_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contract_Template__c</fullName>
        <label>Contract Template</label>
        <referenceTo>Contract_Template__c</referenceTo>
        <relationshipLabel>Template Article</relationshipLabel>
        <relationshipName>Template_Articles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Template Article</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Template x Article Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Templates Article</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/classes/Article_Component_Test.cls
/*
    Test class for class: Article_Component
*/

@isTest
public class Article_Component_Test{

    static testMethod void test(){
    
        PageReference pageRef = Page.contract;
        Test.setCurrentPage(pageRef);

        Account account = Teste_Util.newAccount();
        
        Opportunity opp = Teste_Util.newOpportunity(account.Id);
        
        ApexPages.currentPage().getParameters().put('idOpp', opp.Id);
        Article__c artcle = new Article__c();
        artcle.Name = 'Teste';
        insert artcle;
        Contract_Template__c cont = new Contract_Template__c();
        cont.Name = 'Teste';
        insert cont;
        Template_article__c article = new Template_article__c();
        article.Article__c = artcle.Id;
        article.Contract_Template__c = cont.Id;
        insert article;
        
        opp.Modelo_contrato__c = cont.Id;
        update opp;
        
        Article_Component classe = new Article_Component();
        
        classe.opp = opp;
        classe.idOpportunity = opp.Id;
        classe.getItems();
           
    }

}