WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Article__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <label>Parágrafo</label>
    <nameField>
        <label>Article Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parágrafos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contract Template</label>
        <referenceTo>Contract_Template__c</referenceTo>
        <relationshipLabel>Contratos</relationshipLabel>
        <relationshipName>Contratos</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Contract_Article__c.object
<CustomObject>
    <fields>
        <fullName>Article__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Article</label>
        <referenceTo>Article__c</referenceTo>
        <relationshipLabel>Contract Article</relationshipLabel>
        <relationshipName>Contract_Articles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Can_be_Changed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Can be Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Can_be_Removed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Can be Removed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Contract_Clauses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Lock__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Lock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Article__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Article</label>
        <referenceTo>Contract_Article__c</referenceTo>
        <relationshipLabel>Contract Article</relationshipLabel>
        <relationshipName>Contract_Articles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Article</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contract Article Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Article</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Contract_Template__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Modelo de Contrato</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modelos de Contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Damnum-Salesforce/googlePlus/src/objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Template_Article__c.object
<CustomObject>
    <fields>
        <fullName>Article__c</fullName>
        <label>Article</label>
        <referenceTo>Article__c</referenceTo>
        <relationshipLabel>Template Article</relationshipLabel>
        <relationshipName>Articles_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Can_be_changed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If marked, when inserted in a contract, can be changed</inlineHelpText>
        <label>Can be changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Can_be_removed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If marked, when inserted in a contract, can be removed from the contract</inlineHelpText>
        <label>Can be removed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Template__c</fullName>
        <label>Contract Template</label>
        <referenceTo>Contract_Template__c</referenceTo>
        <relationshipLabel>Template Article</relationshipLabel>
        <relationshipName>Template_Articles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Article__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Article</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Template_Article__c.Contract_Template__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contract_Template__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Template_Article__c</referenceTo>
        <relationshipLabel>Template Article</relationshipLabel>
        <relationshipName>Template_Article</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Template Article</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Template x Article Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Templates Article</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/classes/Contract_Handler.cls
/*
    Test class: Contract_Test
*/

public class Contract_Handler{

    public static void insertArticle(List<Contract> contracts){
        Set<Id> templateId = new Set<Id>();
        Set<Id> contractsId = new Set<Id>();
        
        for(Contract c : contracts){
            contractsId.add(c.Id);
            
            if(!String.isEmpty(c.Contract_Template__c)) templateId.add(c.Contract_Template__c);
        }
        
        delete
            [SELECT Id
            FROM Contract_Article__c
            WHERE Contract__c IN: contractsId];
        
        Map<Id, Contract_Template__c> templateMap = new Map<Id, Contract_Template__c>(
            [SELECT Id
                , Name
                , (SELECT Id
                    , Article__c
                    , Article__r.Description__c
                    , Can_be_Changed__c
                    , Can_be_Removed__c
                    , Parent_Article__c
                    , Article__r.Name
                    , Order__c
                FROM Template_Articles__r
                WHERE Article__r.Inactive__c = false
                ORDER BY Parent_Article__c)
            FROM Contract_Template__c
            WHERE Id IN: templateId]
        );
        
        List<Contract_Article__c> articles = new List<Contract_Article__c>();
        
        Map<Id, Integer> articleMap = new Map<Id, Integer>();
        
        for(Contract c : contracts){
                if(!String.isEmpty(c.Contract_Template__c)){
                for(Template_Article__c tc : templateMap.get(c.Contract_Template__c).Template_Articles__r){
                    if(String.isEmpty(tc.Parent_Article__c)){
                        Contract_Article__c cc = createContractArticle(c.Id, tc);
                            
                        articles.add(cc);
                        
                        articleMap.put(tc.Id, articles.size() - 1);
                    }
                }
            }
        }
        
        if(articles.size() > 0) insert articles;
        
        if(articleMap.size() > 0){
            List<Contract_Article__c> parentClauses = new List<Contract_Article__c>();
                
            for(Contract c : contracts){
                for(Template_Article__c tc : templateMap.get(c.Contract_Template__c).Template_Articles__r){
                    if(!String.isEmpty(tc.Parent_Article__c)){
                        Contract_Article__c cc = createContractArticle(c.Id, tc);
        
                        cc.Parent_Article__c = articles.get(articleMap.get(tc.Parent_Article__c)).Id;
                        
                        parentClauses.add(cc);
                    }
                }
            }
            
            if(parentClauses.size() > 0) insert parentClauses;
        }
    }
    
    private static Contract_Article__c createContractArticle(Id contractId, Template_Article__c tc){
        Contract_Article__c cc = new Contract_Article__c();
        cc.Contract__c = contractId;
        cc.Article__c = tc.Article__c;
        cc.Description__c = tc.Article__r.Description__c;
        cc.Can_be_Removed__c = tc.Can_Be_Removed__c;
        cc.Can_be_Changed__c = tc.Can_be_Changed__c;
        cc.Order__c = tc.Order__c;
        cc.Order_Lock__c = true;
                        
        return cc;
    }

}