WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/ControleAtribuicaoComercial__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>IdFilaRoleta__c</fullName>
        <label>Id da fila roleta</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LimiteLeads__c</fullName>
        <defaultValue>35</defaultValue>
        <inlineHelpText>Quantidade de Lead em que um comercial meuSucesso.com pode receber por dia. Por padrão o campo é preenchido com 35.</inlineHelpText>
        <label>Limite diário Leads</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Controle Atribuição Comercial</label>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DataAtribuicaoComercial__c</fullName>
        <label>Data da atribuição comercial</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Data_Disponibilizacao_Lead__c</fullName>
        <label>Data da disponibilização do Lead</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Prioridade__c</fullName>
        <formula>CASE(LeadSource, &apos;Funil de Vendas&apos;, 1, &apos;Live Class&apos;, 2, &apos;Aula Aberta&apos;, 3, &apos;Material Complementar&apos;, 4, &apos;Voando com os Anjos&apos;, 5, &apos;Especiais&apos;, 6, 7)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prioridade</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UltimaIntegracao__c</fullName>
        <label>Ultima Integração</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UsuarioComercialAtribuido__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comercial Atribuido</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/classes/BatchLeadsForaDoFunil.cls
global class BatchLeadsForaDoFunil implements Database.Batchable<sObject> {
    
    global String query = 'SELECT Id, Leadsource, OwnerId, Prioridade__c FROM Lead WHERE Owner.Name IN (\'meuSucesso Live Class\', \'meuSucesso Aula Aberta\', \'meuSucesso Especiais\', \'meuSucesso Material Complementar\', \'meuSucesso Voe com os Anjos\') AND Data_Disponibilizacao_Lead__c < TODAY ORDER BY Data_Disponibilizacao_Lead__c DESC, UltimaIntegracao__c DESC, Prioridade__c';
    global ControleAtribuicaoComercial__c CAC = ControleAtribuicaoComercial__c.getInstance('meuSucesso #AUTO');
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        Integer SumLeads = [SELECT COUNT() FROM Lead WHERE UsuarioComercialAtribuido__c NOT IN (SELECT Id FROM User WHERE Department = 'Comercial' AND CompanyName = 'meuSucesso.com') AND DataAtribuicaoComercial__c = TODAY];
        
        Integer Comerciais = [SELECT COUNT() FROM User WHERE Department = 'Comercial' AND CompanyName = 'meuSucesso.com']; 
        Decimal LimitLeadCom = CAC.LimiteLeads__c;
        Integer Lim =  Integer.ValueOf(Math.abs((Comerciais * LimitLeadCom) - SumLeads));
        
        query = query + ' LIMIT ' + Lim;
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        List<Lead> leadToUpdate = new List<Lead>();
        
        for(Lead l : (List<Lead>)Scope){
            Lead l2 = new Lead(Id = l.Id, OwnerId = CAC.IdFilaRoleta__c);     
            leadToUpdate.add(l2);
            system.debug('l2: ' + l2);
        }
        
        UPDATE leadToUpdate;
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}