WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Contract_Article__c.object
<CustomObject>
    <fields>
        <fullName>Can_be_Changed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Can be Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Can_be_Removed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Can be Removed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Contract_Clauses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Article</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contract Article Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Article</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/classes/Contract_Article_Test.cls
/*
    Test class for trigger: Contract_Article_Trigger
    Test class for class: Contract_Article_Handler
    
    Atualizado por: Jonathan Valoto
    Data: 05/08/2016
*/

@isTest
public class Contract_Article_Test{

    static testMethod void test(){
        Account account = Teste_Util.newAccount();
        
        Contract contract = new Contract();
        contract.AccountId = account.Id;
        contract.StartDate = System.today();
        insert contract;
        
        Contract_Article__c contractArticle = new Contract_Article__c();
        contractArticle.Contract__c = contract.Id;
        contractArticle.Can_Be_Removed__c = false;
        contractArticle.Can_Be_Changed__c = false;
        insert contractArticle;

        try{
            update contractArticle;
        }catch(Exception e){
            System.assert(true);
        }
        
        try{
            delete contractArticle;
        }catch(Exception e){
            System.assert(true);
        }
    }

}