WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CPF__c</fullName>
        <label>CPF</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_nascimento__c</fullName>
        <label>Data de nascimento</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/classes/ClientePotencial_Teste.cls
@isTest
public class ClientePotencial_Teste{
    public static testmethod  void teste(){
        ClientePotencial pop = new ClientePotencial();
        pop.studentName = '';
        pop.studentCPF = '';
        pop.clientName = '';
        pop.clientCPF = '';
        pop.studentBorn = '';
        pop.setResponsavel('','');
        pop.serializeToJson();
        pop.serializeToMultipart();
        
        Lead l = Teste_Util.newLead();
        l.Data_Nascimento__c = System.today();
        l.CPF__c = '520.358.443-55';
        update l;
        try{
            new ClientePotencial(l);
            ClientePotencial.validaCPFLead(l.Id, '', '');
        }catch(Exception ex){
        }
        
        Account acc = Teste_Util.newAccount();
        acc.PersonBirthDate = System.today();
        acc.cpf__pc= '520.358.443-55';
        update acc;
        try{
            new ClientePotencial(acc);
            ClientePotencial.futureIntegrateAcc(new List<string> {acc.Id});
        }catch(Exception ex){
        }
    }
}