WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Log_integracao__c.object
<CustomObject>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_registro__c</fullName>
        <label>Id do registro</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nome_registro__c</fullName>
        <label>Nome do registro</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOAPAction__c</fullName>
        <label>SOAPAction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sistema__c</fullName>
        <label>Sistema</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XML_envio__c</fullName>
        <label>XML envio</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log integração</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Cód. Log integração</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs integração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/classes/SFRequest_Test.cls
/*
    Test class for: SFRequest
*/

@isTest
public class SFRequest_Test{

    static testMethod void testePost(){
        List<Log_integracao__c> logs = new List<Log_integracao__c>();

        Log_integracao__c log = SFRequest.doPost('xxxAAA', 'Registro teste', 'teste', 'www.site.com/servico', 'insert', '<xml>envio</xml>');
        
        System.assertEquals(log.Id_registro__c, 'xxxAAA');
        System.assertEquals(log.Nome_registro__c, 'Registro teste');
        System.assertEquals(log.Endpoint__c, 'www.site.com/servico');
        System.assertEquals(log.Sistema__c, 'teste');
        System.assertEquals(log.SOAPAction__c, 'insert');
        System.assertEquals(log.XML_envio__c, '<xml>envio</xml>');
        
        logs.add(log);
        
        SFRequest.saveLogs(logs);
        
        logs = 
            [SELECT Id
            FROM Log_integracao__c];
            
        System.assertEquals(1, logs.size());
    }
    
    static testMethod void testeGet(){
        List<Log_integracao__c> logs = new List<Log_integracao__c>();

        Log_integracao__c log = SFRequest.doGet('xxxAAA', 'Registro teste', 'teste', 'www.site.com/servico');
        
        System.assertEquals(log.Id_registro__c, 'xxxAAA');
        System.assertEquals(log.Nome_registro__c, 'Registro teste');
        System.assertEquals(log.Endpoint__c, 'www.site.com/servico');
        System.assertEquals(log.Sistema__c, 'teste');
        
        logs.add(log);
        
        SFRequest.saveLogs(logs);
        
        logs = 
            [SELECT Id
            FROM Log_integracao__c];
            
        System.assertEquals(1, logs.size());
    }
    
    static testMethod void testeCreateException(){
        Log_integracao__c log = SFRequest.createException('xxx', 'registro', 'teste', null);
        
        System.assertEquals(log.Id_registro__c, 'xxx');
        System.assertEquals(log.Nome_registro__c, 'registro');
        System.assertEquals(log.SOAPAction__c, 'teste');
    }

}