lanecwe-Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ChannelType__c</fullName>
        <description>This is dependent Picklist based on Channel Field.</description>
        <label>Channel Type</label>
        <picklist>
            <picklistValues>
                <fullName>Affinity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User - Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User - Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User - Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub-Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VAR</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This field is dynamically set.  If it has 0 companies associated to it the value is Prospect.  If it has &gt; 0 companies associated to it then it will be Customer.  There are also some Partner channel specific things that will set the value to Customer.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Contact.object
<CustomObject>
</CustomObject>

dimagi-SalesforceFB/src/objects/Contact.object
    <fields>
        <fullName>Status__c</fullName>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>1- Working - Active Opp Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2- Working - Talking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3- Working - Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4- Strategic Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5- Active Project Team Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6- Active Self Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7- Passive &amp; Friendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8- Passive &amp; Unfriendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9-HOLD Not mine/move</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10-Dimagi Staff</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

AkshayVispute-Salesforce/akshay.vispute@eternussolutions.com/src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>x-Status</label>
        <picklist>
            <picklistValues>
                <fullName>Dead/Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open-Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Session/Needs Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presentation/Proposal/Price Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pilot/Trial/Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation/Verbal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won: Contract/CRA/Booked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/classes/Test_SetAccountStatusOnOpportunity.cls
/*********************************************************************
Name : Test_SetAccountStatusOnOpportunity 
Created On : jan 06, 2012  
Created By : Lalit Bohra
Description : Test class on  Trigger on Opportunity SetAccountStatusOnOpportunity  
**********************************************************************/
@isTest
private class Test_SetAccountStatusOnOpportunity {

    static testMethod void TestSetAccountStatusOnOpportunity() {
        // TO DO: implement unit test
        list<Account> AccountList = new list<Account>();
        list<Contact> ContactList = new list<Contact>();
        list<Opportunity> OpportunityList = new list<Opportunity>();
       
        
       
        Account acc= new Account();
        acc.Name='Test Acc';
        acc.Status__c='Prospect';
        acc.ChannelType__c='Reseller';
        AccountList.add(acc);
        
        Account acc1= new Account();
        acc1.Name='Test Acc1';
        acc1.Status__c='Prospect';
        acc1.ChannelType__c='Reseller';
        AccountList.add(acc1);   
        insert AccountList; 
        
        
        set<Id> AccountIdset=new set<Id>();
        AccountIdset.add(acc.Id);
        AccountIdset.add(acc1.Id);
        
        Contact con= new Contact(); 
        con.LastName='Conlastname';
        con.AccountId=acc.Id;
        //insert con;
        ContactList.add(con);
        
        Contact con1= new Contact(); 
        con1.LastName='Conlastname1';
        con1.AccountId=acc1.Id;
        //insert con1;
        ContactList.add(con1);
        insert ContactList; 
        
        Opportunity opp = new Opportunity();
        opp.Name = 'test';
        opp.AccountId = acc.Id;
        opp.CloseDate = system.today();
        opp.StageName = 'Closed Won';
        opp.CurrencyIsoCode = 'USD';        
        opp.Probability = 0;
        opp.Contact__c=con.Id;
        OpportunityList.add(opp);

        Opportunity opp1 = new Opportunity();
        opp1.Name = 'test1';
        opp1.AccountId = acc1.Id;
        opp1.CloseDate = system.today();
        opp1.StageName = 'Closed Won';
        opp1.CurrencyIsoCode = 'USD';        
        opp1.Probability = 0;
        opp1.Contact__c=con1.Id;
        OpportunityList.add(opp1);
        
        test.startTest();
        insert OpportunityList;
        test.stopTest();
        list<Account> UpdatedList=[Select Status__c from Account where id in:AccountIdset and Status__c=:'Customer'];
        if(UpdatedList != null && UpdatedList.size()>0){
            system.assert(true);
        }
        else{
            system.assert(true);
        }
    }
}