lanecwe-Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/CONMAN_Contract__c.object
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used to set the relationship between Conman Contract and Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CONMAN_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <label>Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sent To Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>CONMAN_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>z_Source__c</fullName>
        <label>z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>CONMAN Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

dimagi-SalesforceFB/src/objects/Opportunity.object
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Account.Name</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>

dimagi-SalesforceFB/src/objects/Opportunity.object
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

lanecwe-Prod/src/classes/SGEmailservice_Test.cls
@isTest (SeeAllData = true)
private class SGEmailservice_Test {
    static testMethod void SGEmailservice_Test() {

        SGLeadCreateREST.sendemail = true;
        
        Account accttest = PGITestUtilities.getAccountDetails();
		insert accttest;
        
        Opportunity opptytest = PGITestUtilities.getOpportunityDetails();
        opptytest.AccountId = accttest.id;
        insert opptytest;
        
        Contact cntcttest = PGITestUtilities.getContactDetails(accttest.id);
        insert cntcttest;

        conman_contract__c cntrcttest 	= new conman_contract__c();
        cntrcttest.Account_Name__c		=	accttest.id;
        cntrcttest.Opportunity__c 		= 	opptytest.id;
        cntrcttest.z_Source__c			=	'Salesgateway'; 

        Test.startTest();
        insert cntrcttest;
        cntrcttest.Contract_Status__c =	'Sent To Customer';
        Update cntrcttest;
        cntrcttest.Contract_Status__c =	'Customer Accepted';
        Update cntrcttest; 
		cntrcttest.Contract_Status__c =	'Customer Rejected';
        Update cntrcttest; 

        /*conman_contract__c loopcntrct = [select Account_Name__c,Opportunity__c,Contract_Status__c]
            new conman_contract__c();
        loopcntrct = cntrcttest;
        
        Test.startTest();
        for (conman_contract__c sendemail : loopcntrct){
        	SGEmailservice.sendsEmail(cntrcttest);
        }*/
        Test.stopTest();
        SGLeadCreateREST.sendemail = false;
    }
}