lanecwe-Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ChannelType__c</fullName>
        <description>This is dependent Picklist based on Channel Field.</description>
        <label>Channel Type</label>
        <picklist>
            <picklistValues>
                <fullName>Affinity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User - Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User - Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User - Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub-Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VAR</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ECommerce_Account_Number__c</fullName>
        <label>ECommerce Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECommerce_Convert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ECommerce Convert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This field is dynamically set.  If it has 0 companies associated to it the value is Prospect.  If it has &gt; 0 companies associated to it then it will be Customer.  There are also some Partner channel specific things that will set the value to Customer.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

rajyeturi16-salesforce/project/objects/Account.object
    <recordTypes>
        <fullName>Direct</fullName>
        <active>true</active>
        <label>Direct</label>
    </recordTypes>

lanecwe-Prod/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChannelType__c</fullName>
        <inlineHelpText>Default value is Direct.  Do not change unless you work in the Partners channel.</inlineHelpText>
        <label>Channel Type</label>
        <picklist>
            <picklistValues>
                <fullName>Affinity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User - Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User - Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User - Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub-Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VAR</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DoNotSolicit__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Ecomm: used in back office for company create</description>
        <label>DoNotSolicit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ECommerce_Account_Number__c</fullName>
        <label>ECommerce Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECommerce_Convert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ECommerce Convert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Z_Source__c</fullName>
        <description>Source Value</description>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Lead.object
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>

lanecwe-Prod/src/objects/Logs__c.object
<CustomObject>
    <description>This object holds all request and response details from provisioning application for create company and create subscriber API</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Cause__c</fullName>
        <label>Exception Cause</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <label>Exception Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <label>Exception Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method_Name__c</fullName>
        <label>Method Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>holds complete request sent to back office</description>
        <label>Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <description>holds complete response from back office</description>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Failure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>start_dtm__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>start_ms__c</fullName>
        <label>Start Time Milliseconds</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>stop_dtm__c</fullName>
        <label>Stop Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>stop_ms__c</fullName>
        <label>Stop Time Milliseconds</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PGiLogs</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGiLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/classes/AuditLog_Test.cls
@isTest
private class AuditLog_Test {
  public class Test01Exception extends Exception {}
  public class Test02Exception extends Exception {}

  // Illustrate use of AuditLog
  private static testMethod void testSimpleCase() {
    //User u2 = [SELECT Id FROM User WHERE Alias='vvall'];
    //User u2 = [select id from user where name = 'E-comm Integration' and isactive=true limit 1];
    //User u2 = [select id from user where name = 'eCommerce Customer' and isactive=true limit 1];
      
    //System.RunAs(u2){   
            AuditLog al = new AuditLog('AuditLogTest','testSimpleCase');
            Test.StartTest(); 
            Lead l    =    new Lead(
                            FirstName = 'Test Queue Lead',
                            LastName = 'Owner Update',
                            Phone = '2222012011',
                            Email = 'LeadQueueOwner@pgi.com',
                            ECommerce_Account_Number__c = 'Ecom-000000001',
                            ECommerce_Convert__c = false,
                            LeadSource = 'ECommerce Customer',
                            Company = 'Pfiz I',
                            ChannelType__c = 'Direct',
                            Status = 'Qualifying',
                            Street = '1500 Main Street',
                            City = 'SanJose',
                            State = 'CA',
                            PostalCode = '95802',
                            Country = 'USA',
                            Business_Type__c = 1,
                            DoNotSolicit__c = true,
                            Z_Source__c = 'eCommerce'
                        );

            insert l;
            
            Map<Id,String> m =  new Map<Id,String>{
              l.Id   => 'yummy',
              l.Id   => 'also yummy'
            };
            
            al.logSourceSystem('Test');
            al.logRecordId(l.Id);
            
            al.setUrl(null);
            al.logMessage('Timer started automatically. Now log short, important messages');
             
            try {   
              new Account(name = 'Test').get('BAD_FIELD_NAME');
              System.assert(false, 'Previous line should have thrown a runtime exception');
            } catch (Exception e) {
              al.logException('Apex Runtime Exception Occurred so log it. Pass the exception too ==> ', e);
            }
            
            al.saveLog();   
            Test.stopTest();
      //}
  }

  // Verify that Logs__c records are populated.
  private static testMethod void testCreateLog() {
    //User u2 = [select id from user where name = 'eCommerce Customer' a/nd isactive=true limit 1];   
    //System.RunAs(u2){  
        AuditLog log = new AuditLog('AuditLogTest','testCreateLog');
        Test.StartTest();
        log.logRequestInfo('No Inputs');
        log.logResponseInfo('No Outputs');
        log.logStatusInfo('Status Message');
        log.logMessage('First Message');
        log.logMessage('Second Message');
        
        try {
          try { 
             log.logErrorMessage('First Error');
             throw new Test01Exception('First Exception');
          } catch (Exception e) {
             log.logErrorMessage('Second Error');
             throw new Test02Exception('Second Exception', e);
          }
        } catch (Exception e) {
          log.logException('Chained Exceptions', e);
        }
        
        Logs__c newlog = log.saveLog();
        
        Logs__c dblog = 
          [select id,class_name__c,method_name__c,start_dtm__c,start_ms__c,
                  request__c,response__c,message__c,error_message__c,
                  stop_dtm__c,stop_ms__c,status__c,
                  exception_cause__c,exception_message__c,exception_type__c
             from Logs__c 
            where id = :newlog.id limit 1 ];
        
        System.assertEquals(newLog.class_name__c, dblog.class_name__c);
        System.assertEquals(newLog.method_name__c, dblog.method_name__c);
        
        System.assertEquals(newLog.start_dtm__c, dblog.start_dtm__c);
        System.assert(dblog.start_dtm__c != null);
        System.assertEquals(newLog.start_ms__c, dblog.start_ms__c);
        System.assert(dblog.start_ms__c != null);
        
        System.assertEquals(newLog.stop_dtm__c, dblog.stop_dtm__c);
        System.assert(dblog.stop_dtm__c != null);
        System.assertEquals(newLog.stop_ms__c, dblog.stop_ms__c);
        System.assert(dblog.stop_ms__c != null);
        
        System.assert(dblog.stop_ms__c >= dblog.start_ms__c);
        
        System.assert(dblog.message__c.contains('First Message') && dblog.message__c.contains('Second Message'),'bad message field');
        System.assert(dblog.error_message__c.contains('First Error') && dblog.error_message__c.contains('Second Error'),
                            'bad error field');
       
        
        System.assert(dblog.exception_cause__c.contains('First Exception'),'bad exception cause field');
        System.assert(dblog.exception_message__c.contains('Second Exception'),'bad exception cause field');
        System.debug('@@@BEN@@@ exception type is ' + dblog.exception_type__c);
        System.assert(dblog.exception_type__c.contains('AuditLog_Test.Test02Exception'),'wrong exception type');
        
        System.debug('\n\n>>> ' + dblog);
        test.stopTest();   
    //}   
  }
  
  
  private static testMethod void testLogLevels() {
    //User u2 = [select id from user where name = 'eCommerce Customer' and isactive=true limit 1];   
    //System.RunAs(u2){
        AuditLog audit = new AuditLog( 'AuditLogTest','testLogLevels');
        Test.startTest();
        audit.logMessage('This message won\'t be written');
        audit.logMessage('Nor this one');
        
        Logs__c dblog = audit.saveLog();
        //System.assert(dblog.id == null, 'Logs__c should not have been saved to Salesforce.');
        
        AuditLog audit2 = new AuditLog( 'AuditLogTest','testLogLevels');
        
        audit2.logMessage('This message will be written');
        audit2.logMessage('And so will this one');
        
        Logs__c msglog = audit2.saveLog();
        Logs__c dblog2 = [select id,message__c from Logs__c where id = :msglog.id limit 1 ];
        System.assert(dblog2.message__c.contains('This message will be written'));
        System.assert(dblog2.message__c.contains('And so will this one'));
        Test.StopTest();
    //}   
  }


  private static testMethod void testVeryLongStrings() {
    //User u2 = [select id from user where name = 'eCommerce Customer' and isactive=true limit 1];   
    //System.RunAs(u2){
        Test.StartTest();
        String str100 = '123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_';
        String str32000 = '';
            
        for(Integer j = 0; j < 320; j++) {
          str32000 += str100;
        }
        
        System.assertEquals(32000,str32000.length());

        AuditLog audit = new AuditLog( str100, str100);

        audit.logMessage(str32000);
        audit.logMessage(str100);
        
        Logs__c dblog = audit.saveLog();
        System.assert(dblog.id != null, 'Logs__c with > 32000 char message & long classname should truncate & save OK.');
        Test.StopTest();
    //}   
  }
  
  
  private static testMethod void testThrowingExceptionWhileLoggingException() {
    //User u2 = [select id from user where name = 'eCommerce Customer' and isactive=true limit 1];   
    //System.RunAs(u2){  
        AuditLog audit = new AuditLog('AuditLogTest', 'testForcingExceptionOnSaveLog');
        Test.StartTest();
        try {
          audit.logException(null);
          audit.logException('Null Exception being passed in', null);
        } catch (Exception e) {
          System.assert(true, 'Logging an exception should never throw another exception');
        }
        Test.StopTest();
    //}
  }
}