lanecwe-Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/CONMAN_Contract__c.object
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used to set the relationship between Conman Contract and Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CONMAN_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <label>Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sent To Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>z_Source__c</fullName>
        <label>z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>CONMAN Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/classes/SGLockContactFields_Test.cls
@isTest (SeeAllData = true)
private class SGLockContactFields_Test {

    static testMethod void SGLockContactFields_Test() {

        Test.startTest();
        
        Account accttest = PGITestUtilities.getAccountDetails();
		accttest.z_source__c	= 'Salesgateway';
        insert accttest;
        
        Contact cntcttest = PGITestUtilities.getContactDetails(accttest.id);
        cntcttest.accountid	=  accttest.Id;
        cntcttest.z_source__c	=  'Salesgateway';
        insert cntcttest;

        conman_contract__c cntrcttest1 = new conman_contract__c(Account_Name__c		=	accttest.id
                                                              ,Contract_Status__c	=	'Sent To Customer');
        insert cntrcttest1;

        cntcttest.FirstName	= 'skiptest';
        update cntcttest;

        cntcttest.phone	= '123456';
        update cntcttest;

        cntcttest.MailingCity	= 'kadapa';
        update cntcttest;

        cntcttest.MailingState	= 'AP';
        update cntcttest;

        cntcttest.MailingStreet	= 'AP';
        update cntcttest;

        cntcttest.MailingCountry	= 'India';
        update cntcttest;

        cntcttest.MailingPostalCode	= '123';
        update cntcttest;

        cntcttest.Email	= 'test@123.com';
        update cntcttest;
 
        Test.stopTest();
    }

}