lanecwe-Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ChannelType__c</fullName>
        <description>This is dependent Picklist based on Channel Field.</description>
        <label>Channel Type</label>
        <picklist>
            <picklistValues>
                <fullName>Affinity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User - Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User - Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User - Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub-Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VAR</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IM_AvgAttendees__c</fullName>
        <label>IM-AvgAttendees</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IM_User_ID__c</fullName>
        <externalId>true</externalId>
        <label>IM-User ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ChannelType__c</fullName>
        <inlineHelpText>Default value is Direct.  Do not change unless you work in the Partners channel.</inlineHelpText>
        <label>Channel Type</label>
        <picklist>
            <picklistValues>
                <fullName>Affinity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User - Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User - Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End User - Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub-Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VAR</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IM_AVGATTENDEES__c</fullName>
        <label>IM_AVGATTENDEES</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IM_USER_ID__c</fullName>
        <externalId>true</externalId>
        <label>IM_USER_ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

lanecwe-Prod/src/classes/Test_ShowIMReportController.cls
/*********************************************************************
Name : Test_ShowIMReportController 
Created On : jan 04, 2012  
Created By : Lalit Bohra
Description : Test class for ShowIMReportController controller.
**********************************************************************/
@isTest
private class Test_ShowIMReportController {
	 public static testMethod void testShowIMReportController() {
	 	
	 	Lead objLead= new Lead();
        objLead.Company='Test Company2';
        objLead.LastName='Test Lead2';
        objLead.Status='Open';
        objLead.CurrencyIsoCode='USD';
        objLead.IM_USER_ID__c='TestUser Id11';
        ObjLead.Email='Testing@testsite.com';
        ObjLead.IM_AVGATTENDEES__c=1.0;  
        ObjLead.ChannelType__c = 'Reseller';   
        insert ObjLead; 
        
        Account acc= new Account();
        acc.Name='Test Acc';
        acc.ChannelType__c = 'Reseller'; 
        insert acc;
        
        
       
        Contact con= new Contact(); 
        con.LastName='Test con1';
        con.AccountId=acc.Id;
        con.Email='Testing@testsite.com'; 
        con.IM_USER_ID__c='TestUser1';    
        insert con;
            	
    	PageReference ShowIMReportPage = Page.ShowIMReport;
        Test.setCurrentPage(ShowIMReportPage);
        ApexPages.currentPage().getParameters().put('ReportType', 'Lead'); 
        ApexPages.currentPage().getParameters().put('ImUserId', 'TestUser Id11');
        ShowIMReportController objShowIMReportController= new ShowIMReportController();
        objShowIMReportController.ShowIMReport();
        ApexPages.currentPage().getParameters().put('ReportType', 'Contact'); 
        ApexPages.currentPage().getParameters().put('ImUserId', 'TestUser1');
        objShowIMReportController.ShowIMReport();
        ApexPages.currentPage().getParameters().put('ImUserId', '');
        objShowIMReportController.ShowIMReport();
    }
}