lanecwe-Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SFDC_Account_ID__c</fullName>
        <description>External ID to Inetgrate with TESLA System. TEsla system also host this field and will be in Synch with Salesforce.</description>
        <displayFormat>{0}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Unique Salesforce Refrerence ID and this will be refrenced in TESLA system.</inlineHelpText>
        <label>SFDC Account ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This field is dynamically set.  If it has 0 companies associated to it the value is Prospect.  If it has &gt; 0 companies associated to it then it will be Customer.  There are also some Partner channel specific things that will set the value to Customer.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/CONMAN_Contract__c.object
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used to set the relationship between Conman Contract and Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CONMAN_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>CONMAN_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>z_Source__c</fullName>
        <label>z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>CONMAN Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Z_Source__c</fullName>
        <description>Source Value</description>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Lead.object
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>

lanecwe-Prod/src/objects/LicenseSet__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enterprise_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enterprise Name</label>
        <referenceTo>Offerings__c</referenceTo>
        <relationshipLabel>LicenseSets</relationshipLabel>
        <relationshipName>LicenseSets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Licensed_Named_Users__c</fullName>
        <label>Number of Licensed Named Users</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>LicenseSets</relationshipLabel>
        <relationshipName>LicenseSets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_License_Term_Months__c</fullName>
        <label>Subscription License Term(Months)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>LicenseSet</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LicenseSets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Logs__c.object
<CustomObject>
    <description>This object holds all request and response details from provisioning application for create company and create subscriber API</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndPoint_Url__c</fullName>
        <label>EndPoint Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Cause__c</fullName>
        <label>Exception Cause</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <label>Exception Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <label>Exception Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method_Name__c</fullName>
        <label>Method Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Record_ID__c</fullName>
        <label>Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>holds complete request sent to back office</description>
        <label>Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <description>holds complete response from back office</description>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Failure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PGiLogs</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGiLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>x-Status</label>
        <picklist>
            <picklistValues>
                <fullName>Dead/Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open-Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Session/Needs Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presentation/Proposal/Price Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pilot/Trial/Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation/Verbal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won: Contract/CRA/Booked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

dimagi-SalesforceFB/src/objects/Opportunity.object
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Opportunity.object
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <picklist>
            <picklistValues>
                <fullName>ICBRR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundations (Banking)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Professional Certificate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundations (Energy)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customized Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertisement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Risk Professional (GRP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GDL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FRM Training</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

lanecwe-Prod/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>LicenseSet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LicenseSet</label>
        <referenceTo>LicenseSet__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>z_Source__c</fullName>
        <label>z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Product_Mappings__c.object
<CustomObject>
    <description>Provides mappings between SFDC and other systems</description>
    <fields>
        <fullName>SFDC_PB_Entry_ID__c</fullName>
        <description>ID of SFDC price book entry</description>
        <inlineHelpText>ID of SFDC price book entry</inlineHelpText>
        <label>SFDC PB Entry ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Product_ID__c</fullName>
        <description>Product ID of SFDC product object</description>
        <label>SFDC Product ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Product_Name__c</fullName>
        <description>Product Name of source system</description>
        <inlineHelpText>Product Name of source system</inlineHelpText>
        <label>Source Product Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Product Mappings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/classes/SGLeadCreateREST.cls
/**** This class is REST API used by sales gateway to create Lead. Once Lead is created succesfully trigger logic will convert this Lead.
 Salesgateway scenario: This API will be executed when contract is send to customer.
****/
@RestResource(urlMapping='/SGLeadCreate/*')
global with sharing class SGLeadCreateREST {
  	public static boolean sendemail = false;
    /*** this is the data class used to serialize error message back to SG ***/
    global class SGErrorResponse{
        string errormessage;
    }
    
    /*** This method upserts Lead based on the LeadID passed from SG ***/
    @HttpPost
    global static String SGLeadCreate(){
        string response;
        string errormessage;
        Logs__c logerror 				= new Logs__c();   
        try {
        /*** Recieving data from salesgateway and deserializing into local data class(SGLeadRequest) Format. ***/
        SGLeadRequest SGReqData =  (SGLeadRequest)JSON.deserialize(
                        RestContext.request.requestbody.tostring(),SGLeadRequest.class);
		system.debug('SGReqData:'+SGReqData);
        logerror.Class_Name__c 			= 'SGLeadCreateREST';    
        logerror.Method_Name__c 		= 'SGLeadCreate';
        logerror.Object_Name__c 		= 'Lead';
		logerror.Request__c				= string.valueOf(SGReqData);
        logerror.Z_Source__c			= SGReqData.source;    
        logerror.Status__c				= 'Success';    
        logerror.Error_Message__c		= 'NA';
        logerror.Exception_Cause__c		= 'NA';
        logerror.Exception_Message__c	= 'NA';
        logerror.EndPoint_Url__c		= 'NA';
        logerror.Record_ID__c			= 'NA';
        logerror.Exception_Type__c		= 'NA';
            
        Lead Insertld = setLeadRecord(SGReqData);
        upsert Insertld;
        
        SGSuccessResponse resp 			= new SGSuccessResponse();
        
        Lead ldRespData = [select id, convertedaccountid, convertedcontactid, convertedopportunityid from lead where id = :Insertld.id];

        /*** Invoke method to insert license sets ***/
        List<SGLeadRequest.Products> ProductDetails1 = new List<SGLeadRequest.Products>(SGReqData.ProductsOfInterest);
        logerror.Object_Name__c 		= 'Lead';
        logerror.Method_Name__c 		= 'InsertLicset';
        InsertLicset(ProductDetails1, ldRespData.convertedopportunityid);
        logerror.Object_Name__c 		= 'OpportunityLineItem';
        logerror.Method_Name__c 		= 'Insertproducts';
        Insertproducts(ProductDetails1, ldRespData.convertedopportunityid);
        
        /*** Setting data For success response back to SG ***/
        Account AcctData = [select SFDC_Account_ID__c,(select Id from CONMAN_Contracts__r) from Account where id=:ldRespData.convertedaccountid];
        List<CONMAN_Contract__c> CntractData = new list<CONMAN_Contract__c>(AcctData.CONMAN_Contracts__r);
        //updating just trigger email trigger
        sendemail = true;
        update CntractData;
        sendemail = false;    
            
        resp.SFDCAccountID  			= AcctData.SFDC_Account_ID__c;
        resp.contractId     			= CntractData[0].Id;
        resp.accountId      			= ldRespData.convertedaccountid;
        resp.opportunityId  			= ldRespData.convertedopportunityid;
        resp.contactId  				= ldRespData.convertedcontactid;

        response 						= JSON.serialize(resp);
        Insert logerror;
        return response;
        }
        catch(Exception e){ 
        /*** Setting data For error response back to SG ***/
            SGErrorResponse ErrorData = new SGErrorResponse();
            ErrorData.errormessage =e.getMessage();
            response = JSON.serialize(ErrorData);       

	        logerror.Status__c				= 'Failure';    
	        //logerror.Method_Name__c 		= 'SGLeadCreate';
            logerror.Error_Message__c		= e.getMessage();
            logerror.Exception_Cause__c		= string.valueof(e.getcause());
            logerror.Exception_Message__c	= e.getStackTraceString();
	        logerror.Exception_Type__c		= e.getTypeName();
            logerror.Response__c			= response;
	        Insert logerror;
    
            return response;        
        }
    }

    /*** This method inserts license sets and relates them to opportunity ***/   
    public static Void InsertLicset(List<SGLeadRequest.Products> ProductDetails1, id opptyId){
        List<LicenseSet__c> LicsetToInsert1 = new List<LicenseSet__c>();

        For(SGLeadRequest.Products PrdctsToInsert : ProductDetails1){
            LicenseSet__c LicsetToInsert = new LicenseSet__c();

            If (LicsetToInsert.Enterprise_Name__c <> null)
            	LicsetToInsert.Enterprise_Name__c               = PrdctsToInsert.EnterpriseName;
           
            LicsetToInsert.Product_Name__c						= PrdctsToInsert.ProductName;
            LicsetToInsert.Number_of_Licensed_Named_Users__c    = PrdctsToInsert.Quantity;
            LicsetToInsert.Subscription_License_Term_Months__c  = PrdctsToInsert.Contractterm;
            LicsetToInsert.Start_Date__c                        = date.valueof(PrdctsToInsert.StartDate);
            LicsetToInsert.End_Date__c                          = date.valueof(PrdctsToInsert.EndDate);
            LicsetToInsert.Opportunity__c                       = opptyId;
            LicsetToInsert.z_Source__c                       	= 'Salesgateway';
            LicsetToInsert.Price__c								= PrdctsToInsert.UnitPrice;
               
            If (PrdctsToInsert.Mincommitment == 'true' && PrdctsToInsert.UnitType == 'Minutes'){
    	        LicsetToInsert.Number_of_Licensed_Named_Users__c = PrdctsToInsert.mincmmtamount/PrdctsToInsert.UnitPrice;
            }
            else{
            If (PrdctsToInsert.Mincommitment == 'false' && PrdctsToInsert.UnitType == 'Minutes'){
    	        LicsetToInsert.Number_of_Licensed_Named_Users__c = 300;
            }else{
    	        LicsetToInsert.Number_of_Licensed_Named_Users__c = PrdctsToInsert.Quantity;
            }
            }
            LicsetToInsert1.add(LicsetToInsert);    
      }
      Insert LicsetToInsert1;
    }

    /*** This method inserts opportunity line items (opportunity products) ***/   
    public static Void Insertproducts(List<SGLeadRequest.Products> Opptyproducts, id opptyId){
        List<OpportunityLineItem> Insertproducts = new List<OpportunityLineItem>();
        For(SGLeadRequest.Products PrdctsToInsert : Opptyproducts){
            If(PrdctsToInsert.UnitType == 'Licenses'){
 	            OpportunityLineItem opptyproducts1 					= new OpportunityLineItem();

                Product_Mappings__c productmappings = [select SFDC_Product_ID__c,SFDC_PB_Entry_ID__c from Product_Mappings__c 
                                                       where Source_Product_Name__c = :PrdctsToInsert.ProductName];
                opptyproducts1.OpportunityId						= opptyId;
                opptyproducts1.PricebookEntryId						= productmappings.SFDC_PB_Entry_ID__c;
                opptyproducts1.New_Sales_Price__c					= PrdctsToInsert.UnitPrice;
                opptyproducts1.Billing_Frequency__c    				= PrdctsToInsert.BillingFrequency;
                opptyproducts1.Contract_Term__c						= PrdctsToInsert.Contractterm;
                opptyproducts1.Min_Commit__c  						= boolean.valueof(PrdctsToInsert.mincommitment);
                opptyproducts1.New_Quantity__c				        = PrdctsToInsert.Quantity;
                opptyproducts1.Unit_Type__c				        	= PrdctsToInsert.UnitType;
                opptyproducts1.z_Source__c				        	= 'Salesgateway';
	            
                Insertproducts.add(opptyproducts1);
            } 
            else{
                OpportunityLineItem opptyproducts2 					= new OpportunityLineItem();

                Product_Mappings__c productmappings = [select SFDC_Product_ID__c,SFDC_PB_Entry_ID__c from Product_Mappings__c 
                                                       where Source_Product_Name__c = :PrdctsToInsert.ProductName];
                opptyproducts2.OpportunityId						= opptyId;
                opptyproducts2.PricebookEntryId						= productmappings.SFDC_PB_Entry_ID__c;
                opptyproducts2.New_Sales_Price__c					= PrdctsToInsert.UnitPrice;
                opptyproducts2.Billing_Frequency__c    				= PrdctsToInsert.BillingFrequency;
                opptyproducts2.Contract_Term__c						= PrdctsToInsert.Contractterm;
                opptyproducts2.Min_Commit__c  						= boolean.valueof(PrdctsToInsert.mincommitment);
                opptyproducts2.Unit_Type__c				        	= PrdctsToInsert.UnitType;
                opptyproducts2.z_Source__c				        	= 'Salesgateway';
               
                If (opptyproducts2.Min_Commit__c == true && PrdctsToInsert.UnitType == 'Minutes'){
    	            opptyproducts2.New_Quantity__c				    = PrdctsToInsert.mincmmtamount/PrdctsToInsert.UnitPrice;
                }
                else{
                If (opptyproducts2.Min_Commit__c == false && PrdctsToInsert.UnitType == 'Minutes'){
    	            opptyproducts2.New_Quantity__c				    = 300;
                }else{
    	            opptyproducts2.New_Quantity__c				    = PrdctsToInsert.Quantity;
                }
                }
                Insertproducts.add(opptyproducts2);
            }
        }
        Insert Insertproducts;
    }

    /*** This method prepares data For lead insert ***/   
    public static lead setLeadRecord(SGLeadRequest SGReqData){
       Lead ldInsertData = new Lead();
       /*** Data from Salesgateway ***/
       If(SGReqData.LeadID<> null){
          ldInsertData.ID    			= SGReqData.LeadID;
       }    
       ldInsertData.SlesgatewayID__c    = SGReqData.SlesgatewayID;
       ldInsertData.Company             = SGReqData.Company;
       ldInsertData.FirstName           = SGReqData.CustomerFirstName;
       ldInsertData.LastName            = SGReqData.CustomerLastName;
       ldInsertData.Phone               = SGReqData.Phone;
       ldInsertData.Email               = SGReqData.Email;
       ldInsertData.Street              = SGReqData.Street;
       ldInsertData.City                = SGReqData.City;
       ldInsertData.State               = SGReqData.State;
       ldInsertData.PostalCode          = SGReqData.PostalCode;
       ldInsertData.Country             = SGReqData.Country;
       ldInsertData.ContractURL__c      = SGReqData.ContractURL;
       ldInsertData.z_Source__c			= SGReqData.Source;
       /*** Retrieving rep uer id from user object to set as owner of Lead ***/
       User userdata                    = [select Id from user where LastName = :SGReqData.RepLastName and FirstName = :SGReqData.RepFirstName];
       ldInsertData.OwnerId             = userdata.Id;
       /*** Data from custom Labels ***/
       if(ldInsertData.LeadSource  != null){
       		ldInsertData.LeadSource = System.Label.LeadSource;
       }
       ldInsertData.ChannelType__c      = System.Label.ChannelType;
       ldInsertData.Status              = System.Label.LeadStatus;
       ldInsertData.DoNotCall           = Boolean.valueof(System.Label.DoNotSolicit);
       ldInsertData.Business_Type__c    = integer.valueof(System.Label.BusinessType);
        
        if(ldInsertData.Omniture_Campaign_Code__c != null){
            ldInsertData.Omniture_Campaign_Code__c = System.Label.OmnitureCampaignCode;
        }
       return ldInsertData;
    }
}