lanecwe-Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SlesgatewayID__c</fullName>
        <label>SalesgatewayID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/CONMAN_Contract__c.object
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used to set the relationship between Conman Contract and Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CONMAN_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <label>Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sent To Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>CONMAN_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SlesgatewayID__c</fullName>
        <label>SalesgatewayID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>z_Source__c</fullName>
        <label>z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>CONMAN Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SlesgatewayID__c</fullName>
        <label>SalesgatewayID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

dimagi-SalesforceFB/src/objects/Opportunity.object
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Account.Name</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>

dimagi-SalesforceFB/src/objects/Opportunity.object
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

lanecwe-Prod/src/classes/SGContractAccept_Test.cls
@isTest (SeeAllData = true)
private class SGContractAccept_Test {

    static testMethod void SGContractAccept_Test() {

        Test.startTest();
        
        Account accttest = PGITestUtilities.getAccountDetails();
		accttest.z_source__c	= 'Salesgateway';
		accttest.SlesgatewayID__c	= '123';
        insert accttest;

        Opportunity opptytest = PGITestUtilities.getOpportunityDetails();
		opptytest.z_source__c	= 'Salesgateway';
        opptytest.accountid		= accttest.id;
        insert opptytest;
        
        Contact cntcttest = PGITestUtilities.getContactDetails(accttest.id);
        cntcttest.accountid	=  accttest.Id;
        cntcttest.z_source__c	=  'Salesgateway';
        insert cntcttest;

        conman_contract__c cntrcttest = new conman_contract__c(Account_Name__c		=	accttest.id
                                                              ,Opportunity__c 		= 	opptytest.id
                                                              ,Contract_Status__c	=	'Sent To Customer'
                                                              ,z_source__c			=	'Salesgateway');
        insert cntrcttest;
        
		Attachment atttest = new Attachment();
        atttest.name = 'testattachment';
        atttest.parentid = cntrcttest.id;
        atttest.Description = 'run only for SG';
        atttest.Body = blob.valueOf('test123');
        insert atttest;

        Test.stopTest();
    }

}