lanecwe-Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Channel from Account Owner&apos;s user record</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>ADM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Conferencing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Care/Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Commerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECS Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECS Base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECS SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA : Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA : Base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fin&amp;Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GCS Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GCS Base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GCS Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GCS Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GCS SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GCS Video Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hunters CEUR/NEUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hunters WEUR/SEUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iMeet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IST Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Admin</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Account.object
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>any 3rd party marketing or re-seller relationship</description>
        <label>Partner</label>
    </recordTypes>

lanecwe-Prod/src/objects/Implementation_Services__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <formula>TEXT( Implementation_Owner__r.Channel__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CheckboxForWFRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CheckboxForWFRule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IST_Status__c</fullName>
        <label>Implementation Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Train</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hand-off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No IS Assigned</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Implementation_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Implementation_Services_Owner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Type__c</fullName>
        <label>Customer Type</label>
        <picklist>
            <picklistValues>
                <fullName>Small Business &lt;2K MRR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid-Size &gt;2K but &lt;20K MRR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Enterprise (Domestic)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Enterprise (Global)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Platinum &gt; 75K MRR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner &lt;20K MRR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner &lt;75K MRR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner &lt;5K MRR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Implementation Services</relationshipLabel>
        <relationshipName>Implementation_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Implementation Services</label>
    <nameField>
        <displayFormat>IST-{000000}</displayFormat>
        <label>Implementation Services Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementation Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Implementation_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Implementation_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Only use this if this is a secondary</inlineHelpText>
        <label>Related Implementation Record</label>
        <referenceTo>Implementation_Services__c</referenceTo>
        <relationshipLabel>Secondary Opportunities</relationshipLabel>
        <relationshipName>Secondary_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

dimagi-SalesforceFB/src/objects/Opportunity.object
    <fields>
        <fullName>Implementation_Services__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Potentially interested in Implementation Services</description>
        <inlineHelpText>Potentially interested in Implementation Services</inlineHelpText>
        <label>Implementation Services</label>
        <type>Checkbox</type>
    </fields>

dimagi-SalesforceFB/src/objects/Opportunity.object
    <fields>
        <fullName>Implementation_Type__c</fullName>
        <label>Implementation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bundles and Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed server</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

lanecwe-Prod/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Used to determine what shows up in Product Select VF page</description>
        <inlineHelpText>What regions should be able to see this product when adding to Opps?</inlineHelpText>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>This is a field that is installed by and used with the Adoption Dashboard AppExchange package. If your org already has a similar field, you can change the reports that are part of the Adoption Dashboard package to use your custom field and then delete this field.</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
                <color>#3333FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
                <color>#CC6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TESLA_SALESMANAGER_ID__c</fullName>
        <label>TESLA SALESMANAGER ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TESLA_SalesRep_Email__c</fullName>
        <label>TESLA SalesRep Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/classes/TestSetImplementationOwnerField.cls
/*********************************************************************
Name : TestSetImplementationOwnerField
Created On : Dec 6, 2012  
Created By :  JP
Description : Test class to check functionality of trigger SetImplementationOwnerField on Opportunity  object
**********************************************************************/
@isTest(SeeAllData=true)
private class TestSetImplementationOwnerField{
    static testMethod void UnitTest_SetImplementationOwnerField() {
    test.startTest();
     User u=createUser();  
     List<Id> oppIds = new List<Id>();
     List<Id> ImpSerRecordIds= new List<Id>(); 

	 Account acc= new Account();
     acc.Name='TestAccountSetImplementationOwnerOnOpportunity';
     insert acc;
            
     Opportunity opp1 = new Opportunity();
     opp1.Name = 'test1';
     opp1.AccountId = acc.Id;
     opp1.CloseDate = system.today();
     opp1.StageName = 'Qualification';
     opp1.CurrencyIsoCode = 'USD';
     insert opp1;

	 Product2 standardProduct = PGITestUtilities.getStdProduct();
     insert standardProduct;
     PricebookEntry standardPbe = PGITestUtilities.CreatePriceBookEntryForProduct(standardProduct);
     insert standardPbe;
     OpportunityLineItem oli = PGITestUtilities.getOpportunityLineItemDetails(opp1.Id, standardPbe.Id);
     insert oli;
     
        Implementation_Services__c imp= new Implementation_Services__c();
        imp.Related_Opportunity__c = opp1.Id;
        imp.Implementation_Owner__c = u.Id;
        imp.IST_Status__c = 'Plan';
        imp.CheckboxForWFRule__c = false;
        imp.Implementation_Type__c = 'Partner <5K MMR';
         insert imp; 
         
          /*Implementation_Services__c imp1= new Implementation_Services__c();
        imp1.Related_Opportunity__c = opp1.Id;
        imp1.Implementation_Owner__c = u.Id;
        imp1.IST_Status__c = 'Plan';
        imp1.CheckboxForWFRule__c = false;
        imp1.Implementation_Type__c = 'Partner <5K MMR';
         insert imp1;*/ 
     
        Opportunity opp2 = new Opportunity();
          opp2.Name = 'test1';
          opp2.AccountId = acc.Id;
          opp2.CloseDate = system.today();
          opp2.StageName = 'Qualification';
          opp2.CurrencyIsoCode = 'USD';
          opp2.Related_Implementation_Record__c=imp.id;
           insert opp2;
        
         OpportunityLineItem oli2 = PGITestUtilities.getOpportunityLineItemDetails(opp2.Id, standardPbe.Id);
     	 insert oli2;
           
         /*Opportunity opp3 = new Opportunity();
         opp3.Name = 'test1';
         opp3.AccountId = acc.Id;
         opp3.CloseDate = system.today();
         opp3.StageName = 'Qualification';
         opp3.CurrencyIsoCode = 'USD';
         opp3.Related_Implementation_Record__c=imp1.id;
         insert opp3 ;
           
         OpportunityLineItem oli3 = PGITestUtilities.getOpportunityLineItemDetails(opp3.Id, standardPbe.Id);
     	 insert oli3;*/
            
  ImpSerRecordIds.add(imp.id);
  //ImpSerRecordIds.add(imp1.id);
  
    //oppIds.add(opp3.id ); 
    oppIds.add(opp2.id); 
        
        
       
        
          
    ClassForSetImplementationOwnerField.UpdateOwnerField(oppIds,ImpSerRecordIds);
            test.stopTest();
      
        }
    
     public static User createUser() {
        // need to change these values
        /*List<Profile> profiles = [select Id From Profile where Name = 'System Administrator' limit 1];
        String profileId = profiles.get(0).Id;
        User user = new User();
        user.Email = 'test@pgi.com';
        user.CommunityNickname = 'test@pgi.com';
        user.UserName = 'test@pgi.com.fulldata30';
        user.FirstName = 'Foo';
        user.LastName = 'Bar';
        user.Alias = 'foo';
        user.ProfileId = profileId;
        user.EmailEncodingKey = 'ISO-2022-JP';
        user.LanguageLocaleKey = 'ja';
        user.LocaleSidKey = 'ja_JP';
        user.TimeZoneSidKey = 'Asia/Tokyo';*/
        User user = PGITestUtilities.getTestUser();
        user.TESLA_SalesRep_Email__c ='testing1@testsite.com';
        user.TESLA_SALESMANAGER_ID__c='testsm1';
        user.Region__c='NA';
        user.Channel__c = 'System Admin';
        insert user;
        return user;
    }
}