lanecwe-Prod/src/objects/Account.object
<CustomObject>
</CustomObject>

jlamontSC-test/src/objects/Account.object
    <fields>
        <fullName>Merge_Survivor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merge Survivor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts To Be Merged</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>

lanecwe-Prod/src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Companies</relationshipLabel>
        <relationshipName>Companies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLIENT_COUNT__c</fullName>
        <label>CLIENT_COUNT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Corporate_Entity__c</fullName>
        <formula>Account__r.Parent.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Corporate Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TESLA_CompanyID__c</fullName>
        <label>x-TESLA-CompanyID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TESLA_InactiveDate__c</fullName>
        <label>TESLA-InactiveDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TESLA_IntlCountryCode__c</fullName>
        <label>TESLA-IntlCountryCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TESLA_Territory_Code__c</fullName>
        <label>TESLA Territory Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Contact.object
<CustomObject>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Contact.object
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>80</length>
        <type>Text</type>
    </fields>

lanecwe-Prod/src/objects/Contract.object
<CustomObject>
</CustomObject>

dimagi-SalesforceFB/src/objects/Contract.object
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Temporary field: Used to edit the account field once a contract has been activated.</inlineHelpText>
        <label>New Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>

lanecwe-Prod/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>used in custom lookup fields</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tesla Company Name</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Type__c</fullName>
        <label>X_LFR_Deal Type</label>
        <picklist>
            <picklistValues>
                <fullName>Existing Customer/Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Logo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upsell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Winback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Customer – Rate Change</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>PGI Operating Region</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TESLA_CompanyID__c</fullName>
        <formula>IF(
! ISBLANK(Tesla_Company_ID__c), Tesla_Company_ID__c, 
Company__r.TESLA_IntlCompanyID__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TESLA-Company ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/classes/PGITeslaCompanyLookupController.cls
/********************************************************************************
Name:  PGITeslaCompanyLookupController()
Copyright © 2012  PGI
======================================================
======================================================
Purpose:
-------
This class used to search Tesla company and Contract name
======================================================
======================================================
History
-------
VERSION  AUTHOR                DATE        DETAIL              FEATURES/CSR/TTP
  1.0 – Capgemini India                                                  23/10/2012        Added 
********************************************************************************/  
public with sharing class PGITeslaCompanyLookupController 
{ 
   public string searchString{get;set;} 
   public List<Company__c> results{get; set;}
   public string accountId{get; set;} 
   public string quoteType{get; set;} 
   public PGITeslaCompanyLookupController() {
    
    try{
        searchString = System.currentPageReference().getParameters().get('lksrch');
        accountId = System.currentPageReference().getParameters().get('accountId');
        quoteType = System.currentPageReference().getParameters().get('quoteType');
        results = performSearch(searchString);  
    } catch(Exception ex){
        system.debug('Test'+ex.getMessage());
    }  
  }
 
  public PageReference search() {
    try{        
        results= performSearch(searchString);      
    }catch (Exception ex){
            PGIErrorUtilities.logPgiError('PGITeslaCompanyLookupController:search()',ex.getMessage(),PGIErrorUtilities.LoggingLevel.INFO);
            system.debug(LoggingLevel.ERROR,'Error When searching Tesla company '+ex.getMessage());
        }

     return null;
  }
   
  private List<company__c> performSearch(string searchString) 
  {
       string strSoql = '';
       system.debug('test'+quoteType);
       if(quoteType.equalsIgnoreCase('Existing Customer/Renewal')  || quoteType.equalsIgnoreCase('Existing Customer – Rate Change'))
       {
            strSoql = 'select id, name ,TESLA_CompanyID__c,Account__r.name,CLIENT_COUNT__c,Corporate_Entity__c,Region__c,TESLA_IntlCountryCode__c,TESLA_Territory_Code__c,TESLA_InactiveDate__c from company__c ';
            if(searchString != '' && searchString != null)
            {
                strSoql = strSoql +  ' where Account__c=:accountId and  name LIKE \'' + searchString +'%\'';
                strSoql = strSoql + ' limit 45';
            }
            else
                strSoql = strSoql +  ' where Account__c=:accountId LIMIT 25';
            
            return database.query(strSoql); 
        }  
        else
           return(new List<company__c>());
  }
    
  public string getFormTag() {
    return System.currentPageReference().getParameters().get('frm');
  }
 
  public string getTextBox() {
    return System.currentPageReference().getParameters().get('txt');
  }
   //Test method for PGITeslaCompanyLookupController
   public static testMethod void TestPGITeslaCompanyLookupController(){
        Account testAcc= PGITestUtilities.getAccountDetails();
        insert testAcc;
        Opportunity testOpp= PGITestUtilities.getOpportunityDetails();      
        insert testOpp;
        Contact cont= PGITestUtilities.getContactDetails(testAcc.Id); 
        insert cont;
        Quote testQuote= PGITestUtilities.getQuoteDetails(testAcc.Id, cont.Id ,testOpp.Id); 
        testQuote.Quote_Type__c='Existing Customer/Renewal';
        insert testQuote;
        Company__c testCompany=PGITestUtilities.getCompany(testAcc.Id);
        insert testCompany;
        Test.startTest();
        PageReference pref=Page.PGITeslaCompanySearch;
        PGITestUtilities.setTestParameter('Id',testQuote.Id);  
        pref.getParameters().put('accountId',testAcc.Id);
        pref.getParameters().put('quoteType',testQuote.Quote_Type__c);
        pref.getParameters().put('lksrch','test');
        Test.setCurrentPage(pref);
        PGITeslaCompanyLookupController con= new PGITeslaCompanyLookupController();
        pref=con.search();
        con.getFormTag();
        con.getTextBox();
        system.assertEquals(con.quoteType,testquote.Quote_Type__c);
        system.assertEquals(con.searchString,'test');
        system.assertEquals(con.results.size(),1);
        Test.stopTest();
   }
 
}