lanecwe-Prod/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Assignment_Date__c</fullName>
        <label>Assignment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECommerce_Account_Number__c</fullName>
        <label>ECommerce Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enterprise Name</label>
        <referenceTo>Offerings__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License Name</label>
        <referenceTo>LicenseSet__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <description>1st Round Moderator Integration 12/11/2013</description>
        <label>Client ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECommerce_Account_Number__c</fullName>
        <label>ECommerce Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/LicenseSet__c.object
<CustomObject>
    <fields>
        <fullName>CompanyID__c</fullName>
        <label>CompanyID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enterprise_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enterprise Name</label>
        <referenceTo>Offerings__c</referenceTo>
        <relationshipLabel>LicenseSets</relationshipLabel>
        <relationshipName>LicenseSets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Licensed_Named_Users__c</fullName>
        <label>Number of Licensed Named Users</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>LicenseSets</relationshipLabel>
        <relationshipName>LicenseSets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <label>SKU</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_License_Term_Months__c</fullName>
        <label>Subscription License Term(Months)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>LicenseSet</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LicenseSets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Offerings__c.object
<CustomObject>
    <description>This object is used for E-commerce and LMS product mappings</description>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <label>SKU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Offerings</label>
    <nameField>
        <label>Enterprise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offerings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Custom field used to map Lead Description to Opportunity Description. By default, SFDC only maps the Lead Description field to the Contact Description field. This will allow for it to also be mapped to the Opportunity via Lead Mapping. A workflow rule on Opportunity will then update the standard Opportunity Description field on the page layout from this custom field.</description>
        <label>Description__c</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ECommerce_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>ECommerce Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Z_Source__c</fullName>
        <label>Z-Source</label>
        <picklist>
            <picklistValues>
                <fullName>eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesgateway</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

dimagi-SalesforceFB/src/objects/Opportunity.object
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

lanecwe-Prod/src/classes/RetrieveAssets.cls
@RestResource(urlMapping='/RetrieveAssets/*')
global with sharing class  RetrieveAssets{
    public static map<id, list<asset>> licsetAssetMap = new map<id, list<asset>>();

    global class AssetsResponse{
        //string transactionId;        
        public String errorMessage;
        public String accountId;
        public list<LicenseSetRecord> licenseSetList;
    }

    global class LicenseSetRecord{
        public list<AssetsRecord> assetsList;
        public String licenseSetId;
        public String  companyID;
        public String  description;
        public Date    endDate;
        public String  enterpriseName;
        public Integer lineNumber;
        public Integer numberOfLicensedNamedUsers;
        public String  opportunityId;
        public String  accountId;
        public Integer orderNumber;
        public Decimal price;
        public String  sku;
        public Date    startDate;
        public Integer subscriptionLicenseTermMonths;
    }

    global class AssetsRecord{
        public String  assetId;
        public Date    assignmentDate;
        public String  clientID;
        public String  eCommerceAccountNumber;
        public String  licenseSetId;
        public String  opportunityId;
        public Date    terminationDate;
        public String  accountId;
        public String  contactId;
        public String  firstname;
        public String  lastname;      
    }
    
    @HttpGet
    global static AssetsResponse retrieveRecord(){
        AuditLog audtLog    = new AuditLog('RetrieveAssets ','retrieveRecord');
        AssetsResponse resp = new AssetsResponse();
        try{
            RestRequest req = RestContext.request;
            RestResponse res = RestContext.response;
            audtLog.logRequestInfo(req.requestURI);
            String accountId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);           
            /*
            AssetsRequest assetReq =  (AssetsRequest)JSON.deserializestrict(
                            RestContext.request.requestbody.tostring(),AssetsRequest.class);
            //resp.transactionId  = assetReq.transactionId;*/
            resp.accountId      = accountId;
            list<Licenseset__c> licSetLst = [select id, name, CompanyID__c, Description__c, End_Date__c, 
                                                 Enterprise_Name__c, Enterprise_Name__r.name, 
                                                 Line_Number__c, Number_of_Licensed_Named_Users__c, Opportunity__c, Opportunity__r.AccountId, 
                                                 Order_Number__c, Price__c, SKU__c, Start_Date__c,Subscription_License_Term_Months__c
                                                /*(
                                                    select  id, name,Assignment_Date__c, Client_ID__c, ECommerce_Account_Number__c, 
                                                            License_Name__c, Opportunity__c, Termination_Date__c, accountid 
                                                        from Assets
                                                )*/
                                            from 
                                                LicenseSet__c where opportunity__r.accountid = :accountId];
            if(licSetLst <> null && licSetLst.size()>0){
                list<LicenseSetRecord> licenseSetRecordList = new list<LicenseSetRecord>();

                for(Asset ast:[select  id, name,Assignment_Date__c, Client_ID__c, ECommerce_Account_Number__c, Z_Source__c,
                                License_Name__c, Opportunity__c, Termination_Date__c, accountid, contactid, contact.firstname, contact.lastname   
                            from Asset where   License_Name__c in :licSetLst]){
                    list<asset> astLst = (licsetAssetMap.containskey(ast.License_Name__c)) ? licsetAssetMap.get(ast.License_Name__c):new list<asset>();
                    audtLog.logSourceSystem(ast.Z_Source__c);
                    astLst.add(ast);
                    licsetAssetMap.put(ast.License_Name__c, astLst);
                }                           
                for(Licenseset__c licset:licSetLst){
                    licenseSetRecordList.add(setLicenseSetRecord(licset));
                }
                resp.licenseSetList     =   licenseSetRecordList;
            }
            else{
                resp.errorMessage = 'No Record Found';
            }
            
            audtLog.logRecordId(resp.accountId);
            
            system.debug('resp: ' + resp);
            audtLog.logResponseInfo(JSON.serialize(resp));
            audtLog.logStatusInfo('Success');
            audtLog.saveLog();
        }
        catch(Exception e){
            audtLog.logRecordId(resp.accountId);
            system.debug('resp: ' + resp);
            resp.errorMessage = e.getMessage();
            audtLog.logResponseInfo(JSON.serialize(resp));
            audtLog.logStatusInfo('Failure');
            audtLog.saveLog();
        }
            
       return resp;
    }
   
    public static LicenseSetRecord setLicenseSetRecord(Licenseset__c licset){
       
        LicenseSetRecord licsetRecord = new LicenseSetRecord();

        licsetRecord.licenseSetId               =   licset.id;
        licsetRecord.companyID                  =   licset.CompanyID__c;
        licsetRecord.description                =   licset.Description__c;
        licsetRecord.endDate                    =   licset.End_Date__c;
        licsetRecord.enterpriseName             =   licset.Enterprise_Name__r.name;
        licsetRecord.lineNumber                 =   (licset.Line_Number__c == null )?0:Integer.valueof(licset.Line_Number__c);
        licsetRecord.numberOfLicensedNamedUsers =   (licset.Number_of_Licensed_Named_Users__c == null)?0:Integer.valueof(licset.Number_of_Licensed_Named_Users__c);
        licsetRecord.opportunityId              =   licset.Opportunity__c;
        licsetRecord.accountId                  =   licset.Opportunity__r.AccountId;
        licsetRecord.orderNumber                =   (licset.Order_Number__c == null)?0:Integer.valueOf(licset.Order_Number__c);
        licsetRecord.price                      =   licset.Price__c;
        licsetRecord.sku                        =   licset.SKU__c;
        licsetRecord.startDate                  =   licset.Start_Date__c;
        licsetRecord.subscriptionLicenseTermMonths  = (licset.Subscription_License_Term_Months__c == null)?0:Integer.valueof(licset.Subscription_License_Term_Months__c);
        
        if(licsetAssetMap <> null && licsetAssetMap.containskey(licset.id)){
            licsetRecord.assetsList = setAssetsRecord(licsetAssetMap.get(licset.id));
        }
        return licsetRecord;
    }
    
    public static list<AssetsRecord> setAssetsRecord(list<Asset> assetLst){
        list<AssetsRecord> astRecordLst = new list<AssetsRecord>();
        for(Asset ast: assetLst){
            AssetsRecord astRecord = new AssetsRecord();
            astRecord.assetId           =   ast.id;
            astRecord.assignmentDate    =   ast.Assignment_Date__c;
            astRecord.clientID          =   ast.Client_ID__c;
            astRecord.eCommerceAccountNumber    =   ast.ECommerce_Account_Number__c;
            astRecord.licenseSetId      =   ast.License_Name__c;
            astRecord.opportunityId     =   ast.Opportunity__c;
            astRecord.terminationDate   =   ast.Termination_Date__c;
            astRecord.accountId         =   ast.accountid;
            astRecord.contactId         =   ast.contactid;
            astRecord.firstname         =   ast.contact.firstname;
            astRecord.lastname          =   ast.contact.lastname;
            astRecordLst.add(astRecord);
        }
        return astRecordLst;
    }
}