lanecwe-Prod/src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>PGi</fullName>
        <active>true</active>
        <businessProcess>SFDC Support</businessProcess>
        <label>SFDC Support</label>
    </recordTypes>
</CustomObject>

lanecwe-Prod/src/objects/Contract.object
<CustomObject>
</CustomObject>

dimagi-SalesforceFB/src/objects/Contract.object
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Temporary field: Used to edit the account field once a contract has been activated.</inlineHelpText>
        <label>New Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>

lanecwe-Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opp_Stage__c</fullName>
        <label>Opp Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Identify Target</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Session/Needs Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal/Price Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pilot/Trial/Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation/Verbal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won - Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won - Implementation Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualify Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Develop Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Develop Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gain Commitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiate Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obtain Final Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkout</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Annual_Value__c</fullName>
        <inlineHelpText>Calculated from the total of all Product Annual Value&apos;s associated with this opportunity.</inlineHelpText>
        <label>ACV</label>
        <summarizedField>OpportunityLineItem.Annual_Value__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.isReportable_Text__c</field>
            <operation>equals</operation>
            <value>Valid</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/QCStatusValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Stores the values of Quote.Status picklist field to be used in apex code.</description>
    <fields>
        <fullName>StatusValue__c</fullName>
        <label>StatusValue</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Q/C Status Values</label>
</CustomObject>

lanecwe-Prod/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>used in custom lookup fields</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Annual_value__c</fullName>
        <description>Calculated from the total of all Quote Line Items Annual Value&apos;s associated with this Quote.</description>
        <label>Annual Contract Value</label>
        <summarizedField>QuoteLineItem.Annual_value__c</summarizedField>
        <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Contract_Value__c</fullName>
        <description>Calculated from the total of all Quote Line Items Contract Value&apos;s associated with this Quote</description>
        <label>TCV</label>
        <summarizedField>QuoteLineItem.Contract_Value__c</summarizedField>
        <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_MRR__c</fullName>
        <description>Calculated from the total of all QuoteLine Items MRR&apos;s associated with this Quote</description>
        <label>Total MRR</label>
        <summarizedField>QuoteLineItem.MRR__c</summarizedField>
        <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/classes/PGIAllQuotesInAccountController.cls
/*


 ********************************************************************************
Name:  PGIAllQuotesInAccountController()
Copyright © 2012  PGI
======================================================
======================================================
Purpose:
-------
This class used to show all Quotes in Account which status is not "Contract signed by Customer"
======================================================
======================================================
History
-------
VERSION  AUTHOR                DATE        DETAIL              FEATURES/CSR/TTP
  1.0 – Capgemini India                                                  11/12/2012        Added 
******************************************************************************* 
*/
public with sharing class PGIAllQuotesInAccountController 
{
    
    public String accId{get; set;}
    public list<Quote> allAccQuotes {get; set;}
     public PGIAllQuotesInAccountController(ApexPages.StandardController controller) 
        {
            try
            {
                accId = Apexpages.currentPage().getParameters().get('Id');
                allAccQuotes = new list<Quote>();
                if(accId != null)
                {
                allAccQuotes = [Select  q.Name, q.Id, q.ExpirationDate, q.CreatedDate,q.Total_Contract_Value__c,q.Total_MRR__c,q.Total_Annual_value__c,q.Status,
                                    q.CreatedById From Quote q where account__c =: accId and Quote.Status !=:QCStatusValues__c.getInstance(PGIQuoteStatusEnum.ContractSignedbyCustomer.name()).StatusValue__c  ]; 
                                     }
            }catch(Exception ex)  
           {     
                system.debug('test error'+ex);
           }
        
    }   
    
    //Test Method for PGIQuoteCloneController
        @istest (seeAlldata = true)
    public static  void testPGIAllQuotesInAccountController()
    {
         //Test Data
         Account testacc= PGITestUtilities.getAccountDetails();
         insert testacc;
         Contact testcon=PGITestUtilities.getContactDetails(testacc.Id); 
         insert testcon;
         Opportunity testopp=PGITestUtilities.getOpportunityDetails();
         testopp.Opp_Stage__c = 'Proposal/Price Quote';
         insert testopp;
         Quote testquote=PGITestUtilities.getQuoteDetails(testacc.Id,testcon.Id, testopp.Id);
         testquote.status = QCStatusValues__c.getInstance(PGIQuoteStatusEnum.Approved.name()).StatusValue__c;
         insert testquote;
         //case 1: +ve
                 //Set Page Params
                 PGITestUtilities.setTestParameter('id',testacc.id);        
                 PGIAllQuotesInAccountController testCase1PGIConst= new PGIAllQuotesInAccountController(PGITestUtilities.getStandardController(testacc));
         //case 2: +ve
                 //Set Page Params
                 PGITestUtilities.setTestParameter('id',testquote.id);        
                 PGIAllQuotesInAccountController testCase2PGIConst= new PGIAllQuotesInAccountController(PGITestUtilities.getStandardController(testquote));
         test.startTest(); 
        
         //Case 1:
                 system.assertEquals(testCase1PGIConst.accId,testacc.id);
                 //Case 2:
                
                  test.stopTest();
                 
    }   
}