lanecwe-Prod/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting/Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service/Care/Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exec - &quot;C&quot; Level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR Generalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR Recruiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT/IS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IM_Account_Cancelled__c</fullName>
        <label>IM-Account Cancelled</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_AvgAttendees__c</fullName>
        <label>IM-AvgAttendees</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IM_BillToFirstName__c</fullName>
        <label>IM-BillToFirstName</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_BillToLastName__c</fullName>
        <label>IM-BillToLastName</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_BillingStartDate__c</fullName>
        <label>IM-BillingStartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_Company__c</fullName>
        <label>IM-Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_CreditCardOnFile__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IM-CreditCardOnFile</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IM_Last_Room_Login__c</fullName>
        <label>IM-Last Room Login</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_Last_iMeet_Room_Login__c</fullName>
        <label>IM-Last iMeet Room Login</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_Location__c</fullName>
        <label>IM-Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_MaxAttendees__c</fullName>
        <label>IM-MaxAttendees</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IM_MeetingsLast30Days__c</fullName>
        <label>IM-MeetingsLast30Days</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IM_MeetingsLast60Days__c</fullName>
        <label>IM-MeetingsLast60Days</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IM_MeetingsLast90Days__c</fullName>
        <label>IM-MeetingsLast90Days</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IM_MostRecentMeeting__c</fullName>
        <label>IM-MostRecentMeeting</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_OfferExpires__c</fullName>
        <label>IM-OfferExpires</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_PGiClientID__c</fullName>
        <label>IM-PGiClientID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_PGi_Acct_ID__c</fullName>
        <label>IM-PGi Acct ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_Phone_1__c</fullName>
        <label>IM-Phone 1</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_Phone_2__c</fullName>
        <label>IM-Phone 2</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_Room_URL__c</fullName>
        <label>IM-Room URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>IM_Sign_up_Date__c</fullName>
        <label>IM-Sign-up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_Text_Notification__c</fullName>
        <label>IM-Text Notification #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_Total_Meetings__c</fullName>
        <label>IM-Total Meetings</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IM_Updated_At__c</fullName>
        <label>IM-Updated At</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_UsageDeleteDate__c</fullName>
        <label>IM-UsageDeleteDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_User_ID__c</fullName>
        <externalId>true</externalId>
        <label>IM-User ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_WebCamUsed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IM-WebCamUsed</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Company_Name_Kana__c</fullName>
        <label>Company Name (Kana)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name_Kanji__c</fullName>
        <label>Company Name (Asian Char)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting/Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service/Care/Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exec - &quot;C&quot; Level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR Generalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR Recruiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT/IS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IM_ACCOUNT_CANCELLED__c</fullName>
        <label>IM_ACCOUNT_CANCELLED</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_AVGATTENDEES__c</fullName>
        <label>IM_AVGATTENDEES</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IM_BILLINGSTARTDATE__c</fullName>
        <label>IM_BILLINGSTARTDATE</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_BILLTOFIRSTNAME__c</fullName>
        <label>IM_BILLTOFIRSTNAME</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_BILLTOLASTNAME__c</fullName>
        <label>IM_BILLTOLASTNAME</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_COMPANY__c</fullName>
        <label>IM_COMPANY</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_CREDITCARDONFILE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IM_CREDITCARDONFILE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IM_LAST_IMEET_ROOM_LOGIN__c</fullName>
        <label>IM_LAST_IMEET_ROOM_LOGIN</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_LAST_ROOM_LOGIN__c</fullName>
        <label>IM_LAST_ROOM_LOGIN</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_LOCATION__c</fullName>
        <label>IM_LOCATION</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_MAXATTENDEES__c</fullName>
        <label>IM_MAXATTENDEES</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IM_MEETINGSLAST30DAYS__c</fullName>
        <label>IM_MEETINGSLAST30DAYS</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IM_MEETINGSLAST60DAYS__c</fullName>
        <label>IM_MEETINGSLAST60DAYS</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IM_MEETINGSLAST90DAYS__c</fullName>
        <label>IM_MEETINGSLAST90DAYS</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IM_MOSTRECENTMEETING__c</fullName>
        <label>IM_MOSTRECENTMEETING</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_OFFEREXPIRES__c</fullName>
        <label>IM_OFFEREXPIRES</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_PGICLIENTID__c</fullName>
        <label>IM_PGICLIENTID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_PGI_ACCT_ID__c</fullName>
        <label>IM_PGI_ACCT_ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_PHONE_1__c</fullName>
        <label>IM_PHONE_1</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_PHONE_2__c</fullName>
        <label>IM_PHONE_2</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_ROOM_URL__c</fullName>
        <label>IM_ROOM_URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>IM_SIGN_UP_DATE__c</fullName>
        <label>IM_SIGN_UP_DATE</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_TEXT_NOTIFICATION__c</fullName>
        <label>IM_TEXT_NOTIFICATION #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_TOTAL_MEETINGS__c</fullName>
        <label>IM_TOTAL_MEETINGS</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IM_UPDATED_AT__c</fullName>
        <label>IM_UPDATED_AT</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_USAGEDELETEDATE__c</fullName>
        <label>IM_USAGEDELETEDATE</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_USER_ID__c</fullName>
        <externalId>true</externalId>
        <label>IM_USER_ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IM_WEBCAMUSED__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IM_WEBCAMUSED</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TESLA_SALESMANAGER_ID__c</fullName>
        <label>x-TESLA SALESMANAGER ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/classes/x_PGIUpdateExistingLeadAndContactsHelper.cls
public with sharing class x_PGIUpdateExistingLeadAndContactsHelper {
	//Improve code coverage
	public static void inactive(){
	}
    // this function will copy new lead fields to existing contact
    /*public static void UpdateExistingContactFromNewLead(Contact ExistingContact,Lead NewLead){
        
        try{       
         //   system.debug('we are calling  UpdateExistingContactFromNewLead------------------');
         //   system.debug('------------------ NewLead'+ NewLead);
         
         system.debug('------------------ ExistingContactId'+ ExistingContact.id);
            if(NewLead.IM_AVGATTENDEES__c != null){
                ExistingContact.IM_AVGATTENDEES__c=NewLead.IM_AVGATTENDEES__c;
            }
            if(NewLead.IM_BILLINGSTARTDATE__c != null){
                ExistingContact.IM_BILLINGSTARTDATE__c=NewLead.IM_BILLINGSTARTDATE__c;
            }
            if(NewLead.IM_BILLTOFIRSTNAME__c != null && NewLead.IM_BILLTOFIRSTNAME__c !=''){
                ExistingContact.IM_BILLTOFIRSTNAME__c=NewLead.IM_BILLTOFIRSTNAME__c;
            }
            if(NewLead.IM_BILLTOLASTNAME__c != null && NewLead.IM_BILLTOLASTNAME__c !=''){
                ExistingContact.IM_BILLTOLASTNAME__c=NewLead.IM_BILLTOLASTNAME__c;
            }
            if(NewLead.IM_COMPANY__c != null && NewLead.IM_COMPANY__c !=''){
                ExistingContact.IM_COMPANY__c=NewLead.IM_COMPANY__c;
            }
            if(NewLead.IM_CREDITCARDONFILE__c != null){
                ExistingContact.IM_CREDITCARDONFILE__c=NewLead.IM_CREDITCARDONFILE__c;
            }
            if(NewLead.IM_LAST_IMEET_ROOM_LOGIN__c != null){
                ExistingContact.IM_LAST_IMEET_ROOM_LOGIN__c=NewLead.IM_LAST_IMEET_ROOM_LOGIN__c;
            }
            if(NewLead.IM_LAST_ROOM_LOGIN__c != null){
                ExistingContact.IM_LAST_ROOM_LOGIN__c=NewLead.IM_LAST_ROOM_LOGIN__c;
            }
            if(NewLead.IM_LOCATION__c != null && NewLead.IM_LOCATION__c !=''){
                ExistingContact.IM_LOCATION__c=NewLead.IM_LOCATION__c;
            }
            if(NewLead.IM_MAXATTENDEES__c != null){
                ExistingContact.IM_MAXATTENDEES__c=NewLead.IM_MAXATTENDEES__c;
            }
            if(NewLead.IM_MEETINGSLAST30DAYS__c != null){
                ExistingContact.IM_MEETINGSLAST30DAYS__c=NewLead.IM_MEETINGSLAST30DAYS__c;
            }
            if(NewLead.IM_MEETINGSLAST60DAYS__c != null){
                ExistingContact.IM_MEETINGSLAST60DAYS__c=NewLead.IM_MEETINGSLAST60DAYS__c;
            }
            if(NewLead.IM_MEETINGSLAST90DAYS__c != null){
                ExistingContact.IM_MEETINGSLAST90DAYS__c=NewLead.IM_MEETINGSLAST90DAYS__c;
            }
            if(NewLead.IM_MOSTRECENTMEETING__c != null){
                ExistingContact.IM_MOSTRECENTMEETING__c=NewLead.IM_MOSTRECENTMEETING__c;
            }
            if(NewLead.IM_OFFEREXPIRES__c != null){
                ExistingContact.IM_OFFEREXPIRES__c=NewLead.IM_OFFEREXPIRES__c;
            }
            if(NewLead.IM_PGI_ACCT_ID__c != null && NewLead.IM_PGI_ACCT_ID__c !=''){
                ExistingContact.IM_PGI_ACCT_ID__c=NewLead.IM_PGI_ACCT_ID__c;
            }
            if(NewLead.IM_PGICLIENTID__c != null && NewLead.IM_PGICLIENTID__c !=''){
                ExistingContact.IM_PGICLIENTID__c=NewLead.IM_PGICLIENTID__c;
            }
            if(NewLead.IM_PHONE_1__c != null && NewLead.IM_PHONE_1__c !=''){
                ExistingContact.IM_PHONE_1__c=NewLead.IM_PHONE_1__c;
            }
            if(NewLead.IM_PHONE_2__c != null && NewLead.IM_PHONE_2__c !=''){
                ExistingContact.IM_PHONE_2__c=NewLead.IM_PHONE_2__c;
            }
            if(NewLead.IM_ROOM_URL__c != null && NewLead.IM_ROOM_URL__c !=''){
                ExistingContact.IM_ROOM_URL__c=NewLead.IM_ROOM_URL__c;
            }           
            if(NewLead.IM_SIGN_UP_DATE__c != null){
                ExistingContact.IM_SIGN_UP_DATE__c=NewLead.IM_SIGN_UP_DATE__c;
            }
            if(NewLead.IM_TEXT_NOTIFICATION__c != null && NewLead.IM_TEXT_NOTIFICATION__c !=''){
                ExistingContact.IM_TEXT_NOTIFICATION__c=NewLead.IM_TEXT_NOTIFICATION__c;
            }
            if(NewLead.IM_TOTAL_MEETINGS__c != null){
                ExistingContact.IM_TOTAL_MEETINGS__c=NewLead.IM_TOTAL_MEETINGS__c;
            }           
            if(NewLead.IM_UPDATED_AT__c != null ){
                ExistingContact.IM_UPDATED_AT__c=NewLead.IM_UPDATED_AT__c;
            }
            if(NewLead.IM_USAGEDELETEDATE__c != null ){
                ExistingContact.IM_USAGEDELETEDATE__c=NewLead.IM_USAGEDELETEDATE__c;
            }
            if(NewLead.IM_USER_ID__c != null && NewLead.IM_USER_ID__c !=''){
                ExistingContact.IM_USER_ID__c=NewLead.IM_USER_ID__c;
            }
            if(NewLead.IM_WEBCAMUSED__c != null){
                ExistingContact.IM_WEBCAMUSED__c=NewLead.IM_WEBCAMUSED__c;
            }       
            if(NewLead.IM_ACCOUNT_CANCELLED__c != null){
                ExistingContact.IM_ACCOUNT_CANCELLED__c=NewLead.IM_ACCOUNT_CANCELLED__c;
            }  
        }
        catch(exception ex){
           // system.debug('----------- exception '+ex);
        }
    }
        
    // this function will copy new lead fields to existing lead
    public static void UpdateLeadFields(Lead OldLead,Lead NewLead){        
        try{
            system.debug('we are calling  UpdateLeadFields------------------');
            system.debug('------------------ NewLead'+ NewLead);
              
            if(NewLead.Company_Name_Kana__c != null && NewLead.Company_Name_Kana__c !=''){
                OldLead.Company_Name_Kana__c=NewLead.Company_Name_Kana__c;
            }
            if(NewLead.Company_Name_Kanji__c != null && NewLead.Company_Name_Kanji__c !=''){
                OldLead.Company_Name_Kanji__c=NewLead.Company_Name_Kanji__c;
            }
            if(NewLead.Department__c != null && NewLead.Department__c !=''){
                OldLead.Department__c=NewLead.Department__c;
            }       
            if(NewLead.IM_ACCOUNT_CANCELLED__c != null){
                OldLead.IM_ACCOUNT_CANCELLED__c=NewLead.IM_ACCOUNT_CANCELLED__c;
            }       
            if(NewLead.IM_AVGATTENDEES__c != null){
                OldLead.IM_AVGATTENDEES__c=NewLead.IM_AVGATTENDEES__c;
            }
            if(NewLead.IM_BILLINGSTARTDATE__c != null){
                OldLead.IM_BILLINGSTARTDATE__c=NewLead.IM_BILLINGSTARTDATE__c;
            }
            if(NewLead.IM_BILLTOFIRSTNAME__c != null && NewLead.IM_BILLTOFIRSTNAME__c !=''){
                OldLead.IM_BILLTOFIRSTNAME__c=NewLead.IM_BILLTOFIRSTNAME__c;
            }
            if(NewLead.IM_BILLTOLASTNAME__c != null && NewLead.IM_BILLTOLASTNAME__c !=''){
                OldLead.IM_BILLTOLASTNAME__c=NewLead.IM_BILLTOLASTNAME__c;
            }
            if(NewLead.IM_COMPANY__c != null && NewLead.IM_COMPANY__c !=''){
                OldLead.IM_COMPANY__c=NewLead.IM_COMPANY__c;
            }
            if(NewLead.IM_CREDITCARDONFILE__c != null){
                OldLead.IM_CREDITCARDONFILE__c=NewLead.IM_CREDITCARDONFILE__c;
            }
            if(NewLead.IM_LAST_IMEET_ROOM_LOGIN__c != null){
                OldLead.IM_LAST_IMEET_ROOM_LOGIN__c=NewLead.IM_LAST_IMEET_ROOM_LOGIN__c;
            }
            if(NewLead.IM_LAST_ROOM_LOGIN__c != null){
                OldLead.IM_LAST_ROOM_LOGIN__c=NewLead.IM_LAST_ROOM_LOGIN__c;
            }
            if(NewLead.IM_LOCATION__c != null && NewLead.IM_LOCATION__c !=''){
                OldLead.IM_LOCATION__c=NewLead.IM_LOCATION__c;
            }
            if(NewLead.IM_MAXATTENDEES__c != null){
                OldLead.IM_MAXATTENDEES__c=NewLead.IM_MAXATTENDEES__c;
            }
            if(NewLead.IM_MEETINGSLAST30DAYS__c != null){
                OldLead.IM_MEETINGSLAST30DAYS__c=NewLead.IM_MEETINGSLAST30DAYS__c;
            }
            if(NewLead.IM_MEETINGSLAST60DAYS__c != null){
                OldLead.IM_MEETINGSLAST60DAYS__c=NewLead.IM_MEETINGSLAST60DAYS__c;
            }
            if(NewLead.IM_MEETINGSLAST90DAYS__c != null){
                OldLead.IM_MEETINGSLAST90DAYS__c=NewLead.IM_MEETINGSLAST90DAYS__c;
            }
            if(NewLead.IM_MOSTRECENTMEETING__c != null){
                OldLead.IM_MOSTRECENTMEETING__c=NewLead.IM_MOSTRECENTMEETING__c;
            }
            if(NewLead.IM_OFFEREXPIRES__c != null){
                OldLead.IM_OFFEREXPIRES__c=NewLead.IM_OFFEREXPIRES__c;
            }
            if(NewLead.IM_PGI_ACCT_ID__c != null && NewLead.IM_PGI_ACCT_ID__c !=''){
                OldLead.IM_PGI_ACCT_ID__c=NewLead.IM_PGI_ACCT_ID__c;
            }
            if(NewLead.IM_PGICLIENTID__c != null && NewLead.IM_PGICLIENTID__c !=''){
                OldLead.IM_PGICLIENTID__c=NewLead.IM_PGICLIENTID__c;
            }
            if(NewLead.IM_PHONE_1__c != null && NewLead.IM_PHONE_1__c !=''){
                OldLead.IM_PHONE_1__c=NewLead.IM_PHONE_1__c;
            }
            if(NewLead.IM_PHONE_2__c != null && NewLead.IM_PHONE_2__c !=''){
                OldLead.IM_PHONE_2__c=NewLead.IM_PHONE_2__c;
            }
            if(NewLead.IM_ROOM_URL__c != null && NewLead.IM_ROOM_URL__c !=''){
                OldLead.IM_ROOM_URL__c=NewLead.IM_ROOM_URL__c;
            }
            if(NewLead.TESLA_SALESMANAGER_ID__c != null && NewLead.TESLA_SALESMANAGER_ID__c !=''){
                OldLead.TESLA_SALESMANAGER_ID__c=NewLead.TESLA_SALESMANAGER_ID__c;
            }
            if(NewLead.IM_SIGN_UP_DATE__c != null){
                OldLead.IM_SIGN_UP_DATE__c=NewLead.IM_SIGN_UP_DATE__c;
            }
            if(NewLead.IM_TEXT_NOTIFICATION__c != null && NewLead.IM_TEXT_NOTIFICATION__c !=''){
                OldLead.IM_TEXT_NOTIFICATION__c=NewLead.IM_TEXT_NOTIFICATION__c;
            }
            if(NewLead.IM_TOTAL_MEETINGS__c != null){
                OldLead.IM_TOTAL_MEETINGS__c=NewLead.IM_TOTAL_MEETINGS__c;
            }
            if(NewLead.IM_UPDATED_AT__c != null ){
                OldLead.IM_UPDATED_AT__c=NewLead.IM_UPDATED_AT__c;
            }
            if(NewLead.IM_USAGEDELETEDATE__c != null ){
                OldLead.IM_USAGEDELETEDATE__c=NewLead.IM_USAGEDELETEDATE__c;
            }
            if(NewLead.IM_USER_ID__c != null && NewLead.IM_USER_ID__c !=''){
                OldLead.IM_USER_ID__c=NewLead.IM_USER_ID__c;
            }
            if(NewLead.IM_WEBCAMUSED__c != null){
                OldLead.IM_WEBCAMUSED__c=NewLead.IM_WEBCAMUSED__c;
            }
             if(NewLead.Industry__c != null && NewLead.Industry__c !=''){            
                OldLead.Industry__c=NewLead.Industry__c;
            }

            if(NewLead.Notes__c != null && NewLead.Notes__c !=''){
                OldLead.Notes__c=NewLead.Notes__c;
            }
            if(NewLead.Number_of_Licenses_Users__c != null){
                OldLead.Number_of_Licenses_Users__c=NewLead.Number_of_Licenses_Users__c;
            }
            if(NewLead.Omniture_Campaign_Code__c != null && NewLead.Omniture_Campaign_Code__c !=''){
                OldLead.Omniture_Campaign_Code__c=NewLead.Omniture_Campaign_Code__c;
            }
          
            if(NewLead.Product_Interest__c != null && NewLead.Product_Interest__c !=''){
                OldLead.Product_Interest__c=NewLead.Product_Interest__c;
            }
            if(NewLead.Referring_URL__c != null && NewLead.Referring_URL__c !=''){
                OldLead.Referring_URL__c=NewLead.Referring_URL__c;
            }
  
            if(NewLead.Channel__c != null && NewLead.Channel__c !=''){
                OldLead.Channel__c=NewLead.Channel__c;
            }  
    
        }
        catch(exception ex){
           // system.debug('----------- exception '+ex);
        } 
    }*/
}