lanecwe-Prod/src/objects/Implementation_Services__c.object
<CustomObject>
    <fields>
        <fullName>CheckboxForWFRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CheckboxForWFRule</label>
        <type>Checkbox</type>
    </fields>
    <label>Implementation Services</label>
    <nameField>
        <displayFormat>IST-{000000}</displayFormat>
        <label>Implementation Services Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementation Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Competitor_s__c</fullName>
        <label>Competitor(s)</label>
        <picklist>
            <picklistValues>
                <fullName>AAPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accutel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adobe Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aethra.net</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allstream</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ArkadinAnyWhere</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkadin Audio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkadin Audio Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkadin Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkadin Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkadin Webcast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkadin Web Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT&amp;T Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT&amp;T Connect Web Conferencing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT Conferencing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automated Conferencing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avistar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basecamp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bell Conferencing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluejeans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BT: WireOne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canon Soft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CenturyLink</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China Telecom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China Unicom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chorus Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citrix OpenVoice</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Incumbent__c</fullName>
        <label>Incumbent</label>
        <picklist>
            <picklistValues>
                <fullName>AAPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accutel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACT Teleconferencing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adobe Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aethra.net</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allstream</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ArkadinAnyWhere</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkadin Audio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkadin Audio Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkadin Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkadin Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkadin Webcast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkadin Web Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT&amp;T Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT&amp;T Connect Web Conferencing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT Conferencing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automated Conferencing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avistar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basecamp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bell Conferencing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluejeans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BT: WireOne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BudgetConference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canon Soft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CenturyLink</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China Telecom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China Unicom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chorus Call</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <label>Primary Lost Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Budget Constrained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Adverse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Conflict</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competition or Stayed with Current Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support Model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lack of Brand Recognition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lack of Service Offering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lacks Functionality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Decision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Too High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship Loyalty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stale Transferred Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T &amp; Cs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Difficulties with Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To In House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown/Lost Contact</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opp_Stage__c</fullName>
        <label>Opp Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Identify Target</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Session/Needs Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal/Price Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pilot/Trial/Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation/Verbal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won - Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won - Implementation Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualify Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Develop Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Develop Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gain Commitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiate Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obtain Final Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkout</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

dimagi-SalesforceFB/src/objects/Opportunity.object
    <fields>
        <fullName>Implementation_Services__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Potentially interested in Implementation Services</description>
        <inlineHelpText>Potentially interested in Implementation Services</inlineHelpText>
        <label>Implementation Services</label>
        <type>Checkbox</type>
    </fields>

lanecwe-Prod/src/classes/Test_SetISTCompletedStatus.cls
/*********************************************************************
Name : Test_SetISTCompletedStatus
Created On : jan 09, 2013  
Created By : JP
Description : Test class on  Trigger on Opportunity SetISTCompletedStatus
**********************************************************************/
@isTest
private class Test_SetISTCompletedStatus{
	@istest (SeeAllData=true)
 	static void TestSetISTCompletedStatus() {
 		Test.startTest();
        Opportunity opp = PGITestUtilities.getOpportunityDetails();
        insert opp;  
        Implementation_Services__c imp = PGITestUtilities.getImplementationServices(opp.Id);
        imp.CheckboxForWFRule__c = false;
		insert imp;
        
        opp.Opp_Stage__c = 'Closed Lost';
        opp.Competitor_s__c = 'test';
        opp.Incumbent__c = 'test';
        opp.Lost_Reason__c = 'test';
        update opp;
        
        Implementation_Services__c retImpServices=[SELECT CheckboxForWFRule__c FROM Implementation_Services__c WHERE Id =: imp.Id];
        System.assertEquals(retImpServices.CheckboxForWFRule__c, true);
        Test.stopTest();
    }
}