lanecwe-Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Is_RFP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is RFP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Annual_Value__c</fullName>
        <inlineHelpText>Calculated from the total of all Product Annual Value&apos;s associated with this opportunity.</inlineHelpText>
        <label>ACV</label>
        <summarizedField>OpportunityLineItem.Annual_Value__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.isReportable_Text__c</field>
            <operation>equals</operation>
            <value>Valid</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Quote_Currency__c</fullName>
        <formula>TEXT(Opportunity.CurrencyIsoCode)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q/C Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Owner__c</fullName>
        <formula>Opportunity.Owner_Copy__r.FirstName  &amp; &apos; &apos; &amp;  Opportunity.Owner_Copy__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q/C Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Id__c</fullName>
        <defaultValue>$User.Terr__c</defaultValue>
        <label>Rep Territory Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signer_Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The person who will be receiving the Contract to Sign.</inlineHelpText>
        <label>Signer Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes (Contact for Signature)</relationshipLabel>
        <relationshipName>Deals2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice__c</label>
        <summarizedField>QuoteLineItem.TotalPrice__c</summarizedField>
        <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Annual_value__c</fullName>
        <description>Calculated from the total of all Quote Line Items Annual Value&apos;s associated with this Quote.</description>
        <label>Annual Contract Value</label>
        <summarizedField>QuoteLineItem.Annual_value__c</summarizedField>
        <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Contract_Value__c</fullName>
        <description>Calculated from the total of all Quote Line Items Contract Value&apos;s associated with this Quote</description>
        <label>TCV</label>
        <summarizedField>QuoteLineItem.Contract_Value__c</summarizedField>
        <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_MRR__c</fullName>
        <description>Calculated from the total of all QuoteLine Items MRR&apos;s associated with this Quote</description>
        <label>Total MRR</label>
        <summarizedField>QuoteLineItem.MRR__c</summarizedField>
        <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Margin__c</fullName>
        <description>This is a summary field that sums &quot;Line Margin Over Term&quot; in Quotelineitem object</description>
        <label>Total Margin</label>
        <summarizedField>QuoteLineItem.Line_Margin_Over_Term__c</summarizedField>
        <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/classes/QuoteAccount.cls
public class QuoteAccount{

    public string quoteId {get; set;}
    public string quoteName {get; set;}
    public string quoteStatus {get; set;}
    public string accountName {get; set;}
    public string salesRepName {get; set;}
    public string Email {get; set;}
    public string phoneNumber {get; set;}
    public string clientContact {get; set;}
    public string accountId {get; set;}
    public string quoteContact{get;set;}
    public double totalAnnualvalue{get;set;}
    public double totalContractValue{get;set;}
    public double totalMRR{get;set;}
    public double totalPrice {get;set;}
    public double totalMargin {get;set;}
    public String quoteCurrency {get;set;}
    public string territoryCode {get;set;}
    public string dealType {get;set;}
    public boolean isRFP{get;set;}
    
    
    public QuoteAccount(){
    }
    public QuoteAccount(Quote objQuote, Opportunity objAccount){
        this.quoteId= objQuote.QuoteNumber;
        this.quoteName = objQuote.Name;
        this.quoteStatus = objQuote.Status;
        this.accountName = objAccount.Account.Name;  
       this.quoteContact  = objQuote.Contact.Name;
        //this.quoteContact  = objQuote.Signer_Contact_Name__r.Name;
       //this.quoteContact  = objQuote.Signer_Contact_Name__c;
        this.phoneNumber = objAccount.Account.phone;
        this.accountId = objAccount.AccountId;
        this.Email=objQuote.Email;
        //this.salesRepName = userinfo.getName();
        this.salesRepName = objQuote.Quote_Owner__c;
        this.totalAnnualvalue=objQuote.Total_Annual_value__c;
        this.totalContractValue=objQuote.Total_Contract_Value__c;
        this.totalMRR=objQuote.Total_MRR__c;
        this.totalPrice=objQuote.TotalPrice__c;
        this.totalMargin=objQuote.Total_Margin__c;
        this.quoteCurrency=objQuote.Quote_Currency__c;
        this.territoryCode=objQuote.Sales_Rep_Id__c;
        this.dealType=objQuote.opportunity.type;
        this.isRFP=objAccount.Is_RFP__c;
        
    }

}