lanecwe-Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Initial Product of Interest</label>
        <picklist>
            <picklistValues>
                <fullName>Audio: GlobalMeet Audio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: GlobalMeet Audio for Microsoft Lync</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: GlobalMeet Hybrid Audio for Lync Server</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: GlobalMeet Hybrid Audio for WebEx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: iMeet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: iMeetLive Managed Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: OnNet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: Op. Assisted: Premium Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: Op. Assisted: Standard Auditorium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle: GlobalMeet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle: GlobalMeet Webinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle: iMeet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle: iMeet Video Room Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner: Partner BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video: Managed Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video: Managed Service - Device</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video: Managed Service - Flat Rate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video: Professional Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: AdobeConnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: Cisco WebEx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: GlobalMeet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: GlobalMeet Active Host</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: GlobalMeet Web for Microsoft Lync</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: GlobalMeet Webinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: iMeet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: iMeet Agenday Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: iMeetLive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: iMeetLive Managed Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: iMeet Projects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: Microsoft Office Live Meeting</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Used to determine what shows up in Product Select VF page</description>
        <inlineHelpText>What regions should be able to see this product when adding to Opps?</inlineHelpText>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Product__c.object
<CustomObject>
    <description>Master Table Used to store Product information</description>
    <label>Add-on/Feature</label>
    <nameField>
        <label>Add On/ Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Add-ons/Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/QCStatusValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Stores the values of Quote.Status picklist field to be used in apex code.</description>
    <fields>
        <fullName>StatusValue__c</fullName>
        <label>StatusValue</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Q/C Status Values</label>
</CustomObject>

lanecwe-Prod/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Comment_For_Approver__c</fullName>
        <label>Comments for Approver</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsCloned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsCloned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Non_Std_Terms_Conditions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non Std T&amp;C&apos;s and 3rd Party Products</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>PGI Operating Region</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>NONE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product_custom</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>Solution__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Service__c.object
<CustomObject>
    <description>This is product top level and each service can be mapped with multiple products</description>
    <fields>
        <fullName>Solution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Solution__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/ServiceCategory__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Add-on/Feature</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>ServiceCategories</relationshipLabel>
        <relationshipName>ServiceCategories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Package</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>ServiceCategories</relationshipLabel>
        <relationshipName>ServiceCategories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ServiceCategory</label>
    <nameField>
        <displayFormat>SOL-{0000}</displayFormat>
        <label>ServiceCategory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ServiceCategories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Solution__c.object
<CustomObject>
    <description>This is Top Level used for Marketing Purpose.</description>
    <label>Product Family</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Level_Of_Authority__c</fullName>
        <description>It depicts which Authority level the User Belongs to</description>
        <inlineHelpText>Anything above Level 1 will typically be for use by sales management, product team, or contract users.</inlineHelpText>
        <label>Level Of Authority</label>
        <picklist>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>This is a field that is installed by and used with the Adoption Dashboard AppExchange package. If your org already has a similar field, you can change the reports that are part of the Adoption Dashboard package to use your custom field and then delete this field.</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
                <color>#3333FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
                <color>#CC6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/classes/PGIQuoteApprovalActionController.cls
/********************************************************************************
Name:  PGIQuoteApprovalActionController() 
Copyright © 2012  PGI 
======================================================
======================================================
Purpose:
-------
This class used to Approve or Reject QuoteLineItems 
submitted for Approval
======================================================
======================================================
History
-------
VERSION  AUTHOR                DATE        DETAIL              FEATURES/CSR/TTP
  1.0 – Capgemini India                                                  1/10/2012        Added 
********************************************************************************/  

public with sharing class PGIQuoteApprovalActionController {
    public string approvalProcessComment {get; set;}
    public QuoteAccount quoteInfo {get; set;}
    public list<PGIProduct.ProductList> allProductDetailsList{get; set;}
    public string requestQuoteId  {get; set;}
    public list<processinstance>approvalstatus ;
    public boolean approvalProcessed {get;set;}
    public boolean bypass{get;set;} 
    public string commentsforapprovar{get;set;}
    public boolean Isapprovalprocess {get;set;}
    public boolean iscloned{get;set;}
    public PGIQuoteApprovalActionController(){
    try{
        requestQuoteId = apexPages.currentpage().getParameters().get('QuoteId'); 
       iscloned=[select IsCloned__c from quote where id=:requestQuoteId].IsCloned__c ;
        bypass=[select Non_Std_Terms_Conditions__c from quote where id =:requestQuoteId ].Non_Std_Terms_Conditions__c;
        commentsforapprovar=[select Comment_For_Approver__c from quote where id =:requestQuoteId ].Comment_For_Approver__c;
        allProductDetailsList =  QuoteLineItemUtil.getAllProductDetails(requestQuoteId);
         quoteInfo= QuoteAccInfoUtilities.getQuoteAccInfo(requestQuoteId); 
        list<ProcessInstanceWorkitem> approvalAction=[Select p.Id from ProcessInstanceWorkitem p where p.ProcessInstance.TargetObjectId =:requestQuoteId limit 1];
                 system.debug('approvalAction'+approvalAction);
                  if(approvalAction.isEmpty()){
                        approvalProcessed=true;
                        Isapprovalprocess=false;
                  }else{
                        approvalProcessed=false;
                        Isapprovalprocess=true;
                  }
        }
       
        catch(exception e)
        {
            system.debug('exception'+e);
        }                                  
    } 
    
    public PageReference approveRequest(){       
        try {
                list<ProcessInstanceWorkitem> approveProcsId=[Select p.Id from ProcessInstanceWorkitem p
                                                                where p.ProcessInstance.TargetObjectId =:requestQuoteId limit 1];
                Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest();
                req2.setComments(approvalProcessComment);
                req2.setAction('Approve');
                req2.setNextApproverIds(null);
                req2.setWorkitemId(approveProcsId[0].Id);
                Approval.ProcessResult result2 =  Approval.process(req2);
                QuoteStatusUtilities.updateApprovalStatus(requestQuoteId,'Approved');
                QuoteStatusUtilities.updateQuoteStatus(requestQuoteId, QCStatusValues__c.getInstance(PGIQuoteStatusEnum.PricingApproved.name()).StatusValue__c);
               
        }
        catch(Exception ex){
               PGIErrorUtilities.logPgiError('PGIQuoteApprovalActionController:approveRequest()',ex.getMessage(),PGIErrorUtilities.LoggingLevel.INFO);
               system.debug(LoggingLevel.ERROR,'Error When approving the request '+ex.getMessage()); 
        }
        PageReference approveReject= new PageReference('/apex/PGIPendingRequest');
        approveReject.setRedirect(true); 
        return approveReject;
    } 
    
     public Pagereference rejectRequest(){
           try { 
               
                 {
                        list<ProcessInstanceWorkitem> rejectProcsId=[Select p.Id from ProcessInstanceWorkitem p
                                                                where p.ProcessInstance.TargetObjectId =:requestQuoteId limit 1];
                        Approval.ProcessWorkitemRequest rejectApp = new Approval.ProcessWorkitemRequest();
                        rejectApp.setComments(approvalProcessComment);
                        rejectApp.setAction('Reject');
                        rejectApp.setNextApproverIds(null);
                        rejectApp.setWorkitemId(rejectProcsId[0].Id);
                        Approval.ProcessResult resApp =  Approval.process(rejectApp);
                         QuoteStatusUtilities.updateQuoteStatus(requestQuoteId,QCStatusValues__c.getInstance(PGIQuoteStatusEnum.QuoteInProgress.name()).StatusValue__c); 
                        approvalstatus =[select status from processinstance where processinstance.targetobjectid=:requestQuoteId and processinstance.status='rejected'];
                        QuoteStatusUtilities.updateApprovalStatus(requestQuoteId,approvalstatus[0].status );
                }
            }
            catch(Exception ex){
                 PGIErrorUtilities.logPgiError('PGIQuoteApprovalActionController:rejectRequest()',ex.getMessage(),PGIErrorUtilities.LoggingLevel.INFO);
                 system.debug(LoggingLevel.ERROR,'Error When rejecting the request '+ex.getMessage());                
           }
        PageReference approveReject= new PageReference('/apex/PGIPendingRequest');
        approveReject.setRedirect(true); 
        return approveReject;
    }
    public Pagereference QuoteDetailpage(){     
        PageReference quoteDetail= new PageReference('/'+requestQuoteId);
        quoteDetail.setRedirect(true); 
        return quoteDetail;
         
    }
  private static testMethod void test_PGIQuoteApprovalActionController(){ 
         
         test.starttest();
         Test.setCurrentPage(Page.PGIQuoteApprovalAction);
         //Test Data
         Account testacc= PGITestUtilities.getAccountDetails();
         insert testacc;
         Contact testcon=PGITestUtilities.getContactDetails(testacc.Id); 
         insert testcon;
         Opportunity testopp=PGITestUtilities.getOpportunityDetails();
         testopp.StageName= 'Proposal/Price Quote';
         insert testopp;
         quote testquote=PGITestUtilities.getQuoteDetails(testacc.Id,testcon.Id, testopp.Id);
         insert testquote;
         //case1: set param for quoteId
         PGITestUtilities.setTestParameter('QuoteId', testquote.Id);
         QuoteAccount testquoteAcc=new QuoteAccount(testquote,testopp);
         System.debug('#test'+testquoteAcc);
         PGIQuoteApprovalActionController testCase1pgiQuteApprovalCon = new PGIQuoteApprovalActionController();
         //case2: set param for quoteId
         PGITestUtilities.setTestParameter('QuoteId', null);
         PGIQuoteApprovalActionController testCase2pgiQuteApprovalCon = new PGIQuoteApprovalActionController();
         //assert:case1
     //    system.assertEquals(testCase1pgiQuteApprovalCon.quoteInfo.quoteName ,testquoteAcc.quoteName );
         //assert:case2
       //  system.assertEquals(testCase1pgiQuteApprovalCon.allProductDetailsList.size(),0 );
         list<ProcessInstanceWorkitem> approvalAction=[Select p.Id from ProcessInstanceWorkitem p where p.ProcessInstance.TargetObjectId =:testquote.id limit 1];
      test.stoptest();    
      }
      
        //Test Method for Approval Request
    @istest (seeAlldata=true) 
    public static void test_approveRequest() {
        test.startTest();
        Test.setCurrentPage(Page.PGIQuoteApprovalAction);
        //Testdata 
        User testUser1=PGITestUtilities.getTestUser(PGITestUtilities.getAdminProfile());
        testUser1.firstName='TestUser1';
        testUser1.Level_Of_Authority__c='Level 1';
        insert testUser1;
        
        Account testAcc= PGITestUtilities.getAccountDetails();
        insert testAcc;
        Opportunity testOpp= PGITestUtilities.getOpportunityDetails();      
        insert testOpp;
        Contact cont= PGITestUtilities.getContactDetails(testAcc.Id); 
        insert cont;
        Quote testQuote= PGITestUtilities.getQuoteDetails(testAcc.Id, cont.Id ,testOpp.Id); 
        insert testQuote;
        Quote testQuote1= PGITestUtilities.getQuoteDetails(testAcc.Id, cont.Id ,testOpp.Id); 
        testQuote1.Non_Std_Terms_Conditions__c=true;
        insert testQuote1;
        Region__c region = PGITestUtilities.getRegionDetails();
        insert region;
        list<Product__c> allProduct= new list<Product__c>();
        Product__c testprod1 = PGITestUtilities.getProductDetails('Add-on', 'TestAddon','10111111');
        insert testProd1;       
        Product__c testprod2 = PGITestUtilities.getProductDetails('Ancillary','TestAncillary','20111111');
        insert testProd2;
        Product__c testprod3= PGITestUtilities.getProductDetails('Service','testserv','30111111');
        insert testProd3;
        Solution__c testSoln = PGITestUtilities.getSolution();
        insert testSoln;
        Service__c testSer= PGITestUtilities.getService(testSoln.Id);
        insert testSer;
        ServiceCategory__c testSc1= PGITestUtilities.getSerCategory(testSer.Id, testProd3.Id, true);
        insert testSc1;
        ServiceCategory__c testSc2= PGITestUtilities.getSerCategory(testSer.Id, testProd2.Id, false);
        insert testSc2;
        ServiceCategory__c testSc3= PGITestUtilities.getSerCategory(testSer.Id, testProd1.Id, false);
        insert testSc3;
        PriceBook2 pb2Standard = [select Id from Pricebook2 where isStandard=true];
        string standardPriceBookId = pb2Standard.Id;
        
        Product2 testProd= PGITestUtilities.getStdProduct();        
        insert testProd;
        
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id=standardPriceBookId, Product2Id=testProd.Id, UnitPrice=99, isActive=true);
        insert pbe;
        OpportunityLineItem oli = PGITestUtilities.getOpportunityLineItemDetails(testOpp.Id, pbe.Id);
        insert oli;    
        QuoteLineItem testquoteLineItem1=PGITestUtilities.getServiceQuoteLineItem(testprod1.Id,testSer.Id,testQuote.Id,pbe);
        insert testquoteLineItem1;
        QuoteLineItem testquoteLineItem2=PGITestUtilities.getTestQuoteLineItem(testprod2.Id,testSer.Id,testQuote.Id,pbe,testquoteLineItem1.Id);
        insert testquoteLineItem2;
        QuoteLineItem testquoteLineItem3=PGITestUtilities.getTestQuoteLineItem(testprod3.Id,testSer.Id,testQuote.Id,pbe,testquoteLineItem1.Id);
        insert testquoteLineItem3;   
        
        list<QuoteLineItem> quotelst=[Select q.UnitPrice, q.Service__c, q.QuoteId, q.Quantity, q.Product__c, q.PricebookEntry.Name, q.PricebookEntryId, q.Approval_Status__c 
        							From QuoteLineItem q 
        							Where QuoteId=:testQuote.Id LIMIT 50000];
    
       // PGITestUtilities.setTestParameter('QuoteId', testquote.Id);
        PGIQuoteApprovalActionController testpgiQuteApprovalCon = new PGIQuoteApprovalActionController();
        testpgiQuteApprovalCon.requestQuoteId=testquote.Id;
        testpgiQuteApprovalCon.approveRequest();
        quotelst=[Select  q.Approval_Status__c From QuoteLineItem q where q.QuoteId=:testpgiQuteApprovalCon.requestQuoteId];
        list<ProcessInstanceWorkitem> approveProcsId=[Select p.Id from ProcessInstanceWorkitem p
                                                                where p.ProcessInstance.TargetObjectId =:testquote.Id limit 1];
      //  System.assertEquals(approveProcsId.size(),0);
        
        /*Added*/
        PGITestUtilities.setTestParameter('QuoteId', testquote1.Id);
        PGIQuoteApprovalActionController testpgiQuteApprovalCon1 = new PGIQuoteApprovalActionController();
        testpgiQuteApprovalCon1.requestQuoteId=testquote1.Id;
        testpgiQuteApprovalCon1.approveRequest();
        quotelst=[Select  q.Approval_Status__c From QuoteLineItem q where q.QuoteId=:testpgiQuteApprovalCon.requestQuoteId];
        list<ProcessInstanceWorkitem> approveProcsId1=[Select p.Id from ProcessInstanceWorkitem p
                                                                where p.ProcessInstance.TargetObjectId =:testquote1.Id limit 1];
        
        
        
        testSubmitApprovalRequest(UserInfo.getUserId(),testquote.Id);
      //  System.assertNotEquals(UserInfo.getUserId(),Null); 
        approveProcsId=[Select p.Id from ProcessInstanceWorkitem p
                                                                where p.ProcessInstance.TargetObjectId =:testquote.Id limit 1];
       // System.assertEquals(approveProcsId.size(),1); 
        quotelst=[Select  q.Approval_Status__c From QuoteLineItem q where q.QuoteId=:testpgiQuteApprovalCon.requestQuoteId];
     //   System.assertEquals(quotelst[0].Approval_Status__c, 'Pending for Approval');
        testpgiQuteApprovalCon.approveRequest();
        quotelst=[Select  q.Approval_Status__c From QuoteLineItem q where q.QuoteId=:testpgiQuteApprovalCon.requestQuoteId];
      //  System.assertEquals(quotelst[0].Approval_Status__c, 'Approved');
        test.stopTest();
        
    } 
        @istest (seeAlldata=true) 
        public static  void test_rejectRequest(){
            test.startTest();
        Test.setCurrentPage(Page.PGIQuoteApprovalAction);
        //Testdata 
        User testUser1=PGITestUtilities.getTestUser(PGITestUtilities.getAdminProfile());
        testUser1.firstName='TestUser1';
        testUser1.Level_Of_Authority__c='Level 1';
        insert testUser1;
        
        Account testAcc= PGITestUtilities.getAccountDetails();
        insert testAcc;
        Opportunity testOpp= PGITestUtilities.getOpportunityDetails();      
        insert testOpp;
        Contact cont= PGITestUtilities.getContactDetails(testAcc.Id); 
        insert cont;
        Quote testQuote= PGITestUtilities.getQuoteDetails(testAcc.Id, cont.Id ,testOpp.Id); 
        insert testQuote;
        Quote testQuote1= PGITestUtilities.getQuoteDetails(testAcc.Id, cont.Id ,testOpp.Id); 
        testQuote1.Non_Std_Terms_Conditions__c=true;
        insert testQuote1;
        Region__c region = PGITestUtilities.getRegionDetails();
        insert region;
        list<Product__c> allProduct= new list<Product__c>();
        Product__c testprod1 = PGITestUtilities.getProductDetails('Add-on','TestAddon','10111111');
        insert testProd1;       
        Product__c testprod2 = PGITestUtilities.getProductDetails('Ancillary','TestAncillary','20111111');
        insert testProd2;
        Product__c testprod3= PGITestUtilities.getProductDetails('Service','testserv','30111111');
        insert testProd3;
        Solution__c testSoln = PGITestUtilities.getSolution();
        insert testSoln;
        Service__c testSer= PGITestUtilities.getService(testSoln.Id);
        insert testSer;
        ServiceCategory__c testSc1= PGITestUtilities.getSerCategory(testSer.Id, testProd3.Id, true);
        insert testSc1;
        ServiceCategory__c testSc2= PGITestUtilities.getSerCategory(testSer.Id, testProd2.Id, false);
        insert testSc2;
        ServiceCategory__c testSc3= PGITestUtilities.getSerCategory(testSer.Id, testProd1.Id, false);
        insert testSc3;
        PriceBook2 pb2Standard = [select Id from Pricebook2 where isStandard=true];
        string standardPriceBookId = pb2Standard.Id;
        
        Product2 testProd= PGITestUtilities.getStdProduct();        
        insert testProd;
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id=standardPriceBookId, Product2Id=testProd.Id, UnitPrice=99, isActive=true);
        insert pbe;
        OpportunityLineItem oli = PGITestUtilities.getOpportunityLineItemDetails(testOpp.Id, pbe.Id);
        insert oli;    
        QuoteLineItem testquoteLineItem1=PGITestUtilities.getServiceQuoteLineItem(testprod1.Id,testSer.Id,testQuote.Id,pbe);
        insert testquoteLineItem1;
        QuoteLineItem testquoteLineItem2=PGITestUtilities.getTestQuoteLineItem(testprod2.Id,testSer.Id,testQuote.Id,pbe,testquoteLineItem1.Id);
        insert testquoteLineItem2;
        QuoteLineItem testquoteLineItem3=PGITestUtilities.getTestQuoteLineItem(testprod3.Id,testSer.Id,testQuote.Id,pbe,testquoteLineItem1.Id);
        insert testquoteLineItem3;
        
        list<QuoteLineItem> quotelst=[Select q.UnitPrice, q.Service__c, q.QuoteId, q.Quantity, q.Product__c, q.PricebookEntry.Name, q.PricebookEntryId, q.Approval_Status__c 
        							From QuoteLineItem q
        							Where QuoteId=:testquoteLineItem1.Id];
        //System.assertNotEquals(quotelst.size(),0);
        //requestQuoteId
      //  PGITestUtilities.setTestParameter('QuoteId', testquote.Id);
        PGIQuoteApprovalActionController testpgiQuteApprovalCon = new PGIQuoteApprovalActionController();
        testpgiQuteApprovalCon.requestQuoteId=testquote.Id;
        testpgiQuteApprovalCon.rejectRequest();
        quotelst=[Select  q.Approval_Status__c From QuoteLineItem q where q.QuoteId=:testpgiQuteApprovalCon.requestQuoteId];
        list<ProcessInstanceWorkitem> rejectProcsId=[Select p.Id from ProcessInstanceWorkitem p
                                                                where p.ProcessInstance.TargetObjectId =:testquote.Id limit 1];
       
      //  System.assertEquals(rejectProcsId.size(),0);
        
        /*Added*/
        PGITestUtilities.setTestParameter('QuoteId', testquote1.Id);
        PGIQuoteApprovalActionController testpgiQuteApprovalCon1 = new PGIQuoteApprovalActionController();
        testpgiQuteApprovalCon1.requestQuoteId=testquote1.Id;
        testpgiQuteApprovalCon1.rejectRequest();
        quotelst=[Select  q.Approval_Status__c From QuoteLineItem q where q.QuoteId=:testpgiQuteApprovalCon.requestQuoteId];
        list<ProcessInstanceWorkitem> rejectProcsId1=[Select p.Id from ProcessInstanceWorkitem p
                                                                where p.ProcessInstance.TargetObjectId =:testquote1.Id limit 1];
        
        
       /* PgiQuoteApprovalController testQuoteApprovalcon=new PgiQuoteApprovalController();
        testQuoteApprovalcon.quoteId=testquote.Id;
        testQuoteApprovalcon.userId=UserInfo.getUserId(); 
        testQuoteApprovalcon.submitApprovalRequest(); */
        testSubmitApprovalRequest(UserInfo.getUserId(),testquote.Id);
        
      //  System.assertNotEquals(UserInfo.getUserId(),Null); 
        rejectProcsId=[Select p.Id from ProcessInstanceWorkitem p
                                                                where p.ProcessInstance.TargetObjectId =:testquote.Id limit 1];
       // System.assertEquals(rejectProcsId.size(),1); 
        quotelst=[Select  q.Approval_Status__c From QuoteLineItem q where q.QuoteId=:testpgiQuteApprovalCon.requestQuoteId];
       // System.assertEquals(quotelst[0].Approval_Status__c, 'Pending for Approval');
        testpgiQuteApprovalCon.rejectRequest();
        quotelst=[Select  q.Approval_Status__c From QuoteLineItem q where q.QuoteId=:testpgiQuteApprovalCon.requestQuoteId limit 1];
      //  System.assertEquals(quotelst.size(), 1);
      //  System.assertEquals(quotelst[0].Approval_Status__c,'Approval Required');
        test.stopTest();
         
       }
        private static testMethod void test_QuoteDetailpage(){
            Test.setCurrentPage(Page.PGIQuoteApprovalAction);
        //  PGITestUtilities.setTestParameter('QuoteId', 'quote123');
            PGIQuoteApprovalActionController testpgiQuteDetailCon = new PGIQuoteApprovalActionController();
            PageReference pageRef=testpgiQuteDetailCon.QuoteDetailpage();  
        }
       
       private static void testSubmitApprovalRequest(String userId,String quoteId){
        try{
            list<ProcessInstanceWorkitem> approveProcsId=[Select p.Id from ProcessInstanceWorkitem p
                                                                where p.ProcessInstance.TargetObjectId =:quoteId limit 1];
            if(approveProcsId.size()==0)    {
     
            Approval.ProcessSubmitRequest req1 = 
                    new Approval.ProcessSubmitRequest();
            req1.setObjectId(quoteId);
            
            req1.setNextApproverIds(new Id[]{userId});
            //req1.setNextApproverIds(userIds);
            Approval.ProcessResult result1 = Approval.process(req1);
            //isCloseWindow   =true;   
            QuoteStatusUtilities.updateQuoteStatus(quoteId,QCStatusValues__c.getInstance(PGIQuoteStatusEnum.SubmittedPriceApproval.name()).StatusValue__c);
            }                              
        }
        catch(Exception ex){
                system.debug('TEST'+ex);
        }
        
      }
     
}