lanecwe-Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Initial Product of Interest</label>
        <picklist>
            <picklistValues>
                <fullName>Audio: GlobalMeet Audio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: GlobalMeet Audio for Microsoft Lync</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: GlobalMeet Hybrid Audio for Lync Server</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: GlobalMeet Hybrid Audio for WebEx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: iMeet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: iMeetLive Managed Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: OnNet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: Op. Assisted: Premium Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio: Op. Assisted: Standard Auditorium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle: GlobalMeet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle: GlobalMeet Webinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle: iMeet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle: iMeet Video Room Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner: Partner BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video: Managed Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video: Managed Service - Device</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video: Managed Service - Flat Rate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video: Professional Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: AdobeConnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: Cisco WebEx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: GlobalMeet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: GlobalMeet Active Host</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: GlobalMeet Web for Microsoft Lync</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: GlobalMeet Webinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: iMeet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: iMeet Agenday Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: iMeetLive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: iMeetLive Managed Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: iMeet Projects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web: Microsoft Office Live Meeting</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Used to determine what shows up in Product Select VF page</description>
        <inlineHelpText>What regions should be able to see this product when adding to Opps?</inlineHelpText>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Product__c.object
<CustomObject>
    <description>Master Table Used to store Product information</description>
    <label>Add-on/Feature</label>
    <nameField>
        <label>Add On/ Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Add-ons/Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/QCStatusValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Stores the values of Quote.Status picklist field to be used in apex code.</description>
    <fields>
        <fullName>StatusValue__c</fullName>
        <label>StatusValue</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Q/C Status Values</label>
</CustomObject>

lanecwe-Prod/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>PGI Operating Region</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>NONE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product_custom</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>Solution__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

lanecwe-Prod/src/objects/Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Service__c.object
<CustomObject>
    <description>This is product top level and each service can be mapped with multiple products</description>
    <fields>
        <fullName>Solution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Solution__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/ServiceCategory__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Add-on/Feature</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>ServiceCategories</relationshipLabel>
        <relationshipName>ServiceCategories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Package</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>ServiceCategories</relationshipLabel>
        <relationshipName>ServiceCategories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ServiceCategory</label>
    <nameField>
        <displayFormat>SOL-{0000}</displayFormat>
        <label>ServiceCategory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ServiceCategories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Solution__c.object
<CustomObject>
    <description>This is Top Level used for Marketing Purpose.</description>
    <label>Product Family</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/classes/PgiPendingRequestController.cls
/********************************************************************************
Name:  PgiPendingRequestController()
Copyright © 2012  PGI
======================================================
======================================================
Purpose:
-------
This class used to Approve or Reject QuoteLineItems 
submitted for Approval
======================================================
======================================================
History
-------
VERSION  AUTHOR                DATE        DETAIL              FEATURES/CSR/TTP
  1.0 – Capgemini India                                                  1/10/2012        Added 
********************************************************************************/  
public with sharing class PgiPendingRequestController { 
    
    public list<PgiQuote> pendingQuote{get;set;}    
    public string requestQuoteId {get;set;}
    public PgiPendingRequestController(){
        try{
             pendingQuote=PgiPendingRequestutilities.getWorkItems();  
        }catch(Exception e){
            System.debug('Exception'+ e);
        }
    }
    
    public PageReference QuoteApproveReject(){
        try{
            PageReference approveReject= new PageReference('/apex/PGIQuoteApprovalAction');
            approveReject.setRedirect(true);
            approveReject.getParameters().put('quoteId',requestQuoteId); 
            return approveReject;
            
        }
        catch (Exception ex){
            PGIErrorUtilities.logPgiError('PgiPendingRequestController:QuoteApproveReject()',ex.getMessage(),PGIErrorUtilities.LoggingLevel.INFO);
                system.debug(LoggingLevel.ERROR,'Error When redirecting to PGIQuoteApprovalAction page '+ex.getMessage());
        }
         return ApexPages.currentPage(); 
    } 
    //Test Method for PgiPendingRequestController
    @istest (seeAlldata=true) 
    public static void test_PgiPendingRequestController() {
        test.startTest();
        
        //Testdata 
        Account testAcc= PGITestUtilities.getAccountDetails();
                insert testAcc;
                Opportunity testOpp= PGITestUtilities.getOpportunityDetails();          
                insert testOpp;
                Contact cont= PGITestUtilities.getContactDetails(testAcc.Id); 
        insert cont;
                Quote testQuote= PGITestUtilities.getQuoteDetails(testAcc.Id, cont.Id ,testOpp.Id); 
                insert testQuote;
                Region__c region = PGITestUtilities.getRegionDetails();
        insert region;
                list<Product__c> allProduct= new list<Product__c>();
                Product__c testprod1 = PGITestUtilities.getProductDetails('Add-on','TestAddon','10111111');
                insert testProd1;               
                Product__c testprod2 = PGITestUtilities.getProductDetails('Ancillary','TestAncillary','20111111');
                insert testProd2;
                Product__c testprod3= PGITestUtilities.getProductDetails('Service','testserv','30111111');
                insert testProd3;
                Solution__c testSoln = PGITestUtilities.getSolution();
                insert testSoln;
                Service__c testSer= PGITestUtilities.getService(testSoln.Id);
                insert testSer;
                ServiceCategory__c testSc1= PGITestUtilities.getSerCategory(testSer.Id, testProd3.Id, true);
                insert testSc1;
                ServiceCategory__c testSc2= PGITestUtilities.getSerCategory(testSer.Id, testProd2.Id, false);
                insert testSc2;
                ServiceCategory__c testSc3= PGITestUtilities.getSerCategory(testSer.Id, testProd1.Id, false);
                insert testSc3;
                PriceBook2 pb2Standard = [select Id from Pricebook2 where isStandard=true];
                string standardPriceBookId = pb2Standard.Id;
                Product2 testProd= PGITestUtilities.getStdProduct();        
        		insert testProd; 
        		PricebookEntry pbe = new PricebookEntry(Pricebook2Id=standardPriceBookId, Product2Id=testProd.Id, UnitPrice=99, isActive=true);
                insert pbe;
                OpportunityLineItem oli = PGITestUtilities.getOpportunityLineItemDetails(testOpp.Id, pbe.Id);
        		insert oli; 
                QuoteLineItem testquoteLineItem1=PGITestUtilities.getServiceQuoteLineItem(testprod1.Id,testSer.Id,testQuote.Id,pbe);
                insert testquoteLineItem1;
                QuoteLineItem testquoteLineItem2=PGITestUtilities.getTestQuoteLineItem(testprod2.Id,testSer.Id,testQuote.Id,pbe,testquoteLineItem1.Id);
                insert testquoteLineItem2;
                QuoteLineItem testquoteLineItem3=PGITestUtilities.getTestQuoteLineItem(testprod3.Id,testSer.Id,testQuote.Id,pbe,testquoteLineItem1.Id);
                insert testquoteLineItem3;   
                list<QuoteLineItem> quotelst=[Select q.UnitPrice, q.Service__c, q.QuoteId, q.Quantity, q.Product__c, q.PricebookEntry.Name, q.PricebookEntryId, q.Approval_Status__c 
                							From QuoteLineItem q 
                							Where QuoteId=:testquoteLineItem1.Id LIMIT 50000];
            PGITestUtilities.setTestParameter('QuoteId', testquote.Id);
                quotelst=[Select  q.Approval_Status__c From QuoteLineItem q where q.QuoteId=:testquote.Id];
        list<ProcessInstanceWorkitem> approveProcsId=[Select p.Id from ProcessInstanceWorkitem p
                                                                where p.ProcessInstance.TargetObjectId =:testquote.Id limit 1];
        //Assert
        System.assertEquals(approveProcsId.size(),0);
            testSubmitApprovalRequest(UserInfo.getUserId(),testquote.Id);
            System.assertNotEquals(UserInfo.getUserId(),Null); 
            approveProcsId=[Select p.Id from ProcessInstanceWorkitem p
                                                               where p.ProcessInstance.TargetObjectId =:testquote.Id limit 1];
        //Assert
       // System.assertEquals(approveProcsId.size(),0); 
        PgiPendingRequestController pgiPenReq=new PgiPendingRequestController();
        Test.stoptest();
        
    }
    @istest (seeAlldata=true) 
    public static void test_QuoteApproveReject() { 
        //Test Data
        Account testAcc= PGITestUtilities.getAccountDetails();
                insert testAcc;
                Opportunity testOpp= PGITestUtilities.getOpportunityDetails();          
                insert testOpp;
                Contact cont= PGITestUtilities.getContactDetails(testAcc.Id); 
        insert cont;
                Quote testQuote= PGITestUtilities.getQuoteDetails(testAcc.Id, cont.Id ,testOpp.Id); 
                insert testQuote;
                PgiPendingRequestController pgiPenReq=new PgiPendingRequestController();
        pgiPenReq.requestQuoteId=testQuote.Id;
        String test1=pgiPenReq.QuoteApproveReject().getUrl();
        system.assertEquals(test1,'/apex/PGIQuoteApprovalAction?quoteId='+testQuote.Id);
        
    }
     private static void testSubmitApprovalRequest(String userId,String quoteId){
        try{
                        list<ProcessInstanceWorkitem> approveProcsId=[Select p.Id from ProcessInstanceWorkitem p
                                                                                                                                where p.ProcessInstance.TargetObjectId =:quoteId limit 1];
                        if(approveProcsId.size()==0)    {
         
                        Approval.ProcessSubmitRequest req1 = 
                                        new Approval.ProcessSubmitRequest();
                        req1.setObjectId(quoteId);
                        
                        req1.setNextApproverIds(new Id[]{userId});
                        //req1.setNextApproverIds(userIds);
                        Approval.ProcessResult result1 = Approval.process(req1);
                        //isCloseWindow   =true;   
                        QuoteStatusUtilities.updateQuoteStatus(quoteId,QCStatusValues__c.getInstance(PGIQuoteStatusEnum.SubmittedPriceApproval.name()).StatusValue__c);
                        }                              
                }
                catch(Exception ex){
                                system.debug('TEST'+ex);
                }
                
      }
}