jlamontSC-test/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>rC_Bios__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Manually populated field indicating is this account active?</description>
        <inlineHelpText>Is this account active?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Category__c</fullName>
        <description>Manually populated field indicating the type of Organization.</description>
        <inlineHelpText>Indicates the type of Organization.</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Foundation</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Household</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Organization</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This field is dynamically set.  If it has 0 companies associated to it the value is Prospect.  If it has &gt; 0 companies associated to it then it will be Customer.  There are also some Partner channel specific things that will set the value to Customer.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

jlamontSC-test/src/objects/Club_Entity__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Reorganizing</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Board Advisory Committees</fullName>
                </value>
                <value>
                    <fullName>Activity Sections</fullName>
                </value>
                <value>
                    <fullName>Grassroot Network Teams</fullName>
                </value>
                <value>
                    <fullName>Board of Directors</fullName>
                </value>
                <value>
                    <fullName>Board Standing Committees</fullName>
                </value>
                <value>
                    <fullName>Board Task Forces</fullName>
                </value>
                <value>
                    <fullName>Campaign &amp; Program Teams</fullName>
                </value>
                <value>
                    <fullName>Canadian Chapter</fullName>
                </value>
                <value>
                    <fullName>Canadian Group</fullName>
                </value>
                <value>
                    <fullName>Committees of the Board</fullName>
                </value>
                <value>
                    <fullName>Campaign Committees</fullName>
                </value>
                <value>
                    <fullName>Chapter</fullName>
                </value>
                <value>
                    <fullName>Cons Initiative Committee</fullName>
                </value>
                <value>
                    <fullName>Sierra Club</fullName>
                </value>
                <value>
                    <fullName>Council of Club Leaders</fullName>
                </value>
                <value>
                    <fullName>Conservation Priority Task Forces</fullName>
                </value>
                <value>
                    <fullName>Campaign Steering Comm</fullName>
                </value>
                <value>
                    <fullName>Digital Innovations Project</fullName>
                </value>
                <value>
                    <fullName>Ecoregion</fullName>
                </value>
                <value>
                    <fullName>Field Office</fullName>
                </value>
                <value>
                    <fullName>TSCF Sierra Club Fdn</fullName>
                </value>
                <value>
                    <fullName>TSCF Committee</fullName>
                </value>
                <value>
                    <fullName>TSCF Board of Directors</fullName>
                </value>
                <value>
                    <fullName>Finance &amp; Risk Management Subcommittees</fullName>
                </value>
                <value>
                    <fullName>Governance Committee</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Inner City Outings Group</fullName>
                </value>
                <value>
                    <fullName>ICO Regional Steering Cmt</fullName>
                </value>
                <value>
                    <fullName>Coordinating Pairs</fullName>
                </value>
                <value>
                    <fullName>Local Committees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Club Entity/Team</label>
    <nameField>
        <label>Club Entity/Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Entities/Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vibhudadhichi-TicketReservation/src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/Contact.object
    <fields>
        <fullName>Status__c</fullName>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>1- Working - Active Opp Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2- Working - Talking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3- Working - Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4- Strategic Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5- Active Project Team Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6- Active Self Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7- Passive &amp; Friendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8- Passive &amp; Unfriendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9-HOLD Not mine/move</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10-Dimagi Staff</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

CACommunity-Salesforce/src/objects/Contact.object
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>A CA may have more than one person filling the role of Primary Point of Contact (POC), and may use a contractor as one of the POCs.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary POC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

jlamontSC-test/src/objects/Leader_Position__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Leader Position</label>
    <nameField>
        <label>Leader Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leader Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Leadership__c.object
<CustomObject>
    <fields>
        <fullName>Club_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Club entities such as chapters and groups.</description>
        <label>Club Entity</label>
        <referenceTo>Club_Entity__c</referenceTo>
        <relationshipName>Leadership</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Leaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Leader_Position__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Position within a club entity or team</description>
        <label>Position</label>
        <referenceTo>Leader_Position__c</referenceTo>
        <relationshipLabel>Leadership/Team Membership</relationshipLabel>
        <relationshipName>Leadership</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Leadership/Team Membership</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Leadership/Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leadership/Team Membership</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Club_Entity__c</fullName>
        <description>Deprecated by the User Lookup object.</description>
        <label>Club Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>San Francisco Bay Chapter - 0100</fullName>
                </value>
                <value>
                    <fullName>Loma Prieta Chapter - 0200</fullName>
                </value>
                <value>
                    <fullName>Redwood Chapter - 0300</fullName>
                </value>
                <value>
                    <fullName>Angeles Chapter - 0400</fullName>
                </value>
                <value>
                    <fullName>San Diego Chapter - 0500</fullName>
                </value>
                <value>
                    <fullName>Kern-Kaweah Chapter - 0600</fullName>
                </value>
                <value>
                    <fullName>Illinois Chapter - 0700</fullName>
                </value>
                <value>
                    <fullName>Atlantic Chapter - 0800</fullName>
                </value>
                <value>
                    <fullName>Mother Lode Chapter - 0900</fullName>
                </value>
                <value>
                    <fullName>Los Padres Chapter - 1000</fullName>
                </value>
                <value>
                    <fullName>Washington State Chapter - 1100</fullName>
                </value>
                <value>
                    <fullName>San Gorgonio Chapter - 1200</fullName>
                </value>
                <value>
                    <fullName>Tehipite Chapter - 1300</fullName>
                </value>
                <value>
                    <fullName>Toiyabe Chapter - 1400</fullName>
                </value>
                <value>
                    <fullName>Ventana Chapter - 1500</fullName>
                </value>
                <value>
                    <fullName>John Muir Chapter - 1600</fullName>
                </value>
                <value>
                    <fullName>Rio Grande Chapter - 1700</fullName>
                </value>
                <value>
                    <fullName>Rocky Mountain Chapter - 1800</fullName>
                </value>
                <value>
                    <fullName>Lone Star Chapter - 1900</fullName>
                </value>
                <value>
                    <fullName>Grand Canyon Chapter - 2000</fullName>
                </value>
                <value>
                    <fullName>Michigan Chapter - 2100</fullName>
                </value>
                <value>
                    <fullName>Maryland Chapter - 2200</fullName>
                </value>
                <value>
                    <fullName>Alaska Chapter - 2300</fullName>
                </value>
                <value>
                    <fullName>Hawaii Chapter - 2400</fullName>
                </value>
                <value>
                    <fullName>Santa Lucia Chapter - 2500</fullName>
                </value>
                <value>
                    <fullName>Cumberland Chapter - 2600</fullName>
                </value>
                <value>
                    <fullName>North Star Chapter - 2700</fullName>
                </value>
                <value>
                    <fullName>Ohio Chapter - 2800</fullName>
                </value>
                <value>
                    <fullName>Utah Chapter - 2900</fullName>
                </value>
                <value>
                    <fullName>Massachusetts Chapter - 3000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/AssignLeaderPermissionsTest.cls
@IsTest
public with sharing class AssignLeaderPermissionsTest {
    static Id accountHouseholdTypeId;
    static Id contactHouseholdTypeId;
    static Id profileId;
    static User user1, user2, user3;
    static Account account1;
    static Contact contact1, contact2, contact3, contact4;

    static {
        accountHouseholdTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        contactHouseholdTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Household').getRecordTypeId();
		profileId = [SELECT Id FROM profile WHERE name='AddUp User'].Id;    
    }
	@IsTest
	public static void testAssignLeaderPermissions() {
		List<PermissionSet> eventPermSet = new List<PermissionSet>([
			select Id from PermissionSet where Name = 'Club_Leader'
		]);
		if(eventPermSet.size() == 0) {
			PermissionSet EventsPermissionSet = new PermissionSet(
				Name = 'Club_Leader',
				Label = 'Club Leader'
			);
			insert EventsPermissionSet;
		}
		
		Club_Entity__c SFBayChapter = new Club_Entity__c(
			Name='SF Bay Chapter',
			Status__c='Active',
			Type__c='Chapter'
		);
		insert SFBayChapter;

		setup();
		
		//Insert preference prior to creating user
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
		Test.startTest();
        System.runAs ( thisUser ) {
			rC_Bios__Preference_Code__c prefcode = new rC_Bios__Preference_Code__c(
				rC_Bios__Code_Value__c = 'SCFDNSTAFF', 
				rC_Bios__Category__c = 'Classification', 
				rC_Bios__Subcategory__c = 'Sierra Club/Foundation Staff'
			);
			insert prefcode;
			rC_Bios__Preference__c pref1 = new rC_Bios__Preference__c(
				rC_Bios__Contact__c = contact3.Id,
				rC_Bios__Code_Value__c = 'SCFDNSTAFF',
				rC_Bios__Active__c = true
			);
			insert pref1;

			List<User> userList = new List<User>();
			user1 = createUser(contact1);
			user2 = createUser(contact2);
			user3 = createUser(contact3);
			
			userList.add(user1);
			userList.add(user2);
			userList.add(user3);
			insert userList;

			//Insert preference after creating user
			rC_Bios__Preference__c pref2 = new rC_Bios__Preference__c(
				rC_Bios__Contact__c = contact2.Id,
				rC_Bios__Code_Value__c = 'SCFDNSTAFF',
				rC_Bios__Active__c = true
			);
			insert pref2;
        }
		
		List<Leader_Position__c> posList = new List<Leader_Position__c>();

		Leader_Position__c ChairPosition = new Leader_Position__c(
			Name='Chair',
			Code__c='CHR',
			ClubEventPermission_NonOutings__c = 'Administrator',
			ClubEventPermission_Outings__c = 'Administrator'
		);
		posList.add(ChairPosition);

		Leader_Position__c TreasurerPosition = new Leader_Position__c(
			Name='Treasurer',
			Code__c='TRS',
			ClubEventPermission_NonOutings__c = 'Standard',
			ClubEventPermission_Outings__c = 'None'
		);
		posList.add(TreasurerPosition);
		
		Leader_Position__c SecretaryPosition = new Leader_Position__c(
			Name='Secretary',
			Code__c='SEC',
			ClubEventPermission_NonOutings__c = 'Standard',
			ClubEventPermission_Outings__c = 'None'
		);
		posList.add(SecretaryPosition);
		
		insert posList;
		
		List<Leadership__c> roleList = new List<Leadership__c>();
		
		Leadership__c ChairRole = new Leadership__c(
			Club_Entity__c = SFBayChapter.id,
 			Leader_Position__c = ChairPosition.Id,
 			Contact__c = contact1.Id,
 			Position_Active__c = true
		);
		roleList.add(ChairRole);		

		Leadership__c SecretaryRole = new Leadership__c(
			Club_Entity__c = SFBayChapter.id,
 			Leader_Position__c = SecretaryPosition.Id,
 			Contact__c = contact1.Id,
 			Position_Active__c = true
		);
		roleList.add(SecretaryRole);		

		Leadership__c TreasurerRole = new Leadership__c(
			Club_Entity__c = SFBayChapter.id,
 			Leader_Position__c = TreasurerPosition.Id,
 			Contact__c = contact2.Id,
 			Position_Active__c = true
		);
		roleList.add(TreasurerRole);		
		
		//Trigger will fire to assign permissions
		insert roleList;

		Test.stopTest();
		
		//Check that permissions were created
		Set<String> leaderPermissionNames = new Set<String>{'Club_Leader'};

		List<PermissionSet> permList = new List<PermissionSet>([
			select Id, Name from PermissionSet
			where Name in :leaderPermissionNames
		]); 
		Map<String, Id>allLeaderPermissions = new Map<String, Id>();
		for(PermissionSet perms : permList) {
			allLeaderPermissions.put(perms.Name, perms.Id);
		}
		
		List<Id> userIdList = new List<Id>();
		userIdList.add(user1.Id);
		userIdList.add(user2.Id);
		List<PermissionSetAssignment> permSetList1 = new List<PermissionSetAssignment>([
			select PermissionSetId, AssigneeId from PermissionSetAssignment
			where AssigneeId in :userIdList and PermissionSetId in :allLeaderPermissions.values()
		]);
		
		for(PermissionSetAssignment psa : permSetList1) {
			System.debug('PermissionSetId:' + psa.PermissionSetId + '   -   ' + 'AssigneeId:' + psa.AssigneeId);
		}
		System.assertEquals(2, permSetList1.size());
		
		//Deactivate some roles and check that permissions were properly adjusted
		TreasurerRole.Position_Active__c = false;
		SecretaryRole.Position_Active__c = false;
		roleList.clear();
		roleList.add(TreasurerRole);
		roleList.add(SecretaryRole);
		update roleList;

		List<PermissionSetAssignment> permSetList2 = new List<PermissionSetAssignment>([
			select PermissionSetId, AssigneeId from PermissionSetAssignment
			where AssigneeId in :userIdList and PermissionSetId in :allLeaderPermissions.values()
		]);
		
		System.assertEquals(1, permSetList2.size());
		
		//Check that routine works properly for Contact that has user attached, but no leadership roles
		List<Id> contactIdList = new List<Id>();
		contactIdList.add(Contact3.Id);
		new AssignLeaderPermissions().assignPermissions(contactIdList);

		List<PermissionSetAssignment> permSetList3 = new List<PermissionSetAssignment>([
			select PermissionSetId, AssigneeId from PermissionSetAssignment
			where AssigneeId in :userIdList and PermissionSetId in :allLeaderPermissions.values()
		]);
		
		System.assertEquals(1, permSetList3.size());

		//Check that routine works properly for Contact that has no user attached
		contactIdList.clear();
		contactIdList.add(Contact4.Id);
		new AssignLeaderPermissions().assignPermissions(contactIdList);
		
		List<PermissionSetAssignment> permSetList4 = new List<PermissionSetAssignment>([
			select PermissionSetId, AssigneeId from PermissionSetAssignment
			where AssigneeId in :userIdList and PermissionSetId in :allLeaderPermissions.values()
		]);
		
		for(PermissionSetAssignment psa : permSetList4) {
			System.debug('PermissionSetId:' + psa.PermissionSetId + '   -   ' + 'AssigneeId:' + psa.AssigneeId);
		}
		System.assertEquals(1, permSetList4.size());
	}
   	static testMethod void test2() {
   		PermissionSet eventsPermissionSet;
		List<PermissionSet> eventPermSetList = new List<PermissionSet>([
			select Id from PermissionSet where Name = 'Club_Leader'
		]);
		if(eventPermSetList.size() > 0) {
			eventsPermissionSet = eventPermSetList.get(0);
		}
		else {
			eventsPermissionSet = new PermissionSet(
				Name = 'Club_Leader',
				Label = 'Club Leader'
			);
			insert eventsPermissionSet;
		}
		
		setup();
		//Use runAs to avoid mixed dml operation exception
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        System.runAs ( thisUser ) {
			List<User> userList = new List<User>();
			user1 = createUser(contact1);
			user2 = createUser(contact2);
			
			userList.add(user1);
			userList.add(user2);
			insert userList;

			Test.startTest();

			PermissionSetAssignment delPsa = new PermissionSetAssignment(
				AssigneeId = user1.Id,
				PermissionSetId = eventsPermissionSet.Id
			);
			insert delPsa;
			PermissionSetAssignment addPsa = new PermissionSetAssignment(
				AssigneeId = user2.Id,
				PermissionSetId = eventsPermissionSet.Id
			);
			
			List<String> permissionsToAdd = new List<String>();
			List<String> permissionsToDelete = new List<String>();
			permissionsToAdd.add(JSON.Serialize(addPsa));
			permissionsToDelete.add(JSON.Serialize(delPsa));

			AssignLeaderPermissions.adjustPermissions(permissionsToAdd, permissionsToDelete);
			
			Test.stopTest();
        }
		
		List<PermissionSetAssignment> permList1 = [
			select Id from PermissionSetAssignment
			where AssigneeId = :user1.Id and PermissionSetId = :eventsPermissionSet.Id 
		];
		System.assertEquals(0, permList1.size());
   	}
	private static User createUser(Contact ctct) {
		String FirstName = ctct.FirstName;
		String LastName = ctct.LastName;
		String Email = ctct.Email;
		
		string aliasText = '';
            if(FirstName != null && FirstName != '' && Lastname.length()>1){
                    aliasText = FirstName.substring(0,1);
            }
            if(Lastname != null && Lastname != '' && Lastname.length()>2){
                aliasText += Lastname.substring(0,3);
            }
            else{
                aliasText +=Lastname;
            }
        String myNickName = '';
        If (Email.length() > 40) {
          myNickName = Email.substring(0, 40);
        } else {
          myNickName = Email;
        }
        User usr = new User(firstName = FirstName,
                                    lastName = LastName,
                                    Email = Email,
                                    CommunityNickname = myNickName,
                                    languagelocalekey = 'en_US',
                                    localesidkey = UserInfo.getLocale(),
                                    emailEncodingKey = 'UTF-8',
                                    timeZoneSidKey = 'America/Los_Angeles', 
                                    profileId = profileId,
                                    userName = Email,
                                    //Initial_Password__c = newPassword,
                                    ContactId = ctct.Id,
                                    alias = aliasText );
        return usr;
	}
	private static void setup() {
		account1 = new Account(
            Name='Account1',
            RecordTypeId = accountHouseholdTypeId
		);
		insert account1;
		
		List<Contact> contactList = new List<Contact>();
        contact1 = new Contact(
            AccountId = account1.Id,
            FirstName = 'Test',
            LastName = 'Contact1',
            Email = 'test1.contact1@abc.com',
            RecordTypeId = contactHouseholdTypeId
        );
        contactList.add(contact1);  
		
        contact2 = new Contact(
            AccountId = account1.Id,
            FirstName = 'Test',
            LastName = 'Contact2',
            Email = 'test2.contact2@abc.com',
            RecordTypeId = contactHouseholdTypeId
        );  
		contactList.add(contact2);
		
        contact3 = new Contact(
            AccountId = account1.Id,
            FirstName = 'Test',
            LastName = 'Contact3',
            Email = 'test3.contact3@abc.com',
            RecordTypeId = contactHouseholdTypeId
        );  
		contactList.add(contact3);
		
        contact4 = new Contact(
            AccountId = account1.Id,
            FirstName = 'Test',
            LastName = 'Contact4',
            Email = 'test4.contact4@abc.com',
            RecordTypeId = contactHouseholdTypeId
        );  
		contactList.add(contact4);
		
		insert contactList;
	}
}