jlamontSC-test/src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vibhudadhichi-TicketReservation/src/objects/Account.object
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

jlamontSC-test/src/objects/Club_Entity__c.object
<CustomObject>
    <fields>
        <fullName>Entity_Category__c</fullName>
        <label>Entity/Team Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Board</fullName>
                </value>
                <value>
                    <fullName>Conservation Dept</fullName>
                </value>
                <value>
                    <fullName>Foundation</fullName>
                </value>
                <value>
                    <fullName>Grassroots Network</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Outings</fullName>
                </value>
                <value>
                    <fullName>SSC</fullName>
                </value>
                <value>
                    <fullName>Volunteer or Local Entity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity/Team Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Entity_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Entity_Team_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Club Entity/Team</label>
    <nameField>
        <label>Club Entity/Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Entities/Teams</pluralLabel>
    <recordTypes>
        <fullName>Team</fullName>
        <active>true</active>
        <label>Team</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AkshayVispute-Salesforce/akshay.vispute@eternussolutions.com/src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Leader_Position__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Entity_Types__c</fullName>
        <label>Entity/Team Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Entity_Team_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Leader Position</label>
    <nameField>
        <label>Leader Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leader Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Leadership__c.object
<CustomObject>
    <fields>
        <fullName>Club_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Club entities such as chapters and groups.</description>
        <label>Club Entity</label>
        <referenceTo>Club_Entity__c</referenceTo>
        <relationshipName>Leadership</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Leaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Leader_Position__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Position within a club entity or team</description>
        <label>Position</label>
        <referenceTo>Leader_Position__c</referenceTo>
        <relationshipLabel>Leadership/Team Membership</relationshipLabel>
        <relationshipName>Leadership</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Leadership/Team Membership</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Leadership/Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leadership/Team Membership</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/TeamMemberControllerExtTest.cls
@isTest
public class TeamMemberControllerExtTest {
    
    private static Id accountHouseholdTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
    private static Id contactHouseholdTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Household').getRecordTypeId();
    private static Id teamTypeId = Schema.SObjectType.Club_Entity__c.getRecordTypeInfosByName().get('Team').getRecordTypeId();
    
    static testMethod void myUnitTest() {
        
        Account account1 = new Account(
            Name='Account1',
            RecordTypeId = accountHouseholdTypeId
        );
        insert account1;
        
        Contact contact1 = new Contact(
            AccountId = account1.Id,
            FirstName = 'Test',
            LastName = 'Contact1',
            Email = 'test1.contact1@abc.com',
            RecordTypeId = contactHouseholdTypeId
        );           
        insert contact1;
        
        Club_Entity__c entity = new Club_Entity__c(
            Name = 'Test Entity',
            RecordTypeId = teamTypeId,
            Entity_Category__c = 'Conservation Dept',
            Entity_Type__c = 'Organizing Teams'
        );
        insert entity;
        
        Leader_Position__c pos = new Leader_Position__c(
            Name = 'Test Position',
            Code__c = 'TEST',
            Active__c = true,
            Entity_Types__c = 'Organizing Teams'
        );        
        insert pos;
      
        Leadership__c lead = new Leadership__c(Club_Entity__c = entity.Id, Contact__c = contact1.id, Leader_Position__c = pos.id);
        insert lead;
        
        PageReference PageRef = Page.NewAction;
        Test.setCurrentPage(PageRef);   
        TeamMemberControllerExt controller = new TeamMemberControllerExt(new ApexPages.StandardController(lead));
        controller.getPositionOptions();
        
    }    

}