jlamontSC-test/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>The city the account is located in.</inlineHelpText>
        <label>City (old)</label>
        <length>80</length>
        <type>Text</type>
    </fields>

lanecwe-Prod/src/objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This field is dynamically set.  If it has 0 companies associated to it the value is Prospect.  If it has &gt; 0 companies associated to it then it will be Customer.  There are also some Partner channel specific things that will set the value to Customer.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

jlamontSC-test/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Autoresponder_Text__c</fullName>
        <inlineHelpText>You can use HTML to format text in this field. Otherwise, it will display as a single paragraph of plain text.</inlineHelpText>
        <label>Additional Autoresponder Text</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Autoresponder_Type__c</fullName>
        <label>Event Branding</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sierra Club</fullName>
                </value>
                <value>
                    <fullName>SierraRise</fullName>
                </value>
                <value>
                    <fullName>ClimateParents</fullName>
                </value>
                <value>
                    <fullName>SSC</fullName>
                </value>
                <value>
                    <fullName>SeizeTheGrid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Custom_Field_1_Label__c</fullName>
        <label>Custom Field 1 Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Field_2_Label__c</fullName>
        <label>Custom Field 2 Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Field_3_Label__c</fullName>
        <label>Custom Field 3 Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Field_4_Label__c</fullName>
        <label>Custom Field 4 Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Field_5_Label__c</fullName>
        <label>Custom Field 5 Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <inlineHelpText>This is the name that will display on the Event Details page</inlineHelpText>
        <label>Event Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Events_Category__c</fullName>
        <description>Category of Event</description>
        <label>Event Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Activist Event</fullName>
                </value>
                <value>
                    <fullName>Club Support Event</fullName>
                </value>
                <value>
                    <fullName>Outing</fullName>
                </value>
                <value>
                    <fullName>Social Event</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Events_Type__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Events_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Backpack</fullName>
                </value>
                <value>
                    <fullName>Base camping</fullName>
                </value>
                <value>
                    <fullName>Biking</fullName>
                </value>
                <value>
                    <fullName>Bus trip</fullName>
                </value>
                <value>
                    <fullName>Canoeing</fullName>
                </value>
                <value>
                    <fullName>Canvassing/Walking area</fullName>
                </value>
                <value>
                    <fullName>Canyoneering</fullName>
                </value>
                <value>
                    <fullName>Car Camping</fullName>
                </value>
                <value>
                    <fullName>Commission/Town hall meeting</fullName>
                </value>
                <value>
                    <fullName>Committee meeting</fullName>
                </value>
                <value>
                    <fullName>Community forum</fullName>
                </value>
                <value>
                    <fullName>Cruise</fullName>
                </value>
                <value>
                    <fullName>Dinner</fullName>
                </value>
                <value>
                    <fullName>Dog sledding</fullName>
                </value>
                <value>
                    <fullName>Educational</fullName>
                </value>
                <value>
                    <fullName>Film</fullName>
                </value>
                <value>
                    <fullName>Fishing</fullName>
                </value>
                <value>
                    <fullName>Fundraiser</fullName>
                </value>
                <value>
                    <fullName>General meeting</fullName>
                </value>
                <value>
                    <fullName>Hearing</fullName>
                </value>
                <value>
                    <fullName>Hike</fullName>
                </value>
                <value>
                    <fullName>Hiking-Canine</fullName>
                </value>
                <value>
                    <fullName>Horseback riding</fullName>
                </value>
                <value>
                    <fullName>Houseparty</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Kayaking</fullName>
                </value>
                <value>
                    <fullName>Leader training</fullName>
                </value>
                <value>
                    <fullName>Letter writing</fullName>
                </value>
                <value>
                    <fullName>Lobbying</fullName>
                </value>
                <value>
                    <fullName>Lodge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_RSVP_to_Leader__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, the Primary Leader will receive an email notification each time a user registers for the event. Registrations must be enabled, above, for notifications to be sent.</inlineHelpText>
        <label>Send RSVP notifications to Leader?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sponsor_Description__c</fullName>
        <inlineHelpText>If you do not enter a value, this field will auto populate when you select a Club Entity and Save</inlineHelpText>
        <label>Sponsor Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <inlineHelpText>Times must be in format h:mm AM/PM</inlineHelpText>
        <label>Start Time</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Event will not be published until Status is set to Active</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Development</fullName>
                    <default>true</default>
                    <label>In Development</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>At Capacity</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary_Description__c</fullName>
        <inlineHelpText>A short description that may be displayed in public search results, etc.</inlineHelpText>
        <label>Text Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Local Time</fullName>
                    <default>true</default>
                    <label>Local Time</label>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Pacific</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Eastern</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Events</fullName>
        <active>true</active>
        <description>Events</description>
        <label>Events</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

vibhudadhichi-TicketReservation/src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/Contact.object
    <fields>
        <fullName>Status__c</fullName>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>1- Working - Active Opp Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2- Working - Talking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3- Working - Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4- Strategic Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5- Active Project Team Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6- Active Self Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7- Passive &amp; Friendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8- Passive &amp; Unfriendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9-HOLD Not mine/move</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10-Dimagi Staff</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

jlamontSC-test/src/objects/Event_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Event Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Event Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>Campaign&apos;s Event Name field, for layout purposes.</description>
        <formula>Campaign__r.Event_Name__c</formula>
        <label>Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Registered</fullName>
                    <default>true</default>
                    <label>Registered</label>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>ER-{0000000}</displayFormat>
        <label>Event Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/ActionsForEventAttendeesCtlTest.cls
@isTest
private class ActionsForEventAttendeesCtlTest {
    private static Id accountHouseholdTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
    private static Id contactHouseholdTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Household').getRecordTypeId();
    private static Id eventsTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Events').getRecordTypeId();

    static testMethod void myUnitTest() {
        ClubEventTriggerHandler.testing = true;
		Account account1 = new Account(
            Name='Account1',
            RecordTypeId = accountHouseholdTypeId
		);
		insert account1;
		
		List<Contact> contactList = new List<Contact>();
        Contact contact1 = new Contact(
            AccountId = account1.Id,
            FirstName = 'Test',
            LastName = 'Contact1',
            Email = 'test1.contact1@abc.com',
            RecordTypeId = contactHouseholdTypeId
        );
        contactList.add(contact1);  
          
		insert contactList;

    	Campaign evnt = new Campaign(
    		RecordTypeId = eventsTypeId,
    		Name = 'Testing',
    		Event_Name__c = 'Testing',
    		Status__c = 'In Development',
    		Events_Category__c = 'Outing',
    		Events_Type__c = 'Hike',
    		Start_Date__c = System.today(),
    		Start_Time__c = '8:00 AM',
    		Time_Zone__c = 'Local Time',
    		Summary_Description__c = 'Testing',
    		Sponsor_Description__c = 'Test Sponsor',
    		Custom_Field_1_Label__c = '',
    		Custom_Field_2_Label__c = '',
    		Custom_Field_3_Label__c = '',
    		Custom_Field_4_Label__c = '',
    		Custom_Field_5_Label__c = '',
    		Autoresponder_Text__c = '',
    		Send_RSVP_to_Leader__c = true,
			Autoresponder_Type__c = 'National'
		);
    	insert evnt;
		
    	Event_Registration__c reg = new Event_Registration__c(
    		Campaign__c = evnt.Id,
    		Contact__c = contact1.Id,
    		Status__c = 'Registered',
    		First_Name__c = 'Test',
    		Last_Name__c = 'Contact1',
    		Email__c = 'test.contact1@sierraclub.org',
    		Phone__c = '',
    		Mobile_Phone__c = '',
    		Street__c = '',
    		City__c = '',
    		State__c = '',
    		PostalCode__c = '',
    		Custom_Field_1_Response__c = '',
    		Custom_Field_2_Response__c = '',
    		Custom_Field_3_Response__c = '',
    		Custom_Field_4_Response__c = '',
    		Custom_Field_5_Response__c = ''
    	);
    	insert reg;
	
		PageReference PageRef = Page.ActionsForEventAttendees;
		Test.setCurrentPage(PageRef);
		ApexPages.currentPage().getParameters().put('id', evnt.Id); 	
		ActionsForEventAttendeesCtl controller = new ActionsForEventAttendeesCtl();
		
		String eventTitle = controller.getEventTitle();
		System.assertEquals(evnt.Event_Name__c, eventTitle);
		
		kweos__EOCS_Data__c action = controller.action;
		action.Action__c = 'Petition Collection';
		action.Action_Status__c = 'Committed';
		action.Action_Date__c = System.today();
		
		List<ActionsForEventAttendeesCtl.Wrapper> attendeeList = controller.getRegistrantList();
		ActionsForEventAttendeesCtl.Wrapper wrapper = attendeeList.get(0);
		wrapper.isSelected = true;
		controller.save();
		
		List<kweos__EOCS_Data__c> actionList = [
			select Action__c, Action_Status__c, Action_Date__c
			from kweos__EOCS_Data__c
			where kwac__Contact__c = :contact1.Id
		];
		System.assertEquals(1, actionList.size());
		kweos__EOCS_Data__c actionForContact = actionList.get(0);
		System.assertEquals('Petition Collection', actionForContact.Action__c);
		System.assertEquals('Committed', actionForContact.Action_Status__c);
		System.assertEquals(System.today(), actionForContact.Action_Date__c);
		
		action.Action__c = 'Petition Collection';
		action.Action_Status__c = 'Committed';
		action.Action_Date__c = System.today();
		controller.saveAndMore();
		
		controller.cancel();
    }
}