jlamontSC-test/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Original_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Original_Campaign__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Original Campaign for newly created accounts and contacts, if blank. Org-wide and profile-level defaults.</description>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <label>Campaign Name</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Original Campaign</label>
</CustomObject>

jlamontSC-test/src/classes/AccountTriggerTest.cls
//*********************************************************************//
// (c) 2014 Appirio, Inc.
//
//	Test  Class for account trigger.
//	18 March 2014   KapiL Choudhary(Jaipur D.C.)
//  Updated: 
//**********************************************************************//   


@isTest
private class AccountTriggerTest {

    static testMethod void defaultCampaignTest() {
    	TestDataUtility tDu = new TestDataUtility();
    	Campaign camp = new Campaign (Name='Z17Z567890');
    	Original_Campaign__c oCampName = new Original_Campaign__c(Campaign_Name__c = camp.Name);
    	insert oCampName;
    	
    	account acc = tDu.createNewAccount(true,'testAccName',null);
    	list<account> accList = [select Original_Campaign__c from account where id=:acc.id];
    	// original campaign is set.
    	system.assertEquals(accList[0].Original_Campaign__c, camp.id);
    }
}