jlamontSC-test/src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Account.object
    <fields>
        <fullName>Address__c</fullName>
        <description>Address for account record</description>
        <label>BillingAddress</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>

jlamontSC-test/src/objects/DuplicateAddress__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DuplicateAddresses</relationshipLabel>
        <relationshipName>DuplicateAddresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Address</label>
        <referenceTo>rC_Bios__Account_Address__c</referenceTo>
        <relationshipLabel>DuplicateAddresses</relationshipLabel>
        <relationshipName>DuplicateAddresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DuplicateAddress</label>
    <nameField>
        <displayFormat>DA-{00000000}</displayFormat>
        <label>DuplicateAddress Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DuplicateAddresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/DuplicateAddressLocatorTest.cls
@IsTest
public with sharing class DuplicateAddressLocatorTest {
	@IsTest
	static void testDupLocator() {
		Account account1, account2;
		rC_Bios__Account_Address__c addr1, addr2, addr3, addr4;
		List<Account> accounts = new List<Account>();
		List<rC_Bios__Account_Address__c> addrs = new List<rC_Bios__Account_Address__c>();

		account1 = new Account(Name='Account1');
		account2 = new Account(Name='Account2');
		accounts.add(account1);
		accounts.add(account2);
		insert accounts;

		addr1 = new rC_Bios__Account_Address__c(
			rC_Bios__Account__c = account1.Id,
			rC_Bios__Type__c = 'HOME'
		);		
		addr2 = new rC_Bios__Account_Address__c(
			rC_Bios__Account__c = account1.Id,
			rC_Bios__Type__c = 'HOME'
		);		
		addr3 = new rC_Bios__Account_Address__c(
			rC_Bios__Account__c = account2.Id,
			rC_Bios__Type__c = 'HOME'
		);		
		addr4 = new rC_Bios__Account_Address__c(
			rC_Bios__Account__c = account2.Id,
			rC_Bios__Type__c = 'WORK'
		);
		addrs.add(addr1);
		addrs.add(addr2);
		addrs.add(addr3);
		addrs.add(addr4);
		insert addrs;
		
		Test.startTest();
		Database.executeBatch(new DuplicateAddressLocator());
		Test.stopTest();
		
       	List<DuplicateAddress__c> dupList = new List<DuplicateAddress__c>([
       		SELECT Account__c, Address__c FROM DuplicateAddress__c
       	]);
       	
       	System.assertEquals(2, dupList.size());
       	for(DuplicateAddress__c addr : dupList) {
       		System.assertEquals(account1.Id, addr.Account__c);
       	}
	}
}