jlamontSC-test/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Membership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Membership</label>
        <referenceTo>Membership__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>AccountsMembership</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Leader_Position__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Leader Position</label>
    <nameField>
        <label>Leader Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leader Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Leadership__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Leaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Leader_Position__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Position within a club entity or team</description>
        <label>Position</label>
        <referenceTo>Leader_Position__c</referenceTo>
        <relationshipLabel>Leadership/Team Membership</relationshipLabel>
        <relationshipName>Leadership</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Leadership/Team Membership</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Leadership/Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leadership/Team Membership</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>Member_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Merge_Request__c.object
<CustomObject>
    <fields>
        <fullName>Date_Last_Step_Completed__c</fullName>
        <label>Date Last Step Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <defaultValue>&quot;&quot;</defaultValue>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Step_Completed__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Last Step Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Account__c</fullName>
        <label>Previous Account Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retained_Account__c</fullName>
        <label>Retained Account Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Merge Request</label>
    <nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Merge Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merge Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Reservation__c.object
<CustomObject>
    <description>Club Resv data</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reservations</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/MergeDeleteTest.cls
@IsTest
public with sharing class MergeDeleteTest {
	@IsTest
	static void testMergeDelete() {
		Account account1, account2, account3;
		Contact contact1, contact2;
		List<Account> accounts = new List<Account>();
		List<Contact> contacts = new List<Contact>();
		
		account1 = new Account(Name='Account1');
		account2 = new Account(Name='Account2');
		account3 = new Account(Name='Account3');
		accounts.add(account1);
		accounts.add(account2);
		accounts.add(account3);
		insert accounts;

		rC_Bios__Account_Address__c addr = new rC_Bios__Account_Address__c(	
			rC_Bios__Account__c = account1.Id
		);
		insert addr;
		
		Membership__c mbr = new Membership__c(
			Member_Account__c = account1.Id
		);
		insert mbr;
		
        Leader_Position__c pos = new Leader_Position__c(
            Name = 'Chair',
            Code__c = 'CHR'
        );
        insert pos;
            
		Leadership__c ldr = new Leadership__c(
			Account__c = account1.Id,
            Leader_Position__c = pos.Id
		);
		insert ldr;
		
		Reservation__c resv = new Reservation__c(
			Account__c = account1.Id
		);
		insert resv;
			
		List<Merge_Request__c> requestList = new List<Merge_Request__c>();
		Merge_Request__c request1 = new Merge_Request__c(
			Previous_Account__c = account1.Id,
			Retained_Account__c = account2.Id
		);
		requestList.add(request1);
		Merge_Request__c request2 = new Merge_Request__c(
			Previous_Account__c = account3.Id
		);
		requestList.add(request2);
		insert requestList;

		List<rC_Bios__Account_Address__c> beforeAddrs = new List<rC_Bios__Account_Address__c>([
			SELECT Id, rC_Bios__Account__c FROM rC_Bios__Account_Address__c
		]);
		System.Assert(beforeAddrs.size() == 1);

		List<Membership__c> beforeMbrs = new List<Membership__c>([
			SELECT Id, Member_Account__c FROM Membership__c
		]);
		System.Assert(beforeMbrs.size() == 1);

		List<Leadership__c> beforeLdrs = new List<Leadership__c>([
			SELECT Id, Account__c FROM Leadership__c
		]);
		System.Assert(beforeLdrs.size() == 1);

		List<Reservation__c> beforeRsvs = new List<Reservation__c>([
			SELECT Id, Account__c FROM Reservation__c
		]);
		System.Assert(beforeRsvs.size() == 1);

		List<Account> beforeActs = new List<Account>([
			SELECT Id, Name FROM Account
		]);
		System.Assert(beforeActs.size() == 3);

		Test.startTest();
		MergeDelete.processMerges(requestList);
		Test.stopTest();
		
		List<rC_Bios__Account_Address__c> afterAddrs = new List<rC_Bios__Account_Address__c>([
			SELECT Id, rC_Bios__Account__c FROM rC_Bios__Account_Address__c
		]);
		System.Assert(afterAddrs.size() == 0);

		List<Membership__c> afterMbrs = new List<Membership__c>([
			SELECT Id, Member_Account__c FROM Membership__c
		]);
		System.Assert(afterMbrs.size() == 0);

		List<Leadership__c> afterLdrs = new List<Leadership__c>([
			SELECT Id, Account__c FROM Leadership__c
		]);
		System.Assert(afterLdrs.size() == 0);

		List<Reservation__c> afterRsvs = new List<Reservation__c>([
			SELECT Id, Account__c FROM Reservation__c
		]);
		System.Assert(afterRsvs.size() == 0);

		List<Account> afterActs = new List<Account>([
			SELECT Id, Name FROM Account
		]);
		System.Assert(afterActs.size() == 2);
		
		List<Merge_Request__c> afterMerges = new List<Merge_Request__c>([
			SELECT Last_Step_Completed__c, Date_Last_Step_Completed__c, Error_Message__c FROM Merge_Request__c
		]);
		for(Merge_Request__c request : afterMerges) {
			System.assertEquals(MergeProcessor.deleteObjectsStep, request.Last_Step_Completed__c);
			System.assert(request.Date_Last_Step_Completed__c != null);
			System.assert(String.isEmpty(request.Error_Message__c));
		}
		System.assert(afterMerges.size() == 2);
	}
}