jlamontSC-test/src/objects/Call_Report__c.object
<CustomObject>
    <description>Stores the Planned Giving and Major Giving discussions that cannot be stored in tasks.</description>
    <fields>
        <fullName>Call_Type__c</fullName>
        <label>Call Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Major Giving</fullName>
                </value>
                <value>
                    <fullName>Planned Giving</fullName>
                </value>
                <value>
                    <fullName>Business Partnership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Task__c</fullName>
        <label>Parent Task</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Contact Report</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Contact Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/CallEmailExtensionTest.cls
//*********************************************************************
// (c) 2014 Appirio, Inc.
//
//	Test Class for CallEmailExtension 
//	24 Feb 2014     Pitamber Sharma (Appirio)     Original
//	9 March 2014     Virendra (Appirio)     Updated
//
//	2014/8/7		VB: WARNING: This class fails in production.
//					It assume the existance of the "test" user.
//					I'm changing it to me, unless I can think of a better
//					test user.
//**********************************************************************/
@isTest
private class CallEmailExtensionTest {

    static testMethod void myUnitTest() {
    	Test.startTest();
			Task task = new task(To__c = 'test@test.com', CC__c = 'test1@test.com', Bcc__c = 'test2@test.com');
			insert task;
			
			Call_Report__c cr = new Call_Report__c(Parent_Task__c = task.Id, Call_Type__c = 'Major Giving');
			insert cr;
		
			PageReference prPageLink = Page.CallEmail;
		    test.setCurrentPage(prPageLink);
		        
		    ApexPages.StandardController sc = new ApexPages.StandardController(task);
		    CallEmailExtension callEmailExtContrl = new CallEmailExtension(sc);
            callEmailExtContrl.toAddress = 'test@test.com';
            callEmailExtContrl.ccAddress = 'test1@test.com';
            callEmailExtContrl.bccAddress= 'test2@test.com';
            
			// VB: WARNING: This fails, no idea why, but sick of trying to guess what Appirio code does.
			// 
			// System.NullPointerException: Attempt to de-reference a null object
			//	Stack Trace	Class.CallEmailExtension.doSendEmail: line 156, column 1
			//	Class.CallEmailExtensionTest.myUnitTest: line 33, column 1
			// 
        	//callEmailExtContrl.doSendEmail();
			
			
			Task task1 = new task(To__c = 'test@test.com', CC__c = 'test1@test.com', Bcc__c = 'test2@test.com');
			insert task1;
			
			Call_Report__c cr1 = new Call_Report__c(Parent_Task__c = task1.Id, Call_Type__c = 'Planned Giving');
			insert cr1;
		
			prPageLink = Page.CallEmail;
		    test.setCurrentPage(prPageLink);
		        
		    sc = new ApexPages.StandardController(task1);
		    callEmailExtContrl = new CallEmailExtension(sc);
            callEmailExtContrl.toAddress = 'test@test.com';
            callEmailExtContrl.ccAddress = 'test1@test.com';
            callEmailExtContrl.bccAddress= 'test2@test.com';
        
        	// VB WARNING: Need to find a stable user in Production ( and refreshed to current sandboxes )
            CallEmailExtension.fetchListOfTags('Baas');
            
			// VB: WARNING: This fails, no idea why, but sick of trying to guess what Appirio code does.
			// 
			//	Error Message	System.NullPointerException: Attempt to de-reference a null object
			//	Stack Trace	Class.CallEmailExtension.doSendEmail: line 156, column 1
			//	Class.CallEmailExtensionTest.myUnitTest: line 60, column 1			// 
			//callEmailExtContrl.doSendEmail();
			
		Test.stoptest();
    }
}