jlamontSC-test/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Attended_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Attended Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cancelled_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cancelled Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Club_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Club Event</label>
        <referenceTo>Club_Event__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Registration_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Event Registration Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NoShow_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>NoShow Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Event will not be published until Status is set to Active</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Development</fullName>
                    <default>true</default>
                    <label>In Development</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>At Capacity</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Club_Event__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Club Events</relationshipLabel>
        <relationshipName>Club_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Changes Required</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>At Capacity</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Club Event</label>
    <nameField>
        <displayFormat>CE-{0000000}</displayFormat>
        <label>Club Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AkshayVispute-Salesforce/akshay.vispute@eternussolutions.com/src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Event_Registration__c.object
<CustomObject>
    <fields>
        <fullName>AttendedCount__c</fullName>
        <formula>IF(ISPICKVAL(Status__c, &apos;Attended&apos;), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AttendedCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Event Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CancelledCount__c</fullName>
        <formula>IF(ISPICKVAL(Status__c, &apos;Cancelled&apos;), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CancelledCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Club_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Club Event</label>
        <referenceTo>Club_Event__c</referenceTo>
        <relationshipLabel>Event Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Event Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mobile_Subscriber_Opt_In__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile Subscriber Opt In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NoShowCount__c</fullName>
        <formula>IF(ISPICKVAL(Status__c, &apos;No Show&apos;), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NoShowCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>RegisteredCount__c</fullName>
        <formula>IF(ISPICKVAL(Status__c, &apos;Registered&apos;), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RegisteredCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Registered</fullName>
                    <default>true</default>
                    <label>Registered</label>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>ER-{0000000}</displayFormat>
        <label>Event Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/EventRegistrationTriggerHandler.cls
/*
EventRegistrationTriggerHandler

Called by EventRegistrationTrigger - after delete, after insert, after update

Keeps up-to-date counts on Event Campaigns of Registrations for the Event that are not Cancelled.

Mark Maslow - January 2016

July 2016 - Maslow
Change owner id to Cast Iron to enable regular users to delete registration

January 2017 - Maslow
If lookup to Club Event is missing, get it from Campaign and add it before inserting

Add counts on Campaign for Attended, No Show, Cancelled

April 2017 - Tami Lau
Added deleteBatchUpload method
*/
public without sharing class EventRegistrationTriggerHandler {
    private static final Id castironUserId = UserLookup.getId('ciron');
	public static void handleChange() {
		List<Event_Registration__c> regList;
		if(Trigger.isDelete) {
			regList = Trigger.old;
		}
		else if(Trigger.isInsert){
			regList = Trigger.new;
			if(Trigger.isBefore) {
				Set<Id> campaignIdSet = new Set<Id>();
				for(Event_Registration__c reg : regList) {
					reg.OwnerId = castironUserId;
					if(String.isEmpty(reg.Club_Event__c)) {
						campaignIdSet.add(reg.Campaign__c);
					}
				}
				if( ! campaignIdSet.isEmpty() ) {
					Map<Id, Campaign> campaignToClubEventMap = new Map<Id, Campaign>([
						select Id, Club_Event__c
						from Campaign
						where Id in :campaignIdSet
					]);
					for(Event_Registration__c reg : regList) {
						Campaign camp = campaignToClubEventMap.get(reg.Campaign__c);
						if(camp != null) {
							reg.Club_Event__c = camp.Club_Event__c;
						}
					}
				}
				return;
			}
		}
		else {
			regList = new List<Event_Registration__c>();
			for(sObject obj : Trigger.new) {
				Event_Registration__c reg = (Event_Registration__c)obj;
				Event_Registration__c oldReg = (Event_Registration__c)Trigger.oldMap.get(reg.Id);
				if(oldReg != null) {
					if(reg.Campaign__c != oldReg.Campaign__c) {
						regList.add(reg);
						regList.add(oldReg);	
					}
					else {
						if(reg.Status__c != oldReg.Status__c) {
					    	regList.add(reg);
					    }
					}
				}
			}
		}
		Set<Id> idSet = new Set<Id>();
		for(Event_Registration__c reg : regList) {
			if(reg.Campaign__c != null) {
				idSet.add(reg.Campaign__c);
			}
		}
		if( ! idSet.isEmpty() ) {
			SummarizeRegistrations(idSet);
		}

		List<UpsertMobileIntegrationRequests.MobileIntegrationParameters> contactList = new List<UpsertMobileIntegrationRequests.MobileIntegrationParameters>();
		if(Trigger.isAfter && (Trigger.isInsert || Trigger.isUpdate) ) {
			List<Event_Registration__c> eventRegList = Trigger.new;
			for(Event_Registration__c reg : eventRegList) {
				if(Trigger.isInsert) {
					if(reg.Mobile_Subscriber_Opt_In__c == true) {
						if( ! String.isEmpty(reg.Contact__c) ) {
							if( ! String.isEmpty(reg.Mobile_Phone__c)) {
								UpsertMobileIntegrationRequests.MobileIntegrationParameters parms = new UpsertMobileIntegrationRequests.MobileIntegrationParameters(
									reg.Contact__c,
									reg.Mobile_Phone__c,
									'Event Registration'
								);
								parms.eventRegistrationId = reg.Id;
								contactList.add(parms);
							}
						}
					}
				}
				else if(Trigger.isUpdate) {
					if(reg.Mobile_Subscriber_Opt_In__c == true) {
						if( ! String.isEmpty(reg.Contact__c) ) {
							if( ! String.isEmpty(reg.Mobile_Phone__c)) {
								Event_Registration__c oldReg = (Event_Registration__c) Trigger.oldMap.get(reg.Id);
								if(String.isEmpty(oldReg.Contact__c) || String.isEmpty(oldReg.Phone__c)) {
									UpsertMobileIntegrationRequests.MobileIntegrationParameters parms = new UpsertMobileIntegrationRequests.MobileIntegrationParameters(
										reg.Contact__c,
										reg.Mobile_Phone__c,
										'Event Registration'
									);
									parms.eventRegistrationId = reg.Id;
									contactList.add(parms);
								}
							}
						}
					}
				}
			}
		}
		if( ! contactList.isEmpty() ) {
			UpsertMobileIntegrationRequests.upsertRequests(contactList);
		}
	}
	@future
	public static void SummarizeRegistrations(Set<Id> campIds) {
		//Ensure that all campaigns to summarize actually exist
		//(Deleting campaigns deletes all registrations for deleted campaigns)
		List<Campaign> campaignIdList = [
			select Id
			from Campaign
			where Id in :campIds
		];
		Set<Id> campaignIds = new Set<Id>();
		for(Campaign camp : campaignIdList) {
			campaignIds.add(camp.Id);
		}
		if(campaignIds.isEmpty()) {
			return;
		}
		List<Campaign> campList = new List<Campaign>();
		AggregateResult[] groupedResults = [
  			SELECT
  				Campaign__c,
  				sum(RegisteredCount__c)registered,
  				sum(CancelledCount__c)cancelled,
  				sum(AttendedCount__c)attended,
  				sum(NoShowCount__c)noshow 
  			FROM Event_Registration__c
  			WHERE Campaign__c IN :campaignIds
  			GROUP BY Campaign__c
  		];
  		Set<Id> campaignsWithResults = new Set<Id>();
  		for (AggregateResult ar : groupedResults) {
  			Decimal notCancelledCount =
  				(Decimal)ar.get('registered') +
  				(Decimal)ar.get('attended') + 
  				(Decimal)ar.get('noshow');
  			Campaign camp = new Campaign(
  				Id = (Id)ar.get('Campaign__c'),
  				Event_Registration_Count__c = notCancelledCount,
  				Cancelled_Count__c = (Decimal)ar.get('cancelled'),
  				Attended_Count__c = (Decimal)ar.get('attended'),
  				NoShow_Count__c = (Decimal)ar.get('noshow')
  			);
  			campaignsWithResults.add(camp.Id);
  			campList.add(camp);
  		}
  		for(Id campId : campaignIds) {
  			if( ! campaignsWithResults.contains(campId) ) {
  				Campaign camp = new Campaign(
	  				Id = campId,
	  				Event_Registration_Count__c = 0,
	  				Cancelled_Count__c = 0,
	  				Attended_Count__c = 0,
	  				NoShow_Count__c = 0
  				);
  				campList.add(camp);
  			}
  		}
  		if( ! campList.isEmpty() ) {
			update campList;
  		}
	}
    
	//if the deleted Event Registration had a corresponding batch upload, delete the batch upload
    public static void deleteBatchUpload(List<Event_Registration__c> regs) {
        
        List<String> regIDs = new List<String>();
        for (Event_Registration__c r : regs) {
            regIDs.add(string.valueOf(r.Id));
        }

		List<rC_Connect__Batch_Upload__c> batchUploads = new List<rC_Connect__Batch_Upload__c>([SELECT Id FROM rC_Connect__Batch_Upload__c WHERE Event_Registration_Id__c IN :regIDs]);
		
        if (batchUploads.size() > 0) {
            delete batchUploads;
        }
		       
    }    
}