jlamontSC-test/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Strategy_Global__c</fullName>
        <label>National Campaign Strategy</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>National_Campaign_Global__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Reporting_Attribute_Campaign_Strategy</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Local_Campaign_Global__c</fullName>
        <label>National Sub-Campaign</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Campaign_Strategy_Global__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Reporting_Attribute_Local_Campaign</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>National_Campaign_Global__c</fullName>
        <inlineHelpText>Use for national conservation campaign or program work</inlineHelpText>
        <label>National Campaign</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reporting_Attribute_National_Campaign</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Promo_Description__c</fullName>
        <inlineHelpText>Internal description</inlineHelpText>
        <label>Internal Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Global__c</fullName>
        <description>Primary state in which local campaign is happening, not necessarily where tactic occurs.</description>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tactic_Owner_Category_Global__c</fullName>
        <label>Tactic Owner Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reporting_Attribute_Tactic_Owner_Catego</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tactic_Owner_Global__c</fullName>
        <label>Tactic Owner</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Tactic_Owner_Category_Global__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Reporting_Attribute_Tactic_Owner</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/ActionTagControllerTest.cls
@isTest
private class ActionTagControllerTest {

    static testMethod void myUnitTest() {
    	BulkEntryController bec = new BulkEntryController();
    	ActionTagController atc = new ActionTagController();
    	atc.pageController = bec;
    	
    	Campaign camp = new Campaign(
    		Name='Test Campaign'
    	);
    	insert camp;
    	
    	atc.selectedCampaignId = camp.Id;
    	atc.setSelectedCampaign();
    	
    	atc.setDtStartString('1/1/2017');
    	atc.setDtEndString('12/31/2017');
    	atc.setDtActionString('1/1/2017');
    	atc.getDtStartString();
    	atc.getDtEndString();
    	atc.getDtActionString();
    	
    	atc.campaignName = 'Test Campaign';

		Schema.DescribeFieldResult fieldResult = Campaign.National_Campaign_Global__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		atc.camp.National_Campaign_Global__c = ple.get(0).getValue();
		
		fieldResult = Campaign.Campaign_Strategy_Global__c.getDescribe();
		ple = fieldResult.getPicklistValues();
		atc.camp.Campaign_Strategy_Global__c = ple.get(0).getValue();

		fieldResult = Campaign.Local_Campaign_Global__c.getDescribe();
		ple = fieldResult.getPicklistValues();
		atc.camp.Local_Campaign_Global__c = ple.get(0).getValue();

		fieldResult = Campaign.State_Global__c.getDescribe();
		ple = fieldResult.getPicklistValues();
		atc.camp.State_Global__c = ple.get(0).getValue();

		fieldResult = Campaign.Tactic_Owner_Category_Global__c.getDescribe();
		ple = fieldResult.getPicklistValues();
		atc.camp.Tactic_Owner_Category_Global__c = ple.get(0).getValue();

		fieldResult = Campaign.Tactic_Owner_Global__c.getDescribe();
		ple = fieldResult.getPicklistValues();
		atc.camp.Tactic_Owner_Global__c = ple.get(0).getValue();
		
		atc.camp.Promo_Description__c = 'Test Campaign';
		atc.entityName = 'Test';
		atc.localGrassrootsCampName = 'Test';
		
		atc.search();
		
		atc.saveTag();
		atc.cancelActionTag();
		atc.resetCampaign();
		atc.getCloseAction();
		
		atc.setDtStartString(null);
		atc.setDtEndString(null); 
		atc.setDtActionString(null);   	
    }
}