jlamontSC-test/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Strategy_Global__c</fullName>
        <label>National Campaign Strategy</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>National_Campaign_Global__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Reporting_Attribute_Campaign_Strategy</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Local_Campaign_Global__c</fullName>
        <label>National Sub-Campaign</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Campaign_Strategy_Global__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Reporting_Attribute_Local_Campaign</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketing_Tags_Global__c</fullName>
        <label>Marketing Tags</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Marketing_Tags</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>National_Campaign_Global__c</fullName>
        <inlineHelpText>Use for national conservation campaign or program work</inlineHelpText>
        <label>National Campaign</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reporting_Attribute_National_Campaign</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Global__c</fullName>
        <description>Primary state in which local campaign is happening, not necessarily where tactic occurs.</description>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tactic_Owner_Category_Global__c</fullName>
        <label>Tactic Owner Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reporting_Attribute_Tactic_Owner_Catego</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tactic_Owner_Global__c</fullName>
        <label>Tactic Owner</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Tactic_Owner_Category_Global__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Reporting_Attribute_Tactic_Owner</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/CampaignChange__c.object
<CustomObject>
    <description>Object to store Ids of campaigns that have had changes to reporting attributes. Populated by trigger on Campaign and used by batch process to update reporting attributes on Advocacy Actions.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>CampaignChanges</relationshipLabel>
        <relationshipName>CampaignChanges</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>CampaignChange</label>
    <nameField>
        <displayFormat>CC-{0000000000}</displayFormat>
        <label>CampaignChange Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CampaignChanges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/UpdateActionReportingAttr.cls
/*
	UpdateActionReportingAttr
	
	This class runs as a batch process. It is meant to keep reporting attributes on Advocacy Actions
	in synch with the Campaign which is the Related Action.
	
	It looks for CampaignChange records that were inserted by a trigger on the Campaign object, indicating
	that one or more reporting attributes have been changed.
	
	If it finds changes, it updates reporting attributes on any Advocacy Action that has a lookup
	to the changed Campaigns as Related Actions.
	
	Finally, CampaignChange records that have been processed are deleted.
*/

public class UpdateActionReportingAttr implements Database.Batchable<sObject>, Database.Stateful {
	private Map<Id,Campaign> campaignsUpdated;
	private DateTime maxDateChanged;
	
    public Database.QueryLocator start(Database.BatchableContext BC) {
    	AggregateResult[] aggRslt = [
    		select 
    			Campaign__c,
    			max(CreatedDate) maxDate
    		from CampaignChange__c
    		group by Campaign__c
    	];
    	Set<Id> campaignIds = new Set<Id>();
    	for(AggregateResult ar : aggRslt) {
    		campaignIds.add((Id)ar.get('Campaign__c'));
    		DateTime dateChanged = (DateTime)ar.get('maxDate');
    		if(maxDateChanged == null) {
    			maxDateChanged = dateChanged;
    		}
    		else if(dateChanged > maxDateChanged) {
    			maxDateChanged = dateChanged;
    		}
    	}
    	campaignsUpdated = new Map<Id, Campaign>([
            SELECT 
    			Id, 
    			Marketing_Tags_Global__c,
    			Tactic_Owner_Category_Global__c,
    			Tactic_Owner_Global__c,
    			State_Global__c,
    			National_Campaign_Global__c,
    			Campaign_Strategy_Global__c,
    			Local_Campaign_Global__c
    		from Campaign
    		where Id in :campaignIds
    	]);
        return Database.getQueryLocator([
            SELECT 
    			Id,
    			kwac__Related_Action__c 
    		from kweos__EOCS_Data__c
    		where kwac__Related_Action__c in :campaignIds
    	]);
    }
    public void execute(Database.BatchableContext BC, List<kweos__EOCS_Data__c> scope) {
    	List<kweos__EOCS_Data__c> actionsToUpdate = new List<kweos__EOCS_Data__c>();
    	for(kweos__EOCS_Data__c action : scope) {
    		Campaign camp = campaignsUpdated.get(action.kwac__Related_Action__c);
    		if(camp != null) {
    			actionsToUpdate.add(new kweos__EOCS_Data__c(
    				Id = action.Id,
	    			//Marketing_Tags_Global__c = camp.Marketing_Tags_Global__c,
	    			Tactic_Owner_Category_Global__c = camp.Tactic_Owner_Category_Global__c,
	    			Tactic_Owner_Global__c = camp.Tactic_Owner_Global__c,
	    			State_Global__c = camp.State_Global__c,
	    			National_Campaign_Global__c = camp.National_Campaign_Global__c,
	    			Campaign_Strategy_Global__c = camp.Campaign_Strategy_Global__c,
	    			Local_Campaign_Global__c = camp.Local_Campaign_Global__c
	    		));
    		}
    	}
    	if( ! actionsToUpdate.isEmpty() ) {
    		update actionsToUpdate;
    	}
    }
    public void finish(Database.BatchableContext BC) {
    	List<CampaignChange__c> campChangeList = [
    		select Id
    		from CampaignChange__c
    		where CreatedDate <= :maxDateChanged
    	];
    	if( ! campChangeList.isEmpty() ) {
    		delete campChangeList;
    	}
    }  
}