jlamontSC-test/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Custom_Field_1_Label__c</fullName>
        <label>Custom Field 1 Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <inlineHelpText>This is the name that will display on the Event Details page</inlineHelpText>
        <label>Event Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interest_One__c</fullName>
        <label>Interest One</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Interest_Description</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Three__c</fullName>
        <label>Interest Three</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Interest_Description</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Two__c</fullName>
        <label>Interest Two</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Interest_Description</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Promo_Description__c</fullName>
        <inlineHelpText>Internal description</inlineHelpText>
        <label>Internal Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Events</fullName>
        <active>true</active>
        <description>Events</description>
        <label>Events</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Interest_One__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Interest One</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interest_Three__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Interest Three</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interest_Two__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Interest Two</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

jlamontSC-test/src/classes/PhonebankPDFController.cls
public with sharing class PhonebankPDFController {
	private Campaign camp;
	private List<CampaignMember> campMbrList;
	private Id campId;
	private static Id eventId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Events').getRecordTypeId();
	 
	private Id getCampId() {
		if(campId == null) {
			campId = ApexPages.currentPage().getParameters().get('id');
		}
		return campId;
	}	 
	public Campaign getCamp() {
		if(camp == null) {
			Id id = getCampId();
			if(id != null) {
				List<Campaign> campList = [
					select 
						Id,
						RecordTypeId,
						Name,
						Event_Name__c,
						Promo_Description__c,
						Custom_Field_1_Label__c,
						Interest_One__c,
						Interest_Two__c,
						Interest_Three__c						
					from Campaign
					where Id = :id 
				];
				if( ! campList.isEmpty() ) {
					camp = campList.get(0);
				}
			}
		}
		return camp;		
	}
	public Boolean getIsEventCampaign() {
		Campaign camp = getCamp();
		if(camp == null) {
			return false;
		}
		return camp.RecordTypeId == eventId;
	}
    public List<CampaignMember> getCampMbrList() {
    	if(campMbrList == null) {
	    	Id id = getCampId();
	    	if(id != null) {
	    		campMbrList = [
	    			select
	    				FirstName,
	    				LastName,
	    				Phone
	    			from CampaignMember
	    			where CampaignId = :id
	    			order by FirstName, LastName
	    		];
	    	}
    	}
    	return campMbrList;
    }
}