jlamontSC-test/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Club_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Use to select your local or volunteer entity</inlineHelpText>
        <label>Club Entity</label>
        <referenceTo>Club_Entity__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promo_Description__c</fullName>
        <inlineHelpText>Internal description</inlineHelpText>
        <label>Internal Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Club_Entity__c.object
<CustomObject>
    <label>Club Entity/Team</label>
    <nameField>
        <label>Club Entity/Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Entities/Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Team_Participation__c.object
<CustomObject>
    <fields>
        <fullName>Club_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Club Entity/Team</label>
        <referenceTo>Club_Entity__c</referenceTo>
        <relationshipName>Team_Participation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event/Action Support</label>
    <nameField>
        <displayFormat>EAS-{0}</displayFormat>
        <label>Event/Action Support Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event/Action Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/NewTeamParticipationCtlTest.cls
@isTest
public class NewTeamParticipationCtlTest {
    
    private static Id actionTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Offline Action').getRecordTypeId();
    
    static testMethod void myUnitTest() {
        
        Club_Entity__c ent = new Club_Entity__c(
        	Name = 'Test Entity'
        );     
        insert ent;        
        
    	Campaign actioncmp = new Campaign(
    		RecordTypeId = actionTypeId,
    		Name = '1234567890',
    		Promo_Description__c = 'Testing'
		);
    	insert actioncmp;
        
        Team_Participation__c teampart = new Team_Participation__c();
        insert teampart;
        
        PageReference PageRef = Page.NewAction;
		Test.setCurrentPage(PageRef);	
		NewTeamParticipationCtl controller = new NewTeamParticipationCtl(new ApexPages.StandardController(teampart));
        CampaignSearchController csc = controller.getCampSearchController();
        controller.setCampSearchController(csc);
        controller.getThis();
        controller.setSelectedCampaign(actioncmp);
        
    }

}