jlamontSC-test/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Event_Name__c</fullName>
        <inlineHelpText>This is the name that will display on the Event Details page</inlineHelpText>
        <label>Event Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Event will not be published until Status is set to Active</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Development</fullName>
                    <default>true</default>
                    <label>In Development</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>At Capacity</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject_Line__c</fullName>
        <description>Most recent send&apos;s subject line, populated by workflow</description>
        <label>Subject Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

vibhudadhichi-TicketReservation/src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/Contact.object
    <fields>
        <fullName>Status__c</fullName>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>1- Working - Active Opp Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2- Working - Talking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3- Working - Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4- Strategic Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5- Active Project Team Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6- Active Self Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7- Passive &amp; Friendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8- Passive &amp; Unfriendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9-HOLD Not mine/move</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10-Dimagi Staff</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

AkshayVispute-Salesforce/akshay.vispute@eternussolutions.com/src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Email_Sent__c.object
<CustomObject>
    <fields>
        <fullName>Closing_Name__c</fullName>
        <label>Closing Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closing_Phrase__c</fullName>
        <label>Closing Phrase</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emails_Sent__c</fullName>
        <label>Emails Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Events_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Events Campaign</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Campaign.RecordTypeId</field>
                <operation>equals</operation>
                <value>Events</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Emails Sent</relationshipLabel>
        <relationshipName>Emails_Sent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Image_Link__c</fullName>
        <label>Image Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Paragraph_1__c</fullName>
        <label>Paragraph 1</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Paragraph_2__c</fullName>
        <label>Paragraph 2</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Paragraph_3__c</fullName>
        <label>Paragraph 3</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subject_Line__c</fullName>
        <label>Subject Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Email Sent</label>
    <nameField>
        <displayFormat>E-{0}</displayFormat>
        <label>Email Sent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails Sent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Event_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Event Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Event Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>Campaign&apos;s Event Name field, for layout purposes.</description>
        <formula>Campaign__r.Event_Name__c</formula>
        <label>Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Registered</fullName>
                    <default>true</default>
                    <label>Registered</label>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>ER-{0000000}</displayFormat>
        <label>Event Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/SendEventEmailController.cls
public class SendEventEmailController {
    
	//variables to select statuses
    public Set<String> statuses = new Set<String>();
    public boolean registeredBox {get; set;}
    public boolean attendedBox {get; set;}
    public boolean cancelledBox {get; set;}
    public boolean noshowBox {get; set;}
    
    public List<Wrapper> memberList;
    Id eventid = System.currentPageReference().getParameters().get('eventid');
    Id clubEventId = System.currentPageReference().getParameters().get('clubEventId');
    
    //get running user information for email's From section
    Id userId = UserInfo.getUserId();
	User runningUser = [SELECT Id, Name, Email FROM User WHERE Id = :userId];
    
    //get Event Name to set the email source
    Campaign cmp = [SELECT Id, Event_Name__c FROM Campaign WHERE Id = :eventid];
    String source = 'you are registered for ' + cmp.Event_Name__c;
    
    //variables for page input fields
    public String subjLine {get; set;}
    public String image {get; set;}
    public String text1 {get; set;}
    public String text2 {get; set;}
    public String text3 {get; set;}
    public String close {get; set;}
    public String closeName {get; set;}
 
    //retrieve and display event registrants for id passed through url parameter
    public List<Wrapper> getMemberList() {
		if(memberList == null) {
	        List<Event_Registration__c> memList = [
	        	select
	        		Id,
                	First_Name__c,
                	Last_Name__c,
                	Email__c,
	        		Contact__c,
	        		Status__c
	        	from Event_Registration__c
	        	where 
	        		Campaign__c = :eventid
	        		and Email__c != null
                	and Status__c IN :statuses
	        		
	        	order by Status__c, Last_Name__c, First_Name__c
	        ];
	        memberList = new List<Wrapper>();
	        for(Event_Registration__c mem : memList) {
	        	Wrapper wrap = new Wrapper();
	        	wrap.id = mem.Id;
	        	wrap.firstName = mem.First_Name__c;
	        	wrap.lastName = mem.Last_Name__c;
                wrap.email = mem.Email__c;
                if (mem.Contact__c != null) {
                    wrap.contactId = mem.Contact__c;
                }
	        	wrap.status = mem.Status__c;
	        	wrap.isSelected = true;
	        	memberList.add(wrap);
	        }
		}

        if (memberList.size() > 0 && memberList.size() < 1001) {
            return memberList;
        }
        else if (memberList.size() > 1000) {
            addError('You cannot send email to more than 1,000 contacts at a time.');
            return null;
        }
        else {
            addError('No emailable contacts found.');
            return null;
        }        
    }

    private void setStatuses() {
        if (registeredBox == true) {
            statuses.add('Registered');
        }
        if (attendedBox == true) {
            statuses.add('Attended');
        }
        if (cancelledBox == true) {
            statuses.add('Cancelled');
        }
        if (noshowBox == true) {
            statuses.add('No Show');
        }
    }
    
    private void processList() {
		List<Contact> contactList = new List<Contact>();
		for(Wrapper wrap : memberList) {
			if(wrap.isSelected) {
                Contact ct = new Contact(
                    Id = wrap.contactId,
                    FirstName = wrap.firstName,
                    LastName = wrap.lastName,
                    Email = wrap.email
                );              
				contactList.add(ct);
				wrap.isSelected = false;				
			}
	}
		if(!contactList.isEmpty()) {
            SendTriggeredEmail.sendemail(contactList, subjLine, image, text1, text2, text3, close, closeName, runningUser, source, 'event-comm');
            Email_Sent__c es = new Email_Sent__c(
            	Events_Campaign__c = cmp.Id,
                Subject_Line__c = subjLine,
                Image_Link__c = image,
                Paragraph_1__c = text1,
                Paragraph_2__c = text2,
                Paragraph_3__c = text3,
                Closing_Phrase__c = close,
                Closing_Name__c = closeName,
                Emails_Sent__c = contactList.size()
            );
            insert es;
		}

	}
     
    public PageReference next() {
        setStatuses();
        PageReference pageRef= new PageReference('/apex/SendEventEmail');
        pageRef.setRedirect(false); 
        return pageRef;
    }

    public PageReference preview() {
        PageReference pageRef= new PageReference('/apex/EventEmailPreview');
        if(clubEventId != null) {
	        pageRef.getParameters().put('clubEventId', clubEventId);
        }
        pageRef.setRedirect(false); 
        return pageRef;
    }
    
    public PageReference back() {
        PageReference pageRef= new PageReference('/apex/SendEventEmail');
        pageRef.setRedirect(false); 
        return pageRef;
    }
    
	public PageReference sendemail() {
		processList();
		String baseURL = System.URL.getSalesforceBaseUrl().toExternalForm();
		PageReference pageRef = new PageReference(baseURL + '/apex/SendEmailConfirmation' + '?id=' + eventid);
        if(clubEventId != null) {
	        pageRef.getParameters().put('clubEventId', clubEventId);
        }
		return pageRef;
	}

    public PageReference cancel() {
		String baseURL = System.URL.getSalesforceBaseUrl().toExternalForm();
		return new PageReference(baseURL + '/' + eventid);
	}
    
    	public Class Wrapper {
			public Id id {get; set;}
			public String firstName {get; set;}
			public String lastName {get; set;}
			public Id contactId {get; set;}
			public String status {get; set;}
        	public String email {get; set;}
			public Boolean isSelected {get; set;}
	}
    
    	private static void addError(String message) {
        ApexPages.addmessage(
        	new ApexPages.message(
        		ApexPages.severity.ERROR, message)
        	);
	}

}