jlamontSC-test/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Club_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Use to select your local or volunteer entity</inlineHelpText>
        <label>Club Entity</label>
        <referenceTo>Club_Entity__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Club_Entity__c.object
<CustomObject>
    <fields>
        <fullName>Bypass_Validations__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Validations</label>
        <type>Checkbox</type>
    </fields>
    <label>Club Entity/Team</label>
    <nameField>
        <label>Club Entity/Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Entities/Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AkshayVispute-Salesforce/akshay.vispute@eternussolutions.com/src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Leader_Position__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Leader Position</label>
    <nameField>
        <label>Leader Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leader Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Leadership__c.object
<CustomObject>
    <fields>
        <fullName>Club_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Club entities such as chapters and groups.</description>
        <label>Club Entity</label>
        <referenceTo>Club_Entity__c</referenceTo>
        <relationshipName>Leadership</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Leaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Leader_Position__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Position within a club entity or team</description>
        <label>Position</label>
        <referenceTo>Leader_Position__c</referenceTo>
        <relationshipLabel>Leadership/Team Membership</relationshipLabel>
        <relationshipName>Leadership</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position_Status__c</fullName>
        <label>Position Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Prospective</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Leadership/Team Membership</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Leadership/Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leadership/Team Membership</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Club_Entity__c</fullName>
        <description>Deprecated by the User Lookup object.</description>
        <label>Club Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>San Francisco Bay Chapter - 0100</fullName>
                </value>
                <value>
                    <fullName>Loma Prieta Chapter - 0200</fullName>
                </value>
                <value>
                    <fullName>Redwood Chapter - 0300</fullName>
                </value>
                <value>
                    <fullName>Angeles Chapter - 0400</fullName>
                </value>
                <value>
                    <fullName>San Diego Chapter - 0500</fullName>
                </value>
                <value>
                    <fullName>Kern-Kaweah Chapter - 0600</fullName>
                </value>
                <value>
                    <fullName>Illinois Chapter - 0700</fullName>
                </value>
                <value>
                    <fullName>Atlantic Chapter - 0800</fullName>
                </value>
                <value>
                    <fullName>Mother Lode Chapter - 0900</fullName>
                </value>
                <value>
                    <fullName>Los Padres Chapter - 1000</fullName>
                </value>
                <value>
                    <fullName>Washington State Chapter - 1100</fullName>
                </value>
                <value>
                    <fullName>San Gorgonio Chapter - 1200</fullName>
                </value>
                <value>
                    <fullName>Tehipite Chapter - 1300</fullName>
                </value>
                <value>
                    <fullName>Toiyabe Chapter - 1400</fullName>
                </value>
                <value>
                    <fullName>Ventana Chapter - 1500</fullName>
                </value>
                <value>
                    <fullName>John Muir Chapter - 1600</fullName>
                </value>
                <value>
                    <fullName>Rio Grande Chapter - 1700</fullName>
                </value>
                <value>
                    <fullName>Rocky Mountain Chapter - 1800</fullName>
                </value>
                <value>
                    <fullName>Lone Star Chapter - 1900</fullName>
                </value>
                <value>
                    <fullName>Grand Canyon Chapter - 2000</fullName>
                </value>
                <value>
                    <fullName>Michigan Chapter - 2100</fullName>
                </value>
                <value>
                    <fullName>Maryland Chapter - 2200</fullName>
                </value>
                <value>
                    <fullName>Alaska Chapter - 2300</fullName>
                </value>
                <value>
                    <fullName>Hawaii Chapter - 2400</fullName>
                </value>
                <value>
                    <fullName>Santa Lucia Chapter - 2500</fullName>
                </value>
                <value>
                    <fullName>Cumberland Chapter - 2600</fullName>
                </value>
                <value>
                    <fullName>North Star Chapter - 2700</fullName>
                </value>
                <value>
                    <fullName>Ohio Chapter - 2800</fullName>
                </value>
                <value>
                    <fullName>Utah Chapter - 2900</fullName>
                </value>
                <value>
                    <fullName>Massachusetts Chapter - 3000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/AssignAddUpUserTypeTest.cls
@isTest
public class AssignAddUpUserTypeTest {
    
    static testMethod void unitTest() {
        Id entityTypeId = Schema.SObjectType.Club_Entity__c.getRecordTypeInfosByName().get('Club Entity').getRecordTypeId();
        Id hhAcctTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        Id hhContactTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        
        Account a = new Account(Name = 'Test Account', RecordTypeId = hhAcctTypeId);
        insert a;
        
        Contact c = new Contact(FirstName = 'Test', LastName = 'Contact', RecordTypeId = hhContactTypeId, AccountId = a.Id);
        insert c;
        
        Club_Entity__c ent = new Club_Entity__c(Name = 'Test Entity', RecordTypeId = entityTypeId, Bypass_Validations__c = true);
        insert ent;
        
        Leader_Position__c lp = new Leader_Position__c(Name = 'Test Position', Code__c = 'LPOS');
        insert lp;
        
        Leader_Position__c lp2 = new Leader_Position__c(Name = 'Test Position 2', Code__c = 'LPOT');
        insert lp2;        
        
        //insert a leadership - Contact should be set to user type 4
        Leadership__c l1 = new Leadership__c(Contact__c = c.Id, Club_Entity__c = ent.Id, Leader_Position__c = lp.Id, Position_Status__c = 'Active');
        insert l1;
		Contact ct = [SELECT Id, AddUP_User_Type__c FROM Contact WHERE Id = :c.Id];        
        System.assertEquals('4 - Local Entity Campaign Creator', ct.AddUP_User_Type__c);
        
		//insert another leadership - Contact should retain user type 4
        Leadership__c l2 = new Leadership__c(Contact__c = c.Id, Club_Entity__c = ent.Id, Leader_Position__c = lp2.Id, Position_Status__c = 'Active');
        insert l2; 
        ct = [SELECT Id, AddUP_User_Type__c FROM Contact WHERE Id = :c.Id];
        System.assertEquals('4 - Local Entity Campaign Creator', ct.AddUP_User_Type__c);
        
		//delete a leadership - Contact should retain user type 4 since there is a second leadership
        delete l1;
        ct = [SELECT Id, AddUP_User_Type__c FROM Contact WHERE Id = :c.Id];
        System.assertEquals('4 - Local Entity Campaign Creator', ct.AddUP_User_Type__c);
        
        //delete second leadership - Contact should not have a user type since no more leaderships remain
        delete l2;
        ct = [SELECT Id, AddUP_User_Type__c FROM Contact WHERE Id = :c.Id];
        System.assertEquals(null, ct.AddUP_User_Type__c);        
       
    }

}