jlamontSC-test/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Strategy_Global__c</fullName>
        <label>National Campaign Strategy</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>National_Campaign_Global__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Reporting_Attribute_Campaign_Strategy</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Local_Campaign_Global__c</fullName>
        <label>National Sub-Campaign</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Campaign_Strategy_Global__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Reporting_Attribute_Local_Campaign</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>National_Campaign_Global__c</fullName>
        <inlineHelpText>Use for national conservation campaign or program work</inlineHelpText>
        <label>National Campaign</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reporting_Attribute_National_Campaign</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Promo_Description__c</fullName>
        <inlineHelpText>Internal description</inlineHelpText>
        <label>Internal Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Global__c</fullName>
        <description>Primary state in which local campaign is happening, not necessarily where tactic occurs.</description>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tactic_Owner_Category_Global__c</fullName>
        <label>Tactic Owner Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reporting_Attribute_Tactic_Owner_Catego</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tactic_Owner_Global__c</fullName>
        <label>Tactic Owner</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Tactic_Owner_Category_Global__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Reporting_Attribute_Tactic_Owner</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/CampaignSearchControllerTest.cls
@isTest
private class CampaignSearchControllerTest {

    static testMethod void myUnitTest() {
        Date dtStart = System.today();
        Date dtEnd = dtStart.addDays(30);
        
        Campaign testCamp = new Campaign(
            Name = 'Test Campaign',
            National_Campaign_Global__c = 'Beyond Coal',
            Tactic_Owner_Category_Global__c = 'Digital Dept',
            Tactic_Owner_Global__c = 'AddUp',
            Campaign_Strategy_Global__c = 'Clean Energy',
            Local_Campaign_Global__c = 'My Generation',
            State_Global__c = 'CA',
            Promo_Description__c = 'Test Campaign',
            StartDate = dtStart.addDays(10)
        );
        insert testCamp;
        
        CampaignSearchController controller = new CampaignSearchController();
        controller.setDtStartString(formatDate(dtStart));
        controller.setDtEndString(formatDate(dtEnd));
        controller.getDtStartString();
        controller.getDtEndString();
        Campaign camp = controller.getCampaign();
        camp.National_Campaign_Global__c = 'Beyond Coal';
        camp.Tactic_Owner_Category_Global__c = 'Digital Dept';
        camp.Tactic_Owner_Global__c = 'AddUp';
        camp.Campaign_Strategy_Global__c = 'Clean Energy';
        camp.Local_Campaign_Global__c = 'My Generation';
        camp.State_Global__c = 'CA';
        camp.Promo_Description__c = 'Test Campaign';
        controller.campaignName = 'Test Campaign';
        
        controller.search();
        
        List<Campaign> campList = controller.campList;
        System.assertEquals(1, campList.size());
        System.assertEquals(testCamp.Id, campList.get(0).Id);
        
        controller.setCampaign(testCamp);
        controller.cancel();
        
        TestDataUtility testData = new TestDataUtility();
        Id organizationRecordTypeId = testData.getAccountRecordTypeId('Organization');
        Account testOrganizationAccount = testData.createNewAccount(false,'Test Account2','Organization');
        ApexPages.StandardController sc = new ApexPages.StandardController(testOrganizationAccount);
        
        CampaignSetter setter = new NewAccountExtensionCampSearch(sc);
        controller.pageController = setter;
        controller.selectedCampaignId = testCamp.Id;
        System.assertEquals(testCamp.Id, controller.selectedCampaignId);
        controller.setSelectedCampaign();
    }
    private static String formatDate(Date input) {
        if(input == null) {
            return '';
        }
        DateTime dt = DateTime.newInstance(input.year(), input.month(), input.day());
        return dt.format('MM/dd/yyyy');
    }
}