jlamontSC-test/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <inlineHelpText>Times must be in format h:mm AM/PM</inlineHelpText>
        <label>End Time</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecurringEvent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>RecurringEvent</label>
        <referenceTo>RecurringEvent__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recurring_Dates__c</fullName>
        <label>Recurring Dates</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sponsor_Description__c</fullName>
        <inlineHelpText>If you do not enter a value, this field will auto populate when you select a Club Entity and Save</inlineHelpText>
        <label>Sponsor Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <inlineHelpText>Times must be in format h:mm AM/PM</inlineHelpText>
        <label>Start Time</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Events</fullName>
        <active>true</active>
        <description>Events</description>
        <label>Events</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Event_Leader__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Event Leaders</relationshipLabel>
        <relationshipName>Event_Leaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Is_Primary_Leader__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary Leader?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Leader_Name__c</fullName>
        <label>Leader Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_or_Other_Contact_Information__c</fullName>
        <inlineHelpText>Add a phone number and/or email address that will be publicly displayed on the Event Details page</inlineHelpText>
        <label>Phone or Other Contact Information</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecurringEventLeader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RecurringEventLeader</label>
        <referenceTo>RecurringEventLeader__c</referenceTo>
        <relationshipLabel>Event Leaders</relationshipLabel>
        <relationshipName>Event_Leaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Leader</label>
    <nameField>
        <displayFormat>EL-{0000000}</displayFormat>
        <label>Event Leader Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Leaders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/RecurringEvent__c.object
<CustomObject>
    <label>RecurringEvent</label>
    <nameField>
        <displayFormat>RE-{0000000000}</displayFormat>
        <label>RecurringEvent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RecurringEvents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/RecurringEventLeader__c.object
<CustomObject>
    <label>RecurringEventLeader</label>
    <nameField>
        <displayFormat>REL-{0000000000}</displayFormat>
        <label>RecurringEventLeader Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RecurringEventLeaders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/CreateRecurringEventsTest.cls
@isTest
private class CreateRecurringEventsTest {
    private static Id eventsTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Events').getRecordTypeId();

    static testMethod void myUnitTest() {
    	Date startDate = Date.newInstance(2080, 6, 10);
    	Campaign camp1 = new Campaign(
    		RecordTypeId = eventsTypeId,
    		Start_Date__c = startDate,
    		Start_Time__c = '8:00 AM',
    		End_Date__c = startDate,
    		End_Time__c = '5:00 PM',
    		Sponsor_Description__c = 'Test Sponsor',
            Name = 'Test Events Campaign',
            Recurring_Dates__c= '["2080-06-10T07:00:00.000Z","2080-07-08T07:00:00.000Z"]'
    	);
    	RecurringEvent__c recurringEvent = new RecurringEvent__c();
    	insert recurringEvent;
    	camp1.RecurringEvent__c = recurringEvent.Id;
	    ClubEventTriggerHandler.testing = true;
	   	insert camp1;

		RecurringEventLeader__c recurringLdr = new RecurringEventLeader__c();
		insert recurringLdr;
		
		Event_Leader__c ldr1 = new Event_Leader__c(
			Campaign__c = camp1.Id,
			Leader_Name__c = 'Test Leader',
            Phone_or_Other_Contact_Information__c = '415-977-5661', 
            Email__c = 'tleader@gmail.com',
            Is_Primary_Leader__c = true,
            RecurringEventLeader__c = recurringLdr.Id
		);
	    insert ldr1;
	    
	    CreateRecurringEvents creator = new CreateRecurringEvents(camp1.Id);
	    creator.execute(null);
	    
	    Set<Date> dates = new Set<Date>();
	    Date dt1 = Date.newInstance(2080, 6, 10);
	    Date dt2 = Date.newInstance(2080, 7, 8);
		dates.add(dt1);
		dates.add(dt2);	    
	    List<Campaign> campList = [
	    	select Id, Start_Date__c from Campaign 
	    	where Start_Date__c in :dates and RecurringEvent__c = :recurringEvent.Id
	    ];
	    System.assertEquals(2, campList.size());
	    
	    Set<Id> idSet = new Set<Id>();
	    for(Campaign camp : campList) {
	    	idSet.add(camp.Id);
	    }
	    List<Event_Leader__c> ldrs = [
	    	select Id from Event_Leader__c where Campaign__c in :idSet
	    ];
	    System.assertEquals(2, ldrs.size());
    }
}