jlamontSC-test/src/objects/Club_Entity__c.object
<CustomObject>
    <fields>
        <fullName>EntityId__c</fullName>
        <externalId>true</externalId>
        <label>EntityId</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Reorganizing</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Club Entity/Team</label>
    <nameField>
        <label>Club Entity/Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Entities/Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Club_Event__c.object
<CustomObject>
    <fields>
        <fullName>Club_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Club Entity</label>
        <referenceTo>Club_Entity__c</referenceTo>
        <relationshipLabel>Club Events</relationshipLabel>
        <relationshipName>Club_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Begin__c</fullName>
        <label>Date Begin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Category__c</fullName>
        <label>Event Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Activist Event</fullName>
                </value>
                <value>
                    <fullName>Club Support Event</fullName>
                </value>
                <value>
                    <fullName>Outing</fullName>
                </value>
                <value>
                    <fullName>Social Event</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Title__c</fullName>
        <label>Event Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Changes Required</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>At Capacity</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Club Event</label>
    <nameField>
        <displayFormat>CE-{0000000}</displayFormat>
        <label>Club Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AkshayVispute-Salesforce/akshay.vispute@eternussolutions.com/src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Other_Entity_Event__c.object
<CustomObject>
    <fields>
        <fullName>Club_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Club Entity</label>
        <referenceTo>Club_Entity__c</referenceTo>
        <relationshipLabel>Other Entity Events</relationshipLabel>
        <relationshipName>Other_Entity_Events</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Club_Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Club Event</label>
        <referenceTo>Club_Event__c</referenceTo>
        <relationshipLabel>Other Entity Events</relationshipLabel>
        <relationshipName>Other_Entity_Events</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EntityId__c</fullName>
        <formula>Club_Entity__r.EntityId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EntityId</label>
        <type>Text</type>
    </fields>
    <label>Other Entity Event</label>
    <nameField>
        <displayFormat>OEA-{00000000}</displayFormat>
        <label>Other Entity Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Entity Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Club_Entity__c</fullName>
        <description>Deprecated by the User Lookup object.</description>
        <label>Club Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>San Francisco Bay Chapter - 0100</fullName>
                </value>
                <value>
                    <fullName>Loma Prieta Chapter - 0200</fullName>
                </value>
                <value>
                    <fullName>Redwood Chapter - 0300</fullName>
                </value>
                <value>
                    <fullName>Angeles Chapter - 0400</fullName>
                </value>
                <value>
                    <fullName>San Diego Chapter - 0500</fullName>
                </value>
                <value>
                    <fullName>Kern-Kaweah Chapter - 0600</fullName>
                </value>
                <value>
                    <fullName>Illinois Chapter - 0700</fullName>
                </value>
                <value>
                    <fullName>Atlantic Chapter - 0800</fullName>
                </value>
                <value>
                    <fullName>Mother Lode Chapter - 0900</fullName>
                </value>
                <value>
                    <fullName>Los Padres Chapter - 1000</fullName>
                </value>
                <value>
                    <fullName>Washington State Chapter - 1100</fullName>
                </value>
                <value>
                    <fullName>San Gorgonio Chapter - 1200</fullName>
                </value>
                <value>
                    <fullName>Tehipite Chapter - 1300</fullName>
                </value>
                <value>
                    <fullName>Toiyabe Chapter - 1400</fullName>
                </value>
                <value>
                    <fullName>Ventana Chapter - 1500</fullName>
                </value>
                <value>
                    <fullName>John Muir Chapter - 1600</fullName>
                </value>
                <value>
                    <fullName>Rio Grande Chapter - 1700</fullName>
                </value>
                <value>
                    <fullName>Rocky Mountain Chapter - 1800</fullName>
                </value>
                <value>
                    <fullName>Lone Star Chapter - 1900</fullName>
                </value>
                <value>
                    <fullName>Grand Canyon Chapter - 2000</fullName>
                </value>
                <value>
                    <fullName>Michigan Chapter - 2100</fullName>
                </value>
                <value>
                    <fullName>Maryland Chapter - 2200</fullName>
                </value>
                <value>
                    <fullName>Alaska Chapter - 2300</fullName>
                </value>
                <value>
                    <fullName>Hawaii Chapter - 2400</fullName>
                </value>
                <value>
                    <fullName>Santa Lucia Chapter - 2500</fullName>
                </value>
                <value>
                    <fullName>Cumberland Chapter - 2600</fullName>
                </value>
                <value>
                    <fullName>North Star Chapter - 2700</fullName>
                </value>
                <value>
                    <fullName>Ohio Chapter - 2800</fullName>
                </value>
                <value>
                    <fullName>Utah Chapter - 2900</fullName>
                </value>
                <value>
                    <fullName>Massachusetts Chapter - 3000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/User_Lookups__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Lookups</relationshipLabel>
        <relationshipName>User_Lookups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Lookups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Lookups</label>
    <nameField>
        <displayFormat>UL-{0000000}</displayFormat>
        <label>User Lookups Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Lookups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/OtherEntEventsController.cls
public with sharing class OtherEntEventsController {
	public Id clubEntityId;
	public String sponsoringEntityId {get; set;}
	public String earliestDateString {get; set;}
	public String latestDateString {get; set;}
    private Map<Id, EntityPermissions.EntityPermission> entityPermissionsMap;
    private List<SelectOption> entityOptions;
    private List<Other_Entity_Event__c> otherEntityEvents;
    public List<EventWrapper> searchResults {get; set;} {searchResults = new List<EventWrapper>();}
    public Boolean noSearchResults {get; set;} {noSearchResults = false;}
    private Set<Id> otherEntityEventIds = new Set<Id>();

	public PageReference searchEvents() {
		Boolean hasErrors = false;
	    Club_Entity__c sponsoringEntity;
		if(String.isEmpty(sponsoringEntityId)) {
	        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Sponsoring Entity Id is Required'));
	        hasErrors = true;
		}
		else {
			List<Club_Entity__c> entList = [
				select Id from Club_Entity__c where EntityId__c = :sponsoringEntityId
			];
			if(entList.isEmpty()) {
		        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Sponsoring Entity Not Found'));
		        hasErrors = true;
			}
			else {
				sponsoringEntity = entList.get(0);
			}
		}
		Date earliestDate, latestDate;
		if(String.isEmpty(earliestDateString)) {
	        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Earliest Date is Required'));
	        hasErrors = true;
		}
		else {
			try {
				earliestDate = DateTime.parse(earliestDateString + ' 12:00 AM').date();
			}
			catch (Exception e) {
				System.debug('Exception: ' + e.getMessage());
		        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Earliest Date is Not a Valid Date'));
		        hasErrors = true;
			}
		}
		if(String.isEmpty(latestDateString)) {
	        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Latest Date is Required'));
	        hasErrors = true;
		}
		else {
			try {
				latestDate = DateTime.parse(latestDateString + ' 12:00 AM').date();
			}
			catch (Exception e) {
		        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Latest Date is Not a Valid Date'));
		        hasErrors = true;
			}
		}
		System.debug('hasErrors: ' + hasErrors);
		if(hasErrors) {
			return null;
		}
		List<Club_Event__c> eventList = [
			select
				Id,
				Date_Begin__c,
				Event_Title__c,
				Event_Category__c,
				Event_Type__c
			from Club_Event__c
			where
				Club_Entity__c = :sponsoringEntity.Id
				and Status__c = 'Active'
				and Date_Begin__c >= :earliestDate
				and Date_Begin__c <= :latestDate
		];
		searchResults.clear();
		for(Club_Event__c ev : eventList) {
			searchResults.add(new EventWrapper(ev));
		}
		noSearchResults = searchResults.isEmpty();
		return null;
	}
	public PageReference cancelSearch() {
		searchResults = new List<EventWrapper>();
		sponsoringEntityId = '';
		earliestDateString = '';
		latestDateString = '';
		noSearchResults = false;
		return null;
	}
	public PageReference entityChanged() {
		otherEntityEvents = null;
		return null;
	}
	public PageReference addSelected() {
		List<Other_Entity_Event__c> selectedEvents = new List<Other_Entity_Event__c>();
		for(EventWrapper wrap : searchResults) {
			if(wrap.isChecked) {
				if(! otherEntityEventIds.contains(wrap.Event.Id)) {
					Other_Entity_Event__c oee = new Other_Entity_Event__c(
						Club_Entity__c = clubEntityId,
						Club_Event__c = wrap.Event.Id
					);
					selectedEvents.add(oee);
				}
			}
		}
		if( ! selectedEvents.isEmpty() ) {
			insert selectedEvents;
			otherEntityEvents = null;	
		}
		return null;
	}
	public List<Other_Entity_Event__c> getOtherEntityEvents() {
		if(otherEntityEvents == null) {
			otherEntityEvents = [
				select 
					Id, 
					Club_Event__r.Event_Title__c, 
					Club_Event__r.Club_Entity__r.EntityId__c, 
					Club_Event__r.Club_Entity__r.Name, 
					Club_Event__r.Date_Begin__c 
				from Other_Entity_Event__c 
				where Club_Entity__c = :getClubEntityId()
				order by Club_Event__r.Date_Begin__c
			];
		}
		otherEntityEventIds.clear();
		for(Other_Entity_Event__c oee : otherEntityEvents) {
			otherEntityEventIds.add(oee.Club_Event__c);
		}
		return otherEntityEvents;
	}
	
    public List<SelectOption> getEntities() {
        if(entityOptions == null) {
            entityOptions = new List<SelectOption>();
            for(EntityPermissions.EntityPermission perm : getEntityPermissions().values()) {
                entityOptions.add(new SelectOption(perm.clubEntityId, perm.name));
            }
            entityOptions = QuickSort.sortOptionList(entityOptions);
            if(clubEntityId == null) {
            	clubEntityId = entityOptions.get(0).getValue();
            }
        }
        return entityOptions;
    }
    public Id getClubEntityId() {
    	if(clubEntityId == null) {
    		clubEntityId = getEntities().get(0).getValue();
    	}
    	return clubEntityId;
    }
    public void setClubEntityId (Id entityId) {
    	this.clubEntityId = entityId;
    }
    public PageReference deleteEvent() {
        Id id = System.currentPageReference().getParameters().get('id');
        Other_Entity_Event__c eventToDelete = new Other_Entity_Event__c(Id = id);
        delete eventToDelete;
        otherEntityEvents = null;
        return null;
    }
    public PageReference adminPage() {
    	return Page.ClubEventAdministration;
    }
    
    private Map<Id, EntityPermissions.EntityPermission> getEntityPermissions() {
        if(EntityPermissionsMap == null) {
            Id userId = UserInfo.getUserId();
            Id contactId;
            if(UserInfo.getUserType() == 'Standard') {
            	contactId = [select Contact__c from User_Lookups__c where User__c = :userId].Contact__c;
            }
            else {
	            contactId = [select ContactId from User where Id=:userId].ContactId;
            }
            List<EntityPermissions.EntityPermission> permList = EntityPermissions.getPermissions(contactId);
            entityPermissionsMap = new Map<Id, EntityPermissions.EntityPermission>();
            for(EntityPermissions.EntityPermission perm : permList) {
                entityPermissionsMap.put(perm.clubEntityId, perm);
            }
        }
        return entityPermissionsMap;
    }
    public Class EventWrapper {
    	public Boolean isChecked {get; set;}
    	public Club_Event__c event {get; set;}
    	public EventWrapper(Club_Event__c event) {
    		this.event = event;
    		this.isChecked = false;
    	}
    }
}