jlamontSC-test/src/objects/Club_Entity__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Reorganizing</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Club Entity/Team</label>
    <nameField>
        <label>Club Entity/Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Entities/Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Club_Event__c.object
<CustomObject>
    <fields>
        <fullName>Can_Take_Attendance__c</fullName>
        <formula>IF(ISNULL(Date_End__c), Date_Begin__c &lt;= TODAY() &amp;&amp; Date_Begin__c &gt;= TODAY()-7, Date_Begin__c &lt;= TODAY() &amp;&amp; Date_End__c &gt;= TODAY()-7)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Can Take Attendance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Club_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Club Entity</label>
        <referenceTo>Club_Entity__c</referenceTo>
        <relationshipLabel>Club Events</relationshipLabel>
        <relationshipName>Club_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Begin__c</fullName>
        <label>Date Begin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Title__c</fullName>
        <label>Event Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Changes Required</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>At Capacity</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Club Event</label>
    <nameField>
        <displayFormat>CE-{0000000}</displayFormat>
        <label>Club Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Event_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Club_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Club Event</label>
        <referenceTo>Club_Event__c</referenceTo>
        <relationshipLabel>Event Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Registered</fullName>
                    <default>true</default>
                    <label>Registered</label>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>ER-{0000000}</displayFormat>
        <label>Event Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/EventParticipantListController.cls
public with sharing class EventParticipantListController {
	private Club_Event__c event;
	private List<Event_Registration__c> participantList;
	
	public Club_Event__c getEvent() {
		if(event == null) {
			Id id = ApexPages.currentPage().getParameters().get('id');
			List<Club_Event__c> eventList = [
				select 
					Id,
					Date_Begin__c,
					Event_Title__c,
					Club_Entity__r.Name,
					Can_Take_Attendance__c
				from Club_Event__c
				where Id = :id
			];
			if( ! eventList.isEmpty()) {
				event = eventList.get(0);
			}
		}
		return event;
	}
	public List<Event_Registration__c> getParticipantList() {
		if(participantList == null) {
			Club_Event__c clubEvent = getEvent();
			Id eventId = clubEvent.Id;
			participantList = [
				select
					Id,
					First_Name__c,
					Last_Name__c,
					Phone__c,
					Email__c,
					CreatedDate
				from Event_Registration__c
				where Club_Event__c = :eventId
				and Status__c != 'Cancelled'
				order by Last_Name__c, First_Name__c 
			];
		}
		return participantList;		
	}
	public String getPageBase() {
		return CampfireUtils.getPageBase();
	}
	public PageReference takeAttendance() {
		PageReference pageRef = Page.EventAttendance;
		pageRef.getParameters().put('id',getEvent().Id);
		pageRef.setRedirect(true);
		return pageRef;
	}
}