jlamontSC-test/src/objects/Club_Event__c.object
<CustomObject>
    <fields>
        <fullName>Date_Begin__c</fullName>
        <label>Date Begin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Display_Method__c</fullName>
        <label>Display Method</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Category__c</fullName>
        <label>Event Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Activist Event</fullName>
                </value>
                <value>
                    <fullName>Club Support Event</fullName>
                </value>
                <value>
                    <fullName>Outing</fullName>
                </value>
                <value>
                    <fullName>Social Event</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Title__c</fullName>
        <label>Event Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_URL__c</fullName>
        <label>External URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Sponsor_Description__c</fullName>
        <label>Sponsor Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Changes Required</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>At Capacity</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Begin__c</fullName>
        <label>Time Begin</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waiver_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Waiver Required?</label>
        <type>Checkbox</type>
    </fields>
    <label>Club Event</label>
    <nameField>
        <displayFormat>CE-{0000000}</displayFormat>
        <label>Club Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Event_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Club_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Club Event</label>
        <referenceTo>Club_Event__c</referenceTo>
        <relationshipLabel>Event Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Event_Category__c</fullName>
        <description>The Campaign&apos;s Event Category, for layout purposes.</description>
        <formula>TEXT(Campaign__r.Events_Category__c)</formula>
        <label>Event Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image_Authorization_Declined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Image Authorization Declined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Registered</fullName>
                    <default>true</default>
                    <label>Registered</label>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Waiver_Id__c</fullName>
        <label>Waiver Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waiver_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Waiver Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Waiver_is_Digital__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Waiver is Digital</label>
        <type>Checkbox</type>
    </fields>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>ER-{0000000}</displayFormat>
        <label>Event Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/SiteURL__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>BaseURL__c</fullName>
        <label>Base URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Testing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Testing</label>
        <type>Checkbox</type>
    </fields>
    <label>Site URL</label>
</CustomObject>

jlamontSC-test/src/objects/TriggeredSendEmail__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>RequestBody__c</fullName>
        <label>RequestBody</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>TriggeredSendEmail</label>
    <nameField>
        <displayFormat>TSE-{00000000}</displayFormat>
        <label>TriggeredSendEmail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TriggeredSendEmails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/EventAttendanceControllerTest.cls
@isTest
private class EventAttendanceControllerTest {

    static testMethod void myUnitTest() {
		Club_Event__c event1 = new Club_Event__c(
			Event_Title__c = 'Test Event 1',
			Time_Begin__c = '8:00 AM',
			Date_Begin__c = System.today() + 1,
			Status__c = 'In Development',
			Event_Category__c = 'Outing',
			Sponsor_Description__c = 'Test',
			External_URL__c = 'http://test.com',
			Display_Method__c = 'External URL',
			Waiver_Required__c = true
		);
		EventHelper.sourceObject = 'ClubEvent';
		insert event1;

        Event_Registration__c reg1 = new Event_Registration__c(
        	Club_Event__c = event1.Id,
			First_Name__c = 'Test FirstName',
			Last_Name__c = 'Test LastName',
			Email__c = 'test@gmail.com',
			Status__c = 'Registered',
			Waiver_is_Digital__c = true,
			Waiver_Submitted__c = true,
			Image_Authorization_Declined__c = false
        );
        insert reg1;
		
		SiteURL__c siteUrl = new SiteURL__c(
			Name = 'BaseSite',
			BaseURL__c = 'http://force.com/events/details',
			Testing__c = true
		);
		insert siteUrl;

		EventAttendanceController.ClubEvent evnt = EventAttendanceController.getEvent(event1.Id);
		evnt.signupList.clear();

		EventAttendanceController.Signup su0 = new EventAttendanceController.Signup();
		su0.registrationId = reg1.id;
		su0.email = 'test@gmail.com';
		su0.firstName = 'Test FirstName';
		su0.lastName = 'Test LastName';
		su0.status = 'Registered';
		su0.waiverIsDigital = true;
		su0.waiverSubmitted = true;
		su0.zip = '12345';
		su0.imageAuthorizationDeclined = false;
		su0.isMinor = false;
		evnt.signupList.add(su0);
		
		EventAttendanceController.Signup su1 = new EventAttendanceController.Signup();
		su1.email = 'test@abc.com';
		su1.firstName = 'Test';
		su1.lastName = 'Person1';
		su1.status = 'Attended';
		su1.waiverIsDigital = true;
		su1.waiverSubmitted = true;
		su1.zip = '12345';
		su1.imageAuthorizationDeclined = false;
		su1.isMinor = false;
		evnt.signupList.add(su1);

		EventAttendanceController.Signup su2 = new EventAttendanceController.Signup();
		su2.email = 'test2@xyz.com';
		su2.firstName = 'Test2';
		su2.lastName = 'Person2';
		su2.status = 'Attended';
		su2.waiverIsDigital = true;
		su2.waiverSubmitted = true;
		su2.zip = '54321';
		su2.imageAuthorizationDeclined = false;
		su2.isMinor = true;
		evnt.signupList.add(su2);

		Test.startTest();
		evnt = EventAttendanceController.saveEvent(evnt);
		Test.stopTest();
		
		System.assertEquals(3, evnt.signupList.size());
		
		List<rC_Connect__Batch_Upload__c> buList = [
			select Id from rC_Connect__Batch_Upload__c
			where rC_Connect__Contact_1_Email__c = :su1.email
		];
		System.assertEquals(1, buList.size());
		
		Event_Registration__c reg = [
			select Id, Waiver_Id__c from Event_Registration__c
			where Email__c = :su1.email
		];
		
		String docName = 'Event Waiver for ' + su1.firstName + ' ' + su1.lastName;
		List<Document> docList = [
			select Id, Name from Document
			where 
				Name = :docName
				and Id = :reg.Waiver_Id__c
		];
		System.assertEquals(1, docList.size());
		
		List<TriggeredSendEmail__c> tseList = [
			select 
				Email__c,
				RequestBody__c
			from TriggeredSendEmail__c
		];
		
		System.assertEquals(1, tseList.size());
		
		String pageBase = new EventAttendanceController().getPageBase();
		String salesforceBase = new EventAttendanceController().getSalesforceBase();
    }
}