jlamontSC-test/src/objects/Club_Entity__c.object
<CustomObject>
    <fields>
        <fullName>EntityId__c</fullName>
        <externalId>true</externalId>
        <label>EntityId</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Parent_Chapter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Chapter</description>
        <label>Parent Club Entity/Team</label>
        <referenceTo>Club_Entity__c</referenceTo>
        <relationshipLabel>Club Entities/Teams</relationshipLabel>
        <relationshipName>Club_Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Reorganizing</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Board Advisory Committees</fullName>
                </value>
                <value>
                    <fullName>Activity Sections</fullName>
                </value>
                <value>
                    <fullName>Grassroot Network Teams</fullName>
                </value>
                <value>
                    <fullName>Board of Directors</fullName>
                </value>
                <value>
                    <fullName>Board Standing Committees</fullName>
                </value>
                <value>
                    <fullName>Board Task Forces</fullName>
                </value>
                <value>
                    <fullName>Campaign &amp; Program Teams</fullName>
                </value>
                <value>
                    <fullName>Canadian Chapter</fullName>
                </value>
                <value>
                    <fullName>Canadian Group</fullName>
                </value>
                <value>
                    <fullName>Committees of the Board</fullName>
                </value>
                <value>
                    <fullName>Campaign Committees</fullName>
                </value>
                <value>
                    <fullName>Chapter</fullName>
                </value>
                <value>
                    <fullName>Cons Initiative Committee</fullName>
                </value>
                <value>
                    <fullName>Sierra Club</fullName>
                </value>
                <value>
                    <fullName>Council of Club Leaders</fullName>
                </value>
                <value>
                    <fullName>Conservation Priority Task Forces</fullName>
                </value>
                <value>
                    <fullName>Campaign Steering Comm</fullName>
                </value>
                <value>
                    <fullName>Digital Innovations Project</fullName>
                </value>
                <value>
                    <fullName>Ecoregion</fullName>
                </value>
                <value>
                    <fullName>Field Office</fullName>
                </value>
                <value>
                    <fullName>TSCF Sierra Club Fdn</fullName>
                </value>
                <value>
                    <fullName>TSCF Committee</fullName>
                </value>
                <value>
                    <fullName>TSCF Board of Directors</fullName>
                </value>
                <value>
                    <fullName>Finance &amp; Risk Management Subcommittees</fullName>
                </value>
                <value>
                    <fullName>Governance Committee</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Inner City Outings Group</fullName>
                </value>
                <value>
                    <fullName>ICO Regional Steering Cmt</fullName>
                </value>
                <value>
                    <fullName>Coordinating Pairs</fullName>
                </value>
                <value>
                    <fullName>Local Committees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Club Entity/Team</label>
    <nameField>
        <label>Club Entity/Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Entities/Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vibhudadhichi-TicketReservation/src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/Contact.object
    <fields>
        <fullName>Status__c</fullName>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>1- Working - Active Opp Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2- Working - Talking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3- Working - Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4- Strategic Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5- Active Project Team Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6- Active Self Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7- Passive &amp; Friendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8- Passive &amp; Unfriendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9-HOLD Not mine/move</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10-Dimagi Staff</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

CACommunity-Salesforce/src/objects/Contact.object
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>A CA may have more than one person filling the role of Primary Point of Contact (POC), and may use a contractor as one of the POCs.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary POC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

AkshayVispute-Salesforce/akshay.vispute@eternussolutions.com/src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Leader_Position__c.object
<CustomObject>
    <fields>
        <fullName>ClubEventPermission_NonOutings__c</fullName>
        <label>ClubEventPermission-NonOutings</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClubEventPermission_Outings__c</fullName>
        <label>ClubEventPermission-Outings</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Leader Position</label>
    <nameField>
        <label>Leader Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leader Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Leadership__c.object
<CustomObject>
    <fields>
        <fullName>Club_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Club entities such as chapters and groups.</description>
        <label>Club Entity</label>
        <referenceTo>Club_Entity__c</referenceTo>
        <relationshipName>Leadership</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Leaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Leader_Position__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Position within a club entity or team</description>
        <label>Position</label>
        <referenceTo>Leader_Position__c</referenceTo>
        <relationshipLabel>Leadership/Team Membership</relationshipLabel>
        <relationshipName>Leadership</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Position Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Leadership/Team Membership</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Leadership/Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leadership/Team Membership</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/EntityPermissions.cls
/*
EntityPermissions

Created by: Mark Maslow
Created on: January, 2015

Query leadership roles to get list of entities and permissions within each entity.

10/17/2016 Maslow - Fix problem where lower permission in chapter would override higher permission in a child entity.

December, 2016 Maslow - Add code to check for preference indicating contact is staff. Staff get access to entity CLUB.
*/
public without sharing class EntityPermissions {
	//Input - Contact Id
	//Output - List of entities in which contact has leadership roles, with specific permissions for each entity 
	public static List<EntityPermission> getPermissions(Id contactId) {
	    //Retrieve all Leaderhip Roles for Contact
        List<Leadership__c> allRoles = [  
            select Club_Entity__c, Club_Entity__r.EntityId__c, Club_Entity__r.Name, Club_Entity__r.Type__c, 
            	Leader_Position__r.ClubEventPermission_Outings__c, Leader_Position__r.ClubEventPermission_NonOutings__c 
            from Leadership__c
            where Contact__c = :contactId and Position_Active__c = true and Club_Entity__r.Status__c = 'Active'
            order by Club_Entity__c
        ];
        //
        //Code deleted because staff check is done later
        //
        //If no roles, return empty list
        //if(allRoles.size() == 0) {
        //	return new List<EntityPermission>();
        //}
        
        //Create map to correlate a Club Entity with a Leader Role
        //The role in the map will be populated with the highest access found in the entity
        Map<Id, Leadership__c> positionMap = new Map<Id, Leadership__c>();
        for(Leadership__c role : allRoles) {
    		Leadership__c processedRole = positionMap.get(role.Club_Entity__c);
    		if(processedRole == null) {
    			positionMap.put(role.Club_Entity__c, role);
    		}
    		else {
    			if(role.Leader_Position__r.ClubEventPermission_Outings__c == 'Administrator') {
					processedRole.Leader_Position__r.ClubEventPermission_Outings__c = 'Administrator';	    				
    			}
    			else if(role.Leader_Position__r.ClubEventPermission_Outings__c == 'Standard' && 
    					processedRole.Leader_Position__r.ClubEventPermission_Outings__c != 'Administrator') {
							processedRole.Leader_Position__r.ClubEventPermission_Outings__c = 'Standard';	    				
    			}
    			if(role.Leader_Position__r.ClubEventPermission_NonOutings__c == 'Administrator') {
					processedRole.Leader_Position__r.ClubEventPermission_NonOutings__c = 'Administrator';	    				
    			}
    			else if(role.Leader_Position__r.ClubEventPermission_NonOutings__c == 'Standard' &&
    					processedRole.Leader_Position__r.ClubEventPermission_NonOutings__c != 'Administrator') {
							processedRole.Leader_Position__r.ClubEventPermission_NonOutings__c = 'Standard';	    				
    			}
    			positionMap.put(role.Club_Entity__c, processedRole);
    		}
	    }
	    //Administrators in a Chapter also gets access to child entities of the Chapter
	    //Users with standard access to non-outings events also get access to child entities of the Chapter 
	    List<Id> chapters = new List<Id>();
        Map<Id, EntityPermission> permissionMap = new Map<Id, EntityPermission>();
	    for(Leadership__c role : positionMap.values()) {
	    	EntityPermission ep = new EntityPermission(
	    		role.Club_Entity__c,
	    		role.Club_Entity__r.EntityId__c + '-' + role.Club_Entity__r.Name,
	    		role.Club_Entity__r.Type__c,
	    		role.Leader_Position__r.ClubEventPermission_NonOutings__c, 
	    		role.Leader_Position__r.ClubEventPermission_Outings__c 
	    	);
	    	permissionMap.put(role.Club_Entity__c, ep);
	    	if(
	    		//role.Club_Entity__r.Type__c == 'Chapter' && 
		    	  (
		    	  	role.Leader_Position__r.ClubEventPermission_NonOutings__c == 'Administrator' || 
		    	  	role.Leader_Position__r.ClubEventPermission_NonOutings__c == 'Standard' ||
		    	  	role.Leader_Position__r.ClubEventPermission_Outings__c == 'Administrator'
		    	  )
	    	  ) {
	    			chapters.add(role.Club_Entity__c);
	    	}
	    }
    	if(chapters.size() > 0) {
    		List<Club_Entity__c> children = new List<Club_Entity__c>([
    			select Id, EntityId__c, Name, Type__c, Parent_Chapter__c
    			from Club_Entity__c
    			where Parent_Chapter__c in :chapters and Status__c = 'Active' 
    		]);
    		for(Club_Entity__c ent : children) {
    			EntityPermission parentRole = permissionMap.get(ent.Parent_Chapter__c);
                EntityPermission childRole = permissionMap.get(ent.Id);
                if(childRole == null) {
                    EntityPermission childPermission = new EntityPermission(
                        ent.Id,
                        ent.EntityId__c + '-' + ent.Name,
                        ent.Type__c,
                        parentRole.clubEventPermissionNonOutings,
                        parentRole.clubEventPermissionOutings
                    );
                    permissionMap.put(ent.Id, childPermission);
                }
                else {
                    if(parentRole.clubEventPermissionNonOutings == 'Administrator') {
      					childRole.clubEventPermissionNonOutings = 'Administrator';
                    }
                    else if(parentRole.clubEventPermissionNonOutings == 'Standard') {
                        if(childRole.clubEventPermissionNonOutings == 'None') {
                	        childRole.clubEventPermissionNonOutings = 'Standard';
                        }
                    }
                    if(parentRole.clubEventPermissionOutings == 'Administrator') {
      					childRole.clubEventPermissionOutings = 'Administrator';
                    }
                    else if(parentRole.clubEventPermissionOutings == 'Standard') {
                        if(childRole.clubEventPermissionOutings == 'None') {
                	        childRole.clubEventPermissionOutings = 'Standard';
                        }
                    }
                }
    		}
    	}

    	List<Club_Entity__c> clubEntityList = [
			select Id, EntityId__c, Name, Type__c
			from Club_Entity__c
			where EntityId__c = 'CLUB'
    	];
    	if( ! clubEntityList.isEmpty()) {
    		Club_Entity__c clubEntity = clubEntityList.get(0);
    		if(permissionMap.get(clubEntity.Id) == null) {
				if(isStaff(contactId)) {
                    EntityPermission ep = new EntityPermission(
                        clubEntity.Id,
                        clubEntity.EntityId__c + '-' + clubEntity.Name,
                        clubEntity.Type__c,
                        'Administrator',
                        'None'
                    );
                    permissionMap.put(clubEntity.Id, ep);
				}    			
    		}
    	}
        return permissionMap.values();
    }
    private static Boolean isStaff(Id contactId) {
    	List<rC_Bios__Preference__c> preferenceList = [
    		select Id
    		from rC_Bios__Preference__c
    		where rC_Bios__Contact__c = :contactId
    		and rC_Bios__Code_Value__c = 'SCFDNSTAFF'
       		and rC_Bios__Active__c = true
    	];
    	return ! preferenceList.isEmpty();
    }
    public class EntityPermission {
    	public Id clubEntityId { get; set; }
    	public String name { get; set; }
    	public String entityType {get; set;}
    	public String clubEventPermissionOutings { get; set; }
    	public String clubEventPermissionNonOutings { get; set; }

    	public EntityPermission(Id clubEntityId, String name, String entityType, String clubEventPermissionNonOutings, String clubEventPermissionOutings) {
    		this.clubEntityId = clubEntityId;
    		this.name = name;
    		this.entityType = entityType;
    		this.clubEventPermissionNonOutings = clubEventPermissionNonOutings;
    		this.clubEventPermissionOutings = clubEventPermissionOutings;
    	}
    }
}