jlamontSC-test/src/objects/Team_Participation__c.object
<CustomObject>
    <fields>
        <fullName>Event_Action__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event/Action Campaign</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value must be an Advocacy Form, Events, or Offline Action campaign.</errorMessage>
            <filterItems>
                <field>Campaign.RecordTypeId</field>
                <operation>equals</operation>
                <value>Events, Advocacy Form, Offline Action</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Team_Participation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event/Action Support</label>
    <nameField>
        <displayFormat>EAS-{0}</displayFormat>
        <label>Event/Action Support Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event/Action Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/NewTeamParticipationCtl.cls
public with sharing class NewTeamParticipationCtl implements CampaignSetter {
    
    private final Team_Participation__c teamparticipation;
    
    public NewTeamParticipationCtl(ApexPages.StandardController controller) {
        this.teamparticipation = (Team_Participation__c)controller.getRecord();
    }
    
    private CampaignSearchController campSearchController;
    
    public CampaignSearchController getCampSearchController() {
        return campSearchController;
    }
    public void setCampSearchController(CampaignSearchController controller) {
        campSearchController = controller;
    }
    public CampaignSetter getThis() {
        return this;
    }
    public void setSelectedCampaign(Campaign camp) {
        teamparticipation.Event_Action__c = camp.Id;
    }
}