pulkitchhabra-salesforce/objects/Deal__c.object
<CustomObject>
    <description>Contains all the not converted leads and not closed opportunities.</description>
    <fields>
        <fullName>Deal_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Deal Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pulkitchhabra-salesforce/objects/Lead.object
<CustomObject>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Lead.object
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>

pulkitchhabra-salesforce/classes/CreateDeal.cls
global class CreateDeal implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([Select Id, FirstName, LastName, Salutation, Status from Lead Where IsConverted=False]);
    }
    global void execute(Database.BatchableContext BC, List<Lead> scope){
        List<Deal__c> nDeal=new List<Deal__c>();
        for(Lead l:scope){
            for(Deal__c d:[Select Id, Name, Deal_ID__C from Deal__c]){
                if(d.Deal_Id__c==l.Id){  
                d.RecordTypeId='012280000000xiT';
                d.Deal_Id__c= l.Id;
                if(l.Salutation!=Null){
                    d.Name=l.Salutation+' '+l.FirstName+' '+l.LastName; 
                }
                else{
                    d.Name= l.FirstName+' '+l.LastName;
                }
                d.Lead__c=l.Id;
                d.Status__c=l.Status;
                d.Type__c='Lead';
                nDeal.add(d);
                }    
           }     
        }
        update nDeal;
    }
    global void finish(Database.BatchableContext BC){
        
    }

}