rajyeturi16-salesforce/project/objects/List_Of_Names__c.object
<CustomObject>
    <fields>
        <fullName>MultiSelectIdentifier__c</fullName>
        <label>MultiSelectIdentifier</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>List Of Names</label>
    <nameField>
        <label>List Of Names Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Of Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

rajyeturi16-salesforce/project/classes/GBL_MultiSelectLookup_CTRL.cls
global class GBL_MultiSelectLookup_CTRL {

    public GBL_MultiSelectLookup_CTRL()
    {
        
        
    }
    
    @RemoteAction
    global static  List<List_Of_Names__c> getItemsList(String fieldName)
    {
      List<List_Of_Names__c> listItems;
        
     listItems= [Select Id, Name from List_Of_Names__c where  MultiSelectIdentifier__c=:fieldName  ORDER BY Name ASC ];

        return listItems;
        
   }
    
     public GBL_MultiSelectLookup_CTRL (ApexPages.StandardController controller) 
     {

 
    }
   
}