rajyeturi16-salesforce/project/objects/SFDC_Team__c.object
<CustomObject>
    <fields>
        <fullName>PPT__c</fullName>
        <label>Profile</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>SFDC_Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SFDC_Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

rajyeturi16-salesforce/project/classes/Page_Control.cls
public with sharing class Page_Control {
    public list<SFDC_Team__c> st {set;get;}
    public ApexPages.StandardController controller;
       public Page_Control(ApexPages.StandardController controller) {
    SFDC_Team__c d = (SFDC_Team__c) controller.getRecord();
    d.PPT__c = UserInfo.getUserId();
    this.controller = controller;
    }
    public PageReference save()
    {
     
 PageReference pgref = new PageReference('/apex/form');
      controller.save();
      pgref.setRedirect(true);
      return pgref;
      
    }

}