CACommunity-Salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auditor_Qualifications__c</fullName>
        <description>URL to website attesting to the qualifications of this Auditor to issue the Standard Audit Statement</description>
        <inlineHelpText>URL to website attesting to the qualifications of this Auditor to issue the Standard Audit Statement</inlineHelpText>
        <label>Auditor Qualifications</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Auditor_Website__c</fullName>
        <description>URL to information about this Auditor</description>
        <inlineHelpText>URL to information about this Auditor</inlineHelpText>
        <label>Auditor Website</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Auditor__c</fullName>
        <description>Name of Auditor who issued the Standard Audit Statement</description>
        <inlineHelpText>Name of Auditor who issued the Standard Audit Statement</inlineHelpText>
        <label>Auditor</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Audits_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if audit of parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if audit of parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>Audits Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Statement_Date__c</fullName>
        <description>Date BR Audit Statement Issued</description>
        <inlineHelpText>Date BR Audit Statement Issued</inlineHelpText>
        <label>BR Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Type__c</fullName>
        <label>BR Audit Type</label>
        <picklist>
            <picklistValues>
                <fullName>ETSI TS 102 042</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WebTrust</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BR_Audit__c</fullName>
        <description>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement</description>
        <inlineHelpText>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement</inlineHelpText>
        <label>BR Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CA_Document_Repository__c</fullName>
        <description>URL to where policy documentation specific to this cert may be found</description>
        <inlineHelpText>URL to where policy documentation specific to this cert may be found</inlineHelpText>
        <label>CA Document Repository</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CP_CPS_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if this cert does not have separate policy documentation from the parent cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if this cert does not have separate policy documentation from the parent cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>CP/CPS Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Certificate_Policy_CP__c</fullName>
        <description>URL to Certificate Policy documentation specific to this cert</description>
        <inlineHelpText>URL to Certificate Policy documentation specific to this cert</inlineHelpText>
        <label>Certificate Policy (CP)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certification_Practice_Statement_CPS__c</fullName>
        <description>URL to CPS specific to this cert</description>
        <inlineHelpText>URL to CPS specific to this cert</inlineHelpText>
        <label>Certification Practice Statement (CPS)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Statement_Date__c</fullName>
        <description>Date EV Audit Statement Issued</description>
        <inlineHelpText>Date EV Audit Statement Issued</inlineHelpText>
        <label>EV Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Type__c</fullName>
        <label>EV Audit Type</label>
        <picklist>
            <picklistValues>
                <fullName>ETSI TS 102 042</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WebTrust</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EV_Audit__c</fullName>
        <description>If able to issue EV certs, then URL to EV audit statement</description>
        <inlineHelpText>If able to issue EV certs, then URL to EV audit statement</inlineHelpText>
        <label>EV Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_Policy_OID_s__c</fullName>
        <label>EV Policy OID(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Management_Assertions_By__c</fullName>
        <description>The name (in English) of the organization who made the management assertions for the standard audit. i.e. The name of the organization that validates the data to be included in certificates signed by this issuer.</description>
        <inlineHelpText>The name (in English) of the organization who made the management assertions for the standard audit. i.e. The name of the organization that validates the data to be included in certificates signed by this issuer.</inlineHelpText>
        <label>Management Assertions By</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Policy_Documentation__c</fullName>
        <description>Further documentation or information relevant to this cert</description>
        <inlineHelpText>Further documentation or information relevant to this cert</inlineHelpText>
        <label>Policy Documentation</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Date__c</fullName>
        <description>Date Audit Statement Issued</description>
        <inlineHelpText>Date Audit Statement Issued</inlineHelpText>
        <label>Standard Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Type__c</fullName>
        <label>Standard Audit Type</label>
        <picklist>
            <picklistValues>
                <fullName>ETSI TS 101 456</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ETSI TS 102 042</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Trust</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Standard_Audit__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party</inlineHelpText>
        <label>Standard Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Yet Included</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Included</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provided by CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Trust_Bits__c</fullName>
        <label>Trust Bits</label>
        <picklist>
            <picklistValues>
                <fullName>All Trust Bits Turned Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Websites</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CACommunity-Salesforce/src/objects/Contact.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/Contact.object
    <fields>
        <fullName>Status__c</fullName>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>1- Working - Active Opp Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2- Working - Talking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3- Working - Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4- Strategic Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5- Active Project Team Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6- Active Self Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7- Passive &amp; Friendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8- Passive &amp; Unfriendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9-HOLD Not mine/move</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10-Dimagi Staff</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

CACommunity-Salesforce/src/classes/MassUpdateAuditCPCPSDataController.cls
/**
This is the controller class for the MassUpdateAuditCPPSData VF page.
When the "Mass Update Audit/CP/CPS Data" button is clicked from any Root Certificate 
(Account record where Record Type = Root Certificate) or Intermediate certificate 
(Account record where Record Type = Intermediate Certificate), 
the user is redirected to  MassUpdateAuditCPPSData VF page. 

This controller iterates through all records related to the Parent Account and updates
the Audit, CP/CPS fields upon users response.
**/

global with sharing class MassUpdateAuditCPCPSDataController {

    public Account sourceAccountSo{get; set;}
    public Account targetAccountSo{get; set;}
    List<Account> lstSiblingAccounts;   
    public Integer recordIndex{get; set;}
    public Integer totaltargetAccountCount {get; set;}
    public Boolean showConfirmation{get; set;}
    public Boolean showMessage{get; set;}
    public Boolean hasError{get; set;}
    public Boolean isValidPortalUser{get; set;}
    public String title{get; set;}  
            
    Boolean updateBRAuditFields=FALSE;
    Boolean updateEVAuditFields=FALSE;
    
    static List<String> fields = new List<String>();
    static{
        fields.add('Audits_Same_as_Parent__c');
        fields.add('Standard_Audit__c');
        fields.add('Standard_Audit_Type__c');
        fields.add('Standard_Audit_Statement_Date__c');       
        fields.add('BR_Audit__c');
        fields.add('BR_Audit_Type__c');
        fields.add('BR_Audit_Statement_Date__c');
        fields.add('EV_Audit__c');
        fields.add('EV_Audit_Type__c');
        fields.add('EV_Audit_Statement_Date__c');
        fields.add('Auditor__c');
        fields.add('Auditor_Website__c');
        fields.add('Auditor_Qualifications__c');
        fields.add('Management_Assertions_By__c');
        fields.add('CP_CPS_Same_as_Parent__c');
        fields.add('Policy_Documentation__c');
        fields.add('CA_Document_Repository__c');
        fields.add('Certificate_Policy_CP__c');
        fields.add('Certification_Practice_Statement_CPS__c');
    }
    // constructor method for standard controller
    public MassUpdateAuditCPCPSDataController(ApexPages.StandardController stdController) {
                
         // get the record id on which the button was clicked
         this.sourceAccountSo = (Account)stdController.getRecord();      
         lstSiblingAccounts = new List<Account>();
         this.recordIndex = 0;
         this.showConfirmation = true;
         this.showMessage = false;
         this.hasError = false;
         this.title = 'No more certificates to update';
         this.isValidPortalUser = true;
         
         try{
        
         this.sourceAccountSo = [select Id, Name, ParentId, Parent.Name, Type, EV_Policy_OID_s__c, Trust_bits__c,
                                   Audits_Same_as_Parent__c, Standard_Audit__c, 
                                   Standard_Audit_Type__c, Standard_Audit_Statement_Date__c,
                                   BR_Audit__c, BR_Audit_Type__c, BR_Audit_Statement_Date__c,
                                   EV_Audit__c, EV_Audit_Type__c, EV_Audit_Statement_Date__c,
                                   Auditor__c, Auditor_Website__c, Auditor_Qualifications__c, Management_Assertions_By__c,
                                   CP_CPS_Same_as_Parent__c, Policy_Documentation__c, CA_Document_Repository__c,
                                   Certificate_Policy_CP__c, Certification_Practice_Statement_CPS__c,
                                   Status__c from Account 
                                   where id = :this.sourceAccountSo.id limit 1];        
        
        
        if(this.sourceAccountSo.Status__c == 'Removed'){
            this.title = 'Source Certificate has been removed. You cannot run mass update.';
            this.showMessage = true;
            this.hasError = true;
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'This certificate had been removed. You cannot run mass update.'));
        }
          
          for(Account targertAcc : [select Id, ParentId, Name, Type, EV_Policy_OID_s__c, Trust_bits__c,
                                    Audits_Same_as_Parent__c, Standard_Audit__c, 
                                    Standard_Audit_Type__c, Standard_Audit_Statement_Date__c, BR_Audit__c, 
                                    BR_Audit_Type__c, BR_Audit_Statement_Date__c, EV_Audit__c, EV_Audit_Type__c,
                                    EV_Audit_Statement_Date__c, Auditor__c, Auditor_Website__c, Auditor_Qualifications__c, Management_Assertions_By__c,
                                    CP_CPS_Same_as_Parent__c, Policy_Documentation__c, CA_Document_Repository__c,
                                    Certificate_Policy_CP__c, Certification_Practice_Statement_CPS__c, Status__c
                                    from Account
                                    where ParentId = :sourceAccountSo.ParentId AND Id != :sourceAccountSo.Id]){
              if(isDiffAccount(sourceAccountSo, targertAcc)){
                  continue;
              }
              
              lstSiblingAccounts.add(targertAcc);
          }
                            
         }catch(Exception exp){
             this.hasError = true;
             this.showMessage = true;
             this.title = 'Unexpected Error Occurred, Please contact your administrator.';
             //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Unexpected Error Occurred, Please contact your administrator.'));
         }                     
                              
        if(lstSiblingAccounts != null && lstSiblingAccounts.size() > 0){
            this.totaltargetAccountCount = lstSiblingAccounts.size();
            this.targetAccountSo = lstSiblingAccounts[recordIndex];
            // recordIndex++; commented by Poonam
        }else{
            this.hasError = true;
            this.targetAccountSo = new Account();
            this.showMessage = true;
            this.title = 'No certs to update.';
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ''));
        }  
    }

    
    public void checkPortalUserValidation(){
        
        CreateIntermediateCertController objToCheckUserValidation = new CreateIntermediateCertController(new ApexPages.standardController(this.sourceAccountSo));
        if(!objToCheckUserValidation.isValidPortalUser()){
            this.hasError = true;
            this.isValidPortalUser = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select a Root Cert or Intermediate Cert owned by ' + objToCheckUserValidation.userAccountName));    
        }
        
    }
    
    private Boolean isDiffAccount(sObject source, sObject target){
        for(String fieldApi : fields){
            // System.debug('source: '+source.get(fieldApi)+' --> target: '+target.get(fieldApi));
            if(source.get(fieldApi) != target.get(fieldApi)){
                return false;
            }
        }
        
        return true;
    }
    
    public pagereference redirectToAccount(){
        return new PageReference('/'+this.sourceAccountSo.Id);
    }
    
    
   // update the parent account and redirect to same page showing that the record got updated successfully
   public void syncAccount() {
         
         this.showConfirmation = false;
         
         this.targetAccountSo.Audits_Same_as_Parent__c                = this.sourceAccountSo.Audits_Same_as_Parent__c;
         this.targetAccountSo.Standard_Audit__c                       = this.sourceAccountSo.Standard_Audit__c;
         this.targetAccountSo.Standard_Audit_Type__c                  = this.sourceAccountSo.Standard_Audit_Type__c;   
         this.targetAccountSo.Standard_Audit_Statement_Date__c        = this.sourceAccountSo.Standard_Audit_Statement_Date__c;
         
         // If the (target) root cert has "Trust Bits" field does not have "Websites", then don't copy the BR Audit info    
      
         updateBRAuditFields = (this.targetAccountSo.type == 'Intermediate Certificate' ||
                                (this.targetAccountSo.type == 'Root' && 
                                this.targetAccountSo.trust_bits__c != null &&
                                this.targetAccountSo.trust_bits__c.length()>0 &&
                                this.targetAccountSo.trust_bits__c.contains('Websites'))) ? true : false;                        
               
         if (updateBRAuditFields) {
         this.targetAccountSo.BR_Audit__c                             = this.sourceAccountSo.BR_Audit__c;
         this.targetAccountSo.BR_Audit_Type__c                        = this.sourceAccountSo.BR_Audit_Type__c;   
         this.targetAccountSo.BR_Audit_Statement_Date__c              = this.sourceAccountSo.BR_Audit_Statement_Date__c;
         }                                     
         
         // If the (target) root cert has "EV Policy OID(s)" field "Not EV", then don't copy the EV audit info.
         
         updateEVAuditFields = (this.targetAccountSo.type == 'Intermediate Certificate' || 
                                (this.targetAccountSo.type == 'Root' && 
                                this.targetAccountSo.EV_Policy_OID_s__c != null &&
                                this.targetAccountSo.EV_Policy_OID_s__c != 'Not EV')) ? true : false;
         
         if (updateEVAuditFields) {
             this.targetAccountSo.EV_Audit__c                         = this.sourceAccountSo.EV_Audit__c;
             this.targetAccountSo.EV_Audit_Type__c                    = this.sourceAccountSo.EV_Audit_Type__c;   
             this.targetAccountSo.EV_Audit_Statement_Date__c          = this.sourceAccountSo.EV_Audit_Statement_Date__c;
         }
        
         // System.debug('DEBUGSOURCE: '+sourceAccountSo);
         // System.debug('DEBUGSOURCE: '+targetAccountSo);
                 
         this.targetAccountSo.Auditor__c                              = this.sourceAccountSo.Auditor__c;
         this.targetAccountSo.Auditor_Website__c                      = this.sourceAccountSo.Auditor_Website__c;
         this.targetAccountSo.Auditor_Qualifications__c               = this.sourceAccountSo.Auditor_Qualifications__c; 
         this.targetAccountSo.Management_Assertions_By__c             = this.sourceAccountSo.Management_Assertions_By__c;  
         this.targetAccountSo.CP_CPS_Same_as_Parent__c                = this.sourceAccountSo.CP_CPS_Same_as_Parent__c;
         this.targetAccountSo.Policy_Documentation__c                 = this.sourceAccountSo.Policy_Documentation__c;
         this.targetAccountSo.CA_Document_Repository__c               = this.sourceAccountSo.CA_Document_Repository__c;
         this.targetAccountSo.Certificate_Policy_CP__c                = this.sourceAccountSo.Certificate_Policy_CP__c;
         this.targetAccountSo.Certification_Practice_Statement_CPS__c = this.sourceAccountSo.Certification_Practice_Statement_CPS__c;
        
        try{
            update targetAccountSo;
        }catch(Exception exp){
            this.hasError = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error Occurred while updating the account.'));
        }
    }
    
    
    public void redirectToNextAccount(){
        skipAccount();
        this.showConfirmation = true;
    }
    
    public PageReference redirectTosourceAccount(){
        return new PageReference('/'+this.sourceAccountSo.Id);
    }
    
    public void skipAccount(){
        
        recordIndex = recordIndex + 1;
        // system.debug('record Index: '+recordIndex+' -> size: '+this.lstSiblingAccounts.size());
        
        if(recordIndex < this.lstSiblingAccounts.size()){ 
             this.targetAccountSo = this.lstSiblingAccounts[recordIndex];
        }
        else{
            this.showMessage = true;
            this.recordIndex = this.lstSiblingAccounts.size();
        }  
        
    }
}