CACommunity-Salesforce/src/objects/Survey__c.object
<CustomObject>
    <label>Communication</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CACommunity-Salesforce/src/objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Do_not_publish__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this field if the question and the responses are not for publishing on web.</inlineHelpText>
        <label>Do not publish</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Communication</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>SurveyQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CACommunity-Salesforce/src/objects/SurveyQuestionResponse__c.object
<CustomObject>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SurveyTaker__c</fullName>
        <label>Respondent</label>
        <referenceTo>SurveyTaker__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Survey_Question_Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <label>Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Survey_Question_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>Response-{0000000}</displayFormat>
        <label>Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CACommunity-Salesforce/src/objects/SurveyTaker__c.object
<CustomObject>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <formula>Contact__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CA Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responded By Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Respondents</relationshipLabel>
        <relationshipName>SurveyTakers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Communication</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Respondents</relationshipLabel>
        <relationshipName>SurveyTakers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Respondent</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Respondents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CACommunity-Salesforce/src/classes/CommunicationSummaryReportController.cls
global without sharing class CommunicationSummaryReportController{

 public String communicationId;
 
 public String surveyName {get;set;}
 
 public     Map<String,Map<String,List<QnA>>> resultMap {get;set;}
 
  // constructor method for standard controller
    public CommunicationSummaryReportController() {
    
     if(ApexPages.currentPage().getParameters().get('CommunicationId')!=null)
     {
            communicationId = ApexPages.currentPage().getParameters().get('CommunicationId');     
     }
     else
     {
       ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Error,'Please provide a valid communication id.'));
     }
     
     List<SurveyQuestionResponse__c> allResponseLst = [select Survey_Question__r.Survey__r.name,SurveyTaker__r.CA_Owner__c,SurveyTaker__r.Contact__r.name, 
                                               Survey_Question__R.Name,Response__c   
                                               FROM SurveyQuestionResponse__c 
                                               WHERE Survey_Question__r.Survey__c= :communicationId and
                                                     SurveyTaker__r.CA_Owner__c <> '' and
                                                     Survey_Question__R.Do_not_publish__c <> True
                                               ORDER BY  SurveyTaker__r.CA_Owner__c, SurveyTaker__r.Contact__r.name, 
                                               Survey_Question__R.Name];

    for(SurveyQuestionResponse__c responseSO : allResponseLst )
    {
     
      surveyName = responseSo.Survey_Question__r.Survey__r.name;
     
      if(resultMap!=null && resultMap.size() > 0 && resultMap.containsKey(responseSo.SurveyTaker__r.CA_Owner__c))
      {
         
         Map<String,List<QnA>> tempMap= resultMap.get(responseSo.SurveyTaker__r.CA_Owner__c);
         List<QnA> answerLst;
         if(tempMap.containsKey(responseSo.SurveyTaker__r.Contact__r.name))
         {
           answerLst =tempMap.get(responseSo.SurveyTaker__r.Contact__r.name);

         }
         else
         {
           answerLst =New List<QnA>();         
         }
         
          QnA qnAWrapper = New QnA(); 
          qnAWrapper.question=responseSo.Survey_Question__R.Name;
          qnAWrapper.answer = responseSo.Response__c;
          answerLst.add(qnAWrapper);
          tempMap.put(responseSo.SurveyTaker__r.Contact__r.name,answerLst);
          resultMap.put(responseSo.SurveyTaker__r.CA_Owner__c,tempMap);
      }
      else
      {
         List<QnA > answerLst = New List<QnA >();
         QnA qnAWrapper = New QnA(); 
         qnAWrapper.question=responseSo.Survey_Question__R.Name;
          qnAWrapper.answer = responseSo.Response__c;
          answerLst.add(qnAWrapper);
         Map<String,List<QnA>>     tempMap = New Map<String,List<QnA>>();
         tempMap.put(responseSo.SurveyTaker__r.Contact__r.name,answerLst);
         if(resultMap==null)
         {
         resultMap = New Map<String,Map<String,List<QnA>>>();
         }
         resultMap.put(responseSo.SurveyTaker__r.CA_Owner__c,tempMap); 
      }
    }
        
  }
  
  class QnA
  
  {
   public String question {get;set;}
    public String answer {get;set;}
  
  }

}