robballen75-Salesforce/4-7-15/src/iTools State/Country Validation/objects/Account.object
<CustomObject>
</CustomObject>

jlamontSC-test/src/objects/Account.object
    <fields>
        <fullName>Merge_Survivor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merge Survivor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts To Be Merged</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>

robballen75-Salesforce/4-7-15/src/objects/Acct_Proj_Custom_Rollup__c.object
<CustomObject>
    <description>Custom object used to store project and account related information for the generation of the DocXTools Healthcheck score. The data is used by rollup summary and formula fields on the Account object to calculate the number of total training/consulting hours for projects that meet a specific criteria. Only data for the most recent 12 months are used, so records are purged when they hit that timeframe.</description>
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <description>Date specified as the start date for the project. The value is automatically populated via a trigger using the corresponding field value on the project record.</description>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <description>Current status of the project. The value is automatically populated via a trigger using the corresponding field value on the project record.</description>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending CR Followup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Complete - Pending CR Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Upgrade Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <description>Type of project. The value is automatically populated via a trigger using the corresponding field value on the project record.</description>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Master-Child record to the associated Project.</description>
        <label>Project</label>
        <referenceTo>MS_Project__c</referenceTo>
        <relationshipLabel>Account-Project Custom Rollup</relationshipLabel>
        <relationshipName>Account_Project_Custom_Rollup</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>proj_hrs_logged_billable_not_chargeable__c</fullName>
        <description>Number of non-billable hours currently logged on the project. The value is automatically populated via a trigger using the corresponding field value on the project record.</description>
        <label>Hrs Logged-BILLABLE (Not Chargeable)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>project_hours_logged_f__c</fullName>
        <description>Number of billable hours currently logged on the project. The value is automatically populated via a trigger using the corresponding field value on the project record.</description>
        <label>Project Hours Logged - BILLABLE (f)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Account-Project Custom Rollup</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Account-Project CRU ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account-Project Custom Rollup</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

robballen75-Salesforce/4-7-15/src/objects/MS_Project__c.object
<CustomObject>
    <fields>
        <fullName>Proj_Hrs_Logged_BILLABLE_Not_Chargeable__c</fullName>
        <description>Work that should be billable that isn&apos;t.  It could be due to customer sensitivity, overruns, etc.  It does not include issues such as product problems, planning errors, etc.</description>
        <label>Hrs Logged-BILLABLE (Not Chargeable)</label>
        <summarizedField>MS_Time_Entry__c.TE_Billable_Not_Chargeable__c</summarizedField>
        <summaryForeignKey>MS_Time_Entry__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project_Hours_Logged_f__c</fullName>
        <inlineHelpText>Calculated roll-up of all time entry hours for this project.</inlineHelpText>
        <label>Hrs  Logged - BILLABLE</label>
        <summarizedField>MS_Time_Entry__c.Time_Entry_Hours__c</summarizedField>
        <summaryForeignKey>MS_Time_Entry__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Project Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending CR Followup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Complete - Pending Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Upgrade Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

vibhudadhichi-TicketReservation/src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Project__c.object
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>

lanecwe-Prod/src/objects/Project__c.object
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by Business Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployed to Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Review for Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started/Approved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organizing Project for Cases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending BRD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preliminary Discussions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Review by Business Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Deploy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Business Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewing BRD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User Acceptance Testing</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>

lanecwe-Prod/src/objects/Project__c.object
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>x-Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Small</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

robballen75-Salesforce/4-7-15/src/objects/Project_Product__c.object
<CustomObject>
    <fields>
        <fullName>Project_Product_Type__c</fullName>
        <label>Project Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>3BClean Batch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3BClean Desktop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3BClean Server</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author&apos;s Toolkit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoText and Building Blocks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comparison</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Utility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DocID Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document Workflow Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DocXamine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DocXtools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DocXtools Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EagleEye</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EagleEye Defined Terms Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exchange Connector</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flipping the Switch - Dual Format</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Application Preparedness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Numbering Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office Planning Engagement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patent Companion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDF Compare Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PowerPoint and Themes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal/Retention Effort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ribbon UI Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Templates and Styles Best Practices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TOC Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Validate Refine Align Engagement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MS_Project__c</referenceTo>
        <relationshipLabel>Project Products</relationshipLabel>
        <relationshipName>R00N50000001uCqDEAU</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Product</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Project Product #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

robballen75-Salesforce/4-7-15/src/classes/KPBatch_DocXtoolsTrainConsultCRU.cls
//*********************************************************************************** 
// 
//  KPBatch_DocXtoolsTrainConsultCRU
//   
//  Description:
//  This class implements the Database.Batchable interface and is used to 
//  create Custom Rollup (CRU) records to support the calculation of the 
//  DocXtools training/consulting score component of the KP Health Check Rating.
//
//  This class was developed for Microsystems by InSitu Software LLC.
//   
//  History:
//  InSitu     01/11/2010    Original version
//
// ***********************************************************************************

global with sharing class KPBatch_DocXtoolsTrainConsultCRU implements Database.Batchable<sObject>
{
    ///////////////////////////////////////////////////
    //  Constants
    ///////////////////////////////////////////////////
    
    ///////////////////////////////////////////////////
    //  Member variables
    ///////////////////////////////////////////////////
	public Boolean bTest   {get; set;}	// Needed so that the unit tests can limit the query results to 200.
	
    ///////////////////////////////////////////////////
    //  Methods
    ///////////////////////////////////////////////////

    // Constructor

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
    	// Begin - the following section defines values used in the criteria to determine
        // the projects to be included in the calculation of the Private Training/Consulting hours 
        // component of the KP Health Check.
        
        // Project Product Type - to INCLUDE
        Set<String> setIncludeProjectProductType = new Set<String>();
        setIncludeProjectProductType.add('DocXTools');

        // Project Type - to INCLUDE
        Set<String> setIncludeProjectType = new Set<String>();
        setIncludeProjectType.add('Training');
        setIncludeProjectType.add('Consulting');
        
        // Project Status values - to EXCLUDE
        Set<String> setExcludeProjectStatus = new Set<String>();
        setExcludeProjectStatus.add('Cancelled');
        
        // Number of days
    	integer iMostRecentNumberOfDays = 365;
    	
    	// End -- KP Health Check Criteria values.
    	    

		// Create the query to find all Project Product records associated with Projects to be processed
		Date dateMR = Date.Today() - iMostRecentNumberOfDays;

		// The bTest variable is provided so that the query is limited to 200 records and is sorted such 
		// that the test records are guaranteed to be retrieved. 
		if (bTest != true)
		{
			return Database.getQueryLocator([SELECT project__c, project__r.ID, project_product_type__c
			                                          FROM Project_Product__c
			                                          WHERE project_product_type__c in :setIncludeProjectProductType AND
			                                                project__r.project_type__c in :setIncludeProjectType AND
			                                                project__r.project_status__c NOT in :setExcludeProjectStatus AND
			                                                project__r.project_start_date__c > :dateMR]);
		}
		else
		{
			system.debug('Running test query.');
			return Database.getQueryLocator([SELECT project__c, project__r.ID, project_product_type__c
			                                          FROM Project_Product__c
			                                          WHERE project_product_type__c in :setIncludeProjectProductType AND
			                                                project__r.project_type__c in :setIncludeProjectType AND
			                                                project__r.project_status__c NOT in :setExcludeProjectStatus AND
			                                                project__r.project_start_date__c > :dateMR
			                     // Next two lines are unique just for testing purposes.
			                     					  ORDER BY project__r.name DESC                           
			                                          LIMIT :200]);
		}
    }

	// --------------------------------------------------------
    //  execute
    //
    //  This method is called by the Batch Apex controller. Sets of records are
    //  sent in to be processed in 'batch'. Like a bulkified trigger, this method
    //  places items in collections for querying and updating to limit the number 
    //  of DML statements issued. Got to mind those governor limits! 
    // --------------------------------------------------------

    global void execute(Database.BatchableContext BC, sObject[] listProjProds)
    {
		// Iterate the collection of Project Product items - put all project ids into a set
		// in preparation for the project/account query.
        Set<ID> setProjectIds = new Set<ID>();
        for (integer i=0; i < listProjProds.size(); i++)
        {
            setProjectIds.add(((Project_Product__c)listProjProds[i]).project__r.ID);  
        }   
        
        //system.debug('Number of Project IDs in set = ' + setProjectIds.size());

        // Get all the project objects and associated account data.
        List<MS_Project__c> listProjects = new List<MS_Project__c>();
        listProjects = [SELECT Name, project_hours_logged_f__c, proj_hrs_logged_billable_not_chargeable__c,
                            project_start_date__c, project_status__c, project_type__c, account__r.ID
                        FROM MS_Project__c
                        WHERE ID in :setProjectIds];

        //system.debug('Number of Projects retrieved = ' + listProjects.size());
                        
        // Iterate the projects and create acct_proj_custom_rollup records for each project
        List<acct_proj_custom_rollup__c> listAcctProjCRU = new List<acct_proj_custom_rollup__c>();
        for (integer i=0; i < listProjects.size(); i++)
        {
            acct_proj_custom_rollup__c cruAcctProj = new acct_proj_custom_rollup__c(
	            account__c = listProjects[i].account__r.ID,
	            project__c = listProjects[i].ID,
	            project_type__c = listProjects[i].project_type__c,
	            project_status__c = listProjects[i].project_status__c,
	            project_start_date__c = listProjects[i].project_start_date__c,
	            project_hours_logged_f__c = listProjects[i].project_hours_logged_f__c,
	            proj_hrs_logged_billable_not_chargeable__c = listProjects[i].proj_hrs_logged_billable_not_chargeable__c);
            
            listAcctProjCRU.add(cruAcctProj);
        }   
        if (listAcctProjCRU.size() > 0)
        {
            system.debug('Inserting/Updating AcctProj CRU record count: ' + listAcctProjCRU.size());
            insert listAcctProjCRU;
        }
    }
    
	// --------------------------------------------------------
    //  finish
    //
    //  This method is called by the Batch Apex controller when an error is
    //  encountered during the execution of the Batch Apex Batch. If this should
    //  happen, a notification email is sent out. 
    // --------------------------------------------------------

    global void finish(Database.BatchableContext BC)
    {
    	// Get the ID of the AsyncApexJob representing this batch job from Database.BatchableContext.
		// Query the AsyncApexJob object to retrieve the current job's information.
		ID idJob = BC.getJobId();
		AsyncApexJob apexjobCRU =  [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
						  			FROM AsyncApexJob WHERE Id = :idJob];

		// Because of test coverage issues in this class, need to create the 'failure' email message and only
		// send if there is truly a failure.
		// I can't seem to find a way to fail the job from a test.
		Messaging.SingleEmailMessage emailNotify = new Messaging.SingleEmailMessage();
		String[] toAddresses = new String[] {apexjobCRU.CreatedBy.Email};
		emailNotify.setToAddresses(toAddresses);
		emailNotify.setSubject('KP Health Check Calculation: DocXTools Training/Consulting Time - Completed with Errors');
		emailNotify.setPlainTextBody(
			'The KP Health Check Calculation for the DocXTools Training/Consulting Time component completed, however the job reported ' + apexjobCRU.NumberOfErrors + 
			' errors. If the calculation continues to fail, contact your system administrator or InSitu Software support.');
			
		// if the job did not complete successfully, then send an email to the job's submitter letting them know that there was a problem.
		if (apexjobCRU.Status == 'Failed')
		{
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { emailNotify });
		}
    	
    }   
}