vibhudadhichi-TicketReservation/src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>The city the account is located in.</inlineHelpText>
        <label>City (old)</label>
        <length>80</length>
        <type>Text</type>
    </fields>

lanecwe-Prod/src/objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This field is dynamically set.  If it has 0 companies associated to it the value is Prospect.  If it has &gt; 0 companies associated to it then it will be Customer.  There are also some Partner channel specific things that will set the value to Customer.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

dimagi-SalesforceFB/src/objects/City__c.object
<CustomObject>
    <description>This is a custom object to track cities.</description>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ian-hamilton-salesforce/retrieveMetadata/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Choose a value from the list</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV–{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

pulkitchhabra-salesforce/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Merchandise__c</fullName>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ian-hamilton-salesforce/retrieveMetadata/objects/Line_Item__c.object
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>

ian-hamilton-salesforce/retrieveMetadata/objects/Line_Item__c.object
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>

pulkitchhabra-salesforce/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ian-hamilton-salesforce/retrieveMetadata/objects/Merchandise__c.object
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>

sagarmadkaikar29-Salesforce/Personal Org/src/classes/testQuickOrderController.cls
@isTest
    private class testQuickOrderController {
    static testMethod void testQuickOrderController() {
        Account aTest1 = new Account(Name='test account',Location__Longitude__s=-122.396382, Location__Latitude__s=37.793728);
        Account aTest2 = new Account(Name='test account');
        insert aTest1; insert aTest2;
        
        Warehouse__c wareTest1 = new Warehouse__c(Name='ware test 1', Street_Address__c='640 Brannan St',City__c='San Francsico', Location__Latitude__s=37.783900,Location__Longitude__s=-122.389332);
        Warehouse__c wareTest2 = new Warehouse__c(Name='ware test 2', Street_Address__c='160 Brannan St',City__c='San Francsico',Location__Latitude__s=37.775794, Location__Longitude__s=-122.399579);
        insert wareTest1; insert wareTest2;
        
        Merchandise__c merchTest1 = new Merchandise__c(Name='test iPhone',Price__c=600,Quantity__c=5,Condition__c='New',Warehouse__c=wareTest1.Id);
        Merchandise__c merchTest2 = new Merchandise__c(Name='test MacBook',Price__c=1000,Quantity__c=10,Condition__c='New',Warehouse__c=wareTest2.Id);
        insert merchTest1; insert merchTest2;
        
        QuickOrderController.findWarehouses(aTest1.Id, 'iPhone', '50');
        QuickOrderController.findWarehouses(aTest1.Id, 'Macbook', '10');
        
        Line_Item__c testQuickOrder = QuickOrderController.createQuickOrder(aTest1.Id, merchTest1.Id);
        String testOrderSerialized = JSON.serialize(testQuickOrder);
        QuickOrderController.insertQuickOrder(testOrderSerialized, '100', aTest1.Id);
        
        Invoice__c testInv = new Invoice__c(Account__c=aTest1.Id,Status__c='Open');
        insert testInv;
        QuickOrderController.goBack(testInv.Id);
        
        System.assertEquals(true,WarehouseDataInstall.getHasData());
    }
}