GARPDev-salesforce/eclipse/GARPDev/src/objects/Account.object
<CustomObject>
</CustomObject>

vibhudadhichi-TicketReservation/src/objects/Account.object
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam__c.object
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam_Attempt__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Site__c</fullName>
        <label>Exam Site</label>
        <referenceTo>Exam_Sites__c</referenceTo>
        <relationshipName>Exam_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Exam_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No-Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <formula>Exam_Site__r.Site__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site</label>
        <type>Text</type>
    </fields>
    <label>Exam Registrations</label>
    <nameField>
        <label>Candidate Exam Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam_Sites__c.object
<CustomObject>
    <fields>
        <fullName>Exam__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exam</label>
        <referenceTo>Exam__c</referenceTo>
        <relationshipName>Exam_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Exam Sites</relationshipLabel>
        <relationshipName>Exam_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exam Sites</label>
    <nameField>
        <label>Exam Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Site__c.object
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/code_build/codepkg/classes/deferredExams.cls
public class deferredExams
{
    public Exam_Attempt__c objEA{get;set;}
    public List<Exam_Attempt__c> lstEA{get;set;}
    public List<deferredWrap> lstDeferredWrap{get;set;}
    
    public deferredExams(Apexpages.StandardController std)
    {
        objEA = new Exam_Attempt__c();
    }
    
    public pageReference examAttemptDetails()
    {
        lstDeferredWrap = new List<deferredWrap>();
        for(Exam_Attempt__c objEA : [select id,name,Member__c,Result__c,Exam_Site__r.Name,Exam_Site__r.Site__r.Name,Exam_Site__r.Exam__r.Exam_Group__r.Active__c from Exam_Attempt__c where Exam_Site__r.Exam__r.Exam_Group__r.Active__c =: true and Member__c =: objEA.Member__c and Defered__c =: null])
        {
            lstDeferredWrap.add(new deferredWrap(objEA));
        }
        return null;
    
    }
    
    public pageReference updateDeffered()
    {
        Integer iCount = 0;
        String strPaymentId = '';
        for(deferredWrap objWrap : lstDeferredWrap)
        {
            if(objWrap.isDeferred)
                iCount++;
        }
        if(iCount >= 2)
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Please Select only one.');
            ApexPages.addMessage(myMsg);
            return null;
        }
        else
        {
            for(deferredWrap objWrap : lstDeferredWrap)
            {
                if(objWrap.isDeferred)
                {
                    strPaymentId = portalClass.checkExamAttempts(objWrap.ObjEA.Id,'ENC','4020',true);
                    //strPaymentId = portalClass.checkExamAttempts(objWrap.ObjEA.Id,'FRM1','4020',true);
                
                }
            }
        }
         ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'Deferred process has been initiated, customer needs to make a payment.Please contact account team.');
            ApexPages.addMessage(myMsg);
        
        return null;
    
    }
    
    
    public class deferredWrap
    {
        public Exam_Attempt__c objEA{get;set;}
        public boolean isDeferred{get;set;}
        
        public deferredWrap(Exam_Attempt__c objExamAttempt)
        {
            objEA = objExamAttempt;
            isDeferred = false;
        }
    
    }
    
}