GARPDev-salesforce/eclipse/GARPDev/src/objects/Account.object
<CustomObject>
</CustomObject>

vibhudadhichi-TicketReservation/src/objects/Account.object
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

lanecwe-Prod/src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>xHOLD-Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Companies</relationshipLabel>
        <relationshipName>Companies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Contract.object
<CustomObject>
</CustomObject>

dimagi-SalesforceFB/src/objects/Contract.object
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this Contract Active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Date__c</fullName>
        <label>Exam Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exam_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exam Group</label>
        <referenceTo>Exam_Group__c</referenceTo>
        <relationshipLabel>Exams</relationshipLabel>
        <relationshipName>Exams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exam__c</fullName>
        <label>Exam</label>
        <picklist>
            <picklistValues>
                <fullName>FRM Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FRM Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ERP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Date_For_Early_Registration__c</fullName>
        <inlineHelpText>Select the date so candidate know what&apos;s last date to early registration</inlineHelpText>
        <label>Last Date For Early Registration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Date_For_Late_Registration__c</fullName>
        <inlineHelpText>Select the date so candidate know what&apos;s last date to late registration</inlineHelpText>
        <label>Last Date For Late Registration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Date_For_Standard_Registration__c</fullName>
        <inlineHelpText>Select the date so candidate know what&apos;s last date to standard registration</inlineHelpText>
        <label>Last Date For Standard Registration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Record_id__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record id</label>
        <type>Text</type>
    </fields>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam_Attempt__c.object
<CustomObject>
    <fields>
        <fullName>Candidate_Commitment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look-up to the candidate&apos;s program contract record.</description>
        <label>Candidate Commitment</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Exam Registrations</relationshipLabel>
        <relationshipName>Exam_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exam_Site__c</fullName>
        <label>Exam Site</label>
        <referenceTo>Exam_Sites__c</referenceTo>
        <relationshipName>Exam_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Exam_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No-Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <formula>Exam_Site__r.Site__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site</label>
        <type>Text</type>
    </fields>
    <label>Exam Registrations</label>
    <nameField>
        <label>Candidate Exam Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam_Group__c.object
<CustomObject>
    <description>Aggregates Exams in an exam event.  ( all the exams given on the same weekend )</description>
    <label>Exam Group</label>
    <nameField>
        <label>Exam Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam_Sites__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Date__c</fullName>
        <label>Exam Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exam__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exam</label>
        <referenceTo>Exam__c</referenceTo>
        <relationshipName>Exam_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Exam Sites</relationshipLabel>
        <relationshipName>Exam_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exam Sites</label>
    <nameField>
        <label>Exam Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <picklist>
            <picklistValues>
                <fullName>FRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ICBRR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundations (Banking)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundations (Energy)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Professional Certificate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GARP Digital Library</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customized Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Edition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Publishing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

dimagi-SalesforceFB/src/objects/Opportunity.object
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To define weather the Location is active or not.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Non_selectable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non-selectable</label>
        <type>Checkbox</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/code_build/codepkg/classes/SwitchLayer_test.cls
@isTest
public class SwitchLayer_test {

    static profile profile1;
    static user user1;
    static account acc;
    static opportunity opp;
    static contact contact1;
    static PricebookEntry customPrice;
    static Product2 prod7 ;
    static exam_attempt__c attempt;
    static exam_attempt__c attempt1;
    static exam__c exam;
    static Contract contract1;
    static contact contact;
    
    static void testData(){
        
        ChargentBase__Gateway__c chrgGtway = new ChargentBase__Gateway__c(Name = 'Test',ChargentBase__Merchant_ID__c = 'dasghjtru548709-4',ChargentBase__Active__c = true );
        insert chrgGtway;
        
        insert new UpdateIds__c(Name = 'GARP', Record_Id__c = chrgGtway.id);
        
        Acc = new Account(Name = 'test');
        insert acc;
         
        opp = new Opportunity(amount = 123,Name = 'Test',Eligible_for_Membership_Extension__c = false,company__c = 'Payment', accountId = acc.id,stageName = 'New Lead',Program__c = 'Print' ,closedate = system.today()+ 15);        
        insert opp;
        
        Contract1  = new Contract(Opportunity__c = opp.id, AccountId = opp.AccountId ,ContractTerm = 12     ,StartDate = opp.CloseDate        );
        insert contract1;
        contract1.Status = 'Activated';
        update contract1;
        contact1 = new Contact(recordtypeid = RecordTypeHelper.GetRecordTypeId('Contact','Business Relationship'),firstname = 'test1',lastname = 'test2',AccountId = acc.id,email='testtest@test.com',KPI_ERP_Enrollment_Date__c = Date.newInstance(2009, 2, 17));
        insert contact1;
        
        contact = new Contact(firstname = 'test1',lastname = 'test2',AccountId = acc.id,email='sdftesttest@test.com',KPI_ERP_Enrollment_Date__c = Date.newInstance(2009, 2, 17));
        insert contact;
        
        profile1 = [SELECT Id FROM Profile WHERE usertype = 'CspLitePortal' limit 1]; 
        user1 = new User(Alias = 'newUser', Email='newuser@testorg.com',contactId = contact1.id,EmailEncodingKey='UTF-8', LastName='Test', LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = profile1.Id, TimeZoneSidKey='America/Los_Angeles', UserName='testnewuser@testorg.com');
        
        prod7 = new Product2(Name = 'Laptop X200',productCode = 'GL0051',GL_Code__c = '4002',Family = 'Hardware',isActive = true);
        insert prod7;
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice7 = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prod7.Id,UnitPrice = 10000, IsActive = true);
        insert standardPrice7;
        
    
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        
        customPrice = new PricebookEntry( Pricebook2Id = customPB.Id, Product2Id = prod7.Id,UnitPrice = 12000, IsActive = true);
        insert customPrice;
        
        Site__c site = new Site__c(name = 'test',Display_Address__c = 'test',active__c = true,Non_selectable__c = false);
        insert site;
        
        Exam_Group__c objExamGrp = new Exam_Group__c();
        objExamGrp.Active__c = true;
        Date dt1 = system.today();
        objExamGrp.Registration_Start_Date__c = dt1.addDays(4);
        objExamGrp.Last_Date_For_Early_Registration__c = system.today()+1;
        objExamGrp.Last_Date_For_Standard_Registration__c = system.today() +9 ;
        objExamGrp.Last_Date_For_Late_Registration__c = system.today() +10 ;    
        insert objExamGrp;
        
        exam = new Exam__c();
        exam.Exam_Group__c = objExamGrp.id;
        exam.Exam_Date__c = system.today() + 30;
        exam.exam__c = 'FRM Part 1'; 
        exam.name = 'FRM Part 1';
        insert exam;
        exam__c exam1 = new Exam__c();
        exam1.Exam_Group__c = objExamGrp.id;
        exam1.Exam_Date__c = system.today() + 30;
        exam1.exam__c = 'FRM Part 2'; 
        exam1.name = 'FRM Part 2';
        insert exam1;
        
        Exam_Sites__c exmSite = new Exam_Sites__c(Site__c = site.id,exam__c = exam.id);
        insert exmSite;
        
        attempt = new Exam_Attempt__c(Opportunity__c = opp.id, Exam_Site__c = exmSite.id,Member__c = contact1.id,cancelled__c = false );
        insert attempt;
        
        attempt1 = new Exam_Attempt__c(Result__c = 'Pass',Opportunity__c = opp.id, Exam_Site__c = exmSite.id,Member__c = contact1.id,cancelled__c = false  );
        attempt1.Candidate_Commitment__c  = contract1.id;
        insert attempt1;
        
        
        
    }
    
    static testMethod void unitTest_1(){
      
        test.startTest();
        testData();
        system.runAs(user1){
            SwitchLayer.swithcLogic();
        }
        test.stopTest();
        
    }
    
    static testMethod void unitTest_2(){
               
        test.startTest();
        testData();
        switchlayer.lstExamDetails = new Exam__c []{exam};
        map<string,pricebookentry> mapPriceBookDetails = new map<string,pricebookentry>();
        mapPriceBookDetails.put(prod7.Name,customPrice);
        SwitchLayer.checkERPDetails(true, new exam_attempt__c[]{attempt}, mapPriceBookDetails);
        SwitchLayer.checkFRMDetails(true, new exam_attempt__c[]{attempt}, mapPriceBookDetails);
        SwitchLayer.getProductCodeByMonth(mapPriceBookDetails, exam.name, 12, 'Completed');
        test.stopTest();
        
    }
}