GARPDev-salesforce/eclipse/GARPDev/src/objects/Account.object
<CustomObject>
</CustomObject>

lanecwe-Prod/src/objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This field is dynamically set.  If it has 0 companies associated to it the value is Prospect.  If it has &gt; 0 companies associated to it then it will be Customer.  There are also some Partner channel specific things that will set the value to Customer.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Candidate_Requirement__c.object
<CustomObject>
    <description>Requirements records to manage a candidate&apos;s program progress</description>
    <fields>
        <fullName>Candidate_Commitment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate Commitment</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Candidate Requirements</relationshipLabel>
        <relationshipName>Candidate_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready For Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Candidate Requirement</label>
    <nameField>
        <label>Candidate Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>xHOLD-Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Companies</relationshipLabel>
        <relationshipName>Companies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

dimagi-SalesforceFB/src/objects/Contact.object
    <fields>
        <fullName>Status__c</fullName>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>1- Working - Active Opp Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2- Working - Talking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3- Working - Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4- Strategic Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5- Active Project Team Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6- Active Self Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7- Passive &amp; Friendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8- Passive &amp; Unfriendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9-HOLD Not mine/move</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10-Dimagi Staff</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam__c.object
<CustomObject>
    <fields>
        <fullName>Exam__c</fullName>
        <label>Exam</label>
        <picklist>
            <picklistValues>
                <fullName>FRM Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FRM Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ERP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Record_id__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record id</label>
        <type>Text</type>
    </fields>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Lead.object
<CustomObject>
</CustomObject>

WiseUpTi-SalesForce/Wise Up Sales Force/src/objects/Lead.object
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <picklist>
            <picklistValues>
                <fullName>FRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ICBRR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundations (Banking)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundations (Energy)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Professional Certificate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GARP Digital Library</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customized Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Edition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Publishing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

dimagi-SalesforceFB/src/objects/Opportunity.object
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

lanecwe-Prod/src/objects/Opportunity.object
    <fields>
        <fullName>Status__c</fullName>
        <label>x-Status</label>
        <picklist>
            <picklistValues>
                <fullName>Dead/Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open-Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Session/Needs Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presentation/Proposal/Price Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pilot/Trial/Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation/Verbal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won: Contract/CRA/Booked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

GARPDev-salesforce/code_build/codepkg/classes/DataloadModification_test.cls
@isTest
public class DataloadModification_test {

    static Account acc ;
    static Opportunity opp; 
    static Contract contract;
    static Contact contact;
    static Candidate_Requirement__c reqt;
    
    static void testData(){
    
        insert new UpdateIds__c(Name='Payment', Record_Id__c='a0cf00000041nXB');
        insert new UpdateIds__c(Name='User', Record_Id__c='00540000001y7OX');        
        ChargentBase__Gateway__c chrgGtway = new ChargentBase__Gateway__c(Name = 'Test',ChargentBase__Merchant_ID__c = 'dasghjtru548709-4',ChargentBase__Active__c = true );
        insert chrgGtway;
        insert new UpdateIds__c(Name = 'GARP', Record_Id__c = chrgGtway.id);
        
        Acc = new Account(Name = 'test');
        insert acc;
         
        opp = new Opportunity(amount = 123,Name = 'Test',Eligible_for_Membership_Extension__c = false,company__c = 'Payment', accountId = acc.id,stageName = 'New Lead',Program__c = 'Print' ,closedate = system.today()+ 15);        
        insert opp;
    
        Contract  = new Contract(Opportunity__c = opp.id, AccountId = opp.AccountId ,ContractTerm = 12 ,StartDate = opp.CloseDate );
        insert contract;
        
        reqt = new Candidate_Requirement__c();
        reqt.recordTypeId = RecordTypeHelper.GetRecordTypeId('Candidate_Requirement__c','Exam');
        reqt.Candidate_Commitment__c = contract.id;
        reqt.name = 'FRM1 test';
        reqt.status__c = 'Initial';
        reqt.Exam__c = 'FRM Full';
        insert reqt;
        
        
    }
    
    static testMethod void unitTest_1(){
        testData();
        test.startTest();
        DataloadModification dataload = new DataloadModification();
        database.executeBatch(dataload);
        test.stopTest();
        
    }
    
}