GARPDev-salesforce/eclipse/GARPDev/src/objects/Candidate_Requirement__c.object
<CustomObject>
    <description>Requirements records to manage a candidate&apos;s program progress</description>
    <fields>
        <fullName>Candidate_Commitment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate Commitment</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Candidate Requirements</relationshipLabel>
        <relationshipName>Candidate_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Candidate Requirement</label>
    <nameField>
        <label>Candidate Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam__c.object
<CustomObject>
    <fields>
        <fullName>Cloned_From__c</fullName>
        <label>Cloned From</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exam_Date__c</fullName>
        <label>Exam Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exam_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exam Group</label>
        <referenceTo>Exam_Group__c</referenceTo>
        <relationshipLabel>Exams</relationshipLabel>
        <relationshipName>Exams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exam__c</fullName>
        <label>Exam</label>
        <picklist>
            <picklistValues>
                <fullName>FRM Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FRM Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ERP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam_Attempt__c.object
<CustomObject>
    <fields>
        <fullName>Candidate_Commitment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look-up to the candidate&apos;s program contract record.</description>
        <label>Candidate Commitment</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Exam Registrations</relationshipLabel>
        <relationshipName>Exam_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Candidate_Requirement__c</fullName>
        <description>Links this exam attempt to the Program Requirement that it satisfies.</description>
        <inlineHelpText>Links this exam attempt to the Program Requirement that it satisfies.</inlineHelpText>
        <label>Candidate Requirement</label>
        <referenceTo>Candidate_Requirement__c</referenceTo>
        <relationshipLabel>Exam Registrations</relationshipLabel>
        <relationshipName>Exam_Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exam_Site__c</fullName>
        <label>Exam Site</label>
        <referenceTo>Exam_Sites__c</referenceTo>
        <relationshipName>Exam_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Exam_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <formula>text(Exam_Site__r.Exam__r.Exam__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Section</label>
        <type>Text</type>
    </fields>
    <label>Exam Registrations</label>
    <nameField>
        <label>Candidate Exam Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam_Group__c.object
<CustomObject>
    <description>Aggregates Exams in an exam event.  ( all the exams given on the same weekend )</description>
    <label>Exam Group</label>
    <nameField>
        <label>Exam Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam_Sites__c.object
<CustomObject>
    <fields>
        <fullName>Cloned_From__c</fullName>
        <label>Cloned From</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exam_Date__c</fullName>
        <label>Exam Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exam__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exam</label>
        <referenceTo>Exam__c</referenceTo>
        <relationshipName>Exam_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exam Sites</label>
    <nameField>
        <label>Exam Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/code/codepkg/classes/updateExamGroupdfrm.cls
global class updateExamGroupdfrm implements Database.Batchable<sObject>,Database.StateFul{
    
   global Database.QueryLocator start(Database.BatchableContext BC){
      
     //run this batch for only one record at once.

         String StrDefered = 'Pending';       
         String oppstatus = 'closed';
         Set<String> strSection = new Set<String>{'FRM Part 1','FRM Part 2'};
         return Database.getQueryLocator('select id,Section__c,Exam_Site__r.Exam_Site_Code_idetifier__c,Opportunity__c,Deferral_Status__c,Candidate_Commitment__c,Member__c,Candidate_Requirement__c,Exam_Site__c,Defered__c from Exam_Attempt__c where  Defered__c =: StrDefered  and Opportunity_StageName__c =:oppstatus and cancelled__c !=true and Section__c in: strSection and Exam_Date__c = 2015-11-21'); 
   
   }

   global void execute(Database.BatchableContext BC, List<Exam_Attempt__c> scope){
        
        Map<String,Id> mapOldSiteCodes = new Map<String,Id>();
        Map<String,Id> mapNewSiteCodes = new Map<String,Id>();
        List<Exam_Attempt__c> lstToUpdate = new List<Exam_Attempt__c>();
        List<Exam_Attempt__c> lstToUpdate1 = new List<Exam_Attempt__c>();
         
        for(Exam_sites__c  objSite : [select id,name,Exam_Site_Code_idetifier__c from Exam_sites__c where Exam__r.Exam_Group__c ='a1c400000039NuE'])
        {
            mapNewSiteCodes.put(objSite.Exam_Site_Code_idetifier__c,objSite.Id);
        }
         if(test.isRunningTest()){
        for(Exam_sites__c  objSite : [select id,name,Exam_Site_Code_idetifier__c from Exam_sites__c])
        {
            mapNewSiteCodes.put(objSite.Exam_Site_Code_idetifier__c,objSite.Id);
        }}
       
        Map<Id,Exam_Attempt__c> mapDetails = new Map<Id,Exam_Attempt__c>();
        for(Exam_Attempt__c obj : scope)  
        {
            mapOldSiteCodes.put(obj.Exam_Site__r.Exam_Site_Code_idetifier__c,obj.Exam_Site__c);
            Exam_Attempt__c clonedRec = obj.clone(false,true,false,false);
           
            clonedRec.Exam_Site__c = mapNewSiteCodes.get(obj.Exam_Site__r.Exam_Site_Code_idetifier__c);
            clonedRec.Defered__c = 'Approved';
            clonedRec.Deferral_Status__c = 'Deferred In';
            clonedRec.Cloned_From__c = obj.id;

            obj.Defered__c = 'Approved';
            obj.Cancelled__c =true;
            obj.Cancel_Reason__c ='Deferral';
            obj.Deferral_Status__c ='Deferred Out';
                   
           lstToUpdate.add(obj);
           lstToUpdate1.add(clonedRec);
            
        }

       upsert lstToUpdate;
       upsert lstToUpdate1;
       
      
        }
    
  global void finish(Database.BatchableContext BC){
   
   }
}