GARPDev-salesforce/eclipse/GARPDev/src/objects/Candidate_Requirement__c.object
<CustomObject>
    <description>Requirements records to manage a candidate&apos;s program progress</description>
    <fields>
        <fullName>Candidate_Commitment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate Commitment</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Candidate Requirements</relationshipLabel>
        <relationshipName>Candidate_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Completion__c</fullName>
        <description>This field is used to store the date the candidate sat for the exam that he subsequently passed to satisfy this requirement.  Needed for workflow that sets the contract start date for FRM candidates.</description>
        <label>Date of Completion</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready For Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Candidate Requirement</label>
    <nameField>
        <label>Candidate Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam_Attempt__c.object
<CustomObject>
    <fields>
        <fullName>Candidate_Commitment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look-up to the candidate&apos;s program contract record.</description>
        <label>Candidate Commitment</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Exam Registrations</relationshipLabel>
        <relationshipName>Exam_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Candidate_Requirement__c</fullName>
        <description>Links this exam attempt to the Program Requirement that it satisfies.</description>
        <inlineHelpText>Links this exam attempt to the Program Requirement that it satisfies.</inlineHelpText>
        <label>Candidate Requirement</label>
        <referenceTo>Candidate_Requirement__c</referenceTo>
        <relationshipLabel>Exam Registrations</relationshipLabel>
        <relationshipName>Exam_Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No-Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <formula>text(Exam_Site__r.Exam__r.Exam__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Section</label>
        <type>Text</type>
    </fields>
    <label>Exam Registrations</label>
    <nameField>
        <label>Candidate Exam Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GARPDev-salesforce/code_build/codepkg/classes/Datacompletionbatch2.cls
global class Datacompletionbatch2 implements Database.Batchable<SObject>
{
   global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('select id,Exam_Date__c,Candidate_Commitment__c,Result__c,Section__c,Cancelled__c,Candidate_Requirement__c from Exam_Attempt__c');
     }
    
    
    global void execute(Database.BatchableContext BC, List<Exam_Attempt__c> scope){
        Map<Id,Exam_Attempt__c> mapEA = new Map<Id,Exam_Attempt__c>();
        List<Exam_Attempt__c> lstExamAttempts = new List<Exam_Attempt__c>();
        for(Exam_Attempt__c obj : scope)
        {
             if(obj.Result__c == 'Pass')
                mapEA.put(obj.Candidate_Requirement__c,obj);
            
        }
        
        if(!mapEA.isEmpty())
        {
        
            List<Candidate_Requirement__c>  lstCR = new List<Candidate_Requirement__c>();
            for(Candidate_Requirement__c objCR : [select id,Name,Date_of_Completion__c,Status__c from Candidate_Requirement__c where id in: mapEA.keySet()])
            {
                Exam_Attempt__c objEA = mapEA.get(objCR.Id);
                if(objEA.Result__c == 'Pass')
                {
                    objCR.Date_of_Completion__c = mapEA.get(objCR.Id).Exam_Date__c;
                    objCR.Status__c = 'Completed';
                }
               lstCR.add(objCR);
            }
            if(!lstCR.isEmpty())
                update lstCR;
        }
        
        
        
        if(lstExamAttempts.size() > 0)
            update lstExamAttempts;
        
    }
   
    global void finish(Database.BatchableContext BC){
         
       
    }

}