GARPDev-salesforce/eclipse/GARPDev/src/objects/Candidate_Requirement__c.object
<CustomObject>
    <description>Requirements records to manage a candidate&apos;s program progress</description>
    <fields>
        <fullName>Candidate_Commitment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate Commitment</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Candidate Requirements</relationshipLabel>
        <relationshipName>Candidate_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready For Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Candidate Requirement</label>
    <nameField>
        <label>Candidate Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/code_build/codepkg/classes/Datacompletionbatch19.cls
global class Datacompletionbatch19 implements Database.Batchable<SObject>
{
    global Id cpeRecType = RecordTypeHelper.GetRecordTypeId('Candidate_Requirement__c','CPE');
    global Id attestRecType = RecordTypeHelper.GetRecordTypeId('Candidate_Requirement__c','Attest');
    global Database.QueryLocator start(Database.BatchableContext BC){
        String today = date.today().format();
        return Database.getQueryLocator('select id,Approved_Credits__c,Status__c,recordTypeId,Candidate_Commitment__c from Candidate_Requirement__c where Candidate_Commitment__r.EndDate <= today and (recordTypeId =: cpeRecType or recordTypeId =: attestRecType)');
     }
    
    
    global void execute(Database.BatchableContext BC, List<Candidate_Requirement__c> scope){

        Set<Id> setIds = new Set<Id>();
        for(Candidate_Requirement__c obj : scope)
        {
            if(obj.recordTypeId == cpeRecType && obj.Approved_Credits__c >= 40)
            {
                setIds.add(obj.Candidate_Commitment__c);
            }
        }

        List<Candidate_Requirement__c> lstCR = new List<Candidate_Requirement__c>();
        for(Candidate_Requirement__c objCR : [select id,Status__c from Candidate_Requirement__c where recordTypeId =: attestRecType and Status__c =: 'Initial'])
        {
            objCR.Status__c = 'Completed';
            lstCR.add(objCR);
        }

        if(lstCR.size() > 0)
            update lstCR;
    
    
    
    }
        

        
    
   
    global void finish(Database.BatchableContext BC){
         
       
    }

}