GARPDev-salesforce/eclipse/GARPDev/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>GARP_ID__c</fullName>
        <externalId>true</externalId>
        <label>GARP ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Middle_Initial__c</fullName>
        <label>Middle Initial</label>
        <length>2</length>
        <type>Text</type>
    </fields>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam__c.object
<CustomObject>
    <fields>
        <fullName>Exam__c</fullName>
        <label>Exam</label>
        <picklist>
            <picklistValues>
                <fullName>FRM Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FRM Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ERP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam_Attempt__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Site__c</fullName>
        <label>Exam Site</label>
        <referenceTo>Exam_Sites__c</referenceTo>
        <relationshipName>Exam_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Exam_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seat_No__c</fullName>
        <label>Seat No:</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <formula>Exam_Site__r.Site__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site</label>
        <type>Text</type>
    </fields>
    <label>Exam Registrations</label>
    <nameField>
        <label>Candidate Exam Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Exam_Sites__c.object
<CustomObject>
    <fields>
        <fullName>Exam__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exam</label>
        <referenceTo>Exam__c</referenceTo>
        <relationshipName>Exam_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Exam Sites</relationshipLabel>
        <relationshipName>Exam_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exam Sites</label>
    <nameField>
        <label>Exam Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Site__c.object
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/code/codepkg/classes/siteSeatChart.cls
public class siteSeatChart {
   
    private final Site__c site;
    public string header{get;set;}
    public List<wrapper> lstwrapper {get; set;}
    public class wrapper{
        public string SFid {get; set;}
        public string GARPid {get; set;}
        public string FirstName {get; set;}
        public string MiddleInitial {get; set;}
        public string LastName {get; set;}
        public string Exam {get; set;}
        public string Section {get; set;}
        public string Seat {get; set;}
    }
   
    public string Filetype{get;set;}
    public boolean isExcel {get;set;}
    public boolean isCsv {get;set;}   
 
    public siteSeatChart(ApexPages.StandardController stdcontroller){
            this.site = (Site__c)stdController.getRecord();
            Filetype = '';
            lstwrapper = new List<wrapper>();
            header = 'SFid,GARP ID,First Name, Middle Initial, Last Name, Exam, Section, Seat';    //  \r\n   
                          
    }
 
   
    public void getEAList(){
          // Get the ExamSiteIDs associated with this site
          set<id> examSiteIDs = new set<id>  () ;
          for ( Exam_Sites__c s : [ SELECT id FROM Exam_Sites__c WHERE Site__c = : site.id ] ) examSiteIDs.add(s.id) ; 
          system.debug('examSiteIDs :'+examSiteIDs);
          // Get the EA's for this site
          list<Exam_Attempt__c> EAs2Send = [ 
            SELECT id, member__r.firstName, member__r.Middle_Initial__c, member__r.lastName, member__r.GARP_ID__c,
            exam_site__r.exam__r.name, Seating_Section__c, Seat_No__c  
            FROM Exam_Attempt__c 
            WHERE Exam_Site__c IN :examSiteIDs
            ORDER BY exam_site__r.exam__r.name, member__r.lastName,  member__r.firstName ASC 
            LIMIT 3000 ] ;
          system.debug('EAs2Send :'+EAs2Send);
          if(EAs2Send.size()>0){
              for(Exam_Attempt__c eaItem : EAs2Send ){
                  wrapper w = new wrapper();
                  w.SFid = eaItem.id ;
                  w.GARPid = eaItem.member__r.GARP_ID__c ;
                  w.FirstName = eaItem.member__r.firstName ;
                  w.MiddleInitial = eaItem.member__r.Middle_Initial__c ;
                  w.LastName = eaItem.member__r.lastName ;
                  w.Exam = eaItem.exam_site__r.exam__r.name ;
                  w.Section = eaItem.Seating_Section__c ;
                  w.seat = eaItem.Seat_No__c ;
                  lstwrapper.add(w);               
              }             
          }
          system.debug('lstwrapper :'+lstwrapper.size());
    }
 
public string getJSONExport() {
    
    String str = JSON.serialize(lstwrapper); 
    return str ;
  }     
 
}