GARPDev-salesforce/eclipse/GARPDev/src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Alias__c</fullName>
        <description>This is the alias for a milestone.</description>
        <inlineHelpText>An alias helps you associate a task to a milestone using the single line entry home page component.</inlineHelpText>
        <label>Milestone Alias</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>A general description of the milestone.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Milestone1_Task__c.object
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>The general description of the task. For example, what is the purpose of the task.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project_Milestone__c</fullName>
        <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
        <label>Milestone</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GARPDev-salesforce/eclipse/GARPDev/src/objects/Task.object
<CustomObject>
</CustomObject>

jlamontSC-test/src/objects/Task.object
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>

GARPDev-salesforce/eclipse/GARPDev/src/classes/Milestone1_One_Line_Controller.cls
public with sharing class Milestone1_One_Line_Controller {
    
    public String line {get; set;}
    public Milestone1_Task__c task {get;set;}
    public Milestone1_One_Line_Controller()
    {
        task = null;
    }
    
    public void executeLine()
    {
        task = null;
        List<String> stringTokens = line.split('---',2);
        if(stringTokens.size() == 2)
        {
            String milestoneAlias = stringTokens.get(0).trim();
            Milestone1_Milestone__c milestone = getMilestoneByAlias(milestoneAlias);
            if(milestone != null)
            {
                try
                {
                    task = new Milestone1_Task__c();
                    String descriptionString = stringTokens.get(1).trim();
                    String nameString = stringTokens.get(1).trim();
                    nameString = Milestone1_General_Utility.processTaskName(nameString);
                    task.Name = nameString; 
                    if(descriptionString.length() >= 5000)
                    {
                        descriptionString = descriptionString.substring(0,4999);
                    }
                    task.Description__c = descriptionString;
                    task.Project_Milestone__c = milestone.Id;
                    insert task;
                    line = '';
                }catch(Exception e)
                {
                    ApexPages.Message errorMsg = new ApexPages.Message(ApexPages.Severity.FATAL, 'There was a Salesforce DML Error: ' + e.getMessage());
                    ApexPages.addMessage(errorMsg);
                }
            }else
            {
                ApexPages.Message errorMsg = new ApexPages.Message(ApexPages.Severity.FATAL, 'The alias( ' + milestoneAlias + ') did not match any milestone.');
                ApexPages.addMessage(errorMsg);
            }
        }else
        {
            ApexPages.Message errorMsg = new ApexPages.Message(ApexPages.Severity.FATAL, 'The line command was incorrect. Please use format <Alias> --- <DESCRIPTION>');
            ApexPages.addMessage(errorMsg);
        }   
    }
    

    
    private Milestone1_Milestone__c getMilestoneByAlias(String alias)
    {
        List<Milestone1_Milestone__c> milestones = [Select Id, Name, Alias__c from Milestone1_Milestone__c Where alias__c = :alias];
        //Milestones - Alias field is Unique, so we should only have one return value.
        if(milestones.size() > 0)
        {
            return milestones.get(0);
        }
        return null;
    }
    

}