JacksonRiver-salesforce/jra/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Legislator_Data_Status__c</fullName>
        <description>Has this record been processed by Jackson River Legislator Service?</description>
        <inlineHelpText>Has this record been processed by Jackson River Legislator Service?</inlineHelpText>
        <label>Legislator Data Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Processed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error in Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid ZipCode</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforcedotcom-salesforce/src/objects/Contact.object
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>

JacksonRiver-salesforce/jra/src/objects/JR_Advocacy_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Store general settings for JR Advocacy Package</description>
    <fields>
        <fullName>String_Value__c</fullName>
        <description>Store general parameter values</description>
        <inlineHelpText>Store general parameter values</inlineHelpText>
        <label>String Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>JRA Advocacy Settings</label>
</CustomObject>

JacksonRiver-salesforce/jra/src/classes/JRA_BatchAdvocacyUpdateScheduler.cls
global class JRA_BatchAdvocacyUpdateScheduler implements Schedulable {
/*
PNC June 2015
To enable legisaltor updates via batch, we provide a simple schedulable interface
Client can write their own version that calls the JRA Batch
Class can be scheduled via Dev Console using something like this:

JRA_BatchAdvocacyUpdateScheduler m = new JRA_BatchAdvocacyUpdateScheduler();
String sch = '00 15 * * * ?';
String jobID = system.schedule('Test Update Job', sch, m);
*/

global void execute(SchedulableContext sc) {
    //Set a default PostalCode Field
    String sZipCodeField = 'MailingPostalCode';

    //Get PostalCode Field from Custom Setting
    if (JR_Advocacy_Settings__c.getvalues('ZipCodeField') != NULL) {
    	if (String.IsEmpty(JR_Advocacy_Settings__c.getvalues('ZipCodeField').String_Value__c) == FALSE) {
        	sZipCodeField = JR_Advocacy_Settings__c.getvalues('ZipCodeField').String_Value__c;
    	}
	}
    
    //Invoke batch with basic query that includes all records marked ready to process
    String sQuery = 'Select Id, Legislator_Data_Status__c, ' + sZipCodeField + ' FROM CONTACT WHERE Legislator_Data_Status__c = \'Ready to Process\' ';
	JRA_BatchLegislatorUpdate jba = new JRA_BatchLegislatorUpdate();
	jba.sQuery = sQuery;
    //Scope is set at 25 to avoid callout limits
	database.executebatch(jba,25);

}


}