CodeScanDemo-Salesforce/src/objects/UnfollowRule__c.object
<CustomObject>
    <description>Create rules which are evaluated each night.  If any records match your rule criteria, all people following that rule will be unfollowed from that record.

For example: if you have a rule to unfollow cases 2 days after the status is set to Closed and a case with 2 followers closes today, 2 days from now both of those followers will be unfollowed from the case.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Only Active rules are evaluated each night.  This lets you create rules that you only want to run periodically, not every night.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DaysDelay__c</fullName>
        <defaultValue>0</defaultValue>
        <description>If a number is entered, the rule will not unfollow people from records that match the criteria that night, but rather will wait the specified number of days.  

The maximum delay possible is 99 days.</description>
        <label>Unfollow Delay in Days (optional)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>This is the field that will be evaluated such as Stage for an Opportunity rule.</description>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldType__c</fullName>
        <description>Stores Schema.DisplayType for the field selected to prevent running out of describes when building the batch Apex query from the rule criteria.  Type is needed to determine whether to use quotes or not (string fields need them, numbers don&apos;t).

Cannot be manually updated as the trigger will always overwrite (expected &amp; desirable behavior).</description>
        <label>Field Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <description>Name of the object such as Opportunity or Case.  This is the API name.</description>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>not equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>does not contain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>starts with</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>equals TODAY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Unfortunately this application does not support blank criteria such as Opportunity Account equals &lt;blank&gt;.  This is enforced in the code, not in a validation rule nor in the field definition itself.</description>
        <label>Unfollow Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Chatter Unfollow Rules</label>
    <nameField>
        <label>Chatter Unfollow Rule</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chatter Unfollow Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CodeScanDemo-Salesforce/src/classes/UnfollowRunThisRuleButtonController.cls
Global with sharing class UnfollowRunThisRuleButtonController{

    public Boolean RunRuleRendered {get;set;}
    public Boolean notRunRuleRendered {get;set;}
    public final UnfollowRule__c u;

    public UnfollowRunThisRuleButtonController(ApexPages.StandardController controller) {
        this.u=(UnfollowRule__c)controller.getRecord();
        renderRunRuleButton();
    }
    
    public void renderRunRuleButton(){
        RunRuleRendered = TRUE;
        if (u.DaysDelay__c!=null){
            if(u.DaysDelay__c>0){
                RunRuleRendered =FALSE;
            }//if 2
        }//if 1
        notRunRuleRendered =!RunRuleRendered ;
    }//renderRunRuleButton

    // Code we will invoke on button click.
    public void runThisNonDelayedRuleNow() {
        Integer numBatchApexJobsLimit=5;//at time of coding, there are at most 5 concurrent batch apex jobs in any org
        List<AsyncApexJob> numBatchJobs = [SELECT Id, Status FROM AsyncApexJob WHERE Status = 'Queued' OR Status = 'Processing'];
        //This is the number of jobs that can be queued up by this method
        Integer numJobsAvailable=numBatchApexJobsLimit - numBatchJobs.size();
      
        List<UnfollowRule__c> rules = [Select Id, ObjectName__c, Active__c, FieldName__c, FieldType__c, Operator__c, Value__c, DaysDelay__c FROM UnfollowRule__c WHERE ID = :u.Id];
        
        //First check if there's a slot available - max of 5 concurrent jobs across all apps
        Boolean addFieldNames=FALSE;            
        String query=unfollowExecute.buildQuery(rules[0].objectName__c, rules, addFieldNames);
        if(numJobsAvailable>0){
            UnfollowRecordsBatch  unfollowRecords= new UnfollowRecordsBatch();
            unfollowRecords.ObjectName=rules[0].objectName__c;
            unfollowRecords.numRulesUsedInThisObject=rules.size();
            unfollowRecords.sObjectQuery =  query;
//                system.debug('The sObjectQuery string is: '+unfollowRecords.sObjectQuery);
            unfollowRecords.sendEmail=TRUE;
            Id unfollowRulesProcessId = Database.executeBatch(unfollowRecords, 200); 
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.CONFIRM,'Unfollow scheduled to begin now.  This can take ~10-30 minutes for each 10,000 followers.  You will receive a confirmation email once completed.');
            ApexPages.addMessage(myMsg);
        }else{
            u.addError('There are already 5 batch jobs running for your org, so more cannot be added.  To view the queue, click Setup-->Monitoring-->Apex Jobs');
        }//if 1
    }//runThisNonDelayedRuleNow
}