robballen75-Salesforce/4-7-15/src/objects/Acct_Case_Custom_Rollup__c.object
<CustomObject>
    <description>Custom object used to store case and account related information for the generation of the DocXTools Healthcheck score. The data is used by rollup summary and formula fields on the Account object to calculate the Document Support Usage and Recency component scores. Only data for the most recent 12 months are used, so records are purged when they hit that timeframe.</description>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>The value is automatically populated via a trigger using the corresponding field value on the case record.</description>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>Admin / Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Knowledge Base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Support</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master-Child record to associated Case.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Account-Case Custom Rollup</relationshipLabel>
        <relationshipName>Account_Case_Custom_Rollup</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account-Case Custom Rollup</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Account-Case CRU ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account-Case Custom Rollup</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

vibhudadhichi-TicketReservation/src/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Case.object
    <fields>
        <fullName>Case_Type__c</fullName>
        <formula>IF(
Owner:Queue.Id = &quot;00G13000004Gmhq&quot; /* *SFDC Projects */, &quot;Project&quot;,
IF(
Emergency_Request__c = True &amp;&amp; Enhancement_Request__c = True, &quot;Emergency - Enhancement&quot;, 
IF(
Emergency_Request__c = True &amp;&amp;  Service_Support__c = True, &quot;Emergency - Support&quot;, 
IF(
Enhancement_Request__c = True &amp;&amp;  Owner:Queue.Id = &quot;00G30000002zgdH&quot; /* *SFDC Support* Enhancement Review */, &quot;Enhance - Sales Ops Review&quot;, 
IF(
Enhancement_Request__c = True &amp;&amp;  Owner:Queue.Id = &quot;00G30000002zgdM&quot; /* *SFDC Support* Ops Accepted Enhancements */, &quot;Enhance - CRM Team Review&quot;,
IF(
Enhancement_Request__c = True &amp;&amp;
OR(
Owner:User.Id = &quot;005a000000Ao61s&quot;,  /* Josh Goodling  */
Owner:User.Id = &quot;005a0000009lTTN&quot;,  /* Matt Santy */
Owner:User.Id = &quot;005300000060JMO&quot;,  /* Andrew Davidson  */
Owner:User.Id = &quot;005a000000ApZ4w&quot;,  /* Carmen Wong  */
Owner:User.Id = &quot;0051300000BALhj&quot;,  /* Prakash Srivastava  */
Owner:User.Id = &quot;005a0000009lhX4&quot;  /* Amit Madhoriya  */
), &quot;Enhance - Assigned&quot;, 
IF(
Service_Support__c = True &amp;&amp;  Owner:Queue.Id = &quot;00Ga0000003d8it&quot; /* *SFDC Support* Escalation Request */, &quot;Support - Unassigned&quot;,
IF(
Service_Support__c = True &amp;&amp;
OR(
Owner:User.Id = &quot;005a000000Ao61s&quot;,  /* Josh Goodling  */
Owner:User.Id = &quot;005a0000009lTTN&quot;,  /* Matt Santy */
Owner:User.Id = &quot;005300000060JMO&quot;,  /* Andrew Davidson  */
Owner:User.Id = &quot;005a000000ApZ4w&quot;,  /* Carmen Wong  */
Owner:User.Id = &quot;0051300000BALhj&quot;,  /* Prakash Srivastava  */
Owner:User.Id = &quot;005a0000009lhX4&quot;  /* Amit Madhoriya  */
), &quot;Support - Assigned&quot;, 
IF(
RecordType.Id = &quot;01230000001ElQa&quot;, &quot;Tier 1 Support&quot;, &quot;Unclassified&quot;
)))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Type</label>
        <type>Text</type>
    </fields>

robballen75-Salesforce/4-7-15/src/classes/Acct_Case_CRU_OnCase_TEST.cls
@isTest
// *********************************************************************************** 
// 
//  Acct_Case_CRU_OnCase_TEST
//  
//  Description:
//  Class for all of the unit tests associated with the 
//  Acct_Case_CRU_OnCase trigger.
//
//  Developed for Microsystems by InSitu Software LLC.
//
//  History:
//  RMN    01/10/2010    Original version
// ***********************************************************************************
private class Acct_Case_CRU_OnCase_TEST 
{
	// ----------------------------------------------------------
	// Test1 - Insert Processing, 1 Case
	// ----------------------------------------------------------
    static testMethod void Test1() 
    {
    	// Setup the Account
     	Account acctTest = new Account (Name = 'ACCRS Test Account 1');
     	insert acctTest;
     	
     	// Set up the Case
     	Case caseTest = new Case (AccountId = acctTest.Id,
     	                          Origin = 'Web',
     	                          Type = 'Document Support',
     	                          Subject = 'Test');
     	
     	insert caseTest;
     	
     	acct_case_custom_rollup__c resultAcctCase =  
     			[SELECT Id, Case_Type__c FROM acct_case_custom_rollup__c WHERE Case__r.Id = :caseTest.Id]; 
     			
     	System.assertEquals('Document Support', resultAcctCase.Case_Type__c);                         	   
    }
    
    // ----------------------------------------------------------
	// Test2 - Insert Processing, Multiple Cases
	// ----------------------------------------------------------
    static testMethod void Test2() 
    {
    	// Setup the Account
     	Account acctTest = new Account (Name = 'ACCRS Test Account 1');
     	insert acctTest;
     	
     	// Set up the Cases
     	List<Case> listTestCases = new List<Case>();
     	Case caseTest1 = new Case (AccountId = acctTest.Id,
     	                           Origin = 'Web',
     	                           Type = 'Document Support',
     	                           Subject = 'Test 1');
     	listTestCases.add(caseTest1);  
     	                         
     	Case caseTest2 = new Case (AccountId = acctTest.Id,
     	                           Origin = 'Web',
     	                           Type = 'Admin / Billing',
     	                           Subject = 'Test 2');
     	listTestCases.add(caseTest2);  
     	                         
     	Case caseTest3 = new Case (AccountId = acctTest.Id,
     	                           Origin = 'Web',
     	                           Type = 'Sales Support',
     	                           Subject = 'Test 3');
     	listTestCases.add(caseTest3);  
     	                                                    
     	
     	insert listTestCases;
     	
     	List<acct_case_custom_rollup__c> listTestAcctCaseResults = new List<acct_case_custom_rollup__c>( 
     			[SELECT Id, Case_Type__c FROM acct_case_custom_rollup__c WHERE Case__r.Id IN :listTestCases]); 
     			
     	System.assertEquals(3, listTestAcctCaseResults.size());                         	   
    }
    
    // ----------------------------------------------------------
	// Test3 - Update Processing, 1 Update, no impact
	// ----------------------------------------------------------
    static testMethod void Test3() 
    {
    	// Setup the Account
     	Account acctTest = new Account (Name = 'ACCRS Test Account 1');
     	insert acctTest;
     	
     	// Set up the Case
     	Case caseTest = new Case (AccountId = acctTest.Id,
     	                          Origin = 'Web',
     	                          Type = 'Document Support',
     	                          Subject = 'Test');
     	
     	insert caseTest;
     	
     	caseTest.Subject = 'Test Change';
     	
     	update caseTest;
     	
     	acct_case_custom_rollup__c resultAcctCase =  
     			[SELECT Id, Case_Type__c FROM acct_case_custom_rollup__c WHERE Case__r.Id = :caseTest.Id]; 
     			
     	System.assertEquals('Document Support', resultAcctCase.Case_Type__c);                         	   
    }
    
    // ----------------------------------------------------------
	// Test4 - Update Processing, Multiple Updates, someo impact
	// ----------------------------------------------------------
    static testMethod void Test4() 
    {
    	// Setup the Account
     	Account acctTest = new Account (Name = 'ACCRS Test Account 1');
     	insert acctTest;
     	
     	// Set up the Cases
     	List<Case> listTestCases = new List<Case>();
     	Case caseTest1 = new Case (AccountId = acctTest.Id,
     	                           Origin = 'Web',
     	                           Type = 'Document Support',
     	                           Subject = 'A');
     	listTestCases.add(caseTest1);  
     	                         
     	Case caseTest2 = new Case (AccountId = acctTest.Id,
     	                           Origin = 'Web',
     	                           Type = 'Admin / Billing',
     	                           Subject = 'B');
     	listTestCases.add(caseTest2);  
     	                         
     	Case caseTest3 = new Case (AccountId = acctTest.Id,
     	                           Origin = 'Web',
     	                           Type = 'Sales Support',
     	                           Subject = 'C');
     	listTestCases.add(caseTest3);  
     	                                                    
     	
     	insert listTestCases;
     	
     	listTestCases[0].Type = 'Product Support';
     	listTestCases[1].Origin = 'Phone';
     	listTestCases[2].Type = 'Knowledge Base';
     	
     	update listTestCases;
     	
     	
     	List<acct_case_custom_rollup__c> listTestAcctCaseResults = new List<acct_case_custom_rollup__c>( 
     			[SELECT Id, Case_Type__c FROM acct_case_custom_rollup__c WHERE Case__r.Id IN :listTestCases ORDER BY Case_Type__c]); 
     			
     	System.assertEquals(3, listTestAcctCaseResults.size());
     	System.assertEquals('Admin / Billing', listTestAcctCaseResults[0].Case_Type__c);
     	System.assertEquals('Knowledge Base', listTestAcctCaseResults[1].Case_Type__c); 
     	System.assertEquals('Product Support', listTestAcctCaseResults[2].Case_Type__c);                        	   
    }
    
    // ----------------------------------------------------------
	// Test5 - Case initially added with no Account
	// ----------------------------------------------------------
    static testMethod void Test5() 
    {
    	// Setup the Account
     	Account acctTest = new Account (Name = 'ACCRS Test Account 1');
     	insert acctTest;
     	
     	// Set up the Cases
     	List<Case> listTestCases = new List<Case>();
     	Case caseTest1 = new Case (Origin = 'Web',
     	                           Type = 'Document Support',
     	                           Subject = 'A');                                                  
     	
     	listTestCases.add(caseTest1);  
     	insert listTestCases;
     	     	
     	// Should not have been any record added.  
     	List<acct_case_custom_rollup__c> listTestAcctCaseResults1 = new List<acct_case_custom_rollup__c>( 
     			[SELECT Id, Case_Type__c FROM acct_case_custom_rollup__c WHERE Case__r.Id IN :listTestCases]); 
     			
        System.assertEquals (true, listTestAcctCaseResults1.isEmpty());
     	
     	listTestCases[0].Type = 'Product Support';     	
     	update listTestCases;
     	
     	// Should not have attempted to update the record because the Account ID is still null.
     	// No need to test as an exception would be thrown if we did try.
     	
     	// Now add an account
     	listTestCases[0].AccountId = acctTest.Id;     	
     	update listTestCases;
     	
     	List<acct_case_custom_rollup__c> listTestAcctCaseResults2 = new List<acct_case_custom_rollup__c>( 
     			[SELECT Id, Case_Type__c FROM acct_case_custom_rollup__c WHERE Case__r.Id IN :listTestCases ORDER BY Case_Type__c]); 
     			
     	System.assertEquals(1, listTestAcctCaseResults2.size());
     	                 	   
    }
    
    // ----------------------------------------------------------
	// Test6 - Case initially added with no Type
	// ----------------------------------------------------------
    static testMethod void Test6() 
    {
    	// Setup the Account
     	Account acctTest = new Account (Name = 'ACCRS Test Account 1');
     	insert acctTest;
     	
     	// Set up the Cases
     	List<Case> listTestCases = new List<Case>();
     	Case caseTest1 = new Case (AccountId = acctTest.Id,
     							   Origin = 'Web',
     	                           Subject = 'A');                                                  
     	
     	listTestCases.add(caseTest1);  
     	insert listTestCases;
     	     	
     	// Should still create the CRU record
     	List<acct_case_custom_rollup__c> listTestAcctCaseResults1 = new List<acct_case_custom_rollup__c>( 
     			[SELECT Id, Case_Type__c FROM acct_case_custom_rollup__c WHERE Case__r.Id IN :listTestCases]); 
     			
        System.assertEquals(1, listTestAcctCaseResults1.size());
     	
     	listTestCases[0].Type = 'Product Support';     	
     	update listTestCases;
     	
     	// Type should have been updated.
     	List<acct_case_custom_rollup__c> listTestAcctCaseResults2 = new List<acct_case_custom_rollup__c>( 
     			[SELECT Id, Case_Type__c FROM acct_case_custom_rollup__c WHERE Case__r.Id IN :listTestCases ORDER BY Case_Type__c]); 
     			
     	System.assertEquals('Product Support', listTestAcctCaseResults2[0].Case_Type__c);
     	                 	   
    }
    
   
}