robballen75-Salesforce/4-7-15/src/objects/Acct_Campaign_Custom_Rollup__c.object
<CustomObject>
    <description>Custom object used to store campaign and account related information for the generation of the DocXTools Healthcheck score. The data is used by rollup summary and formula fields on the Account object to calculate the number of open enrollment training hours for campaigns that meet a specific criteria. Only data for the most recent 12 months are used, so records are purged when they hit that timeframe.</description>
    <fields>
        <fullName>Purge_Date__c</fullName>
        <description>Formula field used by the KP Health check scoring system. The value represents the date on which the data in the record is no longer relevant and should be purged.</description>
        <formula>Campaign_Start_Date__c + 365</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Purge Date</label>
        <type>Date</type>
    </fields>
    <label>Account-Campaign Custom Rollup</label>
    <nameField>
        <displayFormat>AC-{00000}</displayFormat>
        <label>Account-Campaign CRU ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account-Campaign Custom Rollups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

robballen75-Salesforce/4-7-15/src/objects/Acct_Case_Custom_Rollup__c.object
<CustomObject>
    <description>Custom object used to store case and account related information for the generation of the DocXTools Healthcheck score. The data is used by rollup summary and formula fields on the Account object to calculate the Document Support Usage and Recency component scores. Only data for the most recent 12 months are used, so records are purged when they hit that timeframe.</description>
    <fields>
        <fullName>Purge_Date__c</fullName>
        <description>Formula field used by the KP Health check scoring system. The value represents the date on which the data in the record is no longer relevant and should be purged.</description>
        <formula>Case_Open_Date__c +365</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Purge Date</label>
        <type>Date</type>
    </fields>
    <label>Account-Case Custom Rollup</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Account-Case CRU ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account-Case Custom Rollup</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

robballen75-Salesforce/4-7-15/src/objects/Acct_Proj_Custom_Rollup__c.object
<CustomObject>
    <description>Custom object used to store project and account related information for the generation of the DocXTools Healthcheck score. The data is used by rollup summary and formula fields on the Account object to calculate the number of total training/consulting hours for projects that meet a specific criteria. Only data for the most recent 12 months are used, so records are purged when they hit that timeframe.</description>
    <fields>
        <fullName>Purge_Date__c</fullName>
        <description>Formula field used by the KP Health check scoring system. The value represents the date on which the data in the record is no longer relevant and should be purged.</description>
        <formula>Project_Start_Date__c + 365</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Purge Date</label>
        <type>Date</type>
    </fields>
    <label>Account-Project Custom Rollup</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Account-Project CRU ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account-Project Custom Rollup</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

robballen75-Salesforce/4-7-15/src/classes/KP_HealthCheck_Util.cls
//*********************************************************************************** 
// 
//  KP_HealthCheck_Util
//   
//  Description:
//  This class contains utility methods used to perform calculation and record updates
//  for the Knowledge Partnership Healthcheck scoring system.
//
//  This class was developed for Microsystems by InSitu Software LLC.
//   
//  History:
//  InSitu  01/10/2010  Original version
// ***********************************************************************************

public with sharing class KP_HealthCheck_Util 
{
    // -----------------------------------------------------
    //  Custom KP Healthcheck Exception class
    // -----------------------------------------------------
    public class KPHC_Exception extends Exception {}

    ///////////////////////////////////////////////////
    //  Constants
    ///////////////////////////////////////////////////
    
    ///////////////////////////////////////////////////
    //  Member variables
    ///////////////////////////////////////////////////


    ///////////////////////////////////////////////////
    //  Methods
    ///////////////////////////////////////////////////


	// --------------------------------------------------------
    //  runKPHealthCheckMaintenance
    //
    //  Performs the following KP Health Check Maintenance routines: 
    //  1.	Creates custom rollup records to support the DocXTools Training/Consulting time calculation.
    //  2.	Purges outdated Account-Case custom rollup records. 
    //  3.	Purges outdated Account-Campaign custom rollup records. 
    // --------------------------------------------------------
    public static void runKPHealthCheckMaintenance() 
    {
        try
        {
            // Purge outdated Account-Case custom rollup records.
            purgeAccountCase();

            // Purge outdated Account-Campaign custom rollup records.
            purgeAccountCampaign();

            // Run the routine to create custom rollup records to support the DocXTools Training /Consulting time calculation.
            runDocXToolsTrainConsultTimeCRU();

            // Run the routine to calculate project exception status.
            runProjectExceptionCalc();
        }
        catch (Exception e) 
        {
            // Something happened with the query or processing the query results.   
            throw new KPHC_Exception('The following error occurred while executing the KP Health Check Maintenance routine - ' + e.getMessage());
        }       
    }

	// -----------------------------------------------------------
	// Purge the Account-Case Rollup Summary records
	// -----------------------------------------------------------
	public static void purgeAccountCase()
	{
	    try
		{
		    // Fill a collection of Account-Case records that need to be purged
		    for (acct_case_custom_rollup__c[] listAcctCaseToPurge : [SELECT Id FROM acct_case_custom_rollup__c WHERE Purge_Date__c < :System.Today()])
		    {
			    // Delete all records that matched the criteria. 
		        delete listAcctCaseToPurge;
		    }
	    }
        catch(Exception e)  
        {
            // Something happened with the query or processing the query results.   
            throw new KPHC_Exception('Account-Case Custom Rollup Purge: ' + e.getMessage());
        } 
	}

	// -----------------------------------------------------------
	// Purge the Account-Campaign Rollup Summary records
	// -----------------------------------------------------------
	public static void purgeAccountCampaign()
	{
	    try
		{
		    // Fill a collection of Account-Campaign records that need to be purged
		    for (acct_campaign_custom_rollup__c[] listAcctCampaignToPurge : [SELECT Id FROM acct_campaign_custom_rollup__c WHERE Purge_Date__c < :System.Today()])
		    {
			    // Delete all records that matched the criteria. 
		        delete listAcctCampaignToPurge;
		    }
	    }
        catch(Exception e)  
        {
            // Something happened with the query or processing the query results.   
            throw new KPHC_Exception('Account-Campaign Custom Rollup Purge: ' + e.getMessage());
        }
	}


	// -----------------------------------------------------------
    // Create custom rollup records to support the DocXTools Training/Consulting time calculation. 
	// -----------------------------------------------------------
    public static void runDocXToolsTrainConsultTimeCRU() 
    {
		try
		{
	    	// Delete all existing acct_proj_custom_rollup__c records.
			for (acct_proj_custom_rollup__c[] listAcctProjCRU : [SELECT ID from acct_proj_custom_rollup__c])
			{
				delete listAcctProjCRU;
			}

			// The calculation is going to be done in batch. Create an instance of the Apex Batch class and
			// initiate the batch processing.
			KPBatch_DocXtoolsTrainConsultCRU batchDocXtoolsCRU = new KPBatch_DocXtoolsTrainConsultCRU();
		 	Id idJob = database.executeBatch(batchDocXtoolsCRU, 200);
	
        }
        catch(Exception e)  
        {
            // Something happened with the query or processing the query results.   
            throw new KPHC_Exception('DocXtools Training/Consulting Total Project Time: ' + e.getMessage());
        }
    }

	// -----------------------------------------------------------
    // Processes Project records to determine which ones are in an 'exception' state - meaning
    // that something is potentially not going as expected. For those found in the exception state,
    // a project exception status is set. On a regularly scheduled basis, reports are generated using this
    // information to alert key personnel of the situation. 
	// -----------------------------------------------------------
    public static void runProjectExceptionCalc() 
    {
		try
		{
			// The calculation is going to be done in batch. Create an instance of the Apex Batch class and
			// initiate the batch processing.
			Batch_ProjectExceptionCalc batchProjectExceptionCalc = new Batch_ProjectExceptionCalc();
		 	Id idJob = database.executeBatch(batchProjectExceptionCalc, 200);
	
        }
        catch(Exception e)  
        {
            // Something happened with the query or processing the query results.   
            throw new KPHC_Exception('Project Exception Status Calc: ' + e.getMessage());
        }
    }


    
}