robballen75-Salesforce/4-7-15/src/objects/MS_Project__c.object
<CustomObject>
    <fields>
        <fullName>Proj_Hrs_Logged_BILLABLE_Not_Chargeable__c</fullName>
        <description>Work that should be billable that isn&apos;t.  It could be due to customer sensitivity, overruns, etc.  It does not include issues such as product problems, planning errors, etc.</description>
        <label>Hrs Logged-BILLABLE (Not Chargeable)</label>
        <summarizedField>MS_Time_Entry__c.TE_Billable_Not_Chargeable__c</summarizedField>
        <summaryForeignKey>MS_Time_Entry__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Hours_Logged_f__c</fullName>
        <inlineHelpText>Calculated roll-up of all time entry hours for this project.</inlineHelpText>
        <label>Hrs  Logged - BILLABLE</label>
        <summarizedField>MS_Time_Entry__c.Time_Entry_Hours__c</summarizedField>
        <summaryForeignKey>MS_Time_Entry__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project_Hours__c</fullName>
        <description>This is the number of hours specified in the SOW.  If there is no SOW, this is the number of hours agreed upon to be done for the client/prospect.</description>
        <inlineHelpText>Enter hours included for this project.</inlineHelpText>
        <label>Project Hours (Approved or in SOW)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending CR Followup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Complete - Pending Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Upgrade Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>project_exception_status__c</fullName>
        <description>Read-only field used by the Project Exception Alert report.The value is set by an automated process and is assigned using criteria that determines if the project is Overdue, Over budget or stalled.</description>
        <label>Project Exception Status</label>
        <picklist>
            <picklistValues>
                <fullName>Overdue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>project_exception_status_last_update__c</fullName>
        <description>Read-only field used by the Project Exception Alert report.The value is set by an automated process and is assigned using criteria that determines if the project is Overdue, Over budget or stalled.</description>
        <label>Project Exception Status Last Update</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

robballen75-Salesforce/4-7-15/src/classes/Batch_ProjectExceptionCalc.cls
//*********************************************************************************** 
// 
//  Batch_ProjectExceptionCalc
//   
//  Description:
//  This class implements the Database.Batchable interface and is used to 
//  calculate the project exception status for active projects (those whose status is
//  not Closed or Cancelled). 
//
//  The project exception status is set to one of the three values if the associated condition is met:
//	1.	Overdue - If the Project End Date has been met or exceeded.
//	2.	Over Budget - If the Project Hours Logged - Billable plus Project Hours Logged - NonBillable is equal or greater than Project Hours.
//  3.	Stalled - if the project status is set to 'Hold' or 'Stalled'
//
//  This class was developed for Microsystems by InSitu Software LLC.
//   
//  History:
//  InSitu     01/13/2010    Original version
//
// ***********************************************************************************
global with sharing class Batch_ProjectExceptionCalc implements Database.Batchable<sObject>
{
    ///////////////////////////////////////////////////
    //  Constants
    ///////////////////////////////////////////////////
    
    public static final String EXCEPTION_STATUS_OVERDUE = 'Overdue';
    public static final String EXCEPTION_STATUS_OVERBUDGET = 'Over Budget';
    public static final String EXCEPTION_STATUS_STALLED = 'Stalled';    
    
    ///////////////////////////////////////////////////
    //  Member variables
    ///////////////////////////////////////////////////
	global Set<String> setIncludeProjectStatus = new Set<String>();
	global Set<String> setExcludeProjectStatus = new Set<String>();


    ///////////////////////////////////////////////////
    //  Methods
    ///////////////////////////////////////////////////

    // Constructor
    global Batch_ProjectExceptionCalc()
    {
    	// Begin - the following section defines values used in the criteria to determine
        // the projects for which the exception calculations should be run. 
        
        // Project Status - to INCLUDE
        setIncludeProjectStatus.add('Hold');
        setIncludeProjectStatus.add('Stalled');
        
        // Project Status values - to EXCLUDE
        setExcludeProjectStatus.add('Cancelled');
        setExcludeProjectStatus.add('Closed');
        
    	// End -- Project Exception Criteria values.
    }

    global Database.QueryLocator start(Database.BatchableContext BC)
    {

		// Create the query to find all Project records that meet at least one of three criteria
		// that places them in the possible 'exception' category.
		
		// Number of days
    	Date dateToday = Date.today();
				
		return Database.getQueryLocator([SELECT ID, name, project_status__c, project_end_date__c, project_exception_status__c,
										 project_hours__c, project_hours_logged_f__c, proj_hrs_logged_billable_not_chargeable__c
		                                 FROM ms_project__c
		                                 WHERE project_status__c NOT in :setExcludeProjectStatus AND (not name like '%microsystems%') and
		                                 	   (project_end_date__c < :dateToday OR
		                                        project_status__c in :setIncludeProjectStatus OR
		                                        project_hours_logged_f__c > 0 OR
		                                        proj_hrs_logged_billable_not_chargeable__c > 0)]);
    }

	// --------------------------------------------------------
    //  execute
    //
    //  This method is called by the Batch Apex controller. Sets of records are
    //  sent in to be processed in 'batch'. Like a bulkified trigger, this method
    //  processes and updates the items in collections to limit the number 
    //  of DML statements issued. Got to mind those governor limits! 
    // --------------------------------------------------------

    global void execute(Database.BatchableContext BC, sObject[] listProjects)
    {
        // Iterate the projects and determine which projects should have their exception status set.
        List<ms_project__c> listProjectsToUpdate = new List<ms_project__c>();
        for (sObject projObj : listProjects)
        {
            String sStatus = null;
            ms_project__c proj = (ms_project__c)projObj;

            if (proj.project_end_date__c < Date.today())
            {
            	// If project exception status is not already set to Overdue, set the status.
            	if (proj.project_exception_status__c != EXCEPTION_STATUS_OVERDUE)
            		sStatus = EXCEPTION_STATUS_OVERDUE;
            }
            else if (proj.project_hours_logged_f__c + proj.proj_hrs_logged_billable_not_chargeable__c > proj.project_hours__c)
            {
            	// If project exception status is not already set to Over budget, then set the status
            	if (proj.project_exception_status__c != EXCEPTION_STATUS_OVERBUDGET)
            		sStatus = EXCEPTION_STATUS_OVERBUDGET;
            }
            else if (setIncludeProjectStatus.contains(proj.project_status__c))
            {
            	// If project exception status is not already set to Stalled, then set the status
            	if (proj.project_exception_status__c != EXCEPTION_STATUS_STALLED)
	            		sStatus = EXCEPTION_STATUS_STALLED;
            }
 
            // Determine if the exception status needs to be set for the project
            if (sStatus != null)
            {
            	ms_project__c projUpdate = proj;
            	projUpdate.project_exception_status__c = sStatus;
            	projUpdate.project_exception_status_last_update__c = Date.today();
            	
            	listProjectsToUpdate.add(projUpdate);
            }
        }   
        if (listProjectsToUpdate.size() > 0)
        {
            system.debug('Updating Project record count: ' + listProjectsToUpdate.size());
            update listProjectsToUpdate;
        }
    }
    
	// --------------------------------------------------------
    //  finish
    //
    //  This method is called by the Batch Apex controller when an error is
    //  encountered during the execution of the Batch Apex Batch. If this should
    //  happen, a notification email is sent out. 
    // --------------------------------------------------------

    global void finish(Database.BatchableContext BC)
    {
    	// Get the ID of the AsyncApexJob representing this batch job from Database.BatchableContext.
		// Query the AsyncApexJob object to retrieve the current job's information.
		ID idJob = BC.getJobId();
		AsyncApexJob apexjobCRU =  [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
						  			FROM AsyncApexJob WHERE Id = :idJob];

		// Because of test coverage issues in this class, need to create the 'failure' email message and only
		// send if there is truly a failure.
		// I can't seem to find a way to fail the job from a test.
		Messaging.SingleEmailMessage emailNotify = new Messaging.SingleEmailMessage();
		String[] toAddresses = new String[] {apexjobCRU.CreatedBy.Email};
		emailNotify.setToAddresses(toAddresses);
		emailNotify.setSubject('Project Exception Status Calculation - Completed with Errors');
		emailNotify.setPlainTextBody(
			'The Project Exception Status Calculation completed, however the job reported ' + apexjobCRU.NumberOfErrors + 
			' errors. If the calculation continues to fail, contact your system administrator or InSitu Software support.');
			
		// if the job did not complete successfully, then send an email to the job's submitter letting them know that there was a problem.
		if (apexjobCRU.Status == 'Failed')
		{
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { emailNotify });
		}
    	
    }   
}