Up2Go-travelexpenses/src/objects/CompensationRate__c.object
<CustomObject>
    <description>Various rates to reimburse dependant expense types e.g. travels with private vehicles etc.</description>
    <fields>
        <fullName>cur_FullDailyRate__c</fullName>
        <label>Full Daily Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>pct_FullDayAllowanceRate__c</fullName>
        <inlineHelpText>For more than 8 hours absence.</inlineHelpText>
        <label>Full Day Allowance Rate</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Compensation Rate</label>
    <nameField>
        <label>Compensation Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compensation Rates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Up2Go-travelexpenses/src/objects/Expense__c.object
<CustomObject>
    <description>Contains informations about the expenses.</description>
    <fields>
        <fullName>cur_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Overall cost of the expense.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>cur_OriginalAmount__c</fullName>
        <label>Original Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>dat_CheckInDate__c</fullName>
        <label>Check In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dat_CheckOutDate__c</fullName>
        <label>Check Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dat_ExpenseDate__c</fullName>
        <description>To assign a Expense to a specific travel date.</description>
        <label>Expense Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dtm_ArrivalTime__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_DepartureTime__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_End__c</fullName>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>lkp_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a location.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_MealInvitation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meal Invitation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MealInvitation__c.mdr_Travel__c</field>
                <operation>equals</operation>
                <valueField>$Source.mdr_Travel__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MealInvitation__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_ReturnTrip__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Return Trip</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>mdr_Travel__c</fullName>
        <label>Travel</label>
        <referenceTo>Travel__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>pkl_Reimbursement__c</fullName>
        <label>Reimbursement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>I paid for this, please reimburse me.</fullName>
                </value>
                <value>
                    <fullName>The company paid for this.</fullName>
                </value>
                <value>
                    <fullName>The customer paid for this.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Expense #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Up2Go-travelexpenses/src/objects/MealInvitation__c.object
<CustomObject>
    <fields>
        <fullName>lkp_Breakfast__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Breakfast</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a Meal.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Meal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Meal Invitations</relationshipLabel>
        <relationshipName>Meal_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_Dinner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Dinner</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a meal.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Meal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Meal Invitations (Dinner)</relationshipLabel>
        <relationshipName>Meal_Invitations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_Lunch__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Lunch</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a meal.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Meal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Meal Invitations (Lunch)</relationshipLabel>
        <relationshipName>Meal_Invitations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>mdr_Travel__c</fullName>
        <label>Travel</label>
        <referenceTo>Travel__c</referenceTo>
        <relationshipLabel>Meal Invitations</relationshipLabel>
        <relationshipName>MealInvitations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Meal Invitation</label>
    <nameField>
        <displayFormat>MI-{0000}</displayFormat>
        <label>Meal Invitation #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meal Invitations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Up2Go-travelexpenses/src/objects/Travel__c.object
<CustomObject>
    <description>Records of business travels.</description>
    <fields>
        <fullName>dtm_End__c</fullName>
        <label>End</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Travel</label>
    <nameField>
        <label>Travel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Up2Go-travelexpenses/src/classes/DailySummaries_Test.cls
@isTest
public with sharing class DailySummaries_Test {
	
	private static final Date FIRST_DAY = System.Today();
	private static final Date SECOND_DAY = FIRST_DAY.addDays(1);
	private static final Date THIRD_DAY = FIRST_DAY.addDays(2);
	
	private static final DateTime TRAVEL_START = dateTime(FIRST_DAY, 8);
	private static final DateTime TRAVEL_STOP = dateTime(THIRD_DAY, 20);
	
	static {
		CustomSettings.addDefault();
	}
	
	
	@isTest
	private static void generatesNoRowsForEmptyTravel() {
		
		// Setup
		Exception unexpectedException;
		String message = '';
		
		List<Expense__c> sortedExpenses = new List<Expense__c>();
		
		List<DailySummaries.Row> generatedRows;
		
		
		// Exercise
		try {
			generatedRows = new DailySummaries(sortedExpenses).getRows();
		}
		catch(Exception e) {
			unexpectedException = e;
			message = e.getStackTraceString();
		}
		
		
		// Verify
		System.assertEquals(null,unexpectedException, message);
		System.assertEquals(0, generatedRows.size());
	}
	
	
	@isTest
	private static void generateNoAdditionalElementsForTravelWithoutDeduction() {
		
		// Setup
		Exception unexpectedException;
		String message = '';
		
		Travel__c travel = createTravelWithoutDeduction();
		List<Expense__c> sortedExpenses = getTravel(travel.Id).Expenses__r;
		
		List<DailySummaries.Row> generatedRows;
		
		
		// Exercise
		try {
			generatedRows = new DailySummaries(sortedExpenses).getRows();
		}
		catch(Exception e) {
			unexpectedException = e;
			message = e.getStackTraceString();
		}
		
		
		// Verify
		Integer expectedElements = sortedExpenses.size();		
		Integer generatedElements = countRowElements(generatedRows);
		
		System.assertEquals(null,unexpectedException, message);
		System.assertEquals(expectedElements,generatedElements);
	}
	
	
	@isTest
	private static void generatesInfoElementsForEachMealInvitation() {
		
		// Setup
		Exception unexpectedException;
		String message = '';
		
		Travel__c travel = createTravelWithDeduction();
		List<Expense__c> sortedExpenses = getTravel(travel.Id).Expenses__r;
		
		List<DailySummaries.Row> generatedRows;
		
		
		// Exercise
		try {
			generatedRows = new DailySummaries(sortedExpenses).getRows();
		}
		catch(Exception e) {
			unexpectedException = e;
			message = e.getStackTraceString();
		}
		
		
		// Verify
		Integer expectedElements = 9 + sortedExpenses.size();		
		Integer generatedElements = countRowElements(generatedRows);
		
		System.assertEquals(null,unexpectedException, message);
		System.assertEquals(expectedElements,generatedElements);
	}
	
	
	// TESTHELPER
	
	private static Travel__c createTravelWithoutDeduction() {
		DateTime departure = dateTime(FIRST_DAY,8);
		DateTime arrival = dateTime(FIRST_DAY, 16);
		DateTime returnDeparture = dateTime(THIRD_DAY, 12);
		DateTime returnArrival = dateTime(THIRD_DAY, 20);
		
		Travel__c result = new TravelBuilder(TRAVEL_START,TRAVEL_STOP)
							   .addRoundFlight(departure, arrival, returnDeparture, returnArrival)
							   .addDefaultAccommodation(FIRST_DAY, THIRD_DAY)
							   .create();
							   
		return result;
	}
	
	
	private static Travel__c createTravelWithDeduction() {
		DateTime departure = dateTime(FIRST_DAY,8);
		DateTime arrival = dateTime(FIRST_DAY, 16);
		DateTime returnDeparture = dateTime(THIRD_DAY, 12);
		DateTime returnArrival = dateTime(THIRD_DAY, 20);
		
		Travel__c result = new TravelBuilder(TRAVEL_START,TRAVEL_STOP)
							   .addRoundFlight(departure, arrival, returnDeparture, returnArrival)
							   .addDefaultAccommodation(FIRST_DAY, THIRD_DAY)
							   .addMealInvitation(FIRST_DAY, false, false, true)
							   .addMealInvitation(SECOND_DAY,true,true,true)
							   .addMealInvitation(THIRD_DAY,true,true,false)
							   .create();
							   
		return result;
	}
	
	
	private static Travel__c getTravel(Id travel) {
		Travel__c result = [SELECT Id, dtm_Start__c, dtm_End__c,
	   							  (SELECT Id, Name, RecordType.Name, cur_Amount__c, dtm_DepartureTime__c, 
				                          dtm_ArrivalTime__c, dat_CheckInDate__c, dat_CheckOutDate__c, 
				                          lkp_Location__c, CurrencyIsoCode, dat_ExpenseDate__c, mdr_Travel__c, 
				                          pkl_Reimbursement__c,cur_OriginalAmount__c,
				                          lkp_Location__r.cur_FullDailyRate__c,
				                          lkp_MealInvitation__r.lkp_Breakfast__c, lkp_MealInvitation__r.lkp_Breakfast__r.pct_FullDayAllowanceRate__c,
				                          lkp_MealInvitation__r.lkp_Lunch__c, lkp_MealInvitation__r.lkp_Lunch__r.pct_FullDayAllowanceRate__c,
				                 		  lkp_MealInvitation__r.lkp_Dinner__c, lkp_MealInvitation__r.lkp_Dinner__r.pct_FullDayAllowanceRate__c
                   				   FROM Expenses__r
                   				   ORDER BY dat_ExpenseDate__c ASC, dtm_DepartureTime__c ASC, RecordType.Name ASC)
	   					   FROM Travel__c
	   					   WHERE Id = :travel];
   					   
   		return result;
	}	
	
	private static Integer countRowElements(List<DailySummaries.Row> generatedRows) {
		Integer result = 0;
		
		for(DailySummaries.Row r : generatedRows) {
			result += r.expenses.size();
		}
		
		return result;
	}
	
	
	private static DateTime dateTime(Date day, Integer hour) {
		Time t = Time.newInstance(hour,00,00,00);
		
		DateTime result = DateTime.newInstance(day,t);
		
		return result;
	}
}