Up2Go-travelexpenses/src/objects/CompensationRate__c.object
<CustomObject>
    <description>Various rates to reimburse dependant expense types e.g. travels with private vehicles etc.</description>
    <label>Compensation Rate</label>
    <nameField>
        <label>Compensation Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compensation Rates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Up2Go-travelexpenses/src/objects/MealInvitation__c.object
<CustomObject>
    <fields>
        <fullName>chk_Breakfast__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Breakfast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>chk_Dinner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dinner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>chk_Lunch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lunch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>lkp_Breakfast__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Breakfast</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a Meal.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Meal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Meal Invitations</relationshipLabel>
        <relationshipName>Meal_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_Dinner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Dinner</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a meal.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Meal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Meal Invitations (Dinner)</relationshipLabel>
        <relationshipName>Meal_Invitations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_Lunch__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Lunch</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a meal.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Meal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Meal Invitations (Lunch)</relationshipLabel>
        <relationshipName>Meal_Invitations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>mdr_Travel__c</fullName>
        <label>Travel</label>
        <referenceTo>Travel__c</referenceTo>
        <relationshipLabel>Meal Invitations</relationshipLabel>
        <relationshipName>MealInvitations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Meal Invitation</label>
    <nameField>
        <displayFormat>MI-{0000}</displayFormat>
        <label>Meal Invitation #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meal Invitations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Up2Go-travelexpenses/src/objects/Travel__c.object
<CustomObject>
    <description>Records of business travels.</description>
    <fields>
        <fullName>dtm_End__c</fullName>
        <label>End</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>fcur_Reimbursement__c</fullName>
        <formula>rsum_ReimbursableExpenses__c  +  rsum_PerDiems__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Reimbursement</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>rsum_PerDiems__c</fullName>
        <label>Total per Diems</label>
        <summarizedField>Expense__c.cur_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Expense__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>per Diem</value>
        </summaryFilterItems>
        <summaryForeignKey>Expense__c.mdr_Travel__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>rsum_ReimbursableExpenses__c</fullName>
        <label>Reimbursable Expenses</label>
        <summarizedField>Expense__c.cur_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Expense__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Flight, Accommodation, Train Ride, Private Vehicle Ride, Miscellaneous, Sea Travel, Entertainment, Rental Vehicle, Company Vehicle Ride</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Expense__c.pkl_Reimbursement__c</field>
            <operation>equals</operation>
            <value>&quot;I paid for this, please reimburse me.&quot;</value>
        </summaryFilterItems>
        <summaryForeignKey>Expense__c.mdr_Travel__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>rsum_TotalExpenses__c</fullName>
        <label>Total Expenses</label>
        <summarizedField>Expense__c.cur_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Expense__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Flight, Accommodation, Train Ride, Private Vehicle Ride, Miscellaneous, Sea Travel, Entertainment, Rental Vehicle, Company Vehicle Ride</value>
        </summaryFilterItems>
        <summaryForeignKey>Expense__c.mdr_Travel__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>txa_Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>txt_Reason__c</fullName>
        <label>Reason</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Travel</label>
    <nameField>
        <label>Travel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Up2Go-travelexpenses/src/classes/MealInvitationsTriggerHandler.cls
public with sharing class MealInvitationsTriggerHandler extends AbstractTriggerHandler{
	
	private List<MealInvitation__c> newMealInvitations;
	private List<MealInvitation__c> oldMealInvitations;
	
	private RuleValidator validator;
	
	
	// CONSTRUCTOR
	
	public MealInvitationsTriggerHandler() {
		newMealInvitations = (List<MealInvitation__c>) Trigger.new;
		oldMealInvitations = (List<MealInvitation__c>) Trigger.old;
		
		validator = new RuleValidator(RuleType.MealInvitationRule);
	}
	
	
	// PUBLIC METHODS
	
	public override void onBeforeInsert() {
		validator.validate(newMealInvitations);
		
		populateLookupFields(newMealInvitations);
	}
	
	
	public override void onBeforeUpdate() {
		validator.validate(newMealInvitations);
		
		populateLookupFields(newMealInvitations);
	}
	
	
	public override void onAfterInsert() {
		calculatePerDiems(newMealInvitations);
	}
	
	
	public override void onAfterUpdate() {
		calculatePerDiems(newMealInvitations);
	}
	
	
	public override void onAfterDelete() {
		calculatePerDiems(oldMealInvitations);
	}
	
	
	// PRIVATE METHODS
	
	private void calculatePerDiems(List<MealInvitation__c> mealInvitations) {
		Set<Id> mealInvitationIds = new Set<Id>();
		for(MealInvitation__c mi : mealInvitations) {
			mealInvitationIds.add(mi.mdr_Travel__c);
		}
		
		for(Travel__c travel : [SELECT Id, Name, CurrencyIsoCode, txt_Reason__c, txa_Description__c, 
         							   dtm_Start__c, dtm_End__c, Owner.FirstName, Owner.LastName, 
         							   rsum_TotalExpenses__c, rsum_ReimbursableExpenses__c, rsum_PerDiems__c, 
         							   fcur_Reimbursement__c
							    FROM Travel__c 
							    WHERE Id IN :mealInvitationIds]) {
							    	
			PerDiemCalculator perDiemCalculator = new PerDiemCalculator(travel);
        	perDiemCalculator.calculate();
		}
	}
	
	
	private void populateLookupFields(List<MealInvitation__c> mealInvitations) {
		Map<String, Id> mealIdsByName = queryMealIdsByName();
        
        for(MealInvitation__c m : mealInvitations) {
			m.lkp_Breakfast__c = null;
			m.lkp_Lunch__c = null;
			m.lkp_Dinner__c = null;
			
			if(m.chk_Breakfast__c) {
				m.lkp_Breakfast__c = mealIdsByName.get('Breakfast');
			}
			if(m.chk_Lunch__c) {
				m.lkp_Lunch__c = mealIdsByName.get('Lunch');
			}
			if(m.chk_Dinner__c) {
				m.lkp_Dinner__c = mealIdsByName.get('Dinner');
			}
		}
	}
    
    
    private Map<String, Id> queryMealIdsByName() {
        Map<String, Id> results = new Map<String, Id>();
        
		for(CompensationRate__c rate : [SELECT Id, Name 
					 					FROM CompensationRate__c 
					 					WHERE RecordTypeId = :CompensationRateType.getMealId()]) {
 			results.put(rate.Name, rate.Id);
 		}
        
        return results;
    }
}