Up2Go-travelexpenses/src/objects/Expense__c.object
<CustomObject>
    <description>Contains informations about the expenses.</description>
    <fields>
        <fullName>chk_BreakfastIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Breakfast Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>chk_RoundTrip__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RoundTrip</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cur_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Overall cost of the expense.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>cur_Bill__c</fullName>
        <label>Bill</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>cur_Tip__c</fullName>
        <label>Tip</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>dat_CheckInDate__c</fullName>
        <label>Check In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dat_CheckOutDate__c</fullName>
        <label>Check Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dat_ExpenseDate__c</fullName>
        <description>To assign a Expense to a specific travel date.</description>
        <label>Expense Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dat_ReturnDate__c</fullName>
        <label>Return Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dtm_DepartureTime__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_End__c</fullName>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_ReturnArrival__c</fullName>
        <label>Return Arrival</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_ReturnDeparture__c</fullName>
        <label>Return Departure</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>fcur_MilageCosts__c</fullName>
        <formula>lkp_VehicleType__r.cur_MilageAllowance__c  *  num_Milage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milage Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>mdr_Travel__c</fullName>
        <label>Travel</label>
        <referenceTo>Travel__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>pkl_Reimbursement__c</fullName>
        <label>Reimbursement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>I paid for this, please reimburse me.</fullName>
                </value>
                <value>
                    <fullName>The company paid for this.</fullName>
                </value>
                <value>
                    <fullName>The customer paid for this.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>txa_Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>txt_Reason__c</fullName>
        <label>Reason</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Expense #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Up2Go-travelexpenses/src/objects/Travel__c.object
<CustomObject>
    <description>Records of business travels.</description>
    <fields>
        <fullName>dtm_End__c</fullName>
        <label>End</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>fcur_Reimbursement__c</fullName>
        <formula>rsum_ReimbursableExpenses__c  +  rsum_PerDiems__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Reimbursement</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>rsum_PerDiems__c</fullName>
        <label>Total per Diems</label>
        <summarizedField>Expense__c.cur_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Expense__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>per Diem</value>
        </summaryFilterItems>
        <summaryForeignKey>Expense__c.mdr_Travel__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>rsum_ReimbursableExpenses__c</fullName>
        <label>Reimbursable Expenses</label>
        <summarizedField>Expense__c.cur_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Expense__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Flight, Accommodation, Train Ride, Private Vehicle Ride, Miscellaneous, Sea Travel, Entertainment, Rental Vehicle, Company Vehicle Ride</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Expense__c.pkl_Reimbursement__c</field>
            <operation>equals</operation>
            <value>&quot;I paid for this, please reimburse me.&quot;</value>
        </summaryFilterItems>
        <summaryForeignKey>Expense__c.mdr_Travel__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>rsum_TotalExpenses__c</fullName>
        <label>Total Expenses</label>
        <summarizedField>Expense__c.cur_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Expense__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Flight, Accommodation, Train Ride, Private Vehicle Ride, Miscellaneous, Sea Travel, Entertainment, Rental Vehicle, Company Vehicle Ride</value>
        </summaryFilterItems>
        <summaryForeignKey>Expense__c.mdr_Travel__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>txa_Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>txt_Reason__c</fullName>
        <label>Reason</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Travel</label>
    <nameField>
        <label>Travel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Up2Go-travelexpenses/src/classes/ExpensesTriggerHandler.cls
public with sharing class ExpensesTriggerHandler extends AbstractTriggerHandler{
	
	private List<Expense__c> newExpenses;
	private List<Expense__c> oldExpenses;
	private Map<Id, Expense__c> oldExpensesById;
	
	private RuleValidator validator;
		
	
	//CONSTRUCTOR
	
	public ExpensesTriggerHandler() {
		newExpenses = filterOutPerDiems(Trigger.new);
		oldExpenses = filterOutPerDiems(Trigger.old);
		oldExpensesById = filterOutPerDiems(Trigger.oldMap);
		
		validator = new RuleValidator(RuleType.ExpenseRule);
	}
	
	
	// PUBLIC METHODS
	
	public override void onBeforeInsert() {
		validator.validate(newExpenses);	
			
		populateFields(newExpenses);
		manageBreakfastInclusionForInsert(newExpenses);
	}
	
	
	public override void onBeforeUpdate() {
		validator.validate(newExpenses);		
		
		populateFields(newExpenses);
		manageBreakfastInclusionForUpdate(newExpenses);
	}
	
	
	public override void onBeforeDelete() {
		manageBreakfastInclusionForDelete(oldExpenses);
	}
	
	
	public override void onAfterInsert() {
		calculatePerDiems(newExpenses);
	}
	
	
	public override void onAfterUpdate() {
		calculatePerDiems(newExpenses);
	}
	
	
	public override void onAfterDelete() {
		calculatePerDiems(oldExpenses);
	}
			
	
	// PRIVATE METHODS
	
	private List<Expense__c> filterOutPerDiems(List<SObject> expenses) {
		List<Expense__c> results = new List<Expense__c>();
		
		if(expenses != null && !expenses.isEmpty()) {
			for(Expense__c e : (List<Expense__c>) expenses) {
				if(!ExpenseType.isPerDiem(e)) {
					results.add(e);
				}
			}
		}
		
		return results;
	}
	
	
	private Map<Id, Expense__c> filterOutPerDiems(Map<Id,SObject> oldExpenses) {
		Map<Id, Expense__c> resultMap = new Map<Id, Expense__c>();
		
		if( oldExpenses != null && !oldExpenses.isEmpty()) {
			for(Expense__c e : (List<Expense__c>)oldExpenses.values()) {
				resultMap.put(e.Id, e);
			}
		}
		
		return resultMap;
	}
	
	
	private void calculatePerDiems(List<Expense__c> expenses) {
		Set<Id> travels = new Set<Id>();
		for(Expense__c e : expenses) {
			travels.add(e.mdr_Travel__c);
		}
		
		for(Travel__c t : [SELECT Id, Name, CurrencyIsoCode, txt_Reason__c, txa_Description__c, 
     							  dtm_Start__c, dtm_End__c, Owner.FirstName, Owner.LastName, 
     							  rsum_TotalExpenses__c, rsum_ReimbursableExpenses__c, rsum_PerDiems__c, 
     							  fcur_Reimbursement__c
						   FROM Travel__c 
						   WHERE Id IN :travels]) {
						   	
			PerDiemCalculator perDiemCalculator = new PerDiemCalculator(t);
        	perDiemCalculator.calculate();
		}
	}
	
	
	private void populateFields(List<Expense__c> expenses) {
		for(Expense__c expense : expenses) {
			populateExpenseDate(expense);
			populateAmount(expense);
			populateReimbursement(expense);
			clearRoundTripFields(expense);
		}		
	}
	
	
	private void clearRoundTripFields(Expense__c expense) {
		if(expense.chk_RoundTrip__c == false) {
			expense.dtm_ReturnDeparture__c = null;
			expense.dtm_ReturnArrival__c = null;
		}
	}


	private void populateExpenseDate(Expense__c expense) {
		if(ExpenseType.isMovement(expense)) {
			expense.dat_ExpenseDate__c = expense.dtm_DepartureTime__c.date();
		}
		else if(ExpenseType.isAccommodation(expense)) {
			expense.dat_ExpenseDate__c = expense.dat_CheckOutDate__c;
		}
		else if(ExpenseType.isRentalVehicle(expense)) {
			expense.dat_ExpenseDate__c = expense.dat_ReturnDate__c;
		}
	}
	
	
	private void populateAmount(Expense__c expense) {
		if(ExpenseType.isPrivateVehicle(expense)) {			
			expense.cur_Amount__c = expense.fcur_MilageCosts__c;
		}
		else if(ExpenseType.isEntertainment(expense)) {
			expense.cur_Amount__c = expense.cur_Bill__c + expense.cur_Tip__c;
		}
	}
	
	
	private void populateReimbursement(Expense__c expense) {
		if(ExpenseType.isPrivateVehicle(expense)) {			
			expense.pkl_Reimbursement__c = 'I paid for this, please reimburse me.';
		}
		else if(ExpenseType.isCompanyVehicle(expense)) {			
			expense.pkl_Reimbursement__c = 'The company paid for this.';
		}
	}
	
	
	private void manageBreakfastInclusionForInsert(List<Expense__c> expenses) {
		List<Expense__c> accommodations = findAccommodationsWithBreakfastIncluded(expenses);
		Boolean includeBreakfast = true;
		
		if( !accommodations.isEmpty()) {
			BreakfastInclusionHandler handler = new BreakfastInclusionHandler(accommodations);
			handler.handleInclusion(includeBreakfast);
		}
	}
	
	
	private void manageBreakfastInclusionForUpdate(List<Expense__c> expenses) {
		List<Expense__c> accommodations = findAccommodationsWhichNeedHandler(expenses);
		List<Expense__c> oldAccommodations = findAccommodationsWithRedundantInvitations(accommodations);
		
		if( !accommodations.isEmpty()) {
			BreakfastInclusionHandler handler = new BreakfastInclusionHandler(accommodations);
			handler.handleRedundantInvitations(oldAccommodations);
			handler.handleInclusionForUpdate();
		}
	}
	
	
	private void manageBreakfastInclusionForDelete(List<Expense__c> expenses) {
		List<Expense__c> accommodations = findAccommodationsWithBreakfastIncluded(expenses);
		Boolean includeBreakfast = false;
		
		if( !accommodations.isEmpty()) {
			BreakfastInclusionHandler handler = new BreakfastInclusionHandler(accommodations);
			handler.handleInclusion(includeBreakfast);
		}
	}
	
	
	private List<Expense__c> findAccommodationsWithBreakfastIncluded(List<Expense__c> expenses) {
		List<Expense__c> results = new List<Expense__c>();
		
		for(Expense__c a : onlyAccommodationsIn(expenses)) {
			if(a.chk_BreakfastIncluded__c) {
				results.add(a);
			}
		}
		
		return results;
	}
	
	
	private List<Expense__c> onlyAccommodationsIn(List<Expense__c> expenses) {
		List<Expense__c> results = new List<Expense__c>();
		
		for(Expense__c e : expenses) {
			if(ExpenseType.isAccommodation(e)) {
				results.add(e);
			}
		}
		
		return results;
	}
	
	
	private List<Expense__c> findAccommodationsWhichNeedHandler(List<Expense__c> expenses) {
		List<Expense__c> results = new List<Expense__c>();
		
		for(Expense__c updated : onlyAccommodationsIn(expenses)) {
			Expense__c old = oldExpensesById.get(updated.Id);
			
			if(needsBreakfastInclusion(updated, old)) {
				results.add(updated);
			}
		}
		
		return results;
	}
	
	
	private Boolean needsBreakfastInclusion(Expense__c updated, Expense__c old) {
		Boolean result = (updated.chk_BreakfastIncluded__c && timePeriodChanged(updated, old))
						 || breakfastIncludedChanged(updated, old);
		
		return result;
	}
	
	
	private Boolean timePeriodChanged(Expense__c updated, Expense__c old) {
		Boolean result = (updated.dat_CheckInDate__c != old.dat_CheckInDate__c) 
						 || (updated.dat_CheckOutDate__c != old.dat_CheckOutDate__c);
		
		return result;
	}
	
	
	private Boolean breakfastIncludedChanged(Expense__c updated, Expense__c old) {
		Boolean result = (updated.chk_BreakfastIncluded__c != old.chk_BreakfastIncluded__c);
		
		return result;
	}
	
	
	private List<Expense__c> findAccommodationsWithRedundantInvitations(List<Expense__c> accommodations) {
		List<Expense__c> results = new List<Expense__c>();
		
		for(Expense__c updated : accommodations) {
			Expense__c old = oldExpensesById.get(updated.Id);
			
			if(timePeriodHasBeenReduced(updated, old)) {
				results.add(old);
			}
		}
		
		return results;
	}
	
	
	private Boolean timePeriodHasBeenReduced(Expense__c updated, Expense__c old) {
		Boolean result = (updated.dat_CheckInDate__c > old.dat_CheckInDate__c)
						 || (updated.dat_CheckOutDate__c < old.dat_CheckOutDate__c);
		
		return result;
	}
}