Up2Go-travelexpenses/src/objects/Expense__c.object
<CustomObject>
    <description>Contains informations about the expenses.</description>
    <fields>
        <fullName>chk_RoundTrip__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RoundTrip</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>dat_CheckInDate__c</fullName>
        <label>Check In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dat_CheckOutDate__c</fullName>
        <label>Check Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dat_ExpenseDate__c</fullName>
        <description>To assign a Expense to a specific travel date.</description>
        <label>Expense Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dat_PickUpDate__c</fullName>
        <label>Pick-up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dat_ReturnDate__c</fullName>
        <label>Return Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dtm_ArrivalTime__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_DepartureTime__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_End__c</fullName>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_ReturnArrival__c</fullName>
        <label>Return Arrival</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_ReturnDeparture__c</fullName>
        <label>Return Departure</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>mdr_Travel__c</fullName>
        <label>Travel</label>
        <referenceTo>Travel__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Expense #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Up2Go-travelexpenses/src/objects/Travel__c.object
<CustomObject>
    <description>Records of business travels.</description>
    <fields>
        <fullName>dtm_End__c</fullName>
        <label>End</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Travel</label>
    <nameField>
        <label>Travel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Up2Go-travelexpenses/src/classes/ExpenseCannotBeOutsideOfTravelPeriod.cls
public with sharing class ExpenseCannotBeOutsideOfTravelPeriod implements ExpenseRule{     
     
     private String errorMessage = System.Label.ExpenseCannotBeOutsideOfTravelPeriod;
     private Travel__c travel;
     
     
	// PUBLIC METHODS
     
    public void validate(List<SObject> records) {
    	List<Expense__c> expenses = (List<Expense__c>) records;

    	Map<Id,Travel__c> relevantTravels = queryRelevantTravels(expenses);
    	
		for(Expense__c expense : expenses) {
			travel = relevantTravels.get(expense.mdr_Travel__c);
			
	        if(ExpenseType.isMovement(expense)) {
	        	checkMovementExpense(expense);
	        }
	        else if(ExpenseType.isAccommodation(expense)) {
	    		checkAccommodationExpense(expense);
        	}
			else if(ExpenseType.isRentalVehicle(expense)) {
				checkRentalVehicleExpense(expense);
			}
			else if((ExpenseType.isEntertainment(expense) || ExpenseType.isMiscellaneous(expense))){
				checkLocalExpense(expense);
			}
		}
    }
    
    
    // PRIVATE METHODS
    
    private Map<Id,Travel__c> queryRelevantTravels(List<Expense__c> expenses) {
    	Set<Id> travels = new Set<Id>();
    	for(Expense__c e : expenses) {
    		travels.add(e.mdr_Travel__c);
    	}
    	
    	Map<Id,Travel__c> resultMap = new Map<Id,Travel__c>([SELECT Id, dtm_Start__c, dtm_End__c 
    														  FROM Travel__c
    														  WHERE Id IN :travels]);
    	
    	return resultMap;
    }
    
    
    private void checkMovementExpense(Expense__c expense) {
    	if(isOutsideOfTravel(expense.dtm_DepartureTime__c)) {
            expense.dtm_DepartureTime__c.addError(errorMessage);            
    	}
    	if(isOutsideOfTravel(expense.dtm_ArrivalTime__c)) {
    		expense.dtm_ArrivalTime__c.addError(errorMessage);
    	}
    	
    	if(hasRoundTrip(expense)) {
    		
    		if(isOutsideOfTravel(expense.dtm_ReturnDeparture__c)) {
    			expense.dtm_ReturnDeparture__c.addError(errorMessage);
    		}
    		if(isOutsideOfTravel(expense.dtm_ReturnArrival__c)) {
    			expense.dtm_ReturnArrival__c.addError(errorMessage);
    		}
    	}
    }
    
    
    private void checkAccommodationExpense(Expense__c expense) {
    	if(isOutsideOfTravel(expense.dat_CheckInDate__c)) {
    		expense.dat_CheckInDate__c.addError(errorMessage);     
		}
		if(isOutsideOfTravel(expense.dat_CheckOutDate__c)) {
			expense.dat_CheckOutDate__c.addError(errorMessage);
		}
    }
    
    
    private void checkRentalVehicleExpense(Expense__c expense) {
    	if(isOutsideOfTravel(expense.dat_PickUpDate__c)) {
			expense.dat_PickUpDate__c.addError(errorMessage);
		}
		if(isOutsideOfTravel(expense.dat_ReturnDate__c)) {
			expense.dat_ReturnDate__c.addError(errorMessage);
		}				
    }
    
    
    private void checkLocalExpense(Expense__c expense) {
    	if(IsOutsideOfTravel(expense.dat_ExpenseDate__c)) {
			expense.dat_ExpenseDate__c.addError(errorMessage);
    	}
    }
    
    
    private Boolean isOutsideOfTravel(Date day) {
    	Boolean result = day < travel.dtm_Start__c.date() || day > travel.dtm_End__c.date();
        				  
        return result;
    }
    
    
    private Boolean isOutsideOfTravel(DateTime dtm) {
    	Boolean result = dtm < travel.dtm_Start__c || dtm > travel.dtm_End__c;

    	return result;
    }
    
    
    private Boolean hasRoundTrip(Expense__c e) {
    	Boolean result = e.chk_RoundTrip__c && e.dtm_ReturnDeparture__c != null && e.dtm_ReturnArrival__c != null;
    	
    	return result;
    }
}