AkshayVispute-Salesforce/akshay.vispute@eternussolutions.com/src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/User_Lookups__c.object
<CustomObject>
    <fields>
        <fullName>Chapter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Club Entity object, filtered for Chapters.</description>
        <label>Chapter</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Club_Entity__c.Type__c</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Club_Entity__c</referenceTo>
        <relationshipLabel>Chapter Users</relationshipLabel>
        <relationshipName>User_Lookups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Lookups</relationshipLabel>
        <relationshipName>User_Lookups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Lookups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Lookups</label>
    <nameField>
        <displayFormat>UL-{0000000}</displayFormat>
        <label>User Lookups Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Lookups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/classes/UserLookupsExtension.cls
// *************************************************************************/
// UserLookupsExtension Class
//      VB: This class is a User standard controller extension that 
//			pulls the list of User Lookup records associated with a   
//          specific user.  This is so the User detail page can display  
//          this list of records, which isn't allowed due to the
//			limitations around Users and lookup fields and related lists.
//           
//  2016/06/22      Vernon Baas         Original
// *************************************************************************/
public with sharing class UserLookupsExtension {

	// This is the list that is displayed on the VF page
	public List<User_Lookups__c> UserLookups {get; set;}
    
	public UserLookupsExtension(ApexPages.StandardController controller) {
		
        UserLookups = new List<User_Lookups__c>();	// Initialize the list
		User thisUser  = (User) controller.getRecord();    //Get User from controller.
        
		//Query and loop through the (hopefully one) lookups.
        for (User_Lookups__c theLookup : [Select Chapter__c, Contact__c from User_Lookups__c where User__c = :thisUser.Id]) {
        	
            UserLookups.add(theLookup);
        }
    }
    
}