dimagi-SalesforceFB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <inlineHelpText>What field is the account in.</inlineHelpText>
        <label>Sector</label>
        <picklist>
            <picklistValues>
                <fullName>Agriculture and Food Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education and Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services for the Poor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gender Equality and Women&apos;s Empowerment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governance and Accountability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water, Sanitation, &amp; Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal, Human Rights</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Area__c</fullName>
        <label>Sub Sector</label>
        <picklist>
            <picklistValues>
                <fullName>*** Agriculture and Food Security ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Economic Development ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rural Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safety &amp; Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urban Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Education and Training ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Childhood Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Emergency Response ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Financial Services for the Poor ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Cash Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services to the Poor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Gender Equality and Women&apos;s Emp ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gender Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sex Workers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Governance and Accountability ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Accountability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Health ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiac Diseases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cervical Cancer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diagnostics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diarrhea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Planning</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/Country__c.object
<CustomObject>
    <description>The different countries we work in</description>
    <fields>
        <fullName>Area__c</fullName>
        <inlineHelpText>Auto-populated to show all sectors for deployments in this country.</inlineHelpText>
        <label>Sector</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Area__c</fullName>
        <inlineHelpText>Stores a concatenation of all sub sectors that a deployment in this country have.</inlineHelpText>
        <label>Sub Sector</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/Project__c.object
<CustomObject>
    <description>A Dimagi Project</description>
    <fields>
        <fullName>Area__c</fullName>
        <label>Sector</label>
        <picklist>
            <picklistValues>
                <fullName>Agriculture and Food Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education and Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services for the Poor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gender Equality and Women&apos;s Empowerment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governance and Accountability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water, Sanitation, &amp; Hygiene</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementing Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Area__c</fullName>
        <label>Sub Sector</label>
        <picklist>
            <picklistValues>
                <fullName>*** Agriculture and Food Security ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Economic Development ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rural Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urban Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safety &amp; Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Education and Training ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Childhood Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Emergency Response ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Financial Services for the Poor ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Cash Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services to the Poor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Gender Equality and Women&apos;s Emp ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gender Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sex Workers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Governance and Accountability ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Accountability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Health ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiac Diseases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cervical Cancer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diagnostics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diarrhea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Planning</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/ProjectCountry__c.object
<CustomObject>
    <description>Allows showing open and closed projects on the country page layout.</description>
    <fields>
        <fullName>Area__c</fullName>
        <formula>Project__r.Area_Text__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Deployments</relationshipLabel>
        <relationshipName>Project_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Countries</relationshipLabel>
        <relationshipName>Project_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Area__c</fullName>
        <formula>Project__r.Sub_Area_Text__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub Area</label>
        <type>Text</type>
    </fields>
    <label>Project Country</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Project Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/SFDC_Employee__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/classes/ProjectCountrySubSector.cls
public with sharing class ProjectCountrySubSector {
	
	public static void updateCountrySubSector(Country__c country) {
		
		Set<Id> deletedProjects = new Set<Id>();
		updateCountrySubSector(country, deletedProjects);
	}
	
	public static void updateCountrySubSector(Country__c country, Set<Id> deletedProjects) {
		
			String newSubSectorsString;
			String newSectorsString;
			Set<String> newSubSectorsSet = new Set<String>();
			Set<String> newSectorsSet = new Set<String>();
			Country__c currentCountry = country;
			Set<Id> deletedProjectIds = deletedProjects;
									
			// Loop through each deployment and add each deployments subsectors to the Set
			for (ProjectCountry__c pc : [select Project__c, Project__r.Sub_Area__c, Project__r.Area__c
										 from ProjectCountry__c
										 where Country__r.Id = :currentCountry.Id
										 and   Project__r.Id not in :deletedProjectIds
										 and   Project__r.Id != null]) {
				
				// Add each deployment's sub sector to the full set of subsectors
				if (pc.Project__r.Sub_Area__c != null) {
					newSubSectorsSet.addAll(pc.Project__r.Sub_Area__c.split(';'));		
				}
				if (pc.Project__r.Area__c != null) {
					newSectorsSet.addAll(pc.Project__r.Area__c.split(';'));
				}
			}
			
		 // Turn the new Sets set into strings
		 currentCountry.Sub_Area__c = toString(newSubSectorsSet);
		 currentCountry.Area__c = toString(newSectorsSet);
		 update currentCountry;

/*		 
		 if(newSubSectorsString != null) {
		 	currentCountry.Sub_Area__c = newSubSectorsString.replace('null','').removeEnd('; ');
		 }
		 else {
		 	currentCountry.Sub_Area__c = '';
		 }
		 
		 		 if(newSectorsString != null) {
		 	currentCountry.Area__c = newSectorsString.replace('null','').removeEnd('; ');
		 }
		 else {
		 	currentCountry.Area__c = '';
		 }
		 
	 
		 	update currentCountry;
*/		
		}
		

	// Gets all country Ids of Countries attached to a Deployment
	public static Set<Country__c> getCountries(Set<Id> projectId) {
		
		Set<ID> pIds = projectId;
		
		Set<Country__c> countries = new Set<Country__c>(
			[Select Id
			 from Country__c 
			 where Id in
					(Select Country__c
					 from ProjectCountry__c
					 where Project__r.Id in :pIds)]);
	
		return countries;
	}
	
	public static String toString(Set<String> inputSet) {
		
		String result = '';
		
		for (String s : inputSet) {
		 	result += s +'; ';
		 }
		
		if(String.isEmpty(result)) {
			result = '';
		}
		return result.replace('null','').removeEnd('; ');
		
	}

	public static testMethod void unitTest() {
		
		Account account = new Account(Name='test');
		insert account;
		Project__c project = new Project__c(Name='Testing', Implementing_Account__c=account.Id);
		insert project;
		Country__c country = new Country__c(Name='Testing Country');
		insert country;
		ProjectCountry__c pc = new ProjectCountry__c(Country__c=country.Id, Project__c=project.Id);
		insert pc;
		
		project.Sub_Area__c = 'Agriculture;Health';
		update project;
		
	}
		
}