dimagi-SalesforceFB/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Validate = Need to contact; 
Connect = remind every 10 days; 
Active = an active opportunity; 
Passive = remind every 3 months.</inlineHelpText>
        <label>Status_old</label>
        <picklist>
            <picklistValues>
                <fullName>Validate</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jlamontSC-test/src/objects/Account.object
    <fields>
        <fullName>Merge_Survivor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merge Survivor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts To Be Merged</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>

dimagi-SalesforceFB/src/objects/Child_Account__c.object
<CustomObject>
    <description>Used to enable hierarchy reporting on accounts.  Every time a parent-child relationship is made for accounts a trigger will create one of these links.</description>
    <fields>
        <fullName>Child_Account__c</fullName>
        <label>Child Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Parent Accounts</relationshipLabel>
        <relationshipName>Child_Accounts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Child Accounts</relationshipLabel>
        <relationshipName>Child_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Child Account</label>
    <nameField>
        <label>Child Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Child Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>1- Working - Active Opp Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2- Working - Talking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3- Working - Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4- Strategic Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5- Active Project Team Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6- Active Self Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7- Passive &amp; Friendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8- Passive &amp; Unfriendly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9-HOLD Not mine/move</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10-Dimagi Staff</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/Country__c.object
<CustomObject>
    <description>The different countries we work in</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which account is the contract signed with.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>DContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <inlineHelpText>When the project actually ends.</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <inlineHelpText>When the contract actually starts.</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Implementing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which organization is implementing the contract.</inlineHelpText>
        <label>Implementing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Implement_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Dimagi PM</inlineHelpText>
        <label>Project Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Email</field>
                <operation>contains</operation>
                <value>@dimagi.com</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts (Project Manager)</relationshipLabel>
        <relationshipName>Contracts_PM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>What country is this opportunity taking place.</inlineHelpText>
        <label>Implementing Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lanecwe-Prod/src/objects/Opportunity.object
    <fields>
        <fullName>Status__c</fullName>
        <label>x-Status</label>
        <picklist>
            <picklistValues>
                <fullName>Dead/Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open-Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Session/Needs Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presentation/Proposal/Price Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pilot/Trial/Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation/Verbal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won: Contract/CRA/Booked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

dimagi-SalesforceFB/src/objects/Project__c.object
<CustomObject>
    <description>A Dimagi Project</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementing Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementing_Account__c</fullName>
        <inlineHelpText>The organization that is implementing the project.</inlineHelpText>
        <label>Implementing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deployments (Implementer)</relationshipLabel>
        <relationshipName>Deployments_Implementing</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <inlineHelpText>The date the project ended</inlineHelpText>
        <label>Deployment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Who is running the project from Dimagi.</inlineHelpText>
        <label>Deployment Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Name</field>
                <operation>contains</operation>
                <value>Dimagi</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deployments (Deployment Manager)</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <inlineHelpText>A short description of the project.</inlineHelpText>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>&quot;Inactive&quot; means either not started or on hold. &quot;Complete&quot; means the project is closed.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/SFDC_Employee__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/classes/CountryListAcc.cls
public class CountryListAcc{
    
    //Public properties
    public List<Account> lstAcc {get; set;}
    public List<Contact> lstCon {get; set;}
    public List<DContract__c> lstContr {get; set;}
    public List<DContract__c> lstContrclosed {get; set;}
    public List<Project__c> lstDeplmnt {get; set;}
    public List<Project__c> lstDeplmntClosed {get; set;}
    public List<Opportunity> lstoppty {get; set;}
    public List<Opportunity> lstopptyClosed {get; set;}
    public List<ParentAcc> hierarchy {get; set;}    
    public String recId{get; set;}
    public String SearchString {get;set;}    
    Public Boolean showpage{get;set;}
    Public Boolean showChild{get;set;}
    
    Public List<AccountWrapper> wrapperList{get;set;}
    
    public map<id,string> accountMap=new map<id,string>();
    
    //Account selected by radio button
    public String selectedAccountId { get; set; }
    public List<Account> childAccounts { get; set; }
    
    //Private variables
    Set<Id> setId = new Set<Id>();
    List<Id> accIdList = new List<Id>();
    
     //Constructor
    public CountryListAcc(){
        
       
        
        //Initializing properties
        childAccounts = new List<Account>();
        lstCon = new List<Contact>();
        lstContr = new List<DContract__c>();
        lstContrclosed = new List<DContract__c>();
        lstDeplmnt = new List<Project__c>();
        lstDeplmntClosed = new List<Project__c>();
        lstoppty = new List<Opportunity>();
        lstopptyClosed = new List<Opportunity>();
        showPage = False;
        wrapperList = new List<AccountWrapper>();
        accountMap.clear();
        String strX = ApexPages.currentPage().getParameters().get('q');
        
        String accountId = ApexPages.currentPage().getParameters().get('id');
        
        if(strX!=null){
            SearchString=strX;
            Search();
            if(accountId!=null){
                selectedAccountId=accountId;
                searchByAccount();
            }
        }
    }
    
    //Function to search accounts
    public pageReference Search()
    {  
        //Clears all collections binded on page
        wrapperList.clear();
        childAccounts.clear();
        lstCon.clear();
        lstContrclosed.clear();
        lstDeplmnt.clear();
        lstDeplmntClosed.clear();
        lstoppty.clear();
        lstopptyClosed.clear();     
        
        //Select records from Account according to given search string
        String SearchQuery='Select Name,Id,Country__r.Name,Status__c,Parent.Name from account where name like \'%'+SearchString+'%\'';  
        lstAcc = Database.query(SearchQuery);
       
       //Create collection of wrapper class
        if(lstAcc.size() > 0){
            for(Account ac: lstAcc){
                wrapperList.add(new AccountWrapper(ac,false));
                setId.add(ac.Id);
                accIdList.add(ac.Id);
                accountMap.put(ac.Id,ac.Name);
            }    
        }
                
        for(Account acc: [Select Name,Id,Country__r.Name,Status__c,Parent.Name From Account Where ParentId IN : accIdList])
        {
            if(!setId.contains(acc.Id))
            {
                wrapperList.add(new AccountWrapper(acc,true));
                lstAcc.add(acc);
                setId.add(acc.Id);
            }
            
        }
    
        showPage = True;
        
        PageReference page=new PageReference('/apex/CountryList?q='+SearchString);
        //page.getParameters().put('q', SearchString);
        
        page.setRedirect(true);
        
        return page;
    }
    
    //Action on radiobutton
    public PageReference searchByAccount(){
        
        
        string selectedAccountName=accountMap.get(selectedAccountId);
        PageReference page=new PageReference('/apex/CountryList?q='+selectedAccountName+'&id='+selectedAccountId);
        page.setRedirect(true);
        
        
        
        //Get child accounts
        childAccounts = [Select Name,Id,Country__r.Name,Status__c,Parent.Name from account where Parent.Id =: selectedAccountId]; 
        
        //Create set of child accounts IDs
        Set<Id> childAccountIDs = new Set<Id>();
        if(childAccounts.size() > 0){
            for(Account ac: childAccounts){                
                childAccountIDs.add(ac.Id);                
            }    
        }       
       
       //Get all children objects by account Id
       
       //Contacts
        lstCon=[SELECT Id, Account.Name,Email,Title, Name, Country__c 
                FROM Contact 
                WHERE AccountId =: selectedAccountId];
        
        //Contracts Open        
        lstContr =   [SELECT Id, Name,Account__c, DContract__c.Account__r.Name, 
                                     Contract_Start_Date__c, Contract_End_Date__c, Project_Manager__c, 
                                     Project_Manager__r.Name, Status__c, Short_Description__c 
                          FROM DContract__c 
                          WHERE Account__c =: selectedAccountId AND Status__c != 'Complete' ];              
        
        //Contracts Closed      
        lstContrclosed = [SELECT Id, Name,Account__c, DContract__c.Account__r.Name, 
                                     Contract_Start_Date__c, Contract_End_Date__c, Project_Manager__c, 
                                     Project_Manager__r.Name, Status__c, Short_Description__c 
                          FROM DContract__c 
                          WHERE Account__c =: selectedAccountId AND Status__c = 'Complete' ];
        
        //Deployements Open
        lstDeplmnt = [SELECT Id, Name, Implementing_Account__c,Project__c.Implementing_Account__r.Name,
                             Project_End_Date__c, Project_Manager__c, Project__c.Project_Manager__r.Name,
                             Status__c, Short_Description__c 
                       FROM Project__c WHERE Implementing_Account__c =: selectedAccountId AND Status__c != 'Complete'];
        
        //Deployements Closed       
        lstDeplmntClosed = [SELECT Id, Name, Implementing_Account__c,Project__c.Implementing_Account__r.Name,
                                   Project_End_Date__c, Project_Manager__c, Project__c.Project_Manager__r.Name,
                                   Status__c, Short_Description__c 
                             FROM Project__c WHERE Implementing_Account__c =: selectedAccountId AND Status__c ='Complete'];
        
        //Opportunities Open
        lstoppty = [SELECT Id, Name,Account.Name, Description,Country__c,Country__r.Name, StageName
                    FROM Opportunity 
                    WHERE AccountId =: selectedAccountId AND 
                         (StageName = 'Stage 1 - Connect' OR 
                          StageName = 'Stage 2 - Talking' OR 
                          StageName = 'Stage 3 - Prospect' OR 
                          StageName = 'Stage 4 - Proposal Development' OR 
                          StageName = 'Stage 5 - Submitted' OR 
                          StageName = 'Stage 6 - In Negotiations' OR 
                          StageName = 'On Hold')];
        
        //Opportunities Closed 
        lstopptyClosed = [SELECT Id, Name,Account.Name, Description,Country__c,Country__r.Name, StageName 
                          FROM Opportunity 
                          WHERE AccountId =: selectedAccountId AND (StageName = 'Closed - Lost' OR StageName = 'Closed - Won')];
        
        
        //Get all child objects by child accounts IDs
        
        //Contacts
        List<Contact> lstConChild =[SELECT Id, Account.Name,Email,Title, Name, Country__c 
                                    FROM Contact 
                                    WHERE AccountId IN: childAccountIDs];
        lstCon.addAll(lstConChild);
        
        //Contracts Open    
        List<DContract__c> lstContrChild =   [SELECT Id, Name,Account__c, DContract__c.Account__r.Name, 
                                                         Contract_Start_Date__c, Contract_End_Date__c, Project_Manager__c, 
                                                         Project_Manager__r.Name, Status__c, Short_Description__c 
                                              FROM DContract__c 
                                              WHERE Account__c IN: childAccountIDs AND Status__c != 'Complete' ];           
        
        lstContr.addAll(lstContrChild);     
       
       //Contracts Closed
        List<DContract__c> lstContrclosedChild = [SELECT Id, Name,Account__c, DContract__c.Account__r.Name, 
                                                             Contract_Start_Date__c, Contract_End_Date__c, Project_Manager__c, 
                                                             Project_Manager__r.Name, Status__c, Short_Description__c 
                                                  FROM DContract__c 
                                                  WHERE Account__c IN: childAccountIDs AND Status__c = 'Complete' ];
        
        lstContrclosed.addAll(lstContrclosedChild);
        
        //Deployements Open
        List<Project__c> lstDeplmntChild = [SELECT Id, Name, Implementing_Account__c,Project__c.Implementing_Account__r.Name,
                                                 Project_End_Date__c, Project_Manager__c, Project__c.Project_Manager__r.Name,
                                                 Status__c, Short_Description__c 
                                            FROM Project__c WHERE Implementing_Account__c IN: childAccountIDs AND Status__c != 'Complete'];
       
        lstDeplmnt.addAll(lstDeplmntChild);        
       
       //Deployements Closed
        List<Project__c> lstDeplmntClosedChild = [SELECT Id, Name, Implementing_Account__c,Project__c.Implementing_Account__r.Name,
                                                       Project_End_Date__c, Project_Manager__c, Project__c.Project_Manager__r.Name,
                                                       Status__c, Short_Description__c 
                                                 FROM Project__c WHERE Implementing_Account__c IN: childAccountIDs AND Status__c ='Complete'];
        
        lstDeplmntClosed.addAll(lstDeplmntClosedChild);
        
        //Opportunities Open
        List<Opportunity> lstopptyChild = [SELECT Id, Name,Account.Name, Description,Country__c,Country__r.Name, StageName
                                      FROM Opportunity 
                                      WHERE AccountId IN: childAccountIDs AND 
                                             (StageName = 'Stage 1 - Connect' OR 
                                              StageName = 'Stage 2 - Talking' OR 
                                              StageName = 'Stage 3 - Prospect' OR 
                                              StageName = 'Stage 4 - Proposal Development' OR 
                                              StageName = 'Stage 5 - Submitted' OR 
                                              StageName = 'Stage 6 - In Negotiations' OR 
                                              StageName = 'On Hold')];
         
        lstoppty.addAll(lstopptyChild);
        
        //Opportunities Closed
        List<Opportunity> lstopptyClosedChild = [SELECT Id, Name,Account.Name, Description,Country__c,Country__r.Name, StageName 
                                                 FROM Opportunity 
                                                 WHERE AccountId IN: childAccountIDs AND 
                                                 (StageName = 'Closed - Lost' OR StageName = 'Closed - Won')];
         
        lstopptyClosed.addAll(lstopptyClosedChild);   
        
        return page;                         
    }
    
   
    //Inner class for parent accounts
    public class ParentAcc{
        public List<Contact> Conlist {get; set;}
        public Account gparent {get;set;}
        public List<Child_Account__c>  chAcc{get; set;}

        public ParentAcc(Account  gp, List<Child_Account__c> c){
            chAcc = c;
            gparent = gp;
        }
    }
    
    //Function to fetch parent accounts
    public List<ParentAcc> mainnodes(){
        hierarchy = new List<ParentAcc>();
        List<Account> tempparent = [SELECT Id, Name, Phone FROM Account];
        
        for (Integer i =0; i< tempparent.size() ; i++){
            List<Child_Account__c> tempchildren = [SELECT Id, Name,Child_Account__c,Parent_Account__c 
                                                   FROM Child_Account__c WHERE Parent_Account__c = :tempparent[i].Id];
            if(tempchildren.size() > 0)
                hierarchy.add(new ParentAcc(tempparent[i],tempchildren));
        }
        
        System.Debug('________ hierarchy ________'+hierarchy);
        System.Debug('___ tempparent ____'+tempparent);
        return hierarchy;
    }
    
    //Functon to fetch child objects
    public void ContList(){
        lstCon=[SELECT Id, Account.Name,Email,Title, Name, Country__c FROM Contact WHERE AccountId =: recId];
        
        lstContr = [SELECT Id, Name,Account__c, DContract__c.Account__r.Name, Contract_Start_Date__c, Contract_End_Date__c, 
                            Project_Manager__c, Project_Manager__r.Name, Status__c, Short_Description__c 
                    FROM DContract__c WHERE Account__c =: recId AND Status__c = 'Active' ];
        
        lstContrclosed = [SELECT Id, Name,Account__c, DContract__c.Account__r.Name, Contract_Start_Date__c, Contract_End_Date__c, 
                                 Project_Manager__c, Project_Manager__r.Name, Status__c, Short_Description__c 
                          FROM DContract__c WHERE Account__c =: recId AND Status__c = 'Complete' ];
        
        lstDeplmnt = [SELECT Id, Name, Implementing_Account__c,Project__c.Implementing_Account__r.Name, Project_End_Date__c, 
                             Project_Manager__c, Project__c.Project_Manager__r.Name, Status__c, Short_Description__c 
                      FROM Project__c WHERE Implementing_Account__c =:recId AND Status__c ='Active'];
        
        lstDeplmntClosed = [SELECT Id, Name, Implementing_Account__c,Project__c.Implementing_Account__r.Name, Project_End_Date__c, 
                                   Project_Manager__c, Project__c.Project_Manager__r.Name, Status__c, Short_Description__c 
                            FROM Project__c WHERE Implementing_Account__c =:recId AND Status__c ='Complete'];
        
        lstoppty = [SELECT Id, Name,Account.Name, Description,Country__c,Country__r.Name, StageName 
                    FROM Opportunity WHERE AccountId =: recId AND 
                    (StageName = 'Stage 1 - Connect' OR StageName = 'Stage 2 - Talking' OR 
                     StageName = 'Stage 3 - Prospect' OR StageName = 'Stage 4 - Proposal Development' OR 
                     StageName = 'Stage 5 - Submitted' OR StageName = 'Stage 6 - In Negotiations' OR StageName = 'On Hold')];
         
        lstopptyClosed = [SELECT Id, Name,Account.Name, Description,Country__c,Country__r.Name, StageName 
                          FROM Opportunity WHERE AccountId =: recId AND 
                          (StageName = 'Closed - Lost' OR StageName = 'Closed - Won')];
    }
    
    //Inner class to decide account is child or not
    public class AccountWrapper {
        public Account acc {get; set;}
        public Boolean child{get; set;}
        public Boolean selected {get; set;}

        //This is the contructor method. When we create a new cContact object 
        //we pass a Contact that is set to the con property. We also set the selected value to false
        public AccountWrapper(Account c,Boolean ch) {
            acc = c;
            child = ch;
            selected = false;
        }
    }
}