dimagi-SalesforceFB/src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <fields>
        <fullName>Intracompany_Sub_contract__c</fullName>
        <inlineHelpText>For internal accounting. Is this an internal subcontract between Dimagi business units?</inlineHelpText>
        <label>Intracompany Sub-contract</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If an intracompany contract, select the corresponding parent.</inlineHelpText>
        <label>Parent Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Child Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requires_Report_Out__c</fullName>
        <inlineHelpText>Does this contract need a Project Report Out?</inlineHelpText>
        <label>Requires Report Out</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Services_Spend__c</fullName>
        <description>Calculated from FB time data and Loaded Billing Rates (updated daily for last 4 months)</description>
        <inlineHelpText>Calculated from FB time data and Loaded Billing Rates (updated daily for last 4 months)</inlineHelpText>
        <label>Services Spend</label>
        <precision>14</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/classes/BatchUpdateContractServicesSpendTest.cls
@isTest
public class BatchUpdateContractServicesSpendTest {

    @isTest
    public static void shouldUpdateServicesSpendFieldValue() {
        DContract__c dcontract1 = new DContract__c(
            Name = 'Sample Test Name 1 ',
            Status__c = 'Active',
            Requires_Report_Out__c = 'No',
            Intracompany_Sub_contract__c = 'No'
        );
        insert dcontract1;
        DContract__c dcontract2 = new DContract__c(
            Name = 'Sample Test Name 2',
            Status__c = 'Active',
            Requires_Report_Out__c = 'No',
            Intracompany_Sub_contract__c = 'No'
        );
        insert dcontract2;
        DContract__c dcontract3 = new DContract__c(
            Name = 'Sample Test Name 3 ',
            Status__c = 'Active',
            Requires_Report_Out__c = 'No',
            Intracompany_Sub_contract__c = 'Yes',
            Parent_Contract__c = dcontract2.Id
        );
        insert dcontract3;
        DContract__c dcontract4 = new DContract__c(
            Name = 'Sample Test Name 4',
            Status__c = 'Active',
            Requires_Report_Out__c = 'No',
            Intracompany_Sub_contract__c = 'Yes',
            Parent_Contract__c = dcontract2.Id
        );
        insert dcontract4;
        DContract__c dcontract5 = new DContract__c(
            Name = 'Sample Test Name 5',
            Status__c = 'Active',
            Requires_Report_Out__c = 'No',
            Intracompany_Sub_contract__c = 'Yes',
            Parent_Contract__c = dcontract2.Id
        );
        insert dcontract5;

        Map<Id, Decimal> batchData = new Map<Id, Decimal> { dcontract1.Id => 100, dcontract2.Id => 200, dcontract3.Id => 10, dcontract4.Id => 35};

        Test.startTest();
        BatchUpdateContractServicesSpend obj = new BatchUpdateContractServicesSpend(batchData);
        Database.executeBatch(obj, 200);
        Test.stopTest();

        List<DContract__c> contracts = [SELECT Name, Services_Spend__c FROM DContract__c ORDER BY Name];

        System.assertEquals('Sample Test Name 1', contracts.get(0).Name);
        System.assertEquals('Sample Test Name 2', contracts.get(1).Name);
        System.assertEquals('Sample Test Name 3', contracts.get(2).Name);
        System.assertEquals('Sample Test Name 4', contracts.get(3).Name);
        System.assertEquals('Sample Test Name 5', contracts.get(4).Name);

        System.assertEquals(100, contracts.get(0).Services_Spend__c);
        System.assertEquals(245, contracts.get(1).Services_Spend__c);
        System.assertEquals(10, contracts.get(2).Services_Spend__c);
        System.assertEquals(35, contracts.get(3).Services_Spend__c);
        System.assertEquals(null, contracts.get(4).Services_Spend__c);
    }
}