dimagi-SalesforceFB/src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <fields>
        <fullName>First_Nag_Sent_Date__c</fullName>
        <label>First Nag Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_First_Nag_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is First Nag Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Snooze__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Snooze</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Report_Out_Date__c</fullName>
        <inlineHelpText>The most recent date that a report out was filled out for.</inlineHelpText>
        <label>Last Report Out Date</label>
        <summarizedField>Project_Report_Out__c.Report_Out_Date__c</summarizedField>
        <summaryForeignKey>Project_Report_Out__c.Contract__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Last_Report_Out_Status__c</fullName>
        <description>Stores the value from the most recent report out.</description>
        <inlineHelpText>Stores the value from the most recent report out submitted.</inlineHelpText>
        <label>Last Report Out Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Snooze_Date__c</fullName>
        <label>Snooze Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Snooze_Days__c</fullName>
        <label>Snooze Days</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/classes/PROEmailContractFilterHelper.cls
public class PROEmailContractFilterHelper {

    public integer FirstNagDays{
        get; set;
    }

    public integer SecondNagDays{
        get; set;
    }

    public integer ThirdNagDays{
        get; set;
    }

    public integer FourthNagDays{
        get; set;
    }

    public PROEmailContractFilterHelper() {
        FirstNagDays = 4;
        SecondNagDays = 1;
        ThirdNagDays = 3;
        FourthNagDays = 7;
    }

    public List<DContract__c> filter(List<DContract__c> contracts, PROEmailContractFilterType filterType) {
        Date currentDate = Date.Today();
        List<DContract__c> filteredContract = new List<DContract__c>();

        if (filterType == PROEmailContractFilterType.FirstNag) {
            Date latestPRODueDate = GetLatestPRODueDate();
            Date lastAllowedDate = latestPRODueDate.addDays(FirstNagDays);

            for(DContract__c contract: contracts){
                if((contract.Last_Report_Out_Date__c!=null && contract.Last_Report_Out_Date__c<latestPRODueDate) 
                || (contract.Last_Report_Out_Date__c==null && contract.CreatedDate<latestPRODueDate)){
                    if(currentDate>=lastAllowedDate && !contract.Is_First_Nag_Sent__c){
                        if(!contract.Is_Snooze__c || contract.Is_Snooze__c &&  
                            (contract.Snooze_Date__c.addDays(Integer.valueOf(contract.Snooze_Days__c))<currentDate)){
                            filteredContract.add(contract);
                            
                        }
                    }
                }
            }
        }
        else if(filterType==PROEmailContractFilterType.SecondNag){
             for(DContract__c contract: contracts){
                 if(contract.Last_Report_Out_Status__c!='Red' && contract.Is_First_Nag_Sent__c && !contract.Is_Snooze__c && contract.First_Nag_Sent_Date__c.addDays(SecondNagDays)==currentDate){
                     filteredContract.add(contract);
                 }
             }
        }
        else if(filterType==PROEmailContractFilterType.ThirdNag){
             for(DContract__c contract: contracts){
                 if(contract.Last_Report_Out_Status__c!='Red' && contract.Is_First_Nag_Sent__c && !contract.Is_Snooze__c && contract.First_Nag_Sent_Date__c.addDays(ThirdNagDays)==currentDate){
                         filteredContract.add(contract);
                 }
   
             }
        }
        else if(filterType==PROEmailContractFilterType.FourthNag){
             for(DContract__c contract: contracts){
                 if(contract.Last_Report_Out_Status__c!='Red' && contract.Is_First_Nag_Sent__c && !contract.Is_Snooze__c && contract.First_Nag_Sent_Date__c.addDays(FourthNagDays)==currentDate){
                     filteredContract.add(contract);
                 }
             }
        }
        
        return filteredContract;
    }
        /*
        Get latest PRO Due Date.
        PRO is due every Second and fourth Thursday.
    */
    public Date GetLatestPRODueDate(){
        
        Date latestPRODueDate=null;
        
        Date currentDate=Date.today();

        integer currentMonth=currentDate.month();
        integer currentYear=currentDate.year();
        
        List<Date> currentMonthThursDayList=GetAllThursDayOfMonth(currentYear,currentMonth);
        
        //Current Date is less then second Thursday of month, 
        //then used fourth Thursday of previous month.
        if(currentDate<currentMonthThursDayList[1]){
             Date previousMonthDate=currentDate.addMonths(-1);
             integer previousMonth=previousMonthDate.month();
             integer previousYear=previousMonthDate.year();
             //Get previous Month Thursday.
             List<Date> previousMonthThursDayList=GetAllThursDayOfMonth(previousYear,previousMonth);
             
             return previousMonthThursDayList[3];
        }
        else{
            if(currentDate<currentMonthThursDayList[3]){
                latestPRODueDate=currentMonthThursDayList[1];
            }   
            else{
                latestPRODueDate=currentMonthThursDayList[3];
            }
        }
        
        
        return latestPRODueDate;
    }
    /*
        Get List of Thursday of current month.
    */
    private List<Date> GetAllThursDayOfMonth(integer year,integer month){
        List<Date> thuDayDateList=new List<Date>();
        
        Date startDate=date.newInstance(year,month, 1);
        Date endDate=startDate.addMonths(1).addDays(-1);
        
        do{
            Datetime myDateTime = DateTime.newInstance(startDate, Time.newInstance(0, 0, 0, 0));
            String dayOfWeek = myDateTime.format('E');
            if(dayofWeek=='Thu'){
                thuDayDateList.add(startDate);
            }
            startDate=startDate.AddDays(1);
        }while(startDate<endDate);
    
        return thuDayDateList;
    }
}