dimagi-SalesforceFB/src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <fields>
        <fullName>Budget_Used__c</fullName>
        <description>(Services Spend + Product Spend + Project Travel Spend + External Sub-contract Spend + Project Other Spend) / Total Contract Amount</description>
        <formula>(Product_Spend__c+Services_Spend__c+Direct_Costs_Travel_Expenses__c+Direct_Costs_Sub_contract_Expenses__c+Project_Other_Spent__c)/Total_Amount_of_Contract__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>(Services Spend + Product Spend + Project Travel Spend + External Sub-contract Spend + Project Other Spend) / Total Contract Amount</inlineHelpText>
        <label>% Budget Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Buffer_by_SOW_Completed__c</fullName>
        <description>% of Work Completed (populated by PM in PRO) minus % of Budget Used</description>
        <formula>Percent_through_SOW_deliverables__c - Budget_Used__c</formula>
        <inlineHelpText>% of Work Completed (populated by PM in PRO) minus % of Budget Used</inlineHelpText>
        <label>Buffer % by Work Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Direct_Costs_Total_Expenses__c</fullName>
        <description>Calculated (updated monthly): Project Travel Spend + External Sub-contract Spend + Project Other Spend</description>
        <inlineHelpText>Calculated (updated monthly): Project Travel Spend + External Sub-contract Spend + Project Other Spend</inlineHelpText>
        <label>Expense &amp; Travel Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Execution_Efficiency__c</fullName>
        <description>(Services Budget * % of Work Completed) / Services Spend
If any blanks in variables is set to 100%.</description>
        <formula>if(and(Services_Budget__c  &gt; 0, Services_Spend__c &gt;0),(Services_Budget__c *  Percent_through_SOW_deliverables__c )/ Services_Spend__c, 1)</formula>
        <inlineHelpText>(Services Budget * % of Work Completed) / Services Spend
If any blanks in variables is set to 100%.</inlineHelpText>
        <label>Execution Efficiency</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Expected_Buffer__c</fullName>
        <description>Percent of the Total Contract minus Expenses that will not be directly allocated via Fogbugz or Intacct data, and is expected to fund other core activities.</description>
        <inlineHelpText>Percent of the Total Contract minus Expenses that will not be directly allocated via Fogbugz or Intacct data, and is expected to fund other core activities.</inlineHelpText>
        <label>Expected % Buffer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>GS_Execution_Budget__c</fullName>
        <description>Services Budget * % of Services Budget for GS</description>
        <formula>Services_Budget__c *  of_Services_budget_for_GS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Services Budget * % of Serivces Budget for GS</inlineHelpText>
        <label>GS Project Services Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GS_Services_Completed__c</fullName>
        <description>% Work Completed * GS Services Budget</description>
        <formula>Percent_through_SOW_deliverables__c *  GS_Execution_Budget__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>% Work Completed * GS Services Budget</inlineHelpText>
        <label>GS Services Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Income_based_on_SOW_Completed__c</fullName>
        <description>(% of Work Completed * Total Contract Amount) - Total Calculated Costs (Labor &amp; External Expenses)</description>
        <formula>(Percent_through_SOW_deliverables__c *  Total_Amount_of_Contract__c ) -  Total_Costs__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>(% of Work Completed  * Total Contract Amount) - Total Calculated Costs (Labor &amp; External Expenses)</inlineHelpText>
        <label>Net Income based on % Work Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Percent_through_SOW_deliverables__c</fullName>
        <description>Set by the Dimagi PM in PRO (estimated % complete through the SOW/deliverables/work)</description>
        <inlineHelpText>Set by the Dimagi PM in PRO (estimated % complete through the SOW/deliverables/work)</inlineHelpText>
        <label>% of Work Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Spend__c</fullName>
        <description>Product spend to date, which is calculated as Product Budget * % Time into Contract</description>
        <formula>Product_Income_Budget__c *  Percent_through_Contract__c</formula>
        <inlineHelpText>Product spend to date, which is calculated as Product Budget * % Time into Contract</inlineHelpText>
        <label>Product Spend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Services_Spend__c</fullName>
        <description>Calculated from FB time data and Loaded Billing Rates (updated daily for last 4 months)</description>
        <inlineHelpText>Calculated from FB time data and Loaded Billing Rates (updated daily for last 4 months)</inlineHelpText>
        <label>Services Spend</label>
        <precision>14</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Snapshot_Date__c</fullName>
        <formula>$Setup.Snapshot_Settings__c.Snapshot_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Snapshot Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Costs__c</fullName>
        <description>Services Spend (FB data) +  (Calculated from External Sub-contract Spend + Project Travel Spend + Project Other Spend ; Should align with Intacct Monthly)</description>
        <formula>Services_Spend__c +  (Direct_Costs_Sub_contract_Expenses__c+Direct_Costs_Travel_Expenses__c+Project_Other_Spent__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Services Spend (FB data) +  (Calculated from External Sub-contract Spend + Project Travel Spend + Project Other Spend ; Should align with Intacct Monthly)</inlineHelpText>
        <label>Total Calculated Costs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>of_Services_budget_for_GS__c</fullName>
        <defaultValue>1</defaultValue>
        <description>This is the % of the remaining budget (after removing expenses and buffer %) that is planned for GS work</description>
        <inlineHelpText>This is the % of the remaining budget (after removing expenses and buffer %) that is planned for GS work</inlineHelpText>
        <label>% Services budget for GS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/Pipeline_Snapshot__c.object
<CustomObject>
    <description>Used to store historic pipeline information for pipeline reporting. Automatically populated each month.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Pipeline Snapshots</relationshipLabel>
        <relationshipName>Pipeline_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_Date__c</fullName>
        <inlineHelpText>The month of this snapshot.</inlineHelpText>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Stage 1 - Connect</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 2 - Talking</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 3 - Prospect</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 4 - Proposal Development</fullName>
                <color>#DDDDDD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 5 - Submitted</fullName>
                <color>#BBBBBB</color>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 6 - In Negotiations</fullName>
                <color>#999999</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Outstanding Contracted</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Total</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Cash on Hand</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Predicted pipeline</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Core run rate</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Pipeline Snapshot</label>
    <nameField>
        <label>Pipeline Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/PRO_Contract_Snapshot__c.object
<CustomObject>
    <fields>
        <fullName>Budget_Used__c</fullName>
        <label>% Budget Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Buffer_By_Deliverables_Complete__c</fullName>
        <label>Buffer % by Deliverables Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>PRO Contract Snapshot</relationshipLabel>
        <relationshipName>PRO_Contract_Snapshot</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Execution_Efficiency__c</fullName>
        <label>Execution Efficiency</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Expected_Buffer__c</fullName>
        <label>Expected % Buffer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Expense_And_Travel_Spend__c</fullName>
        <label>Expense &amp; Travel Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Income_By_Deliverables_Complete__c</fullName>
        <label>Net Income by Deliverables Complete</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Percent_Of_Work_Completed__c</fullName>
        <label>% of Work Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percent_Services_Budget_For_GS__c</fullName>
        <label>% Services budget for GS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Spend__c</fullName>
        <label>Product Spend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Services_Spend__c</fullName>
        <label>Services Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Snapshot_Date__c</fullName>
        <label>Snapshot Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Calculated_Costs__c</fullName>
        <label>Total Calculated Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>PRO Contract Snapshot</label>
    <nameField>
        <label>PRO Contract Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRO Contract Snapshot</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/classes/SnapshotHelper.cls
/**
 * Helper class used for creating Snasphots objects in the System.
 */
public class SnapshotHelper {

    public static Map<Id, PRO_Contract_Snapshot__c> getOldPROSnapshot(List<DContract__c> contracts, Date currentDate) {
        Map<Id, PRO_Contract_Snapshot__c> snapshotsMap = new Map<Id, PRO_Contract_Snapshot__c>();
        List<PRO_Contract_Snapshot__c> snapshotsList = [SELECT Id, Percent_Of_Work_Completed__c, Services_Spend__c, Expense_And_Travel_Spend__c, Product_Spend__c, Total_Calculated_Costs__c, GS_Services_Completed_Handover__c, Product_Spend2__c,
                                          Contract__c, GS_Services_Completed__c, GS_Net_Income_to_Date__c, GS_Net_Income_to_Date_Handover__c FROM PRO_Contract_Snapshot__c WHERE Snapshot_Date__c <: currentDate
                                          AND Contract__c IN: contracts ORDER BY Snapshot_Date__c DESC];

        for (PRO_Contract_Snapshot__c sn : snapshotsList) {
            if (!snapshotsMap.containsKey(sn.Contract__c)) {
                snapshotsMap.put(sn.Contract__c, sn);
            }
        }

        return snapshotsMap;
    }

    public static PRO_Contract_Snapshot__c getLastPROSnapshot(DContract__c dcontract, Id snapshotId) {
        List<PRO_Contract_Snapshot__c> snapshotsList;
        if (snapshotId == null) {
            snapshotsList = [SELECT Id, Percent_Of_Work_Completed__c, Services_Spend__c, Expense_And_Travel_Spend__c, Product_Spend__c, Total_Calculated_Costs__c, GS_Services_Completed_Handover__c, Product_Spend2__c,
                                          Contract__c, GS_Services_Completed__c, GS_Net_Income_to_Date__c, GS_Net_Income_to_Date_Handover__c FROM PRO_Contract_Snapshot__c WHERE Snapshot_Date__c <: Date.today()
                                          AND Contract__c =: dcontract.Id ORDER BY Snapshot_Date__c DESC LIMIT 1];
        } else {
            snapshotsList = [SELECT Id, Percent_Of_Work_Completed__c, Services_Spend__c, Expense_And_Travel_Spend__c, Product_Spend__c, Total_Calculated_Costs__c, GS_Services_Completed_Handover__c, Product_Spend2__c,
                                          Contract__c, GS_Services_Completed__c, GS_Net_Income_to_Date__c, GS_Net_Income_to_Date_Handover__c FROM PRO_Contract_Snapshot__c WHERE Snapshot_Date__c <: Date.today()
                                          AND Contract__c =: dcontract.Id AND Id !=: snapshotId  ORDER BY Snapshot_Date__c DESC LIMIT 1];
        }

        if (snapshotsList.size() > 0) {
            return snapshotsList.get(0);
        }

        return new PRO_Contract_Snapshot__c();
    }

    public static PRO_Contract_Snapshot__c fillPROSnapshot(Date proDate, PRO_Contract_Snapshot__c proContractSnapshot, DContract__c dcontract, PRO_Contract_Snapshot__c oldSnapshot) {
            proContractSnapshot.Budget_Used__c = dcontract.Budget_Used__c;
            proContractSnapshot.Percent_Of_Work_Completed__c = dcontract.Percent_through_SOW_deliverables__c;
            proContractSnapshot.Percent_Services_Budget_For_GS__c = dcontract.of_Services_budget_for_GS__c;
            proContractSnapshot.Buffer_By_Deliverables_Complete__c = dcontract.Buffer_by_SOW_Completed__c;
            proContractSnapshot.Execution_Efficiency__c = dcontract.Execution_Efficiency__c;
            proContractSnapshot.Expected_Buffer__c = dcontract.Expected_Buffer__c;
            proContractSnapshot.Expense_And_Travel_Spend__c = dcontract.Direct_Costs_Total_Expenses__c;
            proContractSnapshot.Net_Income_By_Deliverables_Complete__c = dcontract.Net_Income_based_on_SOW_Completed__c;
            proContractSnapshot.Product_Spend2__c = dcontract.Product_Spend__c;
            proContractSnapshot.Services_Spend__c = dcontract.Services_Spend__c;
            proContractSnapshot.Total_Calculated_Costs__c = dcontract.Total_Costs__c;
            proContractSnapshot.Contract__c = dcontract.Id;
            proContractSnapshot.Name = dcontract.Name;
            proContractSnapshot.Snapshot_Date__c = proDate;
            proContractSnapshot.GS_Execution_Budget__c = dcontract.GS_Execution_Budget__c;
            proContractSnapshot.GS_Services_Completed_Handover__c = dcontract.GS_Services_Completed_Handover__c;
            proContractSnapshot.GS_Services_Completed__c = dcontract.GS_Services_Completed__c;
            proContractSnapshot.GS_Net_Income_to_Date__c = dcontract.GS_Net_Income_to_Date__c;
            proContractSnapshot.GS_Net_Income_to_Date_Handover__c = dcontract.GS_Net_Income_to_Date_Handover__c;
            proContractSnapshot.GS_Project_Services_Budget_Handoff_Cp__c = dcontract.GS_Project_Services_Budget_Handoff__c;

            proContractSnapshot.Work_Completed_for_Period__c = (dcontract.Percent_through_SOW_deliverables__c != null ? dcontract.Percent_through_SOW_deliverables__c : 0) - (oldSnapshot.Percent_Of_Work_Completed__c != null ? oldSnapshot.Percent_Of_Work_Completed__c : 0);
            proContractSnapshot.Services_Spend_for_Period__c = (dcontract.Services_Spend__c != null ? dcontract.Services_Spend__c : 0) - (oldSnapshot.Services_Spend__c != null ? oldSnapshot.Services_Spend__c : 0);
            proContractSnapshot.Expense_Travel_Spend_for_Period__c = (dcontract.Direct_Costs_Total_Expenses__c != null ? dcontract.Direct_Costs_Total_Expenses__c : 0) - (oldSnapshot.Expense_And_Travel_Spend__c != null ? oldSnapshot.Expense_And_Travel_Spend__c : 0);
            proContractSnapshot.Product_Spend_for_Period__c = (dcontract.Product_Spend__c != null ? dcontract.Product_Spend__c : 0) - (oldSnapshot.Product_Spend2__c != null ? oldSnapshot.Product_Spend2__c : 0);
            proContractSnapshot.Total_Calculated_Costs_for_Period__c = (dcontract.Total_Costs__c != null ? dcontract.Total_Costs__c : 0) - (oldSnapshot.Total_Calculated_Costs__c != null ? oldSnapshot.Total_Calculated_Costs__c : 0);
            proContractSnapshot.GS_Services_Handover_Completed_for_Per__c = (dcontract.GS_Services_Completed_Handover__c != null ? dcontract.GS_Services_Completed_Handover__c : 0) - (oldSnapshot.GS_Services_Completed_Handover__c != null ? oldSnapshot.GS_Services_Completed_Handover__c : 0);
            proContractSnapshot.GS_Services_Completed_for_Period__c = (dcontract.GS_Services_Completed__c != null ? dcontract.GS_Services_Completed__c : 0) - (oldSnapshot.GS_Services_Completed__c != null ? oldSnapshot.GS_Services_Completed__c : 0);
            proContractSnapshot.GS_Net_Income_for_Period__c = (dcontract.GS_Net_Income_to_Date__c != null ? dcontract.GS_Net_Income_to_Date__c : 0) - (oldSnapshot.GS_Net_Income_to_Date__c != null ? oldSnapshot.GS_Net_Income_to_Date__c : 0);
            proContractSnapshot.GS_Net_Income_for_Period_by_Handover__c = (dcontract.GS_Net_Income_to_Date_Handover__c != null ? dcontract.GS_Net_Income_to_Date_Handover__c : 0) - (oldSnapshot.GS_Net_Income_to_Date_Handover__c != null ? oldSnapshot.GS_Net_Income_to_Date_Handover__c : 0);

            return proContractSnapshot;
    }

    public static Map<Id, Pipeline_Snapshot__c> getOldSnapshots(List<Pipeline_Snapshot__c> snapshots, Boolean forTotal) {
        Set<Id> contracts = new Set<Id>();
        for (Pipeline_Snapshot__c sn : snapshots) {
            if (sn.Contract__c != null) {
                contracts.add(sn.Contract__c);
            }
        }

        Date monthDate = snapshots.get(0).Month_Date__c;
        List<Pipeline_Snapshot__c> oldSnapshots;
        if (forTotal) {
            oldSnapshots = [SELECT Id, Contract__c, Work_Completed__c, Services_Spend__c, Expense_Travel_Spend__c, Product_Spend__c, Total_Calculated_Costs__c, GS_Services_Completed__c,
                            GS_Services_Completed_Handover__c, GS_Net_Income_to_Date__c, GS_Net_Income_to_Date_Handover__c FROM Pipeline_Snapshot__c
                            WHERE Contract__c IN: contracts AND Month_Date__c < :monthDate AND Month_Date__c > :monthDate.addMonths(-6)
                            AND Stage__c = 'Total' ORDER BY Month_Date__c DESC];
        } else {
            oldSnapshots = [SELECT Id, Contract__c, Work_Completed__c, Services_Spend__c, Expense_Travel_Spend__c, Product_Spend__c, Total_Calculated_Costs__c, GS_Services_Completed__c,
                            GS_Services_Completed_Handover__c, GS_Net_Income_to_Date__c, GS_Net_Income_to_Date_Handover__c FROM Pipeline_Snapshot__c
                            WHERE Contract__c IN: contracts AND Month_Date__c < :monthDate AND Month_Date__c > :monthDate.addMonths(-6)
                            AND Stage__c != 'Total' ORDER BY Month_Date__c DESC];
        }

        Map<Id, Pipeline_Snapshot__c> oldSnapShotsMap = new Map<Id, Pipeline_Snapshot__c>();
        for(Pipeline_Snapshot__c snapshotObject : oldSnapshots) {
            if (!oldSnapShotsMap.containsKey(snapshotObject.Contract__c)) {
                oldSnapShotsMap.put(snapshotObject.Contract__c, snapshotObject);
            }
        }

        return oldSnapShotsMap;
    }

    public static Map<Id, Pipeline_Snapshot__c> getOldSnapshotsForOpp(List<Pipeline_Snapshot__c> snapshots, Boolean forTotal) {
        Set<Id> opps = new Set<Id>();
        for (Pipeline_Snapshot__c sn : snapshots) {
            if (sn.Opportunity__c != null) {
                opps.add(sn.Opportunity__c);
            }
        }

        Date monthDate = snapshots.get(0).Month_Date__c;
        List<Pipeline_Snapshot__c> oldSnapshots;
        if (forTotal) {
            oldSnapshots = [SELECT Id, Opportunity__c, Buffer_EV__c FROM Pipeline_Snapshot__c
                            WHERE Opportunity__c IN: opps AND Month_Date__c < :monthDate AND Month_Date__c > :monthDate.addMonths(-6)
                            AND Stage__c = 'Total' ORDER BY Month_Date__c DESC];
        } else {
            oldSnapshots = [SELECT Id, Opportunity__c, Buffer_EV__c FROM Pipeline_Snapshot__c
                            WHERE Opportunity__c IN: opps AND Month_Date__c < :monthDate AND Month_Date__c > :monthDate.addMonths(-6)
                            AND Stage__c != 'Total' ORDER BY Month_Date__c DESC];
        }

        Map<Id, Pipeline_Snapshot__c> oldSnapShotsMap = new Map<Id, Pipeline_Snapshot__c>();
        for(Pipeline_Snapshot__c snapshotObject : oldSnapshots) {
            if (!oldSnapShotsMap.containsKey(snapshotObject.Opportunity__c)) {
                oldSnapShotsMap.put(snapshotObject.Opportunity__c, snapshotObject);
            }
        }

        return oldSnapShotsMap;
    }

    public static Pipeline_Snapshot__c calculateForPeriod(Pipeline_Snapshot__c sn, Pipeline_Snapshot__c oldSn) {
            sn.Work_Completed_for_Period__c = (sn.Work_Completed__c != null ? sn.Work_Completed__c : 0) - (oldSn.Work_Completed__c != null ? oldSn.Work_Completed__c : 0);
            sn.Services_Spend_for_Period__c = (sn.Services_Spend__c != null ? sn.Services_Spend__c : 0) - (oldSn.Services_Spend__c != null ? oldSn.Services_Spend__c : 0);
            sn.Expense_Travel_Spend_for_Period__c = (sn.Expense_Travel_Spend__c != null ? sn.Expense_Travel_Spend__c : 0) - (oldSn.Expense_Travel_Spend__c != null ? oldSn.Expense_Travel_Spend__c : 0);
            sn.Product_Spend_for_Period__c = (sn.Product_Spend__c != null ? sn.Product_Spend__c : 0) - (oldSn.Product_Spend__c != null ? oldSn.Product_Spend__c : 0);
            sn.Total_Calculated_Costs_for_Period__c = (sn.Total_Calculated_Costs__c != null ? sn.Total_Calculated_Costs__c : 0) - (oldSn.Total_Calculated_Costs__c != null ? oldSn.Total_Calculated_Costs__c : 0);
            sn.GS_Services_Completed_for_Period__c = (sn.GS_Services_Completed__c != null ? sn.GS_Services_Completed__c : 0) - (oldSn.GS_Services_Completed__c != null ? oldSn.GS_Services_Completed__c : 0);
            sn.GS_Services_Handover_Completed_for_Per__c = (sn.GS_Services_Completed_Handover__c != null ? sn.GS_Services_Completed_Handover__c : 0) - (oldSn.GS_Services_Completed_Handover__c != null ? oldSn.GS_Services_Completed_Handover__c : 0);
            sn.GS_Net_Income_for_Period__c = (sn.GS_Net_Income_to_Date__c != null ? sn.GS_Net_Income_to_Date__c : 0) - (oldSn.GS_Net_Income_to_Date__c != null ? oldSn.GS_Net_Income_to_Date__c : 0);
            sn.GS_Net_Income_for_Period_by_Handover__c = (sn.GS_Net_Income_to_Date_Handover__c != null ? sn.GS_Net_Income_to_Date_Handover__c : 0) - (oldSn.GS_Net_Income_to_Date_Handover__c != null ? oldSn.GS_Net_Income_to_Date_Handover__c : 0);

        return sn;
    }
}