dimagi-SalesforceFB/src/objects/FogBugz_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Sync_Filter__c</fullName>
        <label>Sync Filter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sync_Script_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Script Running</label>
        <type>Checkbox</type>
    </fields>
    <label>FogBugz Settings</label>
</CustomObject>

dimagi-SalesforceFB/src/classes/FogBugzSynchronizer.cls
/**
 * Retrieves FogBugz cases and upserts SF opportunities
 *
 * @author  Antonio Grassi
 * @date    11/14/2012
 */
global without sharing class FogBugzSynchronizer implements Schedulable {

    global void execute(SchedulableContext SC) {
        FogBugz_Settings__c fbSettings = FogBugz_Settings__c.getOrgDefaults();

        if (!fbSettings.Sync_Script_Running__c) {
            Database.executeBatch(new FogBugzSynchronizerBatch(fbSettings.Sync_Filter__c.intValue(), false), 1);
        }
    }
}