dimagi-SalesforceFB/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Days_w_o_Activity__c</fullName>
        <description>Returns the # of days since last Activity</description>
        <formula>today () -   LastActivityDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days w/o Activity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Call_Date__c</fullName>
        <description>Date of the first call with the lead.</description>
        <inlineHelpText>Date of the first call with the lead</inlineHelpText>
        <label>First Call Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Follow_up_Date__c</fullName>
        <description>Use this field to set a specific date that you&apos;d like the follow-up report to remind you to reach back out.</description>
        <inlineHelpText>Use this field to set a specific date that you&apos;d like the follow-up report to remind you to reach back out.</inlineHelpText>
        <label>Follow-up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Follow_up_calls_held__c</fullName>
        <description>Calls in addition to the exploratory call.</description>
        <inlineHelpText>Calls in addition to the exploratory call.</inlineHelpText>
        <label>Follow-up calls held</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hubspot_Next_Activity_Date__c</fullName>
        <description>The next activity date from Hubspot. Oddly enough, this is a text field in Husbpot.</description>
        <inlineHelpText>The next activity date from Hubspot. Oddly enough, this is a text field in Husbpot.</inlineHelpText>
        <label>Hubspot - Next Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead_Status_Reason__c</fullName>
        <description>This field contains the list of reasons for selecting the lead status.</description>
        <inlineHelpText>Choose a reason that helps clarify the lead status.</inlineHelpText>
        <label>Lead Status Reason</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Contacted - Sent Email #1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted - Sent Email #2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted - Sent Email #3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working - Exploratory Call - Trying for</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working - Exploratory Call Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working - No show reminder #1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working - No show reminder #2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working - No show reminder #3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working - Nudge #1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working - Nudge #2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working - Nudge #3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working - Nudge #4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect or invalid email address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiting / Hiring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped responding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity identified but timeline &gt; 6 months out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing client / project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email opt-out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No opportunity identified yet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test email address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speaking request / research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact information request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decided to use another solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request for sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invited user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Dimagier</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/classes/LeadQualifyProcessBatch.cls
/**
 * Batch job used to calculate "Failed Qualifying process at least once" field. Notice in test we are using Follow_up_calls_held__c instead Days_w_o_Activity__c (we cannot mock it).
 */
public without sharing class LeadQualifyProcessBatch implements Database.Batchable<Lead>, Database.Stateful {

    private Date currentDate;

    public LeadQualifyProcessBatch () {
        this.currentDate = Date.today();
    }

    public LeadQualifyProcessBatch (Date currentDate) {
        this.currentDate = currentDate;
    }

    public List<Lead> start(Database.BatchableContext context) {
        Decimal threshold = 7;
        Lead_Qualifying_Process__c settings = Lead_Qualifying_Process__c.getOrgDefaults();
        if (settings != null && settings.Threshold__c != null) {
            threshold = settings.Threshold__c;
        }

        if (!Test.isRunningTest()) {
            return [SELECT Id, Days_w_o_Activity__c, Failed_Qualifying_process_at_least_once__c FROM Lead WHERE Failed_Qualifying_process_at_least_once__c = false AND isConverted = false
                                                      AND Status = 'Working - Talking' AND (Lead_Status_Reason__c = 'Working - Exploratory Call - Trying for' OR Lead_Status_Reason__c = 'Working - Exploratory Call Held')
                                                      AND (Follow_up_Date__c = null OR Follow_up_Date__c <: this.currentDate)
                                                      AND (Hubspot_Next_Activity_Date__c = null OR Hubspot_Next_Activity_Date__c <: this.currentDate)
                                                      AND Days_w_o_Activity__c >: threshold];
        } else { // We cannot mock LastActivityDate so in test we use First_Call_Date__c field !!! IMPORTANT for any changes
            return [SELECT Id, Days_w_o_Activity__c, Failed_Qualifying_process_at_least_once__c FROM Lead WHERE Failed_Qualifying_process_at_least_once__c = false AND isConverted = false
                                                      AND Status = 'Working - Talking' AND (Lead_Status_Reason__c = 'Working - Exploratory Call - Trying for' OR Lead_Status_Reason__c = 'Working - Exploratory Call Held')
                                                      AND (Follow_up_Date__c = null OR Follow_up_Date__c <: this.currentDate)
                                                      AND (Hubspot_Next_Activity_Date__c = null OR Hubspot_Next_Activity_Date__c <: this.currentDate)
                                                      AND Follow_up_calls_held__c >: threshold];
        }

    }

    public void execute(Database.BatchableContext context, List<Lead> leads) {
        List<Lead> leadsToUpdate = new List<Lead>();
        for (Lead l : leads) {
            l.Failed_Qualifying_process_at_least_once__c = true;
            leadsToUpdate.add(l);
        }
        if (leadsToUpdate.size() > 0) {
            update leadsToUpdate;
        }
    }

    public void finish(Database.BatchableContext context) {

    }
}