dimagi-SalesforceFB/src/objects/SFDC_Employee__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Exchange_Rate_Date__c</fullName>
        <label>Effective Exchange Rate Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Salary_Date__c</fullName>
        <label>Effective Salary Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate (Local:USD)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Annual Salary (local)</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/objects/Time_Card__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>SFDC_Employee__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <inlineHelpText>Total Hours</inlineHelpText>
        <label>Total Hours</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dimagi-SalesforceFB/src/classes/BatchRecalculateTimeCardCost.cls
/**
 * Calculates cost of time cards.
 */
public without sharing class BatchRecalculateTimeCardCost implements Database.Batchable<sObject>, Database.Stateful {

    private Set<Id> timeCardsIds;
    private SalaryHistoryHelper salaryHistoryHelper;
    private List<SalaryHistoryRecord> employeeSalaryHistory;
    private String lastEmployee;

    public BatchRecalculateTimeCardCost(Set<Id> timeCards) {
        this.salaryHistoryHelper = new SalaryHistoryHelper();
        this.timeCardsIds = timeCards;
        this.employeeSalaryHistory = new List<SalaryHistoryRecord>();
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        this.salaryHistoryHelper = new SalaryHistoryHelper();
        this.employeeSalaryHistory = new List<SalaryHistoryRecord>();

        String query;
        System.debug('timeCardsIds ' + timeCardsIds);
        if (this.timeCardsIds != null && this.timeCardsIds.size() > 0) {
            query = 'SELECT Time_card_cost__c, Total__c, Employee__c, Date__c FROM Time_Card__c WHERE Id In: timeCardsIds AND Employee__c != \'\' ORDER BY Employee__c';
        } else {
            query = 'SELECT Time_card_cost__c, Total__c, Employee__c, Date__c FROM Time_Card__c WHERE Employee__c != \'\' ORDER BY Employee__c';
        }
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Time_Card__c> toUpdate = new List<Time_Card__c>();
        Date lastFromSalaryDate = Date.newInstance(1900, 1, 1);
        Date lastToSalaryDate = Date.today().addYears(1);
        Decimal lastSalary = 0;

        if (this.employeeSalaryHistory.size() > 0) {
            lastToSalaryDate = this.employeeSalaryHistory.size() > 1 ? this.employeeSalaryHistory.get(1).getValueDate() : Date.today().addYears(1);
            lastSalary = this.employeeSalaryHistory.get(0).getValue();
        }

        for (sObject obj : scope) {
            Time_Card__c tc = (Time_Card__c) obj;

            if (tc.Employee__c != this.lastEmployee) {
                this.lastEmployee = tc.Employee__c;
                this.employeeSalaryHistory = this.salaryHistoryHelper.mergeSalaryHistory([SELECT Name, Salary__c, Effective_Salary_Date__c, Exchange_Rate__c, Effective_Exchange_Rate_Date__c FROM SFDC_Employee__c WHERE Id =: tc.Employee__c]);
                System.debug('New employee : ' + tc.Employee__c);
                lastToSalaryDate = this.employeeSalaryHistory.size() > 1 ? this.employeeSalaryHistory.get(1).getValueDate() : Date.today().addYears(1);
                lastSalary = this.employeeSalaryHistory.get(0).getValue();
                lastFromSalaryDate = Date.newInstance(1900, 1, 1);
            }

            if (tc.Date__c < lastFromSalaryDate || tc.Date__c >= lastToSalaryDate) {
                Integer index = 0;
                for (Integer i = 0; i < this.employeeSalaryHistory.size(); i++) {
                    if (tc.Date__c >= this.employeeSalaryHistory.get(i).getValueDate()) {
                        lastSalary = this.employeeSalaryHistory.get(i).getValue();
                        lastFromSalaryDate = this.employeeSalaryHistory.get(i).getValueDate();
                    } else {
                        index = i - 1;
                        break;
                    }
                }

                lastToSalaryDate = this.employeeSalaryHistory.size() > index + 1 ? this.employeeSalaryHistory.get(index + 1).getValueDate() : Date.today().addYears(1);
            }

            Decimal laborCost = tc.Total__c * lastSalary;
            System.debug('Labor cost ' + laborCost);
            if (tc.Time_card_cost__c != laborCost) {
                tc.Time_card_cost__c = laborCost;
                toUpdate.add(tc);
                System.debug('tc cost ' + tc.Time_card_cost__c);
            }
        }

        if (toUpdate.size() > 0) {
            update toUpdate;
        }
    }

    public void finish(Database.BatchableContext context) {

    }
}