aire-con-gas-Chlacker/src/objects/Channel_Manager__c.object
<CustomObject>
    <fields>
        <fullName>Channel_ID__c</fullName>
        <description>Channel ID fo Slack</description>
        <label>Channel ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Ref_Column__c</fullName>
        <label>Object Ref Column</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Ref_ID__c</fullName>
        <description>Object ID for the object type being referenced</description>
        <label>Object Ref ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <description>Which object is referenced for the channel</description>
        <label>Object Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Channel Manager</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Channel Manager Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

aire-con-gas-Chlacker/src/classes/ChannelManagerService.cls
public class ChannelManagerService {

   public static void createNewChannel(String objType, String objRefCol, String objRefId, String channelId){
       Channel_Manager__c newChannel = new Channel_Manager__c();
       newChannel.Object_Type__c = objType;
       newChannel.Object_Ref_Column__c = objRefCol;
       newChannel.Object_Ref_ID__c = objRefId;
       newChannel.Channel_ID__c = channelId;
       Database.upsert(newChannel);
   } 
  
   public static Channel_Manager__c getChannelByStory(String storyId) {
        return ChannelManagerService.getChannel('story', 'name', storyId);
   }  
  
    // getChannel
    // objType - e.g. story object
    // objRefCol - e.g. story name or story number
    // objRefId - e.g. value of ref col
   public static Channel_Manager__c getChannel(String objType, String objRefCol, String objRefId) {
        return [SELECT Channel_ID__c FROM Channel_Manager__c WHERE Object_Type__c = :objType AND Object_Ref_Column__c = :objRefCol AND Object_Ref_ID__c = :objRefId];
   }
   
}